### ISSUE TITLE
Linux Flatpak errors

### ISSUE THREAD

**Issue by QuintusNX** [citra-emu/citra#5619] opened 2020-11-23 19:35 UTC
When trying to install Citra from official Flatpaks, and on every distro, I get these errors :

(Nightly)
$ flatpak install https://flatpak.citra-emu.org/citra-nightly.flatpakref
error: No such ref 'app/org.citra.citra-nightly/x86_64/master' in remote citra-nightly-origin

(Canary)
$ flatpak install https://flatpak.citra-emu.org/citra-canary.flatpakref
error: No such ref 'app/org.citra.citra-canary/x86_64/master' in remote citra-canary-origin

Seems to be a remote error, or commands not updated on the official website

**Comment by Dragios** [comment] 2020-11-24 00:07
Duplicate of #5588. Next time please check if there is same issue reported before opening an issue.

**Closed** 2020-11-24 00:07 UTC
