### ISSUE TITLE
Thunderblade and other M2 Sega Ages Games Crash After Start up menu loads

### ISSUE THREAD

**Issue by M2GameDeveloper** [citra-emu/citra#5583] opened 2020-10-19 00:17 UTC
Most Sega Ages Games like Sega Ages Thunderblade crash AFTER the intro menu loads. Start Button triggers crash after games hangs for a few seconds. Unable to progress past the Start Screen.

System Information
Windows 10 Pro
Intel i7-4790k 4 cores
NVIDIA GeForce RTX 2070
Citra Nightly 1629
3D Thunder Blade

[citra_log.txt](https://github.com/citra-emu/citra/files/5398418/citra_log.txt)

**Comment by M2GameDeveloper** [comment] 2020-10-19 18:05
Fixed errors I could find by create ,bin save files to correct for errors. Game still crashes however.

[citra_log.txt](https://github.com/citra-emu/citra/files/5403849/citra_log.txt)

**Comment by FearlessTobi** [comment] 2020-10-20 21:28
Duplicate of https://github.com/citra-emu/citra/issues/5081.
It would be nice if you could leave a comment there with your findings/log.

**Closed by FearlessTobi** 2020-10-20 21:28 UTC

**Comment by M2GameDeveloper** [comment] 2020-10-21 00:05
> 
> 
> Duplicate of #5081.
> It would be nice if you could leave a comment there with your findings/log.

Will do. I am sending it there.

**Comment by M2GameDeveloper** [comment] 2020-10-21 00:11
> 
> 
> Duplicate of #5081.
> It would be nice if you could leave a comment there with your findings/log.

P.S. Could you or someone look into this? My friend and I have spent the last two years trying to get someone to help us fix this game but we are ignored., We regularly donate to citra paetron, so we do contribute as best we can.

Anything you can do to help please?

**Comment by M2GameDeveloper** [comment] 2020-10-23 21:37
Could someone please look into this? I've been asking for help for two years now, no fooling. It's Sega's 60th Anniversary and I was hoping to preserve these games I helped programmed for consumers on my hard drive for preservation purposes, to go into a museum of sorts. Any help would be appreciated. Thank you!
