### ISSUE TITLE
Eucliod - Crash while booting

### ISSUE THREAD

**Issue by Andrix44** [citra-emu/citra#1862] opened 2016-05-28 08:07 UTC
[LOG](http://pasted.co/8db82bf4)
This is a homebrew game, and it is not that easy to find on Google, so you can check it out [here](https://gbatemp.net/threads/eucliod-a-homebrew-bullet-hell-for-the-3ds.419553/).
At first I tought that it crashes at `[   1.989495] Service.FS <Error> core\hle\service\fs\archive.cpp:Service::FS::File::SyncRequest:108: Reading from out of bounds offset=0x0 length=0x00000028 file_size=0x0` , but it still crashes after trying it with https://github.com/citra-emu/citra/pull/1634 .
![_j_bitk_p_b](https://cloud.githubusercontent.com/assets/13806656/15626094/c6f9261a-24bb-11e6-907b-834b5704f385.jpg)

**Comment by mailwl** [comment] 2016-05-28 10:32
FYI, cia to 3ds converted works fine. (it's no reason to close this issue)

**Comment by Andrix44** [comment] 2016-05-28 12:10
Yep, it does.

**Comment by Subv** [comment] 2016-11-30 01:15
The 3dsx has a header size of 0x20 and it's trying to open the RomFS.
````
[20:05:10] <Cruel`> subv, 0x20 is the size of the 3dsx header when it's missing the romfs entries (the old header size)
[20:05:22] <Cruel`> I think it's user error not making proper 3dsx
[20:05:41] <Cruel`> maybe using old 3dsxtool
````

I'm closing this as invalid.

**Comment by yuriks** [comment] 2016-11-30 05:24
Is this really invalid? Shouldn't we support 3dsx files with the old header format?

**Comment by Subv** [comment] 2016-11-30 12:43
@yuriks The thing is that it's not really the old format, since it's trying to use the RomFS, it's a badly-generated 3dsx

**Comment by yuriks** [comment] 2016-11-30 14:40
Reopening since old format or not this is still our bug: If opening RomFS fails, we just log to the console and then happily use the nullptr file object to read. We should report and error so that the application knows it failed to open RomFS.

- Log when opening RomFS: https://github.com/citra-emu/citra/blob/e5a7f2ef29a8dc715ab9670dedb632a02b835372/src/core/file_sys/archive_romfs.cpp#L19
- Same file, on line 25, no error checking is done before creating the archive in Open.

**Comment by wwylele** [comment] 2017-02-13 17:43
With #2561 merged, on current master the 3dsx version can boot now, but it hangs when loading

![screenshot from 2017-02-13 19-40-51](https://cloud.githubusercontent.com/assets/4592895/22895271/837b9ad0-f224-11e6-919b-d470ee09ce73.png)

Could someone test if the CIA version still works fine or this is a regression?
I will open a new issue later if I can't figure it out.

**Comment by benderscruffy** [comment] 2018-02-05 10:50
goes ingame now using the latest nightly with the 3dsx file
no sound fx

**Closed** 2018-02-05 12:57 UTC
Labels: A-filesystem, T-bug, T-crash
