### ISSUE TITLE
Android - screen layout hotkey

### ISSUE THREAD

**Issue by darrenhaken** [citra-emu/citra#7240] opened 2023-12-10 19:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I am desperate for you to implement a hotkey that lets me toggle the screen layout - specifically so I can use single screen layout and toggle to see the other screen. 

Citra on my steam deck supports it so I can only guess it’s just not been added to the Android UI.

Is this possible? Would I be even able to contribute the fix for this (I’m an engineer). 

Hopefully I hear back from you.

### Why would this feature be useful?

It would allow me to use full screen on my Odin 2 for the main playing screen. It’s a killer feature.

**Comment by Daisouji** [comment] 2023-12-10 19:59
https://github.com/citra-emu/citra/issues/5885

**Comment by jamfor352** [comment] 2023-12-11 06:44
Hi, I actually have a fork available which implements this... will try to get a PR raised :) Although it's based on Nightly right now.

**Comment by darrenhaken** [comment] 2023-12-11 06:53
Amazing. If you could do that it would be incredible. It’s holding me back from playing 3ds on my Odin 2. 

Nightly is fine, that will end up in canary eventually

**Comment by jamfor352** [comment] 2023-12-11 07:11
yep had the same issue, did it for my Retroid Pocket Flip - not having a hotkey handy makes it laborious to swap screens so I understand the plight! I had a mini-hackathon session last night just to get this working for myself - will clean up the code and make sure it's up to scratch and hopefully this will solve it :) for the time being it's just two hotkeys - toggle layout & swap screen but could hopefully be extended

**Comment by darrenhaken** [comment] 2023-12-11 07:19
That’s the two I want the most. To be honest, I’ll have it single screen with a toggle most of the time.

are the maintainers for Citra good at merging in?

**Comment by FearlessTobi** [comment] 2023-12-11 18:02
Closing as duplicate of https://github.com/citra-emu/citra/issues/5885.

**Closed by FearlessTobi** 2023-12-11 18:02 UTC
