### ISSUE TITLE
（Include bug videos）Mario Kart 7 Creating group stuck。

### ISSUE THREAD

**Issue by Helloworld996** [citra-emu/citra#6540] opened 2023-05-13 18:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

latest nightly and canary

### Description of Issue

Please watch the video carefully. I have submitted this for the third time, and if you still think it is not a bug, then I have nothing to say. There will be no further feedback on any issues.Because I have done my best, I hope the developers can face this issue squarely。

bug video（If you can't play the video online, download it and play it）:
https://drive.google.com/file/d/1JxvJGIamYYhBMQsrTp9K1VsV17jv7EQF/view?usp=drivesdk
（This is not a ROM, it's a bug video.）

### Expected Behavior

#6537

### Reproduction Steps

#6537
![Uploading Screenshot_2023-05-12-16-07-46-158_org.citra.citra_emu.canary.jpg…]()
![Uploading Screenshot_2023-05-12-00-29-22-999_org.citra.citra_emu.canary.jpg…]()

### Log File

nothing in the log file

### System Configuration

CPU:Qualcomm Snapdragon 710
GPU/Driver:Adreno 616
RAM:4G
OS:Android

**Comment by sakuramipha** [comment] 2023-05-13 18:46
You are having this issue _because_ Citra Android does not support multiplayer. That unofficial fork does. Closing this again, if you have any further questions please come into our Discord server and chat with us there: https://discord.gg/FAXfZV9

**Closed** 2023-05-13 18:46 UTC

**Comment by Helloworld996** [comment] 2023-05-13 18:50
> You are having this issue _because_ Citra Android does not support multiplayer. That unofficial fork does. Closing this again, if you have any further questions please come into our Discord server and chat with us there: https://discord.gg/FAXfZV9

The problem is that I went in when I was disconnected from the internet. You can see in the video that I closed the internet connection. This group does not need to be opened to access that page, but once you enter that page, you will need to use the online function. I hope you can also verify it.

**Comment by SleepingSnakezzz** [comment] 2023-05-13 19:54
Whether you are connected to the internet is completely irrelevant to the issue. Citra Android official has no networking code. So any feature in-game that relies on network related calls, like the one you showed in the video, will lead to a softlock. Since multiplayer isn't implemented, that is expected behavior and **not** a bug.

*If* we ever decide to implement local multiplayer on Citra Android official, and *after* that this behavior persists, feel free to open an issue about it. Until then, this isn't relevant whatsoever.
