### ISSUE TITLE
Phoenix Wright Dual Destinies Not working

### ISSUE THREAD

**Issue by YisKudo** [citra-emu/citra#1961] opened 2016-07-18 08:50 UTC
Phoenix wright dual destinies won't open it shows a black screen

**Comment by JayFoxRox** [comment] 2016-07-18 11:23
Duplicate of https://github.com/citra-emu/citra/issues/1597

Closed.

**Closed by JayFoxRox** 2016-07-18 11:23 UTC

**Comment by YisKudo** [comment] 2016-07-18 14:53
But there is no solution on that thread

**Comment by JayFoxRox** [comment] 2016-07-18 15:32
Because it's not a thread. This is a bug tracker for developers of Citra.
The game does not work yet, there is no solution for it yet either.

Also, please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.
