### ISSUE TITLE
Black screen during intro of radiant historia [INTEL REGRESSION FROM #6247]

### ISSUE THREAD

**Issue by hyacantus** [citra-emu/citra#6278] opened 2023-02-02 21:29 UTC
On recent canary build the game started with black screen during intro of the game but then everything loaded normally during actual gameplay. resetting the game after that also let the intro loads normally but after closing citra the game started with the black screen intro again & repeat. the game loads normally on the latest nightly build

**Comment by FearlessTobi** [comment] 2023-02-03 01:55
Can you please go back in the Canary releases list and find the build where this problem started?
https://github.com/citra-emu/citra-canary/releases

**Comment by hyacantus** [comment] 2023-02-03 06:35
The problem started on canary-2383. It works fine on canary-2381. i can't test on canary-2382 since there's no window version build

**Comment by FearlessTobi** [comment] 2023-02-03 16:28
Thanks for testing!

**Comment by FearlessTobi** [comment] 2023-02-03 17:54
I am unable to reproduce this on latest Canary.
The intro video plays normally for me when starting a new game.

**Comment by hyacantus** [comment] 2023-02-03 20:26
Upon further testing i also have the same problems on certain games like ocarina of time & majora mask but everything works just fine on pokemon ultra sun. my drivers are up to date. deleting shader cache & resetting all settings also doesn't do anything. so weird how they don't load only on intro. im sticking with canary-2381 for now

**Comment by vitor-k** [comment] 2023-02-04 17:21
Can you test the build artifacts from #6247 to narrow down the issue? The only difference between canary-2383 and canary-2381 is that PR.
Test the latest nightly as well, just in case.
A [log file](https://community.citra-emu.org/t/how-to-upload-the-log-file/296) would also be appreciated.

**Comment by hyacantus** [comment] 2023-02-04 18:21
This is my log file tested from citra-2386. latest nightly version still works just fine

[citra_log.txt](https://github.com/citra-emu/citra/files/10609348/citra_log.txt)

**Comment by hyacantus** [comment] 2023-02-12 07:23
I just found a workaround. If i opened pokemon ultra sun first (or any working games),stop emulation, then open the game with this problem the game will just load normally after

**Comment by hyacantus** [comment] 2023-02-15 10:22
I started having the same problem on Citra Nightly now as well,starting from Citra Nightly 1841. the same workaround still works though

**Comment by FearlessTobi** [comment] 2023-02-15 11:36
My bad, I forgot about this issue and merged to Nightly.
For the record, this seems to be an Intel-only issue.
Some other people also reported crashes with it, so we are looking into it.

**Closed** 2023-02-18 16:54 UTC
Labels: T-regression
