### ISSUE TITLE
Pokemon Sun/Moon unresponsiveness after winning the first league 

### ISSUE THREAD

**Issue by leaguerr** [citra-emu/citra#2524] opened 2017-02-04 00:23 UTC
I used 
 HEAD-a53714a
 HEAD-632562f
 HEAD-c3303dcd (The latest version)
 etc.

The screen just turned to black after winning the first league, when using the hall of fame.

**Comment by jroweboy** [comment] 2017-02-04 00:47
Closing as a duplicate of https://github.com/citra-emu/citra/issues/2190 There is a workaround for this on the forums. (Look there for more information)

**Closed by jroweboy** 2017-02-04 00:47 UTC
