### ISSUE TITLE
[Feature Request] Free Camera Mode?

### ISSUE THREAD

**Issue by SolidSouless** [citra-emu/citra#5946] opened 2022-02-07 06:58 UTC
A Citra emulation mod that allows Free camera movement in game. I assume it would be difficult as each game is different, but I thought it wouldn't hurt to ask.

**Comment by RocketRobz** [comment] 2022-02-07 07:02
I've opened the same issue: https://github.com/citra-emu/citra/issues/5038

**Comment by AlexDecker64** [comment] 2022-02-09 16:54
would be a good feature :/

**Comment by merryhime** [comment] 2022-02-09 17:40
Duplicate of #5038.

**Closed by merryhime** 2022-02-09 17:40 UTC

**Comment by Dudee15** [comment] 2022-03-04 17:07
I tried compiling the camhax but kept running into errors. To be specific, 498 errors.
