### ISSUE TITLE
Detective Pikachu FMV's run faster than the frame-rate (pipe-3 related)

### ISSUE THREAD

**Issue by robzombie91** [citra-emu/citra#3612] opened 2018-03-31 01:32 UTC
So when starting up the game after the title screen the frame rate runs too fast but it goes back to normal after you actually get into the game.

The Error that its spitting out repeatedly is
Service.Y2R <Warning> core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:198: (STUBBED) called

Here is a paste of the debug log and a video of the issue
https://pastebin.com/WsM9XUi7
https://youtu.be/weSQWGwp6HU

**Comment by NotYukoAsuka** [comment] 2018-08-29 00:50
is this issue still being investigated or forgotten?

**Comment by robzombie91** [comment] 2018-08-29 15:42
Im not sure, i reported it a while ago but nothing has come of it

**Comment by mohalisad** [comment] 2018-10-17 08:53
It's not fixed after 6 months

**Comment by Tabish4675** [comment] 2018-12-10 12:02
what does pipe-3 related means?

**Comment by Dragios** [comment] 2018-12-13 14:30
@Tabish4675 You can read it [here](https://www.3dbrew.org/wiki/DSP:ReadPipeIfPossible#Channel_3_.28Binary.29) but not much info about it yet due to the wiki is not updated with latest finding by @wwylele yet

Also this is fixed with DSP LLE audio PR #4490

**Comment by robzombie91** [comment] 2018-12-15 16:47
[ 783.071003] Kernel.SVC <Error> core/hle/kernel/svc.cpp:CreateThread:894: Newly created thread must run in the SysCore (Core1), unimplemented.
[ 783.102995] Kernel.SVC <Error> core/hle/kernel/svc.cpp:CreateThread:894: Newly created thread must run in the SysCore (Core1), unimplemented.
[ 783.135435] Kernel.SVC <Error> core/hle/kernel/svc.cpp:CreateThread:894: Newly created thread must run in the SysCore (Core1), unimplemented.
[ 783.154173] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:705: called flag=00000000 process=11 thread_id=1
[ 783.163708] HW.Memory <Error> core/hle/service/gsp/gsp_gpu.cpp:VirtualToPhysicalAddress:76: Unknown virtual address @ 0x0821B5D0
[ 783.163713] HW.Memory <Error> core/memory.cpp:GetPhysicalPointer:322: unknown GetPhysicalPointer @ 0x8821B5D0
[ 783.163720] HW.GPU <Critical> core/hw/gpu.cpp:DisplayTransfer:141: invalid output address 0X8821B5D0
[ 783.280272] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:162: Delay generator was not initalized. Using default
[ 783.293943] Service.FS <Error> core/hle/service/fs/file.cpp:Read:56: Reading from out of bounds offset=0x0 length=0x00008FB0 file_size=0x128
[ 783.308589] Service.FS <Error> core/hle/service/fs/file.cpp:Read:56: Reading from out of bounds offset=0x128 length=0x00008E88 file_size=0x128
[ 783.588537] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:441: Firmware hash: 0x8f5a2d2c70f78f12
[ 783.588541] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:445: Structures hash: 0x228655de1258d999
[ 783.588543] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:184: called size=0xC26C, prog_mask=0x000000FF, data_mask=0x001100FF
[ 783.589737] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:250: Registered interrupt=2, channel=2, event=event-00329980
[ 783.590013] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:266: (STUBBED) called
[ 783.590282] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:276: (STUBBED) called mask=0x2000
[ 783.590699] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:201: Application has requested initialization of DSP hardware
[ 783.590893] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:53: called, semaphore_value=4000
[ 783.592786] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:53: called, semaphore_value=4000
[ 783.607398] Kernel.SVC <Error> core/hle/kernel/svc.cpp:CreateThread:894: Newly created thread must run in the SysCore (Core1), unimplemented.
[ 787.592503] Render.OpenGL <Warning> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:530: API PERFORMANCE 131218: Program/shader state performance warning: Vertex shader in program 16 is being recompiled based on GL state.
[ 787.605400] Render.OpenGL <Warning> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:530: API PERFORMANCE 131218: Program/shader state performance warning: Vertex shader in program 16 is being recompiled based on GL state.
[ 788.283446] Service.PTM <Warning> core/hle/service/ptm/ptm.cpp:CheckNew3DS:131: (STUBBED) called isNew3DS = 0x00000000
[ 788.283451] Service.APT <Warning> core/hle/service/apt/apt.cpp:CheckNew3DSApp:850: (STUBBED) called
[ 788.348011] Service.FS <Warning> core/hle/service/fs/file.cpp:OpenLinkFile:195: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]
[ 796.267204] Service.FS <Error> core/hle/service/fs/file.cpp:Read:56: Reading from out of bounds offset=0x0 length=0x00008FB0 file_size=0x8e48
[ 796.281314] Service.FS <Error> core/hle/service/fs/file.cpp:Read:56: Reading from out of bounds offset=0x8e48 length=0x00000168 file_size=0x8e48

**Comment by wwylele** [comment] 2019-01-11 15:49
DSP LLE is merged. Please continue to track this issue on while we fix DSP HLE.

**Comment by xperia64** [comment] 2020-08-25 02:46
I'm looking into this, and for the sake of recording what I've found so far, I'm noting it here.

This issue has nothing to do with pipe-3 as the game doesn't even use it.

Instead, I believe that this issue involves this bit not being handled by DSP HLE: https://github.com/citra-emu/citra/blob/master/src/audio_core/hle/shared_memory.h#L128

This game hammers on the `partial_embedded_buffer_dirty` bit as well as the `partial_reset_flag` during the FMV. I'm not sure yet how to implement this correctly, but I am able to affect the FMV speed by queuing a buffer when this bit is set as per `embedded_buffer_dirty`.

I also believe https://github.com/citra-emu/citra/issues/4281 has the same root cause as this issue, as there are similar symptoms.

**Closed** 2020-11-17 22:31 UTC
Labels: A-audio
