### ISSUE TITLE
White screen in Super Mario 3D Land

### ISSUE THREAD

**Issue by iGom** [citra-emu/citra#5046] opened 2020-01-02 21:12 UTC
Citra Nightly-1399 01686f78fed196e5c7b19fafc8a1f6d8a609c7f8
Citra Canary-1529 6935f38a0b77d6b19f3d7aa907f38d016b03d0f5

White screen issue appeares (with working audio) in Super Mario 3D Land after pressing A on the title screen to access the File Select menu, any other games I have like Pokemon Ultra Sun/Moon, Luigi's Masion or Mario Kart 7 work just fine.
![mario 1](https://user-images.githubusercontent.com/4786772/71693334-219c4f80-2da4-11ea-9589-8bad6d9c57f9.png)
![mario 2](https://user-images.githubusercontent.com/4786772/71693345-26610380-2da4-11ea-8855-7d7b81e9cd9b.png)

[citra_log.txt](https://github.com/citra-emu/citra/files/4017322/citra_log.txt)

**Comment by FearlessTobi** [comment] 2020-01-02 21:13
Duplicate of https://github.com/citra-emu/citra/issues/2489.

**Closed by FearlessTobi** 2020-01-02 21:13 UTC
