### ISSUE TITLE
Intel (and nvidia) driver crash when loading Steel Diver Sub Wars

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#1251] opened 2015-11-23 18:02 UTC
As of 78b0d9c8b0279cc107c4b82e78e1e6b82a6edcb3 citra crashes the Intel driver a few moments after Steel Diver Sub Wars is loaded up, right after one of the glDrawArrays calls.
The nvidia driver keeps going but ultimately crashes citra when trying to exit ("A heap has been corrupted")

Tested on Intel HD 4600
Intel Driver Version: 10.18.15.4256

Attached is an Apitrace of the problem, running this until the last frame will also cause apiretrace to crash
https://drive.google.com/file/d/0B8Y3NfpjZ7WqS0pNZXlWTm1Ya2c/view?usp=sharing

**Comment by RavenHome1** [comment] 2015-11-24 15:53
@Subv 

AMD user here. i was able to go full in game assuming that we are talking about the same steel diver game, i managed to get a couple of min of game play, the game suffered nothing more than a couple of texture glitches and low frame rate and i was able to close out of emulator with no crashes on driver or citra

![capture 88](https://cloud.githubusercontent.com/assets/12820322/11371995/e5f7025a-92d3-11e5-91ff-4044ee281208.PNG)

![capture 99](https://cloud.githubusercontent.com/assets/12820322/11372021/001f3d8c-92d4-11e5-8637-ae2fa6f04137.PNG)

however there was an eye catching error on the console
![capture 101](https://cloud.githubusercontent.com/assets/12820322/11372053/20c530b4-92d4-11e5-9d53-ea97b2b292da.PNG)

also it does not boot in software render 
![console steel software](https://cloud.githubusercontent.com/assets/12820322/11372062/2eff5664-92d4-11e5-8ca2-1608ccd53cf3.PNG)

**Comment by Subv** [comment] 2015-11-24 16:11
I have updated the title and issue to reflect that i was talking about Steel Diver Sub Wars. Thanks for verifying that the normal Steel Diver game does not suffer from this

**Comment by RavenHome1** [comment] 2015-11-24 17:30
@Subv oh, ok no problem, i can get the other game dumped and tested if you want, assuming i can get my hands on one in a short time

**Comment by yuriks** [comment] 2015-11-26 04:59
Is this fixed by #1254 ?

**Comment by Subv** [comment] 2015-11-26 14:46
#1254 does not fix it

**Comment by yuriks** [comment] 2015-12-01 07:54
I can reproduce this. It seems to be memory corruption of some sort. Here it seems to crash when trying to clear the vertex vector.

**Comment by Subv** [comment] 2016-01-16 21:51
The Legend of Zelda: Majora's Mask also has this issue

**Comment by JayFoxRox** [comment] 2016-04-25 07:18
Is this still an issue with the latest HW-renderer? (Also I'm assuming this is a windows-only issue?)

**Comment by Subv** [comment] 2016-04-25 15:52
Huh, it doesn't happen anymore as of 28de7f584e25269a4914a6d11b000f7e817cc1b4 with Intel HD 4600 drivers 20.19.15.4331 on Windows 10. I wonder what fixed it.

**Closed** 2016-04-25 16:05 UTC
Labels: bug, D-hard, regression
