### ISSUE TITLE
Kirby Deluxe JPN - Crash on Second Level

### ISSUE THREAD

**Issue by JanetMerai** [citra-emu/citra#1346] opened 2016-01-08 12:10 UTC
![kirby deluxe jpn crash](https://cloud.githubusercontent.com/assets/4703831/12197640/eada393a-b5c5-11e5-92ee-8368a2797dc7.png)

Once you get on the star on the first level that shows you the A button and reach the next island, it crashes.
Citra build 0144b8e was used for this test.

Hope this is useful :3

**Comment by dogtopus** [comment] 2016-01-17 03:27
I experienced similar issue in the USA version.
Besides that, the game also randomly crashes the emulator when inside a level (no crash on menu, level select screen, etc., at least I didn't experience any)

Tested on latest master (as of write, commit 7b2d034)

Full backtrace attached:
```
#0  0x00007fffeb4083ff in ?? ()
#1  0x000000000074894a in Pica::Shader::Run (state=..., input=..., 
    num_attributes=3)
    at /home/user/src/citra/src/video_core/shader/shader.cpp:100
#2  0x000000000073ae98 in Pica::CommandProcessor::WritePicaReg (id=559, 
    value=1, mask=15)
    at /home/user/src/citra/src/video_core/command_processor.cpp:330
#3  0x000000000073bbdb in Pica::CommandProcessor::ProcessCommandList (
    list=0x7fffb4d2aa40, size=32)
    at /home/user/src/citra/src/video_core/command_processor.cpp:491
#4  0x00000000006a250f in GPU::Write<unsigned int> (addr=6384, data=1)
    at /home/user/src/citra/src/core/hw/gpu.cpp:361
#5  0x000000000068c6c7 in GSP_GPU::<lambda(u32, u32)>::operator()(u32, u32) const (
    __closure=0xab89d0 <GSP_GPU::ExecuteCommand(GSP_GPU::Command const&, unsigned int)::WriteGPURegister>, id=1596, data=1)
    at /home/user/src/citra/src/core/hle/service/gsp_gpu.cpp:361
#6  0x000000000068c86d in GSP_GPU::ExecuteCommand (command=..., thread_id=0)
    at /home/user/src/citra/src/core/hle/service/gsp_gpu.cpp:396
#7  0x000000000068ce01 in GSP_GPU::TriggerCmdReqQueue (self=0x9de8d60)
    at /home/user/src/citra/src/core/hle/service/gsp_gpu.cpp:521
#8  0x000000000069172f in Service::Interface::SyncRequest (this=0x9de8d60)
    at /home/user/src/citra/src/core/hle/service/service.cpp:77
#9  0x00000000007111b2 in SVC::SendSyncRequest (handle=720931)
    at /home/user/src/citra/src/core/hle/svc.cpp:231
#10 0x00000000007154cc in HLE::Wrap<SVC::SendSyncRequest> ()
    at /home/user/src/citra/src/./core/hle/function_wrappers.h:133
#11 0x00000000007142d4 in SVC::CallSVC (immediate=50)
    at /home/user/src/citra/src/core/hle/svc.cpp:1052
#12 0x00000000006cf76b in InterpreterMainLoop (cpu=0x9dd5ab0)
    at /home/user/src/citra/src/core/arm/dyncom/arm_dyncom_interpreter.cpp:6173
#13 0x00000000006b625b in ARM_DynCom::ExecuteInstructions (this=0x9dd4b90, 
    num_instructions=1000)
    at /home/user/src/citra/src/core/arm/dyncom/arm_dyncom.cpp:87
#14 0x0000000000677de3 in ARM_Interface::Run (this=0x9dd4ba0, 
    num_instructions=1000)
    at /home/user/src/citra/src/./core/arm/arm_interface.h:25
#15 0x0000000000677bd9 in Core::RunLoop (tight_loop=1000)
    at /home/user/src/citra/src/core/core.cpp:51
#16 0x000000000065b247 in EmuThread::run (this=0x9e15c30)
    at /home/user/src/citra/src/citra_qt/bootmanager.cpp:50
#17 0x00007ffff634187e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff57f0284 in start_thread (arg=0x7fffbf7fe700)
    at pthread_create.c:333
#19 0x00007ffff552d74d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```

**Comment by yuriks** [comment] 2016-02-28 07:50
Dupe of #1081

**Closed by yuriks** 2016-02-28 07:50 UTC
