### ISSUE TITLE
Join Multiplayer using URL instead of IP

### ISSUE THREAD

**Issue by DaniGTA** [citra-emu/citra#5517] opened 2020-08-20 11:05 UTC
I have a small rasberry pi server for citra at home, but i dont have a static IP but a static URL, can citra support URL for joining a multiplayer lobby ?

**Comment by FearlessTobi** [comment] 2020-08-24 12:41
Duplicate of https://github.com/citra-emu/citra/issues/5385.

**Closed by FearlessTobi** 2020-08-24 12:41 UTC
