### ISSUE TITLE
[Feature Request] Add the ability to set sound output in android

### ISSUE THREAD

**Issue by thenobletheif** [citra-emu/citra#6660] opened 2023-07-03 15:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

In setting-> audio, add a slider which determines citra's output volume. Preferably also with a toggle button to enable/disable sound output.

### Why would this feature be useful?

This would make citra better in several ways:
1. If a game is having sound issues, being able to turn down or disable audio output would reduce frustration while playing that game.
2. In game sound settings are not consistent in their menu location. Having the ability to manage sound in engine would be convenient.
3. By adding sound settings to citra, it would allow users to listen to their own preferred music or podcasts while playing games.

**Comment by SleepingSnakezzz** [comment] 2023-07-03 15:41
Duplicate of https://github.com/citra-emu/citra/issues/6239

**Closed by SleepingSnakezzz** 2023-07-03 15:41 UTC
