### ISSUE TITLE
add full screen mode

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#1354] opened 2016-01-10 19:43 UTC
please add a full screen mode which will help with variable refresh rate monitors

**Comment by linkmauve** [comment] 2016-01-10 19:51
3DS games don’t support variable refresh rate.

Also duplicate of #139.

**Closed by linkmauve** 2016-01-10 19:51 UTC

**Comment by RavenHome1** [comment] 2016-01-10 20:00
no game supports any variable refresh rate technology. this technology only relies on communication between the GPU and the monitor itself,  i don't see why it would not work with citra.

**Comment by yuriks** [comment] 2016-01-10 20:28
You could set the monitor video mode to whatever you want, but you would still need to display on 30/60 frames per second. It would only lead to stuttering.
