### ISSUE TITLE
 A couple of suggestions

### ISSUE THREAD

**Issue by jlalopez** [citra-emu/citra#3932] opened 2018-07-11 21:19 UTC
Hello everyone, first of all congratulations for your great work, I hope you can continue to improve this great emulator, I write this to make 2 suggestions and a question:
1-I would like to talk about the stereoscopic function which is in the graphics section, by activating the option the game screen is divided into 2 (so investigate is not only my pc), but I think it would be more effective if you took a design in which several layers of emulation were superimposed on each other (although this would increase the work of the CPU) but I think it would be worth trying.
2-I would also like to be able to run the program in an OpenGL 2 environment since there are a large number of PC models that are not compatible with versions 3 or higher and this could help increase the number of users and contributors that help improve the code.
3-Finally I would like to see how much progress is being made in the development of citra for Android devices?

**Comment by jroweboy** [comment] 2018-07-11 21:36
Thank you for the suggestions, but please understand that this is an issue tracker and not a forum for discussion :) At any rate, I'll answer your comments, but open a thread on the forums if you have any more suggestions or questions, as its more suited for this kind of chat. (Several developers get emailed about issues, and prefer to keep this strictly for issues features that are likely to be added)

1) This is emulating the 3ds stereoscopic 3d feature for passive 3d monitors. As such, its working as intended, and it doesn't make sense to try and hack a 3d feature into the emulator, when the original system already supports 3d.
2) There is a real reason for requiring opengl 3.3, and its not as easy as just changing a version number. We use several features from opengl 3.3 and its not something we can do with out. The biggest one we use is host geometry shader support (used for correcting interpolation in the glsl shader implementation). Without GL 3.3, those computers could only use cpu shader emulation, which is decidedly much slower, and they were already bottlenecked on the CPU anyway... Basically, it doesn't make any sense to lower the GL requirement as those computers couldn't get full speed without the features in GL 3.3
3) Zero progress. In theory, GLES 3.1 with android extension pack has 90% of the features the citra video core needs, but thats only one part that needs porting. The CPU JIT doesn't support host arm architectures, which is a major roadblock towards full speed android emulation.

Anyway, I will close this issue because like I said, this is an issue tracker and not a forum. I hope that answers some of your questions, and if you have any more, please ask on the forums. Thanks

**Closed by jroweboy** 2018-07-11 21:36 UTC
