### ISSUE TITLE
[Feature Request] Open top/bottom screen in new window 

### ISSUE THREAD

**Issue by Selrun1** [citra-emu/citra#6112] opened 2022-08-29 17:04 UTC
Give us the option to easily open the top or bottom screen out in a new window.
This would be an amazing feature to have and would make things like [this](https://steamdeckhq.com/tips-and-guides/how-to-play-3ds-games-dual-screen-with-citra-and-steam-deck/)  much easier (also shows it's possible and works pretty well)

Certain emulators already have this feature ( DeSmuME and I think cemu does too but I'm not sure)

**Comment by FearlessTobi** [comment] 2022-08-29 17:06
Duplicate of https://github.com/citra-emu/citra/issues/204.

**Closed by FearlessTobi** 2022-08-29 17:06 UTC
