### ISSUE TITLE
Harvest Moon 3D - A New Beginning can't creata the role by Citra

### ISSUE THREAD

**Issue by a8662686626** [citra-emu/citra#3351] opened 2018-01-08 14:37 UTC
The game can run from the beginning, when i create a character will stop by Citra.
Could you help me, i really want to play this 
![1515422015171](https://user-images.githubusercontent.com/35227605/34675407-7def5810-f4c4-11e7-8565-f6096fd6e891.jpg)
![1515422001385](https://user-images.githubusercontent.com/35227605/34675413-817ca492-f4c4-11e7-951d-9c97038fc4aa.jpg)

game.

**Comment by Hexagon12** [comment] 2018-01-08 14:49
Duplicate of #1583.

Requesting to close.

**Closed** 2018-01-08 15:59 UTC

**Comment by lilyxroses** [comment] 2018-06-12 01:56
I don't know either can anyone help?

**Comment by mailwl** [comment] 2018-06-12 02:11
try to use save file from real 3ds, maybe it helps
