### ISSUE TITLE
Gray Screen on MacOS after nightly update

### ISSUE THREAD

**Issue by cherrytwizzler** [citra-emu/citra#3782] opened 2018-05-26 22:43 UTC
Citra Version: 09982c3

When I run any game on the latest Citra Nightly, a gray screen comes up with full audio in the background. I figured this was a graphics issue bc when I shut off "Enable Hardware Shader" everything worked fine. My question is how can I resolve the issue without turning that function off?

Computer: 
MacOS High Sierra V10.13.4 (latest updates installed) 8 GB memory
Graphics Intel Iris Graphics 6100 1536 MB

Thanks!

**Comment by Hexagon12** [comment] 2018-05-27 06:03
Duplicate of #3772.

Requesting to close.

**Closed** 2018-05-27 11:21 UTC
