### ISSUE TITLE
Unchained Blades (NA) - Unknown GetPointer

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1416] opened 2016-02-19 19:00 UTC
The game freezes after logo, the emu reports about "Unknown GetPointer"

![001](https://cloud.githubusercontent.com/assets/13983158/13185816/348d8df2-d754-11e5-9f2d-311bafca6c67.jpg)

**Comment by JohnGodgames** [comment] 2016-02-19 19:13
Dupe of https://github.com/citra-emu/citra/issues/973

**Closed** 2016-02-22 16:43 UTC
