### ISSUE TITLE
[Feature Request] Map Controller Inputs to Hotkeys

### ISSUE THREAD

**Issue by TwosomesUP** [citra-emu/citra#6692] opened 2023-07-12 14:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Allow mapping controller inputs to Hotkeys. Currently this does not work and only allows mapping to keyboard keys. 

### Why would this feature be useful?

This feature would be useful for quickly accessing features such as screenshots, save state loading, and screen swapping when a keyboard is not within reach and while using a controller.

**Comment by SleepingSnakezzz** [comment] 2023-07-12 14:41
Duplicate of https://github.com/citra-emu/citra/issues/5885

**Closed by SleepingSnakezzz** 2023-07-12 14:41 UTC
