### ISSUE TITLE
[Feature Request] Hotkeys compatibility with controllers

### ISSUE THREAD

**Issue by TheMelonMedic** [citra-emu/citra#5697] opened 2021-01-19 23:33 UTC
I've been playing a couple games lately that either have characters that repeat the same long dialogue over again when I'm not expecting it, or long attack animations I don't want to watch every time, so I appreciate the alternate speed hotkey. Though I play with a DS4 controller so it's not very convienent having to press a hotkey on a keyboard every single time I want to speed something up. Could we get the ability to bind the hotkeys in the hotkey tab to controller buttons instead?

**Comment by FearlessTobi** [comment] 2021-01-31 02:20
Thanks for your request. This is a duplicate of https://github.com/citra-emu/citra/issues/4932 though.
Closing

**Closed by FearlessTobi** 2021-01-31 02:20 UTC
