### ISSUE TITLE
[Linux compilation] backend.cpp:258:1: error: control reaches end of non-void functio

### ISSUE THREAD

**Issue by KAMiKAZOW** [citra-emu/citra#4963] opened 2019-10-05 09:12 UTC
Under the newest openSUSE Tumbleweed (rolling release – pretty much the latest of everything like GCC) I get the following compilation error:

```
[  720s] [ 18%] Building CXX object src/common/CMakeFiles/common.dir/logging/backend.cpp.o
[  720s] cd /home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/build/src/common && /usr/bin/g++  -DARCHITECTURE_x86_64=1 -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DNDEBUG -DXBYAK_NO_OP_NAMES -D_FILE_OFFSET_BITS=64 -I/home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/src/. -I/home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/externals/fmt/include -I/home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/externals/./microprofile -I/home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/externals/./xbyak/xbyak  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -O3 -DNDEBUG   -Wall -Wno-attributes -std=gnu++17 -o CMakeFiles/common.dir/logging/backend.cpp.o -c /home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/src/common/logging/backend.cpp
[  722s] /home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/src/common/logging/backend.cpp: In function 'const char* Log::GetLogClassName(Log::Class)':
[  722s] /home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/src/common/logging/backend.cpp:258:1: error: control reaches end of non-void function [-Werror=return-type]
[  722s]   258 | }
[  722s]       | ^
[  722s] /home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/src/common/logging/backend.cpp: In function 'const char* Log::GetLevelName(Log::Level)':
[  722s] /home/abuild/rpmbuild/BUILD/citra-0.0.20191004+git.a7b18efe4/src/common/logging/backend.cpp:275:1: error: control reaches end of non-void function [-Werror=return-type]
[  722s]   275 | }
[  722s]       | ^
[  730s] cc1plus: some warnings being treated as errors
[  730s] make[2]: *** [src/common/CMakeFiles/common.dir/build.make:105: src/common/CMakeFiles/common.dir/logging/backend.cpp.o] Error 1

```

Complete log: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/citra/openSUSE_Tumbleweed/x86_64

See https://build.opensuse.org/package/view_file/home:KAMiKAZOW:Emulators/citra/citra.spec?expand=1 for further details.

Same bug as https://github.com/yuzu-emu/yuzu/issues/2787

**Comment by zhaowenlan1779** [comment] 2019-10-05 09:36
This is a warning that is promoted to an error with the command line flag. I think this warning does not really matter in this case as every possible log level/class is actually handled. I believe currently the best way to solve this problem (for you) is to look for a way to turn off `-Werror=return-type` for your build system.

We may still want to fix this warning though, probably by moving the `UNREACHABLE()` down a bit. (which will however then emit a `-Wswitch` warning, so I'm not so sure.)

**Comment by wwylele** [comment] 2019-10-05 14:35
Closing as you are not building citra using the correct flag as documented in wiki, so not a bug in citra. For others wondering why we have return-type warning triggered: recent gcc starts to choke on UNREACHABLE and generates false positive warnings there.

**Closed by wwylele** 2019-10-05 14:35 UTC
