### ISSUE TITLE
Kirby: Planet Robobot - Doesn't load

### ISSUE THREAD

**Issue by khang06** [citra-emu/citra#2348] opened 2016-12-18 00:32 UTC
The game goes to a black screen with the following log:
`[  22.612962] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::ThrowFatalError:171: Fatal error
[  22.613894] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::ThrowFatalError:174: Fatal error type: Generic
[  22.614382] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:144: PID: 0x0000000A
[  22.614879] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:146: REV: 0x00000000_0x0000EF6D
[  22.615364] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:148: TID: 0x00000000_0x00000000
[  22.615837] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:150: AID: 0x00000000_0x00000000
[  22.616307] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:151: ADR: 0x003743E0
[  22.616783] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:153: RSL: 0xFFFFFFFF
[  22.617255] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:154:   Level: 31
[  22.617727] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:155:   Summary: 63
[  22.618250] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:156:   Module: 255
[  22.618852] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:157:   Desc: 1023
[  22.619477] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::ThrowFatalError:184: Datetime: 2016/12/17 19:25:15`
It used to work before. (regression?) Notably, the same thing happens to MK7 with a similar crash log, except it's just stuck on the loading screen. Maybe Citra can't detect the config savegame anymore?

**Comment by joaozin23** [comment] 2016-12-18 01:13
![esboco 1](https://cloud.githubusercontent.com/assets/17303493/21290770/5d774814-c4ae-11e6-8893-607ccf3b2a94.png)

**Comment by joaozin23** [comment] 2016-12-18 01:13
Kirby: Planet Robobot

**Comment by mailwl** [comment] 2016-12-18 07:03
both games works for me. Maybe you has old config? try to delete file user\nand\data\00000000000000000000000000000000\sysdata\00010017\00000000\config

**Comment by khang06** [comment] 2016-12-18 07:11
I used a config dumped from my N3DS on 11.2 A9LH. The same exact file used to work previously. It also might be worth mentioning that I'm using the AppData/Roaming folder for the user folder.

**Comment by wwylele** [comment] 2016-12-18 07:37
boot here on 20b832c. And by removing my [system archives](https://github.com/citra-emu/citra/wiki/Dumping-System-Archives-and-the-Shared-Fonts-from-a-3DS-Console) I reproduce the error message. Please dump it (or if you have dumped it, make sure it is still there)

--------

This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://discuss.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid

**Closed by wwylele** 2016-12-18 07:37 UTC
