### ISSUE TITLE
[Feature Request] to add dual windows

### ISSUE THREAD

**Issue by Eternal-plasma** [citra-emu/citra#5432] opened 2020-06-26 06:00 UTC
I think it would be nice if we could have an option to split the one window with dual screens into 2 windows that could be moved around (yes I know you can change them to be side by side) :)

**Comment by FearlessTobi** [comment] 2020-06-26 12:57
Duplicate of https://github.com/citra-emu/citra/issues/204.
Please use the issue search the next time when opening a new one.

**Closed by FearlessTobi** 2020-06-26 12:57 UTC

**Comment by Eternal-plasma** [comment] 2020-06-26 18:34
Oops didn't see that sorry
