### ISSUE TITLE
Paper jam: Massive fps slowdown when fighting Goomba Wheel

### ISSUE THREAD

**Issue by Pedrii** [citra-emu/citra#2845] opened 2017-07-26 02:50 UTC
Console spams this: [ 109.398581] Service <Error> core\hle\service\service.cpp:HandleSyncRequest:95: unknown / unimplemented function 'GetStepHistory': port=ptm:u, cmd_buff[1]=0x18, cmd_buff[2]=0xB3315000, cmd_buff[3]=0x7F, cmd_buff[4]=0x30C, cmd_buff[5]=0xFFFFA68
[ 109.411143] Service.HID <Warning> core\hle\service\hid\hid.cpp:GetGyroscopeLowCalibrateParam:342: <STUBBED> called
[ 109.886759] Service <Error> core\hle\service\service.cpp:HandleSyncRequest:95: unknown / unimplemented function 'GetStepHistory': port=ptm:u, cmd_buff[1]=0x18, cmd_buff[2]=0xB3315000, cmd_buff[3]=0x7F, cmd_buff[4]=0x30C, cmd_buff[5]=0xFFFFA68
[ 110.028644] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:478: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.

Im using Nightly Build - f2f3910. Game runs perfectly but when i fight against that wheel, it goes down to 4fps. 

PD: Fighting against paper enemies lags a bit, and after Paper Mario joins, its unplayable.

**Comment by jroweboy** [comment] 2017-07-26 04:05
Closing this as a duplicate of https://github.com/citra-emu/citra/issues/2712 (they have a slightly different log, but neither of the logs have anything to do with the slow down)

**Closed by jroweboy** 2017-07-26 04:05 UTC
