### ISSUE TITLE
Majora's Mask 3D - Stops at the "This game supports Circle Pad Pro" screen.

### ISSUE THREAD

**Issue by allanxp4** [citra-emu/citra#2150] opened 2016-11-01 02:12 UTC
Commit ae2fab4, the latest at the writing of this. Compiled with VC++ 2015.

Game starts and loads fine. After creating a save file, however, something related to the IR communication of the circle pad shows on the console. The game sort of freezes, the loading animation still plays but you can't select the 'Don't use' option to bypass that screen.

**Comment by bunnei** [comment] 2016-11-01 15:29
This is a known issue and a duplicate of #965.

**Closed by bunnei** 2016-11-01 15:29 UTC
