### ISSUE TITLE
Monster hunter 4 ultimate when lauuch is stop responding and graphical issue

### ISSUE THREAD

**Issue by ardian17** [citra-emu/citra#2143] opened 2016-10-27 04:37 UTC
Monster hunter 4 ultimate when lauuch is stop responding and graphical issue

when i start citra the game is not responding or black screen
but i finised the file home folder 
and is not working
when i start the command line say graphical issue not respondng 
and however the emulator is not [responding]
and assualy the command says the grapichal fatal eror
![capture](https://cloud.githubusercontent.com/assets/23024892/19754775/be45cf0e-9c3a-11e6-85f8-0b911314cb24.PNG)
for the graphical:
![capture2](https://cloud.githubusercontent.com/assets/23024892/19755112/741cf31e-9c3d-11e6-8aaf-5b523f06a655.PNG)
Log for graphic:
![capture3](https://cloud.githubusercontent.com/assets/23024892/19755117/7ff932ec-9c3d-11e6-98b6-296b7c6e5aa1.PNG)
up picture is blakcsreen

**Comment by wwylele** [comment] 2016-10-27 05:24
I am confused. 

The first screen shot is apparently not on an official build, for the "dirty" git hash. We don't support unofficial build.

And for the second screen shot and the third one, do you mean it keeps black screen on launching? Possible dupe of #1979?

**Comment by tywald** [comment] 2016-10-28 13:27
I tested with this build which is 5 commits behind(cc7f115), no crash here, just unimplemented things.
![jhgjhkuyjhljhh](https://cloud.githubusercontent.com/assets/10337060/19807933/a9ce13f4-9d22-11e6-9aa0-6b6a8a047ce6.png)
![ghhrfgj](https://cloud.githubusercontent.com/assets/10337060/19807932/a9c8e320-9d22-11e6-9eb8-60ab2d055262.png)

**Comment by JayFoxRox** [comment] 2016-10-28 13:32
This issue is very confusing indeed (not technically, but the way it's described).
I'll close this now. Feel free to open a new issue if you have a technical information and confirmed that there is indeed a problem.

I guess we are all aware that none of the Monster Hunter games work at the moment. There are a handful of unimplemented features, performance problems and more.. If you have better ideas what exactly has to be changed or what problems exist, describe them more precisely. Always document wether you have the home folder, used interpreter / jit, hw / sw rendering, version used etc.

---

Closed as invalid, left unlocked for discussion if necessary

**Closed by JayFoxRox** 2016-10-28 13:32 UTC

**Comment by ardian17** [comment] 2016-11-07 00:13
my spec i5 6200u
nvidia 930mx
4gb ram

**Comment by ardian17** [comment] 2016-11-07 00:15
sorry i tested all of citra emulator offical and unoffical :v sorry 
can anything give me refreshing?
