### ISSUE TITLE
[Feature request] Have a window for each of the 3DS screens

### ISSUE THREAD

**Issue by Martype** [citra-emu/citra#5746] opened 2021-03-26 18:43 UTC
I had the idea of using https://spacedesk.net/ in combination with citra emu. I would like to put the 3DS touch screen onto my android tablet. It works good by dragging the citra window across both monitors side by side. Having the two 3DS screens in separate windows would allow to have each 3DS screen in full screen on different monitors. This would be a mindblowing experience boost imho :-)

**Comment by BreadFish64** [comment] 2021-03-26 18:52
Duplicate of #4780

**Closed** 2021-03-26 18:51 UTC
