### ISSUE TITLE
Rhythm Paradise Megamix (EUR) crashes on first level

### ISSUE THREAD

**Issue by weetabix-su** [citra-emu/citra#3664] opened 2018-04-17 17:51 UTC
Encountered with Citra nightly-656 (HEAD-cb36f9f), crashes upon loading "Karate Man" minigame in "Honeybee Land" level with a fresh savefile.

LOG:
```
[  59.499010] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:RegisterInterruptEvents:251: Registered type=2, pipe=3, event_handle=0x00180084
[  59.500672] Audio.DSP <Critical> audio_core/hle/hle.cpp:PipeWrite:181: pipe_number = 3 unimplemented
[  59.501218] Debug <Critical> audio_core/hle/hle.cpp:PipeWrite:182: Unimplemented code!
```

**Comment by Hexagon12** [comment] 2018-04-17 19:52
Duplicate of #2543

**Comment by weetabix-su** [comment] 2018-04-18 05:44
Thanks, noted. Any news when AAC will be implemented?

**Closed** 2018-04-18 07:36 UTC

**Comment by tommyTsaiTou** [comment] 2018-04-29 13:45
I have exproted a full passed 3ds save data to citra latest canary.
[citra_log.txt](https://github.com/citra-emu/citra/files/1958780/citra_log.txt)
latest canary log:
