### ISSUE TITLE
Separate Windows

### ISSUE THREAD

**Issue by Papermanzero** [citra-emu/citra#6091] opened 2022-08-04 20:48 UTC
It would be good to split the windows foe the pc version. Therefore apps like weylus can be used to control the touchscreen via tablet or mobile.

![ECD8E4D6-3903-4D93-AC67-847E5E9FF5BE](https://user-images.githubusercontent.com/10263536/182949626-5e5324e3-93c2-49b4-b683-2a841eb37ef8.jpeg)

This is a showcase. I used Citra and weylus to mirror the contet from citra to a second screen. I could control everything via realtime on the tablet. Howver the solution is currently buggy because of the used workarounds

**Comment by FearlessTobi** [comment] 2022-08-06 18:08
Duplicate of https://github.com/citra-emu/citra/issues/204.

**Closed by FearlessTobi** 2022-08-06 18:08 UTC
