### ISSUE TITLE
Pokemon Alpha Sapphire - Black Scree Issue

### ISSUE THREAD

**Issue by cxuy97** [citra-emu/citra#4505] opened 2018-12-14 13:57 UTC
Hello.
When i am in seafloor cavern and after defeating Archie the cinematic when the Kyogre awakening dont continue.
The rest of the game works fine, and this issue happens in 2 versions of citra, Canary and Nightly.

### System Specs:
Operating System: Windows 7 Ultimate 64 bits
CPU: Intel(R) Core(TM) I7-4790 CPU @ 3.60GHz
GPU: NVDIA GeForce GTX 960

### Others:
Citra Version: Citra Canary 1121
Game: Pokemon Alpha Sapphire

![sin titulo](https://user-images.githubusercontent.com/45876528/50007108-91b81780-ff8e-11e8-9538-3a0d360fa4c0.jpg)
![sin titulo2](https://user-images.githubusercontent.com/45876528/50007119-967ccb80-ff8e-11e8-9e75-935b03b733ba.jpg)

I tried everything, but nothing.
This is my savedata:
[main.zip](https://github.com/citra-emu/citra/files/2680298/main.zip)

**Comment by valentinvanelslande** [comment] 2018-12-14 13:59
Duplicate of #3691

**Closed** 2018-12-14 14:01 UTC

**Comment by cxuy97** [comment] 2018-12-14 14:16
> Duplicate of #3691

Yes, but I could not solve the problem.

**Comment by zhaowenlan1779** [comment] 2018-12-14 14:22
@cuxy97 This is an issue tracker for developers. This is a duplicate, meaning that we already know the issue and may investigate it in the future. I'm afraid you will have to wait until we fix the issue. In the meanwhile, as is commented in the original issue 3691, it seems you can change the language to workaround the freeze.

**Comment by cxuy97** [comment] 2018-12-14 14:49
@zhaowenlan1779 Thank you very much for your help, but how do I change the language of the game? I've tried everything but the game keeps showing up in Spanish.

**Comment by Tabish4675** [comment] 2018-12-23 07:13
@cxuy97 It may mean that your game is region locked. If not, you can change it in Emulation > Configure > System > Language
