### ISSUE TITLE
Mii Maker/Citra crashes if Software Keyboard (000400300000C802) is installed

### ISSUE THREAD

**Issue by NWPlayer123** [citra-emu/citra#3671] opened 2018-04-18 20:51 UTC
Citra auto-pastes whatever the System Settings username(?) is when you're setting the Mii name or Creator name, but if the Software Keyboard is installed, it will try to load the software keyboard, jump to invalid memory, complain about invalid read32s/read16s, and then after a bit Citra will auto-close/crash. Tested as of HEAD-2d372ba.

**Comment by valentinvanelslande** [comment] 2018-04-18 20:55
Duplicate of #3243

**Comment by Dragios** [comment] 2020-04-24 02:09
I think this is no longer an issue and can be safely close.

**Closed** 2023-04-27 21:25 UTC
