### ISSUE TITLE
[Feature request] CHD compressed file support

### ISSUE THREAD

**Issue by bajolzas** [citra-emu/citra#5434] opened 2020-06-27 14:28 UTC
I don't think this has been asked before, so I'd like to know if it is possible to add MAME's CHD (Compressed Hunks of Data) file support to citra.
It would allow us to greatly reduce the size of games, with lossless compression and in a streamable format.

**Comment by wwylele** [comment] 2020-06-27 14:50
This is a weirdly specific format that I have never seen being used on 3DS games in the community. I am closing this as a duplicate of #2808, which serves as a general feature request for compressed file format.

**Closed by wwylele** 2020-06-27 14:50 UTC

**Comment by bajolzas** [comment] 2020-06-27 18:42
> This is a weirdly specific format that I have never seen being used on 3DS games in the community. I am closing this as a duplicate of #2808, which serves as a general feature request for compressed file format.

It is not used on 3DS games because no 3DS emulator supports it...
Also as far as I am aware no console supports it either, it a format used by MAME for its games that was also adopted by other console emulators.

The fact that zip compression was already asked, does not make this a duplicate. Unlike 7z/zip this format is streamable, wich means its plug and play, no need to exctract, and its compression rate is on par with 7z.

**Comment by wwylele** [comment] 2020-06-27 19:43
A compression format being *streamable* means nothing for a game data. An emulator needs *random-accessable* game data to be able to use it. I don't see how CHD is better than 7z/zip or any other format for supporting random access. I tried to google it, but the lack of proper description also indicates its less known and I don't see why we should support a format that majority of users won't use

To clarify the definition of terms:
"stream": Read n bytes of data in a particular order (usually from file start to end) in O(n) time and O(1) extra space
"random access": Read n bytes of data in arbitrary order in O(n) time and O(1) extra space

**Comment by bajolzas** [comment] 2020-06-27 23:30
"format that majority of users won't use"
It is a format widely used on the emulators that do support it, there's no reason people wouldn't use it on citra as well.

**Comment by wwylele** [comment] 2020-06-28 03:04
Let me clarify another thing: I closed this issue as "a duplicate", not as "invalid", meaning we are still open to implementing compressed file format in general, while there is none implemented currently. Close as duplicate just meaning there is no particular reason to prioritize CHD over other format. Please move further discussion over to #2808.

**Comment by wwylele** [comment] 2020-06-28 03:18
Oh btw, have you noticed that all examples you listed are for consoles that uses optical disk as game media? Here is my guess: optical disk is inherently sequentially accessed (streamed), or at most randomly-accessed on track level, so a streaming format would be suitable. In contrast, 3DS uses cartridges, which allows byte level random access.

**Comment by Sanaki** [comment] 2020-06-28 10:00
CHD is directly seekable, but in the case of 3DS you'd be creating the CHD as a HDD image rather than a CD one. So far as I'm aware, nothing outside of MAME uses that style just yet, but I did open a request for supporting the same thing over at Arisotura/melonDS#642. In theory, it should be an optimal compression format.

**Comment by lonkelle** [comment] 2022-10-22 13:46
This would be a perfect addition to Citra as 3DS games can get a bit large.
