### ISSUE TITLE
[Android]Add local multi-player support 

### ISSUE THREAD

**Issue by Hariu7** [citra-emu/citra#7302] opened 2023-12-30 08:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I felt very sad I know android citra has no local multi-player support as pc version has it. It is not resone that citra android is in development because citra mmj has local multi-player support which is copy of citra. Yuzu android also does not have this

### Why would this feature be useful?

This feature will very useful

**Comment by FearlessTobi** [comment] 2023-12-30 11:34
Duplicate of https://github.com/citra-emu/citra/issues/7247.

**Closed by FearlessTobi** 2023-12-30 11:34 UTC
Labels: request
