### ISSUE TITLE
[Feature Request] Use Joystick buttons as shortcuts

### ISSUE THREAD

**Issue by Shideravan** [citra-emu/citra#5650] opened 2020-12-21 23:03 UTC
I think that is a nice idea to config controller buttons as shortcuts (p. e.: LT for save state and RT for load) as we can do in other emulators.

Thanks!

**Comment by FearlessTobi** [comment] 2021-01-04 04:23
Duplicate of https://github.com/citra-emu/citra/issues/4932.

**Closed by FearlessTobi** 2021-01-04 04:23 UTC
