### ISSUE TITLE
When loading up a game, it dosnt load and "read:181 unmapped read8 @ 0x100000011" gets spammed in the console

### ISSUE THREAD

**Issue by BmanGames** [citra-emu/citra#1791] opened 2016-05-13 21:48 UTC
Title says it all.

**Comment by JayFoxRox** [comment] 2016-05-13 21:53
Closed as invalid because there is not enough information.
Please provide more details:
- Which game
- When does it happen
- Post a full log
- Does the game hang / freeze? does the screen stay black?
- What PC did you use?
...

Memory read/write errors are common, it's more important to figure out how serious they are and what they imply.

**Closed by JayFoxRox** 2016-05-13 21:53 UTC
Labels: invalid

**Comment by KillzXGaming** [comment] 2016-05-13 21:58
Dupe of mine #1790 anyways
