### ISSUE TITLE
"Invalid Texture Format" Upon Executing Lua Code Through ctruLua in Citra

### ISSUE THREAD

**Issue by Saphiresurf** [citra-emu/citra#1631] opened 2016-04-02 08:09 UTC
EDIT: After exiting out and relaunching, the error is no longer encountered which makes it unrecreatable for me. This bug may be best closed because of this.

1. Place a main.lua file with the code here: https://ghostbin.com/paste/5jdf2  into the root of citra's SD card (SDMC/)

2. Downlaod the "Most recent working build" underneath the "Builds" section in their readme (https://github.com/ctruLua/ctruLua, direct link: http://ci.reuh.tk/ctrulua/builds/latest/artifacts/ctruLua.3dsx)

3. Launch ctruLua.smdh

4. Screen is black, repeats this over and over in the log
```
[ 465.022880] Render.OpenGL <Error> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:444: API ERROR 1281: GL_INVALID_VALUE error generated. Invalid texture format.
```

NOTES:
-Executes as it should (a red flashing screen, black circle in the top screen; top left corner, black pixel created where you're touching on the bottom touch screen, this is by far WIP code) on a physical New 3DS XL through the Homebrew Menu on 10.7

**Comment by JayFoxRox** [comment] 2016-04-02 14:14
Steps to reproduce don't reproduce for me either.

**Comment by wwylele** [comment] 2016-04-02 14:46
Works fine here. I can't reproduce it either.
(The flashing screen is really a eye killer, please close this...)

**Comment by Saphiresurf** [comment] 2016-04-05 06:51
This code still haunts me in dreams

**Comment by bunnei** [comment] 2016-04-12 02:02
This seems like an issue on your end - What is your GPU? Do you have the latest drivers?

**Comment by JayFoxRox** [comment] 2016-04-24 21:30
As nobody was able to reproduce it and because of a lack of responses I'll close this. Contact me if you can reproduce it

**Closed by JayFoxRox** 2016-04-24 21:30 UTC
