### ISSUE TITLE
Shader compilation occasionally breaking the HOME menu

### ISSUE THREAD

**Issue by c4artisan** [citra-emu/citra#6415] opened 2023-04-04 22:54 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Citra Nightly 1875 (and Canary 2443)

### Description of Issue

the HOME menu's OpenGL transferable shader file will occasionally (and most likely always) make the menu crash on boot. The only solution to it as of now is to delete the file and reduce the time inside the menu to the minimum.

### Expected Behavior

the HOME Menu's shaders will not cause any issues and it will boot normally.

### Reproduction Steps

Stay in the HOME Menu for a long while
Wait for it to crash (it will either just freeze, or hang)
Try and boot it again (Citra will crash.)

### Log File

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/11153802/citra_log.txt.old.txt)

### System Configuration

CPU: Intel Core i5 11600K
GPU/Driver: NVIDIA GeForce RTX 3050
RAM: 32GB
OS: Windows 11

**Comment by SleepingSnakezzz** [comment] 2023-04-04 23:16
Please check whether this issue still persists on the latest Citra Canary.

**Comment by c4artisan** [comment] 2023-04-04 23:42
> Please check whether this issue still persists on the latest Citra Canary.

It does.

**Comment by c4artisan** [comment] 2023-04-04 23:52
It doesn't. Reopening if it reappears.

**Comment by c4artisan** [comment] 2023-04-04 23:53
Actually i'll leave it open in case

**Comment by SachinVin** [comment] 2023-04-20 17:18
Close as dupe of #6429

**Closed by SachinVin** 2023-04-20 17:18 UTC
