### ISSUE TITLE
Unimplemented function "reply sleep query"

### ISSUE THREAD

**Issue by gidoly** [citra-emu/citra#5910] opened 2021-12-21 04:35 UTC
Davil surviver 2 break record soft locks due to lack of this function

**[  14.694322] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ReplySleepQuery': port='APT:U' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}
[  14.708174] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001**

**Comment by vitor-k** [comment] 2021-12-21 11:11
duplicate of #2151

It's also not likely that that's the cause of your crashing, as that function is commonly called by many games without issues.
If you have a problem with a game crashing or softlocking, please always provide the citra version, a complete log file, a detailed description of how and when it happens.

**Closed** 2021-12-21 11:50 UTC
