### ISSUE TITLE
Phoenix Wright: Ace Attorney - Dual Destinies - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1597] opened 2016-03-28 12:27 UTC
Spams with:

```
[ 148.476101] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:304: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFDA70, buffer2_addr=0x0FFFDA74
[ 148.476426] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'ReplySleepQuery': port=APT:U, cmd_buff[1]=0x300, cmd_buff[2]=0x66630000
[ 148.476600] Service.APT <Error> core\hle\applets\applet.cpp:HLE::Applets::Applet::Create:56: Could not create applet 1031
```

[LOG](http://pasted.co/8659691d)

**Comment by exhalatio** [comment] 2016-03-28 21:20
Looks like bootup in https://github.com/citra-emu/citra/issues/1521 a2024d7

**Comment by TheDcoder** [comment] 2016-04-21 06:52
Same here, Both screens are black. Here is my log (trimmed to 100 lines, actual file is ~50 MB): http://pastebin.com/MXZ5G43D

**Comment by exhalatio** [comment] 2016-05-06 10:12
applet 1031 is eShop applet (mint).
I was tested a patch to create applet, that was bootup with Missing graphics.
So, in order to work this game implement mint and geometry-shader.
https://github.com/exhalatio/citra/tree/hack_mint

**Comment by TheDcoder** [comment] 2016-05-08 02:49
@exhalatio I just tested on Fedora 23 but its still not running :(

Still spamming but a different message this time (will post the log soon)

**Comment by exhalatio** [comment] 2016-05-08 11:06
@TheDcoder I feel you wait a moment to see a intro movie by my patch.
also additional merged JayFoxRox's geometry-shader yourself.

**Comment by TheDcoder** [comment] 2016-05-08 11:23
@exhalatio Does that mean I have to merge JayFoxRox's citra fork with your own?

**Comment by exhalatio** [comment] 2016-05-08 11:29
@TheDcoder Yes, that’s right.

**Comment by TheDcoder** [comment] 2016-05-08 12:24
@exhalatio can't merge @JayFoxRox 's fork with yours... "Automatic merge failed; fix conflicts and then commit the result."

And I can't fix the conflicts because I am not a C++ programmer :cry:

**Comment by dcastro** [comment] 2016-05-17 21:41
@JayFoxRox's, do you plan on merging your branch with master? Thanks.

**Comment by JayFoxRox** [comment] 2016-05-17 22:31
Removed useless posts about people trying to merge GS by @exhalatio, @TheDcoder and @dcastro . And to answer one of the removed posts: Yes, I'm merging my GS branch as we speak (see PR 1750, 1757, 1780, 1783, 1787, 1812).

**Comment by TheDcoder** [comment] 2016-05-18 08:13
I just tried... Still not booting :(

Console/Terminal Output: https://ghostbin.com/paste/xxodo

**Comment by anirudh8860** [comment] 2016-08-21 17:36
The link for hack_mint is giving 404 now. What should I do?

**Comment by TheDcoder** [comment] 2016-09-25 05:15
I have just confirmed the issue with the latest version, still not booting :(

**Comment by Subv** [comment] 2016-11-30 00:12
It's trying to open the eShop applet? (Mint)

**Comment by TheDcoder** [comment] 2016-11-30 13:37
Yes @Subv, still trying to open eShop applet (1031). Tested with latest:
`[  39.693744] Service.APT <Error> core/hle/applets/applet.cpp:Create:60: Could not create applet 1031`

**Comment by wwylele** [comment] 2017-06-13 12:35
Closed as the Mint applet is stubbed and can bypass this issue

**Closed by wwylele** 2017-06-13 12:35 UTC
