### ISSUE TITLE
Can't open folder locations

### ISSUE THREAD

**Issue by Mars7x** [citra-emu/citra#6927] opened 2023-08-27 03:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1978

### Description of Issue

Pressing "Open 'x' Location" doesn't do anything.

Partially related to #6337

### Expected Behavior

Location of the folder to open.

### Reproduction Steps

1. Right click a title
2. Open any location
3. Location doesn't open

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12447194/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 7 3700X
GPU/Driver: AMD Radeon RX 5600 XT
RAM: 32GB
OS: Fedora 38

**Comment by FearlessTobi** [comment] 2023-08-27 21:28
Closing as duplicate of https://github.com/citra-emu/citra/issues/5059 and https://github.com/citra-emu/citra/issues/4471.

**Closed by FearlessTobi** 2023-08-27 21:28 UTC
