### ISSUE TITLE
Theaterythm Final Fantasy Curtain Call Circle Pad dropped/delayed Inputs

### ISSUE THREAD

**Issue by AuraOfTheDawn** [citra-emu/citra#3012] opened 2017-10-18 00:19 UTC
Circle Pad inputs drop or heavily delay randomly on slide triggers in this game. Button presses NEVER suffer from this delay, and slide inputs done with the stylus function with no flaws, only slide inputs with the circle pad will intermittently drop or delay. Issue was replicated across 2 gamepads (DS3 emulating keyboard, and a Logitech F710 in xinput mode), as well as with the circle pad controls mapped to keyboard buttons (direction arrows in this case).

Circle pad suffers no flaws noticable while navigating menus or any other aspect of gameplay except during slide triggers on songs.

Tested on citra nightly - Head e9d1e8c

Upon request, I included a savefile to render testing possible without being forced to play through tutorials, though the flaw exists across all songs (although as short as tutorials were, it may not be noticed in the few inputs one woud make)

Also included a video showing input captured through windows gamepad testing function, adjacent to citra's topscreen, where you can see the input entered, but ignored by the game.

[2017-10-17_20-08-32.zip](https://github.com/citra-emu/citra/files/1393026/2017-10-17_20-08-32.zip)

[savedata.zip](https://github.com/citra-emu/citra/files/1392973/savedata.zip)

Also a sample video clip of the issue from a second user with a different model of controller, exhibiting the same problem https://drive.google.com/file/d/0B9etscnwTNrnN2hVNVlMRmF2c1U/view

**Comment by magnoelcabiadito** [comment] 2018-01-30 01:39
aye, same problem here, but only top and left inputs suffer this problem for some reason, down and right will work perfectly, super weird.

**Comment by benderscruffy** [comment] 2018-02-05 11:10
is this a duplicate of  #2066 ???

**Comment by agentgerbil** [comment] 2018-06-22 05:37
i was able to fix this problem by going into input configuration on the emulator and hitting the "Set Analog Stick" button instead of manually entering the 4 circle pad directions separately.

**Comment by AuraOfTheDawn** [comment] 2018-09-24 04:41
So while poking at this again, I determined an easier way to replicate it. If I hit the analog mode button on a controller (so that it uses the dpad instead of the analog stick) up and left fail universally. This also occurs if I map the 4 directions to keyboard buttons (any keyboard buttons). Hope this helps make it easier to test and track down.

**Comment by Valetek** [comment] 2020-01-10 14:05
There is someone on this thread again ? nobody have found a way to resolve this bug even now it's really frustrating

**Comment by xperia64** [comment] 2020-04-26 07:25
This bug is indeed a duplicate of #2066. Please close.

**Closed** 2020-04-26 08:05 UTC
Labels: has-games-wiki-entry
