### ISSUE TITLE
Citra Windows. SBS Eyes are reversed

### ISSUE THREAD

**Issue by drowhunter** [citra-emu/citra#5604] opened 2020-11-12 05:42 UTC
In SBS the eyes are reversed.  Please add an option to switch eyes

**Comment by FearlessTobi** [comment] 2020-11-24 22:17
Duplicate of https://github.com/citra-emu/citra/issues/4255.

**Closed by FearlessTobi** 2020-11-24 22:17 UTC

**Comment by Dragios** [comment] 2020-11-25 02:28
Side by Side displays the same image for both left and right eye. Why do you need in reverse order if it changes nothing?

**Comment by drowhunter** [comment] 2020-11-30 02:07
what? Left eye image is for left eye and Right eye image is for right eye.

When i put my 3d glasses on the images are in the wrong side so the background appears ahead of the foreground.

**Comment by Dragios** [comment] 2020-11-30 08:29
This is the Side by Side Stereoscopic 3D view which shows both left and right eye display the same image. So my question is why does it need to be reversed? Unless of course you're not talking about Side by Side but some other 3D view.
![image](https://user-images.githubusercontent.com/18496868/100585764-11c91a80-3329-11eb-8974-6bc0f7f4249e.png)

**Comment by drowhunter** [comment] 2020-11-30 14:38
The 3DS is a 3D gaming console.

When sliding the slider on the console the system renders two viewes ( 1 per eye) this gives the illusion of depth or parallax in 3D scenes.

Objects closer to you will be further apart and objects further away from you will be almost identical.

When enabling the Steroscopic view there are several options in the emulator for displaying the original 3ds views in common 3D formats.

Some common 3d formats are Side By Side
Too and Bottom, Line Intetlaced etc

Whats important here is the the camera view of a 3d scene for the left eye MUST be on the left and the right Eye on the right.  Otherwise everytjing looks screwed up.

I will try to take a screen shot of metroid prime 2 later.  

One way to see the depth is to look at the sbs imagr in citra and cross your eyes until the two sides converge.

You will see a virtual image in the center with depth.

I found a reshade fikter that was able to convert the sbs fullscreen image and convert it to Line Interlaced.  Im sure it would be easy to mod it to simply flip the side that the L-R images are rendered to   

But was hoping for a simple "swap eyes" checkbox next to the rest of the stereo scopic options.

**Comment by drowhunter** [comment] 2020-11-30 14:58
These are the settings im talking about
![stereosettings](https://user-images.githubusercontent.com/2817488/100624860-e4ad4580-32f1-11eb-92ac-5549b2cf368f.png)

you cannot look at a 2d screenshot like you posted to see any difference.  you must look at 3d
![image](https://user-images.githubusercontent.com/2817488/100625062-1b835b80-32f2-11eb-9276-3425017bafea.png)

heres a video.
https://www.youtube.com/watch?v=b-xWzypidOo&app=desktop

This screenshot looks fine.  the left and right eye image are ok, but this is not the problem.  Some tv's can only display the image in reverse.  

Notice in that screen shot of the settings there is a Reversed interlaced 

What i need is one more option there Reversed Side By Side .

**Comment by drowhunter** [comment] 2020-11-30 15:02
note i'm not talking about the Side by Side layout. This has nothing to do with stereo 3d and I can see how that would be confusing

![ACYk2wMOqy](https://user-images.githubusercontent.com/2817488/100625940-2985ac00-32f3-11eb-90b4-158180f785d6.png)

**Comment by drowhunter** [comment] 2020-11-30 15:04
![b7mv4VCAVy](https://user-images.githubusercontent.com/2817488/100626048-4c17c500-32f3-11eb-818a-6ac3ffc2a749.png)

note i am NOT talking about the Side By Side Layout option.  I can see how that would be confusing since they are literally called the same thing.
