### ISSUE TITLE
Harvest Moon The Lost Valley Texture and Freeze Problem

### ISSUE THREAD

**Issue by amirlou** [citra-emu/citra#1743] opened 2016-04-30 22:25 UTC
hello so after testing this game with current master i found some problems
1-game got bad texture and buggy screen with jit-Enable
2-game Freeze after first time sleep in game and show only black screen

here is some pic with jit-enable

![xx2 2016-05-01 01-27-25-71](https://cloud.githubusercontent.com/assets/16171668/14938850/04f25d40-0f47-11e6-8edd-635a435afeb5.jpg)

this one with Jit-Disable

![xx2 2016-05-01 01-27-35-33](https://cloud.githubusercontent.com/assets/16171668/14938852/137a9620-0f47-11e6-9460-9103859815b9.jpg)

logs here
https://jpst.it/I1oa

**Comment by amirlou** [comment] 2016-05-04 16:15
just tested this game with current Master (DSP HLE)  game just got graphics problem with jit rest is ok i play it for an hour

**Comment by JayFoxRox** [comment] 2016-05-11 21:41
Unable to reproduce on 86ecbdf + JIT:
![master](http://i.imgur.com/DYaY62F.png)

What CPU do you use?
ftr: I'm on 'model name	: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz' (linux users can use `cat /proc/cpuinfo`)

The panel is drawn in 4 draw calls. I've dumped the shader just-in case but won't upload it unless necessary

**Comment by amirlou** [comment] 2016-05-12 13:00
im using a old cpu AMD Athlone(tm) II x2 240 processor 3.50ghz

**Comment by JohnGodgames** [comment] 2016-05-13 12:46
It's ok on my side (JIT enabled):

![harvest valley](https://cloud.githubusercontent.com/assets/11453507/15248236/655f9bda-1919-11e6-8246-727606fa812f.JPG)

CPU - Intel Core i7 6700K @ 4.60 Ghz
RAM - 16 GB DDR4
GPU - GTX 970 GAMING 100ME 4GB
OS  - Windows 10 64bit

**Comment by JayFoxRox** [comment] 2016-12-03 04:34
Please re-test now. #2255 is merged

**Closed** 2016-12-04 10:20 UTC
Labels: A-graphics, F-gpu:shader-jit
