### ISSUE TITLE
Life bar is not displayed in Puzzle and Dragons Z Plus Puzzle and Dragons Super Mario Bros Edition

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#5408] opened 2020-06-12 20:11 UTC
The enemies ife bar is not displayed in Puzzle and Dragons Z Plus Puzzle and Dragons Super Mario Bros Edition. 

Version of Citra: Citra Canary 1773

Ryzen 5 3600
Nvidia GT 1060 6GB

**Comment by FearlessTobi** [comment] 2020-06-13 00:21
This issue is missing a log file (again)

**Comment by Amnesia1000** [comment] 2020-06-13 00:25
Log File
[citra_log.zip](https://github.com/citra-emu/citra/files/4773724/citra_log.zip)

**Comment by Fijiboy99** [comment] 2020-06-25 17:53
I'm having the same issue

**Comment by Fijiboy99** [comment] 2020-06-26 17:28
Let me know if you find a fix for it, the game's pretty heavily damaged by this issue.

**Comment by Schplee** [comment] 2020-12-16 08:01
Duplicate of #5139

**Closed by Schplee** 2020-12-16 08:01 UTC
