### ISSUE TITLE
Can't generate project files for the build

### ISSUE THREAD

**Issue by hi563145** [citra-emu/citra#2420] opened 2017-01-09 06:12 UTC
I am building my citra but it give me an error when I am generating project files for the build.
I paste this in cmake .. -GXcode to my terminal just like the wiki but my terminal gave me this error

 -- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:36 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:36 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!

Can anyone help me?

**Comment by jroweboy** [comment] 2017-01-09 06:17
Please open this on the forum instead. This is not a support forum, but a place for developers to track bugs instead. Closed as invalid.

----

(To save you some time, the issue is you didn't install the xcode commandline tools so cmake cant find the compiler. You can try to install them from the command line by typing gcc in the terminal and it usually brings up a "would you like to install the Xcode Commandline tools?" confirm dialog. Please don't respond here. If you need more help open an issue on the forums.)

**Closed by jroweboy** 2017-01-09 06:17 UTC
