### ISSUE TITLE
Citra not opening on el capitan 10.11.5

### ISSUE THREAD

**Issue by xxJuiceboxx1** [citra-emu/citra#1958] opened 2016-07-17 07:15 UTC
Following the guide of someone else who recorded the same issue, doing "brew update && brew upgrade qt5" does not seem to work.

Every time i try to run the citra build citra-20160714-f95d119-osx it says the applicated closed unexpectedly. I've taken the report log and uploaded it to here: http://textuploader.com/5edjy

Any ideas?

![screen shot 2016-07-17 at 5 14 53 pm](https://cloud.githubusercontent.com/assets/20021804/16899283/0197dcaa-4c42-11e6-823f-7be88a3b6d64.png)

**Comment by jroweboy** [comment] 2016-07-17 07:52
So, this is a rather frustrating issue for me, since I'm one of the few devs that have OSX, and I can't reproduce it. The latest build works fine for me on mac. I went ahead and poked around QT's source code because thats where the crash says it occurs. It says it crashed in QWidgetPrivate::init which i found here http://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/kernel/qwidget.cpp?h=5.6.1#n1121 and the particular line that I linked was the only fatal error in the function. So... as far as I can reckon, its saying that we didn't init a QApplication first, but we clearly do right here https://github.com/citra-emu/citra/blob/master/src/citra_qt/main.cpp#L584 Does that mean that the QApplication creation somehow failed? I dunno... if i could just reproduce the error it'd be much easier :smile:

**Comment by xxJuiceboxx1** [comment] 2016-07-17 10:08
Yeah i can understand that devs will be receiving a range of issues, but if it assists at all, running an older version of citra seem to run ok. Other than that, it just doesn't seem to run my .3ds as it is unsupported for now

**Comment by MerryMage** [comment] 2016-07-17 11:23
> running an older version of citra

Would you happen to know which version was the first version to start having this problem? (Finding out would be helpful.)

**Comment by xxJuiceboxx1** [comment] 2016-07-17 13:52
I actually haven't used citra too much as of recently (waiting for more stable versions), but the issue came on **citra-20160714-f95d119-osx** but finding an older one **citra-20160312-2f0a61d-osx** is where it started to work for me. Sorry i can't narrow it down any further than that

**Comment by jroweboy** [comment] 2016-07-17 14:47
Merry, people in the forums were saying it was sometime in June that it
stopped working.

**Comment by JayFoxRox** [comment] 2016-07-17 16:01
Clearly a dupe of https://github.com/citra-emu/citra/issues/1932

Closed as invalid

**Closed by JayFoxRox** 2016-07-17 16:01 UTC
