### ISSUE TITLE
Rhythm Heaven Gold desync with HLE audio.

### ISSUE THREAD

**Issue by n1ghttrap** [citra-emu/citra#5045] opened 2020-01-02 17:10 UTC
Any plans to resolve this in HLE or is this purely a "wait for LLE to get faster" thing?  I've seen the closed topics on this, and just thought I'd bring it up again as it's been awhile.  LLE is not viable for playability/real time use (even with a 3700x and multithreading) and HLE is still broken.

**Comment by xperia64** [comment] 2020-04-11 23:15
You're referring to the minigames being too fast, correct? If so, this issue is a duplicate of #4649

**Comment by Subv** [comment] 2020-04-12 00:31
Closing as duplicate of #4649

**Closed by Subv** 2020-04-12 00:31 UTC
