### ISSUE TITLE
Frustrating lost of controller (xbox one) because there is no refresh on the input catch!!!!!

### ISSUE THREAD

**Issue by PatValois** [citra-emu/citra#3793] opened 2018-05-30 01:16 UTC
If I'm loosing the sync (on the controller) for whatever reason, I have to close the emulator and restart it to get the controller back (welcome lost of data), which is really frustrating. There is no way to tell the engine to check again.  :(

**Comment by jroweboy** [comment] 2018-05-31 23:37
Closing as a duplicate of https://github.com/citra-emu/citra/issues/2056

As a workaround, sometimes after the controller reconnects you can open up the configure menu and close it which will force citra to reload controllers.

**Closed by jroweboy** 2018-05-31 23:37 UTC

**Comment by PatValois** [comment] 2018-06-01 01:53
I’ve tried this plenty of time, even opening the controllers specific menu, it was not working. I’ve seen that in other games on occasion but I was not aware of it for Citra, so I’ve lost like 1h of gameplay 2 times. It was frustrating though, because it was the same 2 hours of gameplay and now, I have to do the same hour of gameplay for a third time if I want to progress in the game. haha :P 

Well, I’ll be careful about that from now on.

**Comment by jroweboy** [comment] 2018-06-01 15:48
You mean after you controller reconnected you didn't just change the controls back to keyboard and the use the keyboard to save?

**Comment by PatValois** [comment] 2018-06-01 18:00
Nope, had not thought about it, would have been better. I would have to redo all the controller settings afterward, though, is one year old…which is still a pain in the ass to do every time. It's OK, from now on, I'm just presuming it's not gonna be fixed at all and I save to every save point I see.

**Comment by jroweboy** [comment] 2018-06-01 18:07
It will be fixed someday (i have a branch that fixes it, but its really
ugly, and i'm working on other projects right now) Controller code is lower
priority for me as there are a few other tasks that need to be fixed first.
