### ISSUE TITLE
Fire Emblem Fates:IF Issue (Hard Crash)

### ISSUE THREAD

**Issue by Monoken3** [citra-emu/citra#3725] opened 2018-05-07 07:38 UTC
This is something I noticed acquiring every time I feed Lilith dragon pet or when I advance some job my game drops fps to 0 and screen just gets frozen. It only happens under certain conditions though.

Number 1: There is no BGM in this case you reset game until there is sound coming
Number 2: You Enter building and game lags/stutters (minor graphical glitches)
Number 3: Always happens second time you do repeated action (like in case of job advance when I give Heart Seal it's fine but if I do it on 2nd character right after 1st one game crashes 100% of the time.)

Will there any progress on this types of bugs/glitches for the future of Citra or games like this are doomed and see no light of day. 

If there is something to help with I can always try to learn and do it myself if that something is on game side but as it comes to Citra I'm clueless on what's the issue. I'm guessing most of the games incompatible not because they don't work is because Citra is not a complete project yet. It's very Intriguing on how C++ program tackles each .3ds or .cia different ways.

**Comment by Hexagon12** [comment] 2018-05-07 07:50
Duplicate of #3443 .

Requesting to close.

**Closed** 2018-05-07 07:56 UTC
