### ISSUE TITLE
Rabbids 3D glitch

### ISSUE THREAD

**Issue by Kmog2185** [citra-emu/citra#6520] opened 2023-05-08 10:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All

### Description of Issue

When opening Rabbids 3D, the game's top screen doesn't display properly, showing half the screen in just black. This happens only in cutscenes.

### Expected Behavior

It's supposed to show the entire screen.

### Reproduction Steps

Open the game.

### Log File

No log file

### System Configuration

CPU: Octa-core
GPU/Driver: Adreno 610
RAM: 4GB
OS: Android 11

**Comment by benderscruffy** [comment] 2023-05-08 11:01
duplicate of #3308

**Closed** 2023-05-08 11:59 UTC
