### ISSUE TITLE
In Mini Mario & Friends: Amiibo Challenge when a toy is sliding on any steep hill, the game clash while the BGM continues

### ISSUE THREAD

**Issue by Darth-Koopa** [citra-emu/citra#4712] opened 2019-03-24 12:28 UTC
The log says:HW.GPU <Error> video_core/command_processor.cpp:WritePicaReg:127: Commandlist tried to write to invalid register 0x1055A (value: 00000000, mask: 0)

**Comment by wwylele** [comment] 2019-03-24 12:28
Full log please

**Comment by Darth-Koopa** [comment] 2019-03-24 12:33
[citra_log.txt](https://github.com/citra-emu/citra/files/3000374/citra_log.txt)

**Comment by Darth-Koopa** [comment] 2019-03-24 12:34
![Picture](https://user-images.githubusercontent.com/45894930/54879462-32fb1780-4e74-11e9-8da8-c5531deb2895.png)

**Comment by FearlessTobi** [comment] 2019-03-24 22:26
`The option 'is_new_3ds' is enabled as part of the 'System' settings. Citra does not fully support New 3DS emulation yet!` Regenerate your config file in the settinga and try again.

**Comment by Darth-Koopa** [comment] 2019-03-25 00:03
[citra_log.txt](https://github.com/citra-emu/citra/files/3001035/citra_log.txt)
I disabled new 3ds mode and the bug is still there

**Comment by SleepingSnakezzz** [comment] 2023-04-28 17:47
Please try this issue again on the latest Citra Nightly build.

**Comment by Darth-Koopa** [comment] 2023-04-29 20:07
> 

![image](https://user-images.githubusercontent.com/45894930/235322239-c5a40916-e386-45b5-8b29-4c00f0aaebd2.png)
I tried in Nightly 1894 and the issue is still present.

**Comment by GPUCode** [comment] 2023-09-02 16:23
Can you uplaod a save file for the stage that freezes?

**Comment by benderscruffy** [comment] 2023-09-03 02:20
duplicate of #3183

**Comment by benderscruffy** [comment] 2023-09-03 02:32
here is a save for Mario vs. Donkey Kong: Tipping Stars #3183
[Progress.zip](https://github.com/citra-emu/citra/files/12505058/Progress.zip)

just choose 1-3
just make a diagonally going down on the angle next to the first mini and then click on it
when it goes to walk down the slope
it freezes up with the error

**Comment by Dragios** [comment] 2023-09-03 02:37
@GPUCode I don't think save is needed in this case. Starting new game at Level 1-1, as long you create diagonal girder, and when the mini-toy walks up, will immediately exhibit this issue.

_Note: You need to load Amiibo before can proceed with playing though._
![image](https://github.com/citra-emu/citra/assets/18496868/8894c54b-b3a9-4c20-8d46-accd4cf1f7f8)

**Comment by Darth-Koopa** [comment] 2023-09-03 02:38
> Can you uplaod a save file for the stage that freezes?

[Progress.zip](https://github.com/citra-emu/citra/files/12505070/Progress.zip)
Here you are

**Comment by Darth-Koopa** [comment] 2023-09-03 02:41
> here is a save for Mario vs. Donkey Kong: Tipping Stars #3183 [Progress.zip](https://github.com/citra-emu/citra/files/12505058/Progress.zip)
> 
> just choose 1-3 just make a diagonally going down on the angle next to the first mini and then click on it when it goes to walk down the slope it freezes up with the error

Those are not the same game, but it is possible that the issue is similar

**Comment by GPUCode** [comment] 2023-12-21 11:23
I found the cause of this issue is incorrect command list handling, will open a PR soon

**Closed** 2023-12-28 10:46 UTC

**Comment by Darth-Koopa** [comment] 2023-12-28 12:04
Yes, I can confirm that the issue got resolved
