### ISSUE TITLE
Ridge Racer 3D - Hangs when Intro video should be played

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1154] opened 2015-09-15 02:14 UTC
![ridge racer 3d hang](https://cloud.githubusercontent.com/assets/11453507/9866214/133520ea-5b60-11e5-8e28-d8917d5c31e1.PNG)

LOG:
http://pastie.org/10420420

**Comment by yuriks** [comment] 2015-09-15 02:39
Looks like a dupe of #1139

**Closed** 2015-12-30 03:36 UTC
Labels: bug
