### ISSUE TITLE
[Feature request] Separated windows for top and bottom 

### ISSUE THREAD

**Issue by PacoAvelar** [citra-emu/citra#5739] opened 2021-03-11 17:53 UTC
The only current option to get a multi monitor setup on citra that I have seen is to mod the config file, set up displays on windows as if they where one on the top of the other and then strech the windows to both displays (and in some cases, failing over and over until you manage to fit it)

Is it possible to get the top and bottom screens to render on separed windows ?
If not possible, is it possible to render everything twice on separated windows and give different layouts to them
Ex.
window 1 and 2, render the full scene (top and bottom),
But on window 1 you chose layout to "single screen" and then top screen
on window 2 you chose layout to "single screen" too but with bottom screen

This approach may be not efficient and demanding for some setups, but it still a way to achieve it in some cases

**_btw forgot to say that I am willing to give up to 100 usd bounty for this feature (or a better implementation for it).
If anyone is interested, evaluate according to how much time does it take and lets puts a due date for it to happen_**

Thanks

**Comment by FearlessTobi** [comment] 2021-04-02 14:19
Duplicate of #4780.
As for the bounty, I'd suggest posting a comment under the original issue.

**Closed by FearlessTobi** 2021-04-02 14:19 UTC
