### ISSUE TITLE
Controler stops being recognized.

### ISSUE THREAD

**Issue by kiiritsugu** [citra-emu/citra#3888] opened 2018-06-27 21:23 UTC
When my controler disconects (wireless X Box controller) after i reconect it citra wont recocnize it. So i end up having to change my controller settings to keyboard, save the game, restart citra, change the controller settings back, and restart the game.

Would it be possible either to make it detect the controler was reconected, or allow for contoller/keyboard controls simultaneously/interchangable in the controller settings? 

Version: Citra Canary # 592

**Comment by FearlessTobi** [comment] 2018-06-27 21:28
Duplicate of #2056. Requesting to close.

**Closed** 2018-06-28 07:16 UTC
