### ISSUE TITLE
Theatrhythm Dragon Quest - Gameplay/audio desync issue

### ISSUE THREAD

**Issue by lightgod87** [citra-emu/citra#4527] opened 2018-12-23 16:13 UTC
Good day,

This issue is related to 4169, as it also happens with this game as well. The gameplay and audio desyncs in Citra, even with LLE-Multicore and Enable Audio Stretching. Here's a video I did showcasing the matter.

https://youtu.be/DcwyWCO2fQo

And here's the Citra log:

[citra_log.txt](https://github.com/citra-emu/citra/files/2706101/citra_log.txt)

My specs are like this:

Intel Core i7-8700
16 GBs DDR4 RAM
Nvidia Geforce GTX 1070 Ti
Windows 10

And the Citra revision I was using was Citra Canary 1143.

Thanks in advance.

**Comment by FearlessTobi** [comment] 2018-12-25 16:31
Assuming the problem is not related to audio, it could be caused by the syscore being unimplemented.

**Comment by Subv** [comment] 2020-04-12 00:38
Could someone please re-test this in both LLE and HLE now that syscore support (#4913) has been merged?

**Comment by lightgod87** [comment] 2020-04-12 17:40
Good day,

I have retested this in both Citra Canary 1540 and Citra Nightly 1467, but the desync issue still persisted in all the audio modes (HLE, LLE and LLE multi-core).

**Comment by xperia64** [comment] 2020-04-12 22:32
I can confirm that PM2 (#4562) still drifts too.

**Closed** 2020-06-12 14:25 UTC
Labels: A-audio

**Comment by lightgod87** [comment] 2020-06-13 00:13
I can confirm that in all the audio modes, the desync issue was fixed. Tested in Citra Canary 1773.

Just reporting the results here, that all. Thanks for all your help.
