### ISSUE TITLE
Super Mario 3D Land: Save File not recognized, but still loads correctly

### ISSUE THREAD

**Issue by ddemarco5** [citra-emu/citra#3743] opened 2018-05-13 17:11 UTC
I'm running Canary HEAD-4687EE7, and when I boot the game with a previous save file, it sees none in the load menu.

![image](https://user-images.githubusercontent.com/1832038/39969745-a5ad336c-56ae-11e8-8413-b71f577d3277.png)

In this case, slot A is where the save data is located. When slot A is selected, it takes you through the process of creating a new save file in that slot.

However when the game is loaded, it's not a new game. It is indeed loads the game in its previously saved state.

![image](https://user-images.githubusercontent.com/1832038/39969759-e50d4ca4-56ae-11e8-9e66-360bfc91a1a5.png)

I'm attaching the log to this issue.
[citra_log.txt](https://github.com/citra-emu/citra/files/1998714/citra_log.txt)

**Comment by Hexagon12** [comment] 2018-05-13 17:15
Can be interpreted as a duplicate to #3243, since it tries to launch the Mii Selector application before launching the save select screen.

**Comment by FearlessTobi** [comment] 2018-05-13 17:31
@Hexagon12 Are you sure that's really the cause of the issue?

**Comment by Leo626** [comment] 2018-05-13 19:35
@ddemarco5 Can you upload your save file so the issue can be reproduced?

**Comment by ddemarco5** [comment] 2018-05-13 19:58
No problem.
[GameData.zip](https://github.com/citra-emu/citra/files/1998872/GameData.zip)

Though the issue is very easy to reproduce on its own.

**Comment by Leo626** [comment] 2018-05-14 21:09
I was able to reproduce this with your save with Nightly - 7861be6. It looked like Citra was creating a new save but resumed as normal. I started a new game of my own and it still happened. It appears that this has been an issue for over a year since it also happens with Nightly - 654a508 from Jan 5, 2017.

Out of curiosity I imported your save into my 3DS and the same thing happened. Probably has to do with the way the save file was created on CItra? This doesn't happen with my dumped save on Citra.

https://streamable.com/pfutb

**Comment by ddemarco5** [comment] 2018-05-14 23:09
Interesting! I wasn't expecting that when imported onto a real 3ds...

**Comment by CHNBUILD** [comment] 2018-08-11 07:43
By the way, I can't create archives, I have been stuck in choosing the archive interface. Why?

**Comment by Krusher97** [comment] 2018-11-02 12:56
Seems to be fixed in latest canary(1023)
The first save is an old one which didn't show up until I loaded it and the second one is a save made in 1023
![citra-qt_2018-11-02_18-24-35](https://user-images.githubusercontent.com/25664221/47916596-ae135f80-decc-11e8-99a7-99353afba951.png)

**Comment by FearlessTobi** [comment] 2018-11-02 12:59
@Krusher97 We only close issues when they are fixed in Canary. Also I already noted in my PR https://github.com/citra-emu/citra/pull/4279 that it fixes the issue.

**Comment by Krusher97** [comment] 2018-11-02 13:01
huh? It is fixed in canary though.

**Comment by FearlessTobi** [comment] 2018-11-02 13:04
typo lol, meant Nightly

**Closed** 2018-12-02 00:41 UTC
