### ISSUE TITLE
DQM Joker 3, game crash when opening a stealth box at Darkiron Bastille

### ISSUE THREAD

**Issue by Bronxter** [citra-emu/citra#3900] opened 2018-06-30 12:57 UTC
Hello,

my citra emulator always crashs when I try to open a stealth box. Would be great if you could fix this problem.
![dqmj3](https://user-images.githubusercontent.com/40717366/42125370-e65a2edc-7c75-11e8-9844-222f7459d12e.jpg)

**Comment by mailwl** [comment] 2018-06-30 13:09
bad issue. no log
attach at least save file before crash, none of devs will be play to crash moment

**Comment by Bronxter** [comment] 2018-06-30 15:46
I´m new to this....how to do this?

**Comment by Salijour** [comment] 2018-12-06 16:08
The crash caused by something with the translation patch, not by Citra.
https://gbatemp.net/threads/translation-dragon-quest-monsters-joker-3.492313/

> Known bugs (not yet addressed)
> Game Crashes
> Stealth Box reward messages causing crashes in-game

Bad issue.

**Comment by wwylele** [comment] 2018-12-06 16:40
Closing as this is not citra issue if it is caused by the translation patch. If this is not the case, please comment with more details and I'l reopen.

**Closed by wwylele** 2018-12-06 16:40 UTC
Labels: T-crash, more-info-required
