### ISSUE TITLE
Custom Textures and Texture Filters do not work at the same time, even though they used to on older versions.

### ISSUE THREAD

**Issue by Ullrrific** [citra-emu/citra#6199] opened 2022-11-24 00:20 UTC
So for starters, every version of Citra past Nightly 1691 has this issue.

It's a very simple problem to explain. 

You cannot have Custom Textures and a Texture Filter on at the same time. 
The only filter that does not break the custom textures, is "Linear (Default)".

This was captured on [Canary Build - e608d0f](https://github.com/citra-emu/citra-canary/commit/e608d0f)
however, as I said.
This happens on every version past Nightly 1691, which means this wasn't always an issue. Idk what happened, but Citra games look the best with HD Textures + xBRZ Freescale or Anime 4k Ultrafast. This is currently not possible with the current Citra build.

When I use Nightly 1691, I get less than half of the current FPS that I maintain with the new Citra build. Therefore, I think this is an issue that should be looked at so we can have high FPS and the best quality possible for strong computers and large screens.

![image](https://user-images.githubusercontent.com/63162176/203666577-7d232128-fd6e-4d85-85d3-1d790e8b2917.png)
![image](https://user-images.githubusercontent.com/63162176/203666617-39cfdf48-da3d-494b-b361-5d412ca4c9f8.png)

![image](https://user-images.githubusercontent.com/63162176/203666740-68b40a18-e27e-412a-a1cf-5d9c7f4ad1be.png)
![image](https://user-images.githubusercontent.com/63162176/203666764-df23f87e-0cd7-47c1-a0d0-b810b08a62b3.png)

![image](https://user-images.githubusercontent.com/63162176/203667357-1f185bdf-b3ae-4728-b162-d335dccbc770.png)

**Comment by SleepingSnakezzz** [comment] 2022-11-24 00:28
Duplicate of https://github.com/citra-emu/citra/issues/5819

**Closed** 2022-11-29 10:57 UTC
