### ISSUE TITLE
Installed games do not show in the game list

### ISSUE THREAD

**Issue by shinra358** [citra-emu/citra#4117] opened 2018-08-21 23:44 UTC
When installing cia's, the cia games do not display in the emu's list of games. Therefore I'm not able to select an installed game to play. It no longers shows the installed games tab like it use to in the emulator.

**Comment by shinra358** [comment] 2018-09-29 15:09
1. yes

2. Unknown. But I only started setting citra up since the birth of this post. I saw some game entries that were just random numbered characters so I went to their locations on the disk and deleted them. After that, I could no longer see any of the installed cia games.

**Comment by zhaowenlan1779** [comment] 2018-10-07 03:15
> I saw some game entries that were just random numbered characters so I went to their locations on the disk and deleted them. After that, I could no longer see any of the installed cia games.

Did you delete anything like `00000000.app`, `00000001.app` or so? They are actually the game files, and if you delete them, actually the game is deleted.

**Comment by benderscruffy** [comment] 2018-10-07 07:15
this is a duplicate of #3658

**Comment by BreadFish64** [comment] 2018-10-08 15:52
make sure they are actually installed, and retry on the latest version of canary

**Comment by benderscruffy** [comment] 2018-10-09 05:40
still happens on both the nightly and canary

**Comment by SleepingSnakezzz** [comment] 2023-04-27 21:58
Fixed in https://github.com/citra-emu/citra/pull/5130

**Closed by SleepingSnakezzz** 2023-04-27 21:58 UTC
Labels: more-info-required
