### ISSUE TITLE
Tomodachi Life Camera doesn't work

### ISSUE THREAD

**Issue by theSnak3** [citra-emu/citra#5060] opened 2020-01-17 19:39 UTC
so i'm trying to scan some qr codes for Tomodachi life and i have the camera working in the setting justr not in the game 
![image](https://user-images.githubusercontent.com/32428160/72640781-98a21e00-3936-11ea-8a88-e752e3f08062.png)

and it just in a loading loop 
[citra_log.txt](https://github.com/citra-emu/citra/files/4078663/citra_log.txt)

**Comment by FearlessTobi** [comment] 2020-01-18 15:24
Duplicate of https://github.com/citra-emu/citra/issues/4449.

**Closed by FearlessTobi** 2020-01-18 15:24 UTC
