### ISSUE TITLE
Sonic Boom Fire and Ice Top Screen Not Showing outside of cutscenes

### ISSUE THREAD

**Issue by wintyre01** [citra-emu/citra#7063] opened 2023-10-12 03:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2583 (also tested on latest builds Canary 2651 / Nightly 2009)

### Description of Issue

Whenever I start the game, I only see the touch screen. Maybe the CGI cutscenes will show both screens, but once I leave there, nothing at the top. And when entering a level it's just grey.

Example as shown

![Fire and Ice](https://github.com/citra-emu/citra/assets/143204241/b9992a05-a462-4001-9261-3c79ef9c5b44)

### Expected Behavior

Both screens should be showing. Game is unplayable without top screen.

### Reproduction Steps

Launching game

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12876673/citra_log.txt)

### System Configuration

CPU: 11th Gen Intel(R) Core™ i9-11900K @ 3.50GHz
GPU/Driver: Nvidia GeForce RTX 3060 Ti
RAM: 64 GB
OS: Windows 10 22H2

**Comment by GPUCode** [comment] 2024-02-01 00:55
Cannot reproduce this anymore, so I'll close this. Feel free to reopen if this still an issue

**Closed by GPUCode** 2024-02-01 00:55 UTC
Labels: A-graphics
