### ISSUE TITLE
Glitchy meshes in several games

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#974] opened 2015-07-22 02:39 UTC
#### Turbo - Super Stunt Squad:

![turbo](https://cloud.githubusercontent.com/assets/11453507/8816783/895055b6-302b-11e5-84e2-7f56d065cb3f.PNG)

![turbo 2](https://cloud.githubusercontent.com/assets/11453507/8816786/908ee996-302b-11e5-812e-a4488505b0fa.PNG)

CITRACE: https://goo.gl/QmSKrB

#### Barbie Dreamhouse Party:
SW
![barbie sw](https://cloud.githubusercontent.com/assets/11453507/7871664/a6417502-0591-11e5-9f2c-1fe17a5c3aa5.PNG)

#### 101 Dino Pets 3D:
![101 dino pets 1](https://cloud.githubusercontent.com/assets/11453507/13590246/8784e676-e4de-11e5-9139-2df45aeb4387.JPG)

#### 101 Penguin Pets 3D:
![101 penguins](https://cloud.githubusercontent.com/assets/11453507/13590268/af7fea7c-e4de-11e5-8f19-e1bde76f66ff.JPG)

#### 101 Pony Pets 3D:
![101 pony](https://cloud.githubusercontent.com/assets/11453507/13590271/b36ec716-e4de-11e5-9884-c1f83ceed89c.JPG)

#### The Sims 3:
![the sims 3](https://cloud.githubusercontent.com/assets/11453507/13590288/d2e5fcd6-e4de-11e5-9045-b8e96b7f1236.JPG)

#### The Sims 3 - Pets:
![sims pets](https://cloud.githubusercontent.com/assets/11453507/13590291/d6e37cf0-e4de-11e5-87c0-9f54956fc78d.JPG)

#### Outdoors Unleashed Africa 3D:
![outdoors unleashed africa 3d](https://cloud.githubusercontent.com/assets/11453507/13590294/de035bc2-e4de-11e5-88f7-2b9195d8d571.JPG)

**Comment by yuriks** [comment] 2015-08-06 02:24
Very likely a duplicate of #970

**Comment by TheSoraHD** [comment] 2015-08-31 10:50
Since this have the same problem as #970, can anyone try if #1059 solves it?

**Comment by Subv** [comment] 2015-09-12 17:56
Any news regarding this?

**Comment by JohnGodgames** [comment] 2015-09-12 20:06
still the same...

**Comment by Subv** [comment] 2015-12-06 15:36
Could you see if #1269 fixes it please?

**Comment by JohnGodgames** [comment] 2015-12-06 15:46
hmm nope :( 

![turbo](https://cloud.githubusercontent.com/assets/11453507/11614131/e6c358dc-9c38-11e5-893e-249d1c706041.PNG)

**Comment by yuriks** [comment] 2016-02-04 02:00
This is very likely caused by us not supporting the padding attributes in https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_ATTRIBBUFFERi_CONFIG1

**Comment by RavenHome1** [comment] 2016-02-06 18:24
idk i kinda like barbie dream house this way

**Comment by JayFoxRox** [comment] 2016-03-08 23:45
I'm guessing it's caused by bad relative-addressing.

We had a similar bug in xqemu (Xbox emulator).

![xqemu bug](http://i.imgur.com/tpmLpjP.png)

If the effect only happens on skinned characters it is because the offset into the matrix array is bad. 
Instead of accessing a matrix a bad index will mix 2 matrices (picking some rows from one, and some rows from another) and this will cause the model to explode.

For xqemu it helped to analyze the uniform/transform program uploads and compare that with the code used to access it.
In our case it turned out to be caused by division of the vertex attributes. The attributes where passed as bit integer to the GPU. The GPU then converts the data to float by dividing by 255 (Result differs in different rounding modes!). Due to rounding errors the access in the code using uniforms[765 * float_attrib] was behaving badly (for example: if the attribute value was (uint8)1 the formula gave: (1/255.0)*765.0 which is intended to be index 3, but the actual result we had was 2.99. Floor turned this into index 2)

So it might be worth to take a closer look at attribute conversion and rounding + relative addressing in general

**Comment by yuriks** [comment] 2016-03-09 01:23
@JayFoxRox Thanks for the helpful information!

I've been suspicious of our loop instruction, which is wrong when loops are nested. I suspect that construct is present in skinning shaders and breaks. This is hard to fix in the current JIT but I'll try to re-implement it in the shader interpreter at some point. (I have a WIP branch I have to finish.)

**Comment by Subv** [comment] 2016-03-09 02:33
Oh god, please don't let it be a floating point rounding error, _please_.

**Comment by JohnGodgames** [comment] 2016-03-09 08:59
### Significant changes when we set 
 `state.address_registers[i] = static_cast<s32>(src1[i].ToFloat32() - 5.0/255.0);`

https://github.com/citra-emu/citra/blob/master/src/video_core/shader/shader_interpreter.cpp#L272

![turbo](https://cloud.githubusercontent.com/assets/11453507/13630057/6a22cfb2-e5dd-11e5-9b2e-30ab59d51b81.JPG)
![sims pets 2](https://cloud.githubusercontent.com/assets/11453507/13630063/6f81d93a-e5dd-11e5-95bc-f0ddf422b0b7.JPG)
![101 pony 2](https://cloud.githubusercontent.com/assets/11453507/13630069/74cbcb9e-e5dd-11e5-9148-996612c59634.JPG)
![barbie](https://cloud.githubusercontent.com/assets/11453507/13630076/7c1ac652-e5dd-11e5-9010-39abff4d652b.JPG)

**Comment by JayFoxRox** [comment] 2016-03-09 12:43
@yuriks Using https://github.com/citra-emu/citra/pull/1478 I checked 101 Penguin Pets 3D (the menu during character creation).

The shader doesn't contain any loops.

The attribute mapping seems to be:
v0 = position
v1 = uv
v3 = normal
v6 = bone [integers!]
v7 = bone weights

The code to skin:
r4 = c95 * v6
a0.xy = r4.xy
r1 = c7[a0.y] * v7.y
r2 = c8[a0.y] * v7.y
r3 = c9[a0.y] * v7.y
r1 += c7.x * c7
r2 += c7.x * c8
r3 += c7.x * c9
a0.xy = r4.zw
r1 += c7.z * c7
r2 += c7.z * c8
r3 += c7.z * c9
r1 += c39.z * c7
r2 += c39.z * c8
r3 += c39.w * c9

I'm guessing the MAD encoding is documented wrong. I'm pretty sure MAD has a relative address + what is decoded as c7 and c39 is supposed to be v7. It would result in something like:

r4 = c95 * v6
a0.xy = r4.xy
r1 = c7[a0.y] * v7.y
r2 = c8[a0.y] * v7.y
r3 = c9[a0.y] * v7.y
r1 += c7[a0.x] * v7.x
r2 += c8[a0.x] * v7.x
r3 += c9[a0.x] * v7.x
a0.xy = r4.zw
r1 += c7[a0.x] * v7.z
r2 += c8[a0.x] * v7.z
r3 += c9[a0.x] * v7.z
r1 += c7[a0.y] * v7.w [39 = 7+32]
r2 += c8[a0.y] * v7.w [39 = 7+32]
r3 += c9[a0.y] * v7.w [39 = 7+32]

which would mean c7[] are matrices, r4~v6 is bone index and v7 is weight [which matches my description..]

**Comment by JohnGodgames** [comment] 2016-03-09 15:21
All of these fixed by https://github.com/citra-emu/citra/pull/1479

**Closed** 2016-03-16 17:17 UTC
Labels: bug, graphics
