### ISSUE TITLE
Home menu folders causes graphical glitch

### ISSUE THREAD

**Issue by Rix565** [citra-emu/citra#6345] opened 2023-03-12 18:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1853 (haven't checked other builds)

### Description of Issue

When opening a folder, I see a huge black box behind the folder contents, presumably a graphical glitch.
![Capture d’écran du 2023-03-12 19-00-13](https://user-images.githubusercontent.com/61545240/224563731-28c93224-302f-4d11-9f2a-40bb8ba815b0.png)

### Expected Behavior

It should normally not show this box.

### Reproduction Steps

1. Create a new folder
2. Open it

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/10951614/citra_log.txt)

### System Configuration

CPU: AMD 3020e
GPU/Driver: AMD Radeon Vega 3 Graphics
RAM: 4G w/ 2G swap
OS: Ubuntu 22.10 x64

**Comment by GPUCode** [comment] 2023-09-15 14:55
Could not reproduce the issue, closing

**Closed by GPUCode** 2023-09-15 14:55 UTC
