### ISSUE TITLE
 A link Between worlds begin Button 

### ISSUE THREAD

**Issue by alexis23ange** [citra-emu/citra#1512] opened 2016-03-13 21:27 UTC
ok since people fail at reading the title when you try and start a new game in the link between worlds 
and you hit the Begin button as said in the title you get the error below and the game controls stops and the game never starts and later crashes.
[  76.395101] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'ControlArchive': port=fs:USER, cmd_buff[1]=0x7, cmd_buff[2]=0x0, cmd_buff[3]=0x0, cmd_buff[4]=0x1, cmd_buff[5]=0x1, cmd_buff[6]=0x1A, cmd_buff[7]=0x162F4D60, cmd_buff[8]=0x1C, cmd_buff[9]=0x162F4D64

**Comment by yuriks** [comment] 2016-03-13 21:28
This is quite the terrible bug report, it has almost no info or description of the problem. Improve it or I'll close it.

**Comment by KillzXGaming** [comment] 2016-03-13 21:45
I believe Citra is missing this
https://3dbrew.org/wiki/FS:ControlArchive

**Comment by alexis23ange** [comment] 2016-03-13 21:57
thanks killz at least someone wasnt a rude ass

**Closed** 2016-03-13 21:58 UTC

**Comment by alexis23ange** [comment] 2016-03-13 22:02
figures we try and report a issue and we get ignored for progress to be made first progress must be made finding good team members Citra devs

**Comment by yuriks** [comment] 2016-03-13 22:03
Your report doesn't have any context or useful information about what do you think the problem is. It's not helpful.

**Comment by KillzXGaming** [comment] 2016-03-13 22:03
It's fine, might be a dupe o f#1493

**Comment by KillzXGaming** [comment] 2016-03-13 22:06
Also mailwl working on the issue
https://github.com/mailwl/citra/blob/ctrl_archive/src/core/hle/service/fs/fs_user.cpp#L407
