### ISSUE TITLE
black lines around characters in pokemon moon

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#2225] opened 2016-11-28 11:20 UTC
tested with latest bleeding edge

HEAD-5759a38

black edge lines appear on the edge of characters, disabling scaled resolution removes the lines

with scaled resolution

![capture](https://cloud.githubusercontent.com/assets/12820322/20666401/b78c726c-b56c-11e6-9a5a-70db03059e42.PNG)

without scaled resolution 

![capture2](https://cloud.githubusercontent.com/assets/12820322/20666411/c19544e6-b56c-11e6-8790-41f3e5076060.PNG)

**Comment by wwylele** [comment] 2016-11-28 11:25
dupe of #2220 ?

**Comment by Dragios** [comment] 2016-11-28 11:27
Those are not black lines. It is just *edge marking*. Enabling scaled resolution just makes those marking more sharp therefore more visible. Apparently this is not a valid issue.

**Comment by RavenHome1** [comment] 2016-11-28 11:28
@wwylele appears to be a dupe, should i close this?

**Closed** 2016-11-28 11:39 UTC
