### ISSUE TITLE
Dump romfs/load mod crash

### ISSUE THREAD

**Issue by Colmines92** [citra-emu/citra#5538] opened 2020-08-30 14:43 UTC
Citra canary latest dump romfs/load mod inmediately craches with Final Fantasy Explorers (both USA/EUR), (both original/decrypted).
When you choose dump romfs citra instantly closes.
When you create romfs or romfs_ext folder inside mod directory and try to launch the game citra instantly closes.
However with the other games that I own this does not happen.

PD: I think it is the same as #5467

**Comment by zhaowenlan1779** [comment] 2020-08-30 14:48
Thank you, but as you have pointed out, this is a duplicate of #5467. Please post this as a comment there.

**Closed by zhaowenlan1779** 2020-08-30 14:48 UTC
