### ISSUE TITLE
Things that should be fixed after we migrate to VS2015

### ISSUE THREAD

**Issue by bunnei** [citra-emu/citra#651] opened 2015-03-11 15:24 UTC
I want to keep a running list of VS2013 known hacks/workarounds that should be fixed once VS2015 is released (and we migrate to it), primarily so that we do not miss anything. These are typically C++11 things that VS2013 does not adequately support. Please add to this list.
- `ASSERT_REG_POSITION` (currently used in hid.h, gpu.h, pica.h, ..)

**Comment by purpasmart96** [comment] 2015-03-11 16:15
Also https://github.com/citra-emu/citra/blob/master/src/core/hle/service/cfg/cfg_u.cpp#L16

**Comment by lioncash** [comment] 2015-03-11 20:06
https://github.com/citra-emu/citra/blob/master/src/common/logging/backend.h#L31
https://github.com/citra-emu/citra/blob/master/src/common/thread.cpp#L59

I believe VS 2015  also fixes: https://github.com/citra-emu/citra/blob/master/src/common/bit_field.h#L140 as well.

**Comment by Subv** [comment] 2015-03-12 02:54
https://github.com/citra-emu/citra/blob/master/src/video_core/pica.h#L746

And all the *_REG_INDEX_WORKAROUND macros like https://github.com/citra-emu/citra/blob/master/src/video_core/pica.h#L30

**Comment by neobrain** [comment] 2015-04-17 13:29
I'm hoping to be able to use `static constexpr` member variables in structures iff VS2015 supports that. This would be beneficial for adding metadata inline to data structure definitions; for instance, we could have a `static constexpr regid = 0x54;` within each `Pica::Regs` structure instead of explicitly writing those at the bottom of pica.h in the register position assertions.

**Comment by archshift** [comment] 2015-04-17 22:10
Another alternative is `#defines`, which would currently work quite well even if not totally ideal.

**Comment by neobrain** [comment] 2015-04-17 22:16
@archshift `#define` are neither type-safe nor scoped, though.

**Comment by neobrain** [comment] 2015-07-27 14:06
Apparently, VS 2013 doesn't support alignas properly, either, even though it's a useful thing to have when code relies on some particular alignment of variables.

**Comment by Subv** [comment] 2015-07-27 14:55
When will we be making the switch?

**Comment by neobrain** [comment] 2015-07-27 14:56
We probably need to wait for the Qt 5.5.1 minor release, which will add binaries for VS2015.

**Comment by bunnei** [comment] 2015-08-12 02:44
Regarding alignas, we currently need the macro MEMORY_ALIGNED16 defined in common_funcs.h for the shader JIT. This should be changed once we move to VS2015.

**Comment by Subv** [comment] 2015-11-23 22:40
We've already switched to VS2015, we should start implementing these changes.

**Comment by JayFoxRox** [comment] 2016-04-30 10:48
Reminder.

(Also we should only link to line numbers in specific revisions, most of the links above are broken by now. We'll have to figure out the revision which was used at that time)

**Comment by JayFoxRox** [comment] 2016-11-29 12:40
How is this still a thing MSVC users?

**Comment by Margen67** [comment] 2016-11-29 12:56
What about VS2017?

**Comment by JayFoxRox** [comment] 2016-11-29 14:15
That'd be a seperate issue.. This is about  a list of things which were supposed to happen. However, a majority of those got no response in this issue and the issue is still open.
We should check if VS2015 fixed these issues, strike them through and close this issue. If an issue could not be solved in VS2015 we should create a new issue for the next revision (VS2017?).

(I guess this is a great example how meta-isues are horrible? Nobody feels responsible for fixing and closing these issues - even though some are done we still can't close this)

**Comment by Subv** [comment] 2016-11-29 15:27
ASSERT_REG_POSITION still doesn't work on arrays in VS2015

**Comment by yuriks** [comment] 2017-05-07 20:59
And it still doesn't work on VS2017. Did anyone ever make a bug report to them about that?

**Comment by JayFoxRox** [comment] 2017-05-07 21:23
Again: meta issues.. nobody feels responsible and we tend to forget about those. We should close this one and have seperate issues per compiler.

**Comment by BreadFish64** [comment] 2020-02-20 05:24
Pending #5099 all of these look to be resolved aside from the one in thread.cpp.
@lioncash what specifically was that link referring to?

**Comment by vitor-k** [comment] 2020-03-13 06:42
Btw @BreadFish64 lioncash's links are probably to https://github.com/citra-emu/citra/blob/ebdae19fd226104baec712b9da9939ff82ef3c3a/src/common/bit_field.h#L148 which is done now, and https://github.com/citra-emu/citra/blob/8ce1ec7ffa6b912dfa776d6923a7af18a7761f67/src/common/thread.cpp#L64
The link on that last one is basically dead, but is probably referring `SetThreadDescription`, which is only avaliable in VS2017 15.6 or newer. [reference](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2019)

**Comment by Subv** [comment] 2020-04-16 21:56
What's the status on this nowadays?

**Comment by benderscruffy** [comment] 2023-08-27 10:58
can this be closed now ???

**Comment by FearlessTobi** [comment] 2023-08-27 15:28
i think so

**Closed by FearlessTobi** 2023-08-27 15:28 UTC
Labels: proposal, E-easy
