### ISSUE TITLE
LEGO The Lord of the Rings Demo - Some objects appear black

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#1502] opened 2016-03-12 17:11 UTC
Using master branch as of afb5140

**LEGO The Lord of the Rings Demo**

How it's suppose to look
![capture](https://cloud.githubusercontent.com/assets/17358613/13724103/f289a0c2-e850-11e5-999e-2b696e49fc46.PNG)

What it looks like in the emulator
![citra-qt_2016-03-12_12-29-16](https://cloud.githubusercontent.com/assets/17358613/13724108/ff0def88-e850-11e5-8e36-072b42c43d19.png)
[LOG](https://gist.github.com/Leo626/1aa066b502ae53c296db)

Also occurs in **LEGO Batman 2: DC Super Heroes Demo**

![citra-qt_2016-03-12_12-13-57](https://cloud.githubusercontent.com/assets/17358613/13724111/25544caa-e851-11e5-88d2-0f746a9252aa.png)
[LOG](https://gist.github.com/Leo626/42e3948aeffe33aff2b5)

**Comment by Leo626** [comment] 2016-03-13 04:03
#1508 seemed to have partially fixed LEGO The Lord of the Rings Demo.

![citra-qt_2016-03-12_23-49-16](https://cloud.githubusercontent.com/assets/17358613/13726830/ccfbee42-e8ae-11e5-8092-201f14c44fed.png)

LEGO Batman 2: DC Super Heroes looks correct.

![citra-qt_2016-03-12_23-52-55](https://cloud.githubusercontent.com/assets/17358613/13726832/f01d684c-e8ae-11e5-9d42-f90b018708f9.png)

Animal Crossing: New Leaf remains unchanged so it's probably unrelated.

**Comment by JayFoxRox** [comment] 2016-03-13 12:20
Different issues probably.

* I'd blame the LEGO lotr problem being related to #1508 (maybe we don't have to respect the total attribs?!). I'll probably look into it.
* Animal crossing black arms could be anything (could be similar to LEGO lotr but who knows).
* Animal crossing mountains are very likely caused by depth issues / farclip.

**Comment by Leo626** [comment] 2016-03-13 22:15
I think I made a mistake with LEGO LotR. Because of the lack of lighting I thought the bird was missing textures/black, but it turns out that it is actually colored black. Made a build with a2024d7 merged with #1508 to make sure. Environmental models have textures as well but I'm still not sure about Animal Crossing. Sorry if I confused you @JayFoxRox.

**3DS**
![capture](https://cloud.githubusercontent.com/assets/17358613/13731737/c82ddc70-e946-11e5-9ee3-ab9d96e768bc.PNG)
**Citra**
![untitled](https://cloud.githubusercontent.com/assets/17358613/13731752/22b97bb8-e947-11e5-9730-377be6a9efd2.png)

**Comment by JayFoxRox** [comment] 2016-03-13 23:52
@Leo626: I'd suggest this:

1. Create new issues for animal crossing: "Animal Crossing: New Leaf - Player arms black" and "Animal Crossing: New Leaf - Objects in distance disappear / become black" (note how the fence also becomes black!)
  
 Move the information from your first post in this issue to the respective new issues (= remove them here, post them as new issue)
1. Rename this issue to "LEGO The Lord of the Rings Demo - Some objects appear black"

When #1508 is finally merged this can be closed and the new issues stay opened for discussion.

Thanks for your contribution :)

**Comment by Leo626** [comment] 2016-03-14 00:25
@JayFoxRox you're welcome. Did everything you asked.

**Comment by Leo626** [comment] 2016-03-22 17:06
Now that #1508 has been merged with the master branch, I can finally close this issue. I made sure to test it with the latest master ebbba0d.

**Closed** 2016-03-22 17:06 UTC
Labels: bug, graphics
