### ISSUE TITLE
Suggest Change Saves's path

### ISSUE THREAD

**Issue by anthsalmo** [citra-emu/citra#4260] opened 2018-09-23 05:57 UTC
Recently my OS crash and I had to re-install Windows 

I had Citra on Drive D. I though my saves were secure but when i check all my saves were lost, The reason was all the saves were in this path:

C:\Users\USER\AppData\Roaming\Citra

 so I Suggest the saves and data folder should be move inside the citra's folder

**Comment by zhaowenlan1779** [comment] 2018-09-23 06:08
> I Suggest the saves and data folder should be move inside the citra's folder

It is already possible, but it is not used by default as the directory would be wiped if you installed and updated Citra with the installer.

There are some plans to allow customizing save/nand directories, as mentioned in #3818.

Closing this as duplicate of #3818.

**Closed by zhaowenlan1779** 2018-09-23 06:08 UTC
