### ISSUE TITLE
Shin Megami Tensei 4: Apocalypse 3D models don't have shadows

### ISSUE THREAD

**Issue by Salijour** [citra-emu/citra#2271] opened 2016-12-06 04:19 UTC
Tested on 12/5 master build 9a439b9.

Console spams this error
```
[  19.408699] HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:AppendSource:58: Unhandled texture type 2
[  19.409644] HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:AppendSource:58: Unhandled texture type 2
[  19.413210] HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:AppendSource:58: Unhandled texture type 2
[  19.413523] HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:AppendSource:58: Unhandled texture type 2
```

The console stops this spam in combat, because there are no 3D models. 2D models show shadows correctly.
**Citra:**
![Citra](https://i.gyazo.com/f7e41c2f6298cdc4f9e69921d60a7489.png)

![Citra](https://i.gyazo.com/6d4744fb3f0c773c45cdb9db786caa81.jpg)

**Real:**
![Real](http://i.imgur.com/CqZrEgi.png)

![Real](http://i.imgur.com/5QfiP69.png)

**Comment by JohnGodgames** [comment] 2016-12-06 19:34
Duplicate of https://github.com/citra-emu/citra/issues/1804

**Comment by JayFoxRox** [comment] 2016-12-06 19:55
Not a duplicate, just the same kind of bug

**Comment by wwylele** [comment] 2018-03-13 13:46
What does this look like in software renderer with #3516?

**Comment by windwakr** [comment] 2018-03-18 19:51
@wwylele 
![smtiva](https://user-images.githubusercontent.com/284886/37570274-456098b6-2ac4-11e8-8b58-e97200a7fe53.png)

**Comment by wwylele** [comment] 2018-07-20 15:00
I am assuming this is fine on nightly now, so closing. Please leave a comment if there is any issue

**Closed by wwylele** 2018-07-20 15:00 UTC
Labels: A-graphics, F-gpu:shadow-2d, T-unimplemented
