### ISSUE TITLE
luigi's mansion mp not working

### ISSUE THREAD

**Issue by denis-hash** [citra-emu/citra#5673] opened 2021-01-03 14:43 UTC
Version- Canary 1923
Detail: luigi mansion multiplayer is not working, no matter what you do, it doesn't work, its multiplayer doesn't use download play, I tried connecting to a room, it still didn't work, the "join a room" option doesn't detect the host room, i also tried a portable citra version and tried it with two tabs of citra to check if its ping related, it still doesn't work.
Specs: gtx 1070, 16 GB ram and a intel core i7.
Log: i do not think its needed, the game just doesn't detect the host room.
Citra:
![loooogiii](https://user-images.githubusercontent.com/76909378/103481270-943e7180-4de2-11eb-91e1-336cda757131.png)
![epic luigi moment](https://user-images.githubusercontent.com/76909378/103481286-af10e600-4de2-11eb-91e5-ea554aeb3af5.png)

**Comment by denis-hash** [comment] 2021-01-03 14:59
by the way i tried it with download play too, i enabled it in the "toggle lie services" but when you create a room with that option turned on it results in an error

**Comment by MojoJojoDojo** [comment] 2021-01-03 15:24
Duplicate of https://github.com/citra-emu/citra/issues/4330.
But yeah its one of the games that wont work even with DLP .
The game uses DLP no matter what you do btw.

**Comment by denis-hash** [comment] 2021-01-03 15:35
but that are wrong, they say this mp uses dip, which isn't correct

**Comment by FearlessTobi** [comment] 2021-01-04 04:19
Closing as a duplicate.

**Closed by FearlessTobi** 2021-01-04 04:19 UTC

**Comment by denis-hash** [comment] 2021-01-04 07:12
![Screenshot 2021-01-04 at 09 11 01](https://user-images.githubusercontent.com/76909378/103509890-c694b100-4e6c-11eb-9287-e2da0f90e27d.png)
but the local multiplayer doesn't use dlp man

**Comment by denis-hash** [comment] 2021-01-04 07:13
> Closing as a duplicate.

see my message above

**Comment by denis-hash** [comment] 2021-01-04 07:14
![Screenshot 2021-01-04 at 09 14 10](https://user-images.githubusercontent.com/76909378/103510114-373bcd80-4e6d-11eb-8c85-4a48e7d151b4.png)
SEE

**Comment by denis-hash** [comment] 2021-01-04 14:07
@FearlessTobi @MojoJojoDojo

**Comment by B3n30** [comment] 2021-01-04 14:10
@denis-hash See the first line in your screenshot: "Download Play". And DLP is short for Download Play...

**Comment by B3n30** [comment] 2021-01-04 14:13
and luigis manison uses DLP for all multiplayer stuff even id it sin't visible for the user
