### ISSUE TITLE
"Capture Screenshot" broken since at least Nightly 1803

### ISSUE THREAD

**Issue by sanityormadness** [citra-emu/citra#6182] opened 2022-11-09 14:26 UTC
Since at least 1803 (still the case as of 1806), hitting "Capture Screenshot" or the equivalent hotkey in any game I've tried instantly crashes Citra Nightly. Tested on various games, including Majora's Mask 3D, A Link Between Worlds and Super Mario 3D Land. It does *not* happen on 1779, but I don't have any in-between versions to hand to test.

[citra_log.txt](https://github.com/citra-emu/citra/files/9971911/citra_log.txt)

**Comment by GPUCode** [comment] 2022-11-09 14:48
Bug is caused by a recent commit that causes a null reference capture when taking screenshots: https://github.com/citra-emu/citra/blob/c7e259366d69c3818cbe56602e1e89a058515d6b/src/citra_qt/bootmanager.cpp#L428 Will be fixed shortly thanks for reporting

**Comment by GPUCode** [comment] 2022-11-09 14:51
Fixed by #6183

**Closed by GPUCode** 2022-11-09 14:51 UTC
