### ISSUE TITLE
Texture glitch after installing DLC

### ISSUE THREAD

**Issue by MileniumJoestar** [citra-emu/citra#3974] opened 2018-07-21 18:58 UTC
I installed Fire Emblem Fates DLC in citra, the DLC are working so far, but now im getting these weird texture glitches, any thoughs?

![bug](https://user-images.githubusercontent.com/29901999/43039104-bcad60b2-8cfc-11e8-8168-6313dcd574c8.png)

NVIDIA GeForce GT730
Intel(R) Core(TM) i3-2100 CPU 3.10GHz, 3100 MHz
4 GB RAM
Windows 7 Ultimate 64 bits system.

Log File
[citra_log.txt](https://github.com/citra-emu/citra/files/2216419/citra_log.txt)

**Comment by FearlessTobi** [comment] 2018-07-21 19:00
Can you get us an image how the textures are supposed to look?

**Comment by MileniumJoestar** [comment] 2018-07-21 19:38
Its supposed to look like this
![bug3](https://user-images.githubusercontent.com/29901999/43039464-414d10c2-8d04-11e8-8c38-37cf13efd0fe.png)


But its actually looking like this ever since i installed the DLC, with these weird ''black textures''
![bug2](https://user-images.githubusercontent.com/29901999/43039471-5c1aacac-8d04-11e8-99e9-a85a9b1d8c5d.png)

**Comment by legoj15** [comment] 2018-07-21 22:40
Wasn't able to reproduce on Canary 653. Using my cartridge dump of FE Fates: Birthright, and I dumped all my DLC via the latest commit of GodMode9, and don't notice any differences in the characters.

**Comment by MileniumJoestar** [comment] 2018-07-22 06:56
I figured out, it was a internal resolution issue,  caused by running citra at the lowest native resolution. Once i changed to 4x and higher native, the glitch textures are gone.

**Comment by wwylele** [comment] 2018-07-22 10:49
Please move this to #3910 and close the issue, thanks!

**Comment by wwylele** [comment] 2018-07-22 15:05
@MileniumJoestar Could you test this build to see if it fix your issue? https://ci.appveyor.com/api/buildjobs/p5jae3p3rmqkgme9/artifacts/citra-windows-mingw-20180722-138345f.zip

**Comment by Dragios** [comment] 2018-11-05 01:39
@MileniumJoestar Could you please update regarding this issue? Please redump your DLC using the latest GodMode9 and try it on latest Citra Nightly. If fixed, kindly close this issue.

You may download the latest stable version [here](https://github.com/d0k3/GodMode9/releases/download/v1.7.1/GodMode9-v1.7.1-20180802021438.zip) or latest nightly version [here](https://d0k3.secretalgorithm.com/GodMode9/GodMode9-v1.7.1-30-g75a23a15-20181105013008.zip)

Please try both version as if the latest nightly of GodMode9 solves your issue it means that this is not related to Citra anymore.

**Comment by SushiCat49** [comment] 2019-04-03 09:32
I'm having the same bug in the latest Canary but on Fire Emblem: Awakening, so it's possibly related to the mipmap update as well. I tested in both my GPUs' (Nvidia and Intel) and it happens in both.
![texturebug](https://user-images.githubusercontent.com/48274648/55468648-bdbdde00-55fb-11e9-8020-eeeb2240db75.png)

**Comment by wwylele** [comment] 2019-04-03 16:41
@SushiCat49 Could you provide comparison screenshots of the same scene (nightly vs canary) at **1x native** resolution? Also is this affected by DLC?

**Comment by SushiCat49** [comment] 2019-04-03 17:02
I don't think the DLCs are causing the problem, I do have some installed but the problem only started since Canary 1277.

Here are the screenshots at native resolution:

**Canary**
![Canary](https://user-images.githubusercontent.com/48274648/55498057-933f4580-563a-11e9-9220-e182b47aadfc.png)

**Nightly**
![Nightly](https://user-images.githubusercontent.com/48274648/55498080-a2be8e80-563a-11e9-9c75-b8a1f148a1c4.png)

**Comment by wwylele** [comment] 2019-04-03 20:46
@SushiCat49 Could you post this under #3910? Since we only open issue tracking master branch (=nightly). I am going to close this. Also is that cloth texture difference part of the glitch or not?

**Closed by wwylele** 2019-04-03 20:46 UTC

**Comment by SushiCat49** [comment] 2019-04-03 21:38
Just added the info to the PR. The cloth is part of the bug yes, basically the screenshots should be identical.
