### ISSUE TITLE
Running citra with a certain graphic processor, doesn't make it use the one selected

### ISSUE THREAD

**Issue by karl-police** [citra-emu/citra#5721] opened 2021-02-14 14:03 UTC
This was on a laptop, which has two graphic processors, NVIDIA and an integrated one in the CPU.

When I choose citra.exe and right click on it, I can choose "Run with graphics processor" and choose between "High-performance NVIDIA processor" and "Integrated graphics (default)".

Choosing "Integrated graphics (default)" doesn't seem to affect it in any way, it will use the NVIDIA one instead. I also saw no option in the settings to change which graphics processor it should use.

**Comment by SleepingSnakezzz** [comment] 2023-04-30 11:08
Duplicate of https://github.com/citra-emu/citra/issues/4435

**Closed by SleepingSnakezzz** 2023-04-30 11:08 UTC
