### ISSUE TITLE
Citra-qt no longer loading games on MacOS 10.13

### ISSUE THREAD

**Issue by MojitoFan** [citra-emu/citra#4515] opened 2018-12-16 17:03 UTC
Hello,
From nightly build 1149 d2003da and Canary build 1113 [8b4b40d](https://github.com/citra-emu/citra-canary/commit/8b4b40de3a3db7493d2ac0490518cc89712c6694) onwards (as I found out by testing previous builds) Citra would no longer load games, instead returning this message

> Your GPU may not support OpenGL 3.3, or you do not have the latest graphics driver

My GPU does have support for OpenGL 4.1 and in fact Citra has worked fairly well with games on my system before these updates.
I could not find any significant changes in the changelog that might cause Citra to suddenly stop loading games. Here's the logs from the latest working versions and the latest releases as of this post for comparison.
[citra_log canary 1112 (latest working).txt](https://github.com/citra-emu/citra/files/2683757/citra_log.canary.1112.latest.working.txt)
[citra_log canary 1113.txt](https://github.com/citra-emu/citra/files/2683758/citra_log.canary.1113.txt)
[citra_log canary 1131.txt](https://github.com/citra-emu/citra/files/2683759/citra_log.canary.1131.txt)
[citra_log nightly 1144 (latest working).txt](https://github.com/citra-emu/citra/files/2683760/citra_log.nightly.1144.latest.working.txt)
[citra_log nightly 1149.txt](https://github.com/citra-emu/citra/files/2683761/citra_log.nightly.1149.txt)
[citra_log nightly 1154.txt](https://github.com/citra-emu/citra/files/2683762/citra_log.nightly.1154.txt)

This is not an isolated case and I've seen multiple similar reports, but I saw nothing about those on this rep so I'm putting this up here.

* Operating System: MacOS 10.13.6
* CPU: 2,7 GHz Intel i5
* GPU: AMD Radeon HD 6770M

**Comment by wwylele** [comment] 2018-12-16 17:10
If nightly build 1148 still works, then the cause must be out of our scope because the change from 1148 to 1149 is pretty unrelated and trivial af. It might be that travis CI and/or MacOS silently updated something. Could anyone compile citra locally and test if it still works?

**Comment by JNaftali** [comment] 2018-12-24 01:36
I tried with both the most recent nightly (1161) and also with build 1148 - neither worked for me, although this if my first time installing Citra so I can't guarantee this is the same issue.

I tried to build from source but it failed partway through. If there's anything I can do to help move this issue forward lemme know!

**Comment by farmerpaul** [comment] 2018-12-24 13:31
I too am trying Citra for the first time, and I had exactly the same experience. The latest available build fails with this OpenGL 3.3 error, although I've got a relatively modern Mac. I haven't tried build 1148 since no MacOS build of citra-nightly, but the next most recent MacOS nightly build is 1144, and that one works for me.

**Comment by smallqiang** [comment] 2018-12-25 01:47
I downloaded the latest Citra. It's showed "Your GPU may not support OpenGL 3.3, or you do not have the latest graphics driver". My iMac is the relatively modern. Please quickly to resolve it.

**Comment by JasonDeJonge** [comment] 2018-12-28 14:41
I have same issue. Downloaded update and now my games stopped working due to OpenGL 3.3 support. My drivers support 3.3... this is why I always prefer off the shelf because it actually works

**Comment by Craig-Janssen** [comment] 2019-01-20 18:51
I had the same problem on OS X 10.13.6, running the latest nightly build.  Rolling back to nightly 1144 fixes the problem.

**Comment by Sparen** [comment] 2019-02-02 17:48
Does this issue have a workaround by reverting to a previous build, or have previous builds been retroactively broken?

**Comment by MojitoFan** [comment] 2019-02-02 18:09
As far as I know only the Qt frontend is broken on 10.13, Citra itself still works when launched from terminal commands.

**Comment by Sparen** [comment] 2019-02-02 18:15
I'm able to run on Canary 1112 for now. Thanks for the heads up.

**Comment by DrConflict** [comment] 2019-03-19 01:09
All the laste build do NOT work on High Sierra 10.13.6. Only version 1144.
Wondering when the latest version will be fixed.

**Comment by Omega7343** [comment] 2019-03-19 07:02
I have the same issue. 

System Specs:
macOS High Sierra: 10.13.6 (17G65)
Processor: 2 GHz Intel Core i5

**Comment by lAnatoliyl** [comment] 2019-03-26 16:23
> As far as I know only the Qt frontend is broken in High Sierra, Citra itself does play games fine when launched from terminal commands.

How did you managed to launch citra from terminal?

**Comment by yerejm** [comment] 2019-03-31 02:57
Problem appears to be introduced by QT5.12. Built master against it and reproduced the problem.
Tried with QT5.11 and the problem is not present.
QT5.12.0 was released 2018/12/06, so with a little delay for brew to update, it matches the dates of the nightly builds that no longer work.

So citria will have to fix the QT version that is built against and not rely on brew (or make their own tap for 5.11).

**Comment by Sparen** [comment] 2019-04-17 23:17
I'm glad that the issue has been found, at the very least. Being stuck on Canary 1112 really sucks, especially when building from source fails due to the SDL Joystick library and since the command line version lacks so many UI features.

**Comment by FearlessTobi** [comment] 2019-04-18 00:13
Could someone test if the problem persists on the very latest Canary build?

**Comment by Sparen** [comment] 2019-04-18 00:18
Canary 1298 still has the problem. Just tested.

**Comment by FearlessTobi** [comment] 2019-04-18 00:34
Thanks for the report.

**Comment by yerejm** [comment] 2019-04-20 03:21
To revert qt5 back to the last 5.11 brew in the continuous build, insert in citra/.travis/macos/deps.sh after line 3 "brew update":

`curl -s https://raw.githubusercontent.com/Homebrew/homebrew-core/5eb54ced793999e3dd3bce7c64c34e7ffe65ddfd/Formula/qt.rb > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb`

Those building from source should also be able to do this manually to get a citra compatible QT5.

**Comment by NielsG98** [comment] 2019-05-17 18:46
I have the same problem on a Macbook Pro Late 2011 High Sierra 
(Intel HD Graphics 3000, i7, OpenGL 3.3)

The thing is I can launch games with command line in the terminal. I can run Ocarina of Time 3D smoothly. However, my PS4 controller doesn't work, and I don't know if it's because i'm not running it through the QT GUI, or because my configuration is wrong (I even tried to change settings in conf files, but it didn't work)
So the problem should be related to the Qt5.

I've also tried the fix by yerejm, and building the app, but it didn't work either. It was my first time using CMake, and i didn't try it again

"Issue openend on 16 déc 2018" : I think I will play on Citra on my Android phone first

**Comment by SmiVan** [comment] 2019-05-23 00:27
@yerejm's solution didn't work for me, but I derived a different temporary solution from it that did work.

Run `curl -s https://raw.githubusercontent.com/Homebrew/homebrew-core/5eb54ced793999e3dd3bce7c64c34e7ffe65ddfd/Formula/qt.rb > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb` in console, then `brew reinstall qt5; brew pin qt5`. 
Note that this will prevent Homebrew from updating QT5 to newer versions.
Then build from source as usual.

It will build with the non-broken QT5 version and work just fine.

**Comment by gerger05** [comment] 2019-05-23 03:49
Sorry, I know nothing about coding. Can someone explain how to launch games in Citra from the command line in terminal? I am experiencing the same issue as everyone else.

**Comment by NielsG98** [comment] 2019-05-25 18:12
@gerger05 just open the terminal, use the cd command to move where you have the citra-qt.app and citra files (`cd "Applications/citra/canary"` for me) 
After that just type `./citra "path/to/your/game.3ds" `  and it will launch your game

**Comment by NielsG98** [comment] 2019-05-25 18:21
@SmiVan Yeah so I will have to build every canary version myself, and this computer is not very powerful. And i also need XCode, and this Mac is not compatible with OS X 10.14.3 and I need it for XCode. So i cannot build with the non-broken QT5 version. 
So I would definitely prefer a fixed version by the "developpers"

**Comment by gerger05** [comment] 2019-05-25 19:59
> @gerger05 just open the terminal, use the cd command to move where you have the citra-qt.app and citra files (`cd "Applications/citra/canary"` for me)
> After that just type `./citra "path/to/your/game.3ds" ` and it will launch your game

Thanks so much!

**Comment by gerger05** [comment] 2019-05-25 20:11
> @gerger05 just open the terminal, use the cd command to move where you have the citra-qt.app and citra files (`cd "Applications/citra/canary"` for me)
> After that just type `./citra "path/to/your/game.3ds" ` and it will launch your game

Thanks so much for answering. However, after entering (./citra path/to/your/game.3ds) I receive this error [   0.747731] Loader <Error> core/loader/loader.cpp:GetLoader:126: Failed to load file path/to/your/game.3ds
[   0.748214] Core <Critical> core/core.cpp:Load:103: Failed to obtain loader for path/to/your/game.3ds!

**Comment by SmiVan** [comment] 2019-05-25 20:24
@gerger05 This is a bit off topic from this issue, but I'll pm you instructions.

**Comment by gerger05** [comment] 2019-05-25 20:25
> @gerger05 This is a bit off topic from this issue, but I'll pm you instructions.

Thank you guys

**Comment by SmiVan** [comment] 2019-05-25 20:28
> > @gerger05 This is a bit off topic from this issue, but I'll pm you instructions.
> 
> Thank you guys

Nevermind - I forgot that Github removed private messaging for some reason - so I'll have to post here.
You're supposed to replace "path/to/your/game.3ds" with the actual path to your game, but an easier way to do it would be to just type in `./citra ` and then drag the 3ds file into the terminal window, and it will automatically paste the path for you.
Note that any game that requires software keyboard input may not work when using command-line-launched citra.

**Comment by gerger05** [comment] 2019-05-25 20:32
> > > @gerger05 This is a bit off topic from this issue, but I'll pm you instructions.
> > 
> > 
> > Thank you guys
> 
> Nevermind - I forgot that Github removed private messaging for some reason - so I'll have to post here.
> You're supposed to replace "path/to/your/game.3ds" with the actual path to your game, but an easier way to do it would be to just type in `./citra ` and then drag the 3ds file into the terminal window, and it will automatically paste the path for you.
> Note that any game that requires software keyboard input may not work when using command-line-launched citra.
> 
> Apologies for offtopic, I'll delete it after it's read.

Thanks for the clear instructions. I did that however, I get this message back:
-bash: ./citra/Users/geraldcalderon/Downloads/FEE-SOV-USA-_UNDUB_-DecrTD-Ziperto-1/Fire Emblem Echoes Shadows of Valentia (UNDUB) USA Decrypted.3ds: Not a directory

**Comment by SmiVan** [comment] 2019-05-25 20:32
@gerger05 That's because you need a space after ./citra

**Comment by SmiVan** [comment] 2019-05-25 20:33
@gerger05 Also please delete your offtopic comments as well when we are done so we don't clog up the issue

**Comment by gerger05** [comment] 2019-05-25 20:35
> @gerger05 Also please delete your offtopic comments as well when we are done so we don't clog up the issue

got you, thank you so much!

**Comment by NielsG98** [comment] 2019-05-25 22:10
@SmiVan Thanks it's working, but i will have to build every time there is a new version if I want to stay updated ?

**Comment by NielsG98** [comment] 2019-05-29 22:25
Of course now the performance in my custom build is far worse than when i was testing with the command line in the latest canary version. 
Well I can use the GUI and my controller now, but i have 20fps and I even have some graphics issues (link pants is black, his horse in the cinematic is invisible, etc.)
I tried to tweak the hardware shader settings, but it doesn't work.
Strangely I didn't had this with the command line in the canary version.

**Comment by msikma** [comment] 2019-06-09 12:24
To anyone who wants to try the nightly 1144, [download it here](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1144). Make sure to turn off updating in the settings, at least for now.

It is a very strange bug, though. Has it been reported to QT5? [Plenty of things have changed](https://github.com/qt/qt5/compare/5.11...5.12) between version 5.11 and 5.12. I browsed around on the [bug tracker](https://bugreports.qt.io/browse/QTBUG-76262?jql=status%20in%20(Reported%2C%20%22Need%20More%20Info%22%2C%20Open%2C%20%22In%20Progress%22%2C%20Reopened%2C%20Accepted%2C%20Rejected%2C%20%22Waiting%203rd%20party%22%2C%20%22To%20Do%22%2C%20Blocked)%20AND%20text%20~%20%22opengl%22%20AND%20%22Platform%2Fs%22%20%3D%20macOS%20ORDER%20BY%20created%20DESC) but couldn't find anything relevant. Of course, making a bug report at this stage would be vague since we have very little information, but it might be difficult for non-QT5 developers to track this problem down?

**Comment by NielsG98** [comment] 2019-06-10 01:46
Well, I don't want this old version.

**Comment by Sparen** [comment] 2019-06-10 01:49
Even if you don't want to use an older version, that's all we have for now until the issue is fixed. Whether it is fixed by a temporary workaround or by a permanent solution, it will take time and will need visibility with regards to the importance of this issue.

**Comment by luziferius** [comment] 2019-07-03 12:26
I don’t have a Mac, so I can’t do this myself.

You can use a `git bisect` to find the offending commit in Qt. The diff link already posted (https://github.com/qt/qt5/compare/5.11...5.12) shows 461 commits, so the binary search to find the commit introducing this issue will need 9 iterations.

Each iteration step consists of compiling Qt from source and then linking Citra against the local Qt build.
When you found the offending commit, it’ll be easier to report it to the Qt project.

**Comment by SmiVan** [comment] 2019-07-04 22:28
@luziferius Unfortunately my computer is too weak to recompile Qt5 nine times within any reasonable time-frame, but with some research I found [this old QT bug report](https://bugreports.qt.io/browse/QTBUG-68130) which sounds pretty similar to what's happening here, is it related perhaps?

**Comment by Sparen** [comment] 2019-08-13 21:31
Given that Citra seems to have explicitly dropped support for High Sierra with the latest releases of its macOS application, is it safe to assume that this issue has been abandoned?

**Comment by SmiVan** [comment] 2019-08-25 13:00
> Given that Citra seems to have explicitly dropped support for High Sierra with the latest releases of its macOS application, is it safe to assume that this issue has been abandoned?

Where did you hear about that? The [FAQ](https://citra-emu.org/wiki/faq/) still says that 
> Citra is actively tested and supported on [...] macOS 10.13 High Sierra or higher.
And it compiles and launches just fine on High Sierra, without any deprecation warnings.

**Comment by Sparen** [comment] 2019-08-25 14:02
> > Given that Citra seems to have explicitly dropped support for High Sierra with the latest releases of its macOS application, is it safe to assume that this issue has been abandoned?
> 
> Where did you hear about that? The [FAQ](https://citra-emu.org/wiki/faq/) still says that
> 
> > Citra is actively tested and supported on [...] macOS 10.13 High Sierra or higher.
> 
> And it compiles and launches just fine on High Sierra, without any deprecation warnings, unless I'm missing something.

The official build for end users now requires Mojave or later. Users on High Sierra who used the Citra automatic updater discovered that Citra's update actually bricked the application, preventing it from being launched at all.

I'm perfectly sure that you can build Citra from the source code and get a functioning executable, but if the official Nightly/Canary citra-qt application can't be launched on macOS High Sierra, I think it's safe to say that to a typical end user, they'd think that Citra has dropped support for that OS.

**Comment by SmiVan** [comment] 2019-08-31 12:26
It sounds to me less like dropped support and more like a buggy automatic updater/release package.
I guess we'll have to wait for a word from senior devs on the project regarding this.

**Comment by Sparen** [comment] 2019-09-14 03:14
As of Citra Canary 1471, this issue seems to have been resolved for macOS 10.13, and the application is also running as intended without prompting for an OS update. Please mark this issue as closed.

**Comment by takeshineale128** [comment] 2019-09-14 14:08
> As of Citra Canary 1471, this issue seems to have been resolved for macOS 10.13, and the application is also running as intended without prompting for an OS update. Please mark this issue as closed.
I can confirm it’s working on macOS 10.13

**Comment by wwylele** [comment] 2019-09-14 14:18
Something just magically fixed itself...

**Comment by lambdanerd** [comment] 2019-09-15 22:48
It's also working for me on 10.14.6! Is this still an issue for others?

**Comment by SmiVan** [comment] 2019-09-19 17:52
Can confirm that it's all working now, and I haven't changed anything about my system.

Guess it got fixed in either one of the commits or one of the QT releases.

Safe to close the issue.

**Comment by FearlessTobi** [comment] 2019-09-19 20:52
Closing as the original issue is fixed.

**Closed by FearlessTobi** 2019-09-19 20:52 UTC
