### ISSUE TITLE
Pokemon sun graphical errors related to shaderJIT

### ISSUE THREAD

**Issue by wakka1** [citra-emu/citra#2209] opened 2016-11-24 13:08 UTC
Specs : 
amd HD 6790
Phenom ii X4 955 3.20 ghz
6gb ram
windows 7 64bit
Tested with master d3b7f57
Edit : Forgot to mention in first post that the issue is most likely related to certain hardware as i saw some yotube footage working fine for other people.

With ShaderJIT: broken text box and visual effects
![citra-qt 2016-11-27 14-52-37-44](https://cloud.githubusercontent.com/assets/22716011/20648842/dee82be6-b4b1-11e6-9076-a3ae82f6c92b.jpg)

![citra-qt 2016-11-24 13-44-44-45](https://cloud.githubusercontent.com/assets/22716011/20599435/6d57edf0-b24e-11e6-8bf4-c9d28a1675e1.jpg)
![citra-qt 2016-11-24 13-45-04-78](https://cloud.githubusercontent.com/assets/22716011/20599466/90ac77ee-b24e-11e6-85fc-d20e872c5d4e.jpg)

Without ShaderJIT: works fine
![citra-qt 2016-11-27 14-52-46-94](https://cloud.githubusercontent.com/assets/22716011/20648843/e7375344-b4b1-11e6-9f4a-0160f7f0465b.jpg)

![citra-qt 2016-11-24 13-47-45-31](https://cloud.githubusercontent.com/assets/22716011/20599481/a173da68-b24e-11e6-85cb-4d844592aaa8.jpg)
![citra-qt 2016-11-24 13-48-31-26](https://cloud.githubusercontent.com/assets/22716011/20599497/a7e4ca56-b24e-11e6-8368-c9b612935082.jpg)

Log: 
[error log.txt](https://github.com/citra-emu/citra/files/614729/error.log.txt)

**Comment by JayFoxRox** [comment] 2016-11-24 13:13
Please re-test on current master. There is no support for bleeding edge and there are shader related features in bleeding edge.

**Comment by wakka1** [comment] 2016-11-24 13:38
Sorry for that, i do not have any nightly build and never built  one, i'll see what  i can do.

**Comment by wwylele** [comment] 2016-11-24 15:20
Tested on current master with shader JIT on and doesn't encounter such problem. Probably an issue in GS.

**Comment by wakka1** [comment] 2016-11-24 15:52
Citra crashes when i load a game.  Looks like i couldn't build it right.
 I did check others who got it working good, so i assume it's incompatibility with my gpu or something like that. Sorry can't offer anymore info now, i'll test again when nightly becomes available hopefully. Do close/remove thread if it has no more purpose.

**Comment by freiro** [comment] 2016-11-24 15:58
@wakka1 did you follow https://github.com/citra-emu/citra/wiki/Building-for-Windows ?
In particular where it says "Compile as release"

**Comment by wakka1** [comment] 2016-11-24 16:12
I followed the mingw guide because visual studio would take a long time to download for me

**Comment by jroweboy** [comment] 2016-11-24 16:14
@wakka1 disable microprofile by doing -DMICROPROFILE_ENABLE=0 when configuring the cmake build. See https://github.com/citra-emu/citra/pull/2200 for more info If you need further help with building please take this to the forums where we can help you without bothering the other developers.

**Comment by wakka1** [comment] 2016-11-24 16:54
Disabling microprofile did it , thanks!
I'll edit the first post.

**Comment by Subv** [comment] 2016-11-27 16:44
What CPU do you have? What OS do you have?

**Comment by wakka1** [comment] 2016-11-27 19:28
@Subv  phenom ii x4 955 3.20 ghz  ,6gb ram , windows 7 64bit

**Comment by WoLF18rip** [comment] 2016-11-28 11:42
I´ve got the same problem on my Phenom II x6 1100T, the rest of my specs:
16Gb ram
Win 10 64bit 
GTX 970
Idk if this helps, but i see this message at the console when I open citra: 
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
    QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
    QT_SCREEN_SCALE_FACTORS to set per-screen factors.
    QT_SCALE_FACTOR to set the application global scale factor.

**Comment by freiro** [comment] 2016-11-28 11:48
You are both using the dedicated Video Card (no gpu in your processors). 
Since one is AMD and the other Nvidia I don't think the GPU is the problem.
Intead the problem might be related to AMD since you are both using AMD Phenom CPUs.

**Comment by wakka1** [comment] 2016-11-28 13:43
I hope if someone else has phenom cpu can  test..

**Comment by JayFoxRox** [comment] 2016-11-28 15:00
We had the same report on discord yesterday (Menu broken the same way).
They, however, claimed that it was also broken without JIT?!

I do have an apitrace file from that user (which contains copyrighted material = won't upload). It produces the same visual errors for me on Intel HD 4000 when playing that trace. This confirms that the problem does probably not lie on the GL side.

> video card is Radeon 7880 HD or something
> Phenom II X4 955
> Windows 7

On startup the console log says `ANOMALY: meaningless REX prefix used` 3 times, which might be related?

**Comment by wakka1** [comment] 2016-11-28 15:32
@JayFoxRox For me, the issue definitely doesn't exist with shaderJIT off ( as you can see from the pictures) and it plays good although much slower. I already tried to enable/disable hardware renderer/shaderJIT/scaled resolution, and it only happens with shaderJIT on.

I figured since me and @WoLF18rip both have phenom CPUs but different  GPUs, it couldn't be a GPU problem.
I can do a video or  apitrace (never used before) if it helps.

**Comment by JayFoxRox** [comment] 2016-11-28 20:58
I'd suggest running without shader-jit for now. We have a couple of shader-jit issues anyway, so we should probably have a debug feature to debug the shader-jit.
I've explained how to do this on IRC before but I think the person who wanted to do it disappeared.
If they don't resurface soon I'll probably do it around christmas.

**Comment by JayFoxRox** [comment] 2016-12-03 04:34
Please re-test now. #2255 is merged

**Comment by wakka1** [comment] 2016-12-03 10:03
@JayFoxRox Issue still exist. 

![without shader](https://cloud.githubusercontent.com/assets/22716011/20858577/0bb8c884-b948-11e6-97ea-2266439e9486.jpg)

**Comment by JayFoxRox** [comment] 2016-12-03 16:31
Can you also test wether you can reproduce #1743 for me please? I feel this is a similar issue.
Also does this error also happen in other Pokemon games? I'd like to test this but don't have Pokemon Sun / Moon yet.

**Comment by wakka1** [comment] 2016-12-03 18:29
@JayFoxRox #1743 happens to me too . I have pokemon omega ruby (no AS) and it works fine, no issues.

**Comment by wakka1** [comment] 2016-12-04 10:10
@JayFoxRox Yep both  #2209 and #1743 are  fixed after your latest commit. Much appreciated. :+1:

**Closed** 2016-12-04 10:20 UTC
Labels: A-graphics, F-gpu:shader-jit
