### ISSUE TITLE
Game Compability and Website

### ISSUE THREAD

**Issue by Steamsweet** [citra-emu/citra#5727] opened 2021-02-26 08:15 UTC
Hey Guys:

Idk why but since 1427 (Canary) and 1319 (Nightly) the Compability list does not work. The old versions still works for me.
The Updates might take between 4 August 2019 and 8 August 2019.
Please look on that the hole prozess in citra is only available for US Games.

![Screenshot 2021-02-25 191403](https://user-images.githubusercontent.com/53945997/109273838-034cab00-7813-11eb-94e1-75b083ef5d74.png)
![Screenshot 2021-02-25 184643](https://user-images.githubusercontent.com/53945997/109273854-08a9f580-7813-11eb-8f9f-a7fd1f4bf125.png)

**Comment by SleepingSnakezzz** [comment] 2023-04-30 10:44
Duplicate of https://github.com/citra-emu/citra/issues/4880

**Closed by SleepingSnakezzz** 2023-04-30 10:44 UTC
