### ISSUE TITLE
Can't get build instructions working for Windows.

### ISSUE THREAD

**Issue by WinterMute** [citra-emu/citra#1353] opened 2016-01-10 16:12 UTC
Not sure what's going on with this

Output from Cmake is :-

The C compiler identification is unknown
The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:36 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:36 (project):
  No CMAKE_CXX_COMPILER could be found.

Configuring incomplete, errors occurred!
See also "C:/Users/davem_000/projects/3ds/citra/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/davem_000/projects/3ds/citra/build/CMakeFiles/CMakeError.log".

[CMakeError.log.txt](https://github.com/citra-emu/citra/files/84162/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/citra-emu/citra/files/84163/CMakeOutput.log.txt)

**Comment by wwylele** [comment] 2016-01-10 16:35
`cannot open input file 'kernel32.lib'`
The Windows SDK seems to be missed or damaged.
Have you successfully built a simple windows program on this computer?

**Comment by WinterMute** [comment] 2016-01-11 00:42
I've successfully built many windows programs on this computer. VS 2015 works fine from the IDE.

**Comment by WinterMute** [comment] 2016-01-11 03:28
OK. This appears to be an issue with Windows 10 & Cmake 3.4.1. See https://cmake.org/Bug/view.php?id=15831

I uninstalled 3.4.1 and installed 3.3.2 which works and I can build citra now

**Comment by MerryMage** [comment] 2016-01-15 19:50
For the record the issue is fixed in cmake 3.5.

**Comment by Subv** [comment] 2016-01-15 20:15
This is a CMake bug, not a Citra bug.

**Closed by Subv** 2016-01-15 20:15 UTC
Labels: invalid

**Comment by yuriks** [comment] 2016-01-15 20:23
It still affects us though. I think someone should at least add a note on the build instructions about how to fix/workaround it.

**Comment by Subv** [comment] 2016-01-15 20:27
Do we have a "Requirements" page anywhere? I feel that would be the best way to place this information

**Comment by WinterMute** [comment] 2016-01-15 20:35
https://github.com/citra-emu/citra/wiki/Common-Issues might be a good place
