### ISSUE TITLE
Pokemon Ultra Sun/Ultra Moon - Alola Photo Club lockup

### ISSUE THREAD

**Issue by Hexagon12** [citra-emu/citra#3128] opened 2017-11-17 12:25 UTC
Tested on Nightly c810a3f.

The game locks up (freezes) when you're trying to enter the Alola Photo Club for the first time.
Everything seems frozen, but the music still plays and shows "100% speed, 0 FPS" at the bottom.

Not related to #3091, because the same issue happens on Canary.
This issue makes the game unbeatable without any workarounds.

My observations:

Issue could be similar to the X/Y freezes, because both end with a CRO log.
(I would upload the wait tree as well, but I'm well into the game and forgot to keep a secondary save).

A valid workaround would be to transfer the save data back to the 3DS, save the game after the section is finished and bring back the save data from the 3DS to Citra.

Log file: 
[log.txt](https://github.com/citra-emu/citra/files/1482241/log.txt)

**Comment by CDAGaming** [comment] 2017-11-17 12:34
In Addition to This, This Issue is also similar to Other lockups (Hau Battle after Final Four) but those have different workarounds but the same  symptom

In addition also, another Workaround is mentioned here: https://www.youtube.com/watch?v=kmKhxQCkukU

**Comment by RavenHome1** [comment] 2017-11-18 20:27
you can go to the photo club at anytime so you still can get the wait tree

**Comment by spixi** [comment] 2017-11-18 21:15
Have you tried the workaround mentioned [here](https://projectpokemon.org/home/forums/topic/42368-i-need-an-ultra-moon-save/?tab=comments#comment-222868)?

**Comment by CDAGaming** [comment] 2017-11-18 21:55
@spixi I had mentioned this workaround previously, but yes that is the other one that would work.

**Comment by zackcain** [comment] 2017-11-25 16:54
So until this is fixed you can only play Ultra Sun/Moon for 4/5 hours? I haven't been this bummed out in a while.

**Comment by Hexagon12** [comment] 2017-11-27 09:03
@RavenHome1 The freeze only appears at the first time, and the subsequent times don't cause the game to freeze.

**Comment by ronaldneri** [comment] 2017-11-30 16:19
You can skip this part (photo club), modifying Flags with pkhex, here is a video in Spanish, but it's easy: https://youtu.be/lAdLpZBF4K4

**Comment by CDAGaming** [comment] 2017-11-30 16:23
Again, this workaround has already been mentioned many times, and is a bit out of scope of Citra.

**Comment by boomshroom** [comment] 2017-12-15 03:32
Workarounds let the system get used at all. They do not make this not a bug. Any crashes or freezes, able to be worked around or not, are still bugs (unless the crash is intentional, but very few games can claim so).

**Comment by valentinvanelslande** [comment] 2018-01-01 05:58
with the fix, it freezes on the album with more than one photo

**Comment by Sergio00166** [comment] 2018-01-24 14:13
Solucion:
https://www.youtube.com/watch?v=lAdLpZBF4K4

**Comment by RavenHome1** [comment] 2018-01-24 18:26
i think this should be locked and limited to contributors only, it is only generating noise and is starting to fill up with side tracks about work around while the original issue is to notify contributors of the bug existence and discuss possible solutions

**Comment by jroweboy** [comment] 2018-01-24 18:32
@RavenHome1 agreed. we already know about the fix that someone found (increasing the ipc delay for romfs access), and @B3n30 is working on verifying the behavior on hardware with a hardware test. when we get that all settled, we can update this issue with more information.

**Comment by wwylele** [comment] 2018-03-05 11:19
Fixed by #3440

**Closed by wwylele** 2018-03-05 11:19 UTC
Labels: has-games-wiki-entry
