### ISSUE TITLE
Suggestion: Allow separate screen windows for better multi monitor support

### ISSUE THREAD

**Issue by notmutiny** [citra-emu/citra#3817] opened 2018-06-07 07:45 UTC
<-- not an emulator issue, merely a suggestion and nowhere to put it -->

If there was a screen layout option for hosting each 3DS screen in their own window users could drag them to whatever monitor they want and really fullscreen them. Currently the implementation shares the screens in one window, meaning one is focused while the other is not (assuming you want fullscreen gameplay).

**Comment by FearlessTobi** [comment] 2018-06-07 12:41
Duplicate of https://github.com/citra-emu/citra/issues/3698

Requesting to close.

**Closed** 2018-06-07 14:04 UTC
