### ISSUE TITLE
Fire Emblem Awakening (EUR) Crash on Specific Unit Attack Phase Animation

### ISSUE THREAD

**Issue by Ironclad17** [citra-emu/citra#3635] opened 2018-04-06 22:58 UTC
Crash occurs when enemy Archer attack phase begins. Crash circumvented by skipping enemy attack turn. Most likely a graphics glitch. Crash was recreated several times. Crash did not occur in Canary|HEAD-eb8c415
System Information
    Operating System: Windows 7
    CPU: i7-7700K
    GPU: Nvidia GTX1080
    Citra Version: Nightly|HEAD-39fce60
    Game: Fire Emblem Awakening (EUR)
    Screenshot of Issue:
![fea crash](https://user-images.githubusercontent.com/20147654/38447609-601c4102-39cc-11e8-976f-668794e6dd1c.jpg)
Graphics: 
![graphics](https://user-images.githubusercontent.com/20147654/38447869-44955c50-39ce-11e8-97fe-4cc823d77096.jpg)

[log.txt](https://github.com/citra-emu/citra/files/1885782/log.txt)
Save file: [Chapter1.zip](https://github.com/citra-emu/citra/files/1885796/Chapter1.zip)

To recreate the glitch have an archer attack Chrom with Lissa Support. Just moving him to trees in the Archer's range will be enough to get it to attack him. Placing other units above and to his right will neutralize other attacks.

**Comment by Patrickzzz22** [comment] 2018-04-07 01:05
Can confirm this bug happens to me on the latest nightly build, didn't happen in the previous one.

**Comment by wwylele** [comment] 2018-04-07 07:39
The log file is incomplete. Could you leave the black console window on the screen and take a screenshot when it crashes?

**Comment by tom-overton** [comment] 2018-04-07 21:31
I reproduced the crash on my built version of citra. The reported version is master-39fce601. Here's a link to the callstack: https://pastebin.com/HS4nrD0Q

**Comment by Ironclad17** [comment] 2018-04-08 06:09
![crash with command](https://user-images.githubusercontent.com/20147654/38463904-ebc0a9b8-3ad1-11e8-8f30-a2c54e0f8cc6.jpg)

**Comment by ktellos** [comment] 2018-04-08 09:32
I get the same issue crashes when attacking with Lissa Dark Flyer. It appears to be caused by the merged pull #3497 - gl_rasterizer: implement TextureCube.
Reverting pull #3497 allows the battle to work fine like in the past with the log spamming a few repeated lines of.

[  74.148555] HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:SampleTexture:205: Unhandled texture type 1
[  74.148827] Debug <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:SampleTexture:206: Unimplemented code!

**Comment by wwylele** [comment] 2018-04-08 09:45
Could you please test #3639 ? I have tagged it to the canary build so you can wait for the canary release. Also, if it doesn't crash any more, please also check if there is any graphical glitch where it crashed before.

**Comment by ktellos** [comment] 2018-04-08 10:36
For me #3639 fixes the crash and I didn't see any graphical glitch.

**Comment by tom-overton** [comment] 2018-04-08 18:08
I can also confirm that #3639 fixes the issue. I do not see any apparent graphical glitches, but I can test on hardware as well if you need it.

**Comment by tom-overton** [comment] 2018-04-08 18:40
These aren't the exact same frame due to the fact that it's really hard to pause Citra with perfect timing, but they should be close enough:

![citra.png](https://user-images.githubusercontent.com/12245827/38471111-6d670a80-3b21-11e8-8aaf-70bde8d79f57.png)

![hardware.png](https://user-images.githubusercontent.com/12245827/38471114-7e869074-3b21-11e8-9e21-5c43279956a7.png)

Everything looks good to me, at least.

**Comment by wwylele** [comment] 2018-04-08 21:28
@Ironclad17 because that canary doesn't contain the PR that causes the crash (#3497)

**Comment by Ironclad17** [comment] 2018-04-08 21:30
Well I'm satisfied.

**Closed** 2018-04-12 19:54 UTC
