### ISSUE TITLE
Ace Attorney 6: Bottom touch screen blinking

### ISSUE THREAD

**Issue by coreboot2** [citra-emu/citra#2640] opened 2017-03-25 12:47 UTC
![2017-03-25](https://cloud.githubusercontent.com/assets/22993904/24322284/7b43475a-119b-11e7-86ae-579c7e7fade7.png)

The top screen is ok. But the bottom screen only shows a bit to the left and keeps blinking. 
I had tried the offical build, the bleeding bleeding-edge, enabled/disabled JIT/ vsync. But the bottom screen is always blinking. The game is the Japanese version Ace Attorney 6 called gyakuten saiban 6. I also tried Ace Attorney 5 (gyakuten saiban 5). It also has the same issue.

The full debug log is here: http://pastebin.com/fMcfDZxG

**Comment by JayFoxRox** [comment] 2017-03-25 12:53
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://community.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

We don't support bleeding edge.. so either you fix this issue pronto or we'll have to close it.

**Comment by Hexagon12** [comment] 2017-03-25 15:02
@JayFoxRox BE 86 build didn't have https://github.com/citra-emu/citra/pull/2463 commit. Therefore, DD would not load on BE 86.

**Comment by FearlessTobi** [comment] 2017-11-19 02:23
The issue persists in the latest Nightly so it´s not caused by missing GS. Here is an updated log: https://pastebin.com/cD1iAXsN

**Comment by wwylele** [comment] 2018-03-05 10:54
Fixed by #3281.

**Closed** 2018-03-05 11:01 UTC
