### ISSUE TITLE
Multi Control Config Support

### ISSUE THREAD

**Issue by Qquanwei** [citra-emu/citra#4522] opened 2018-12-19 02:36 UTC
Version: Citra Nightly 1156 | HEAD-29548bb
Host System: Windows 10

In my situation, sometimes I use my PS4 controller and the keyboard of my PC, but Citra Control config only allow to save single config. So I need change my config over and over.

There is a feature in develop? or maybe this can be a feature.

**Comment by zhaowenlan1779** [comment] 2018-12-19 13:37
Kinda duplicate of #4322 .

**Closed** 2018-12-19 13:38 UTC
