### ISSUE TITLE
Pokèmon crystal(europe) bad audio.

### ISSUE THREAD

**Issue by Bighitti** [citra-emu/citra#4551] opened 2019-01-04 17:22 UTC
Hi! i have some problems about the audio with the crystal version eshop,my pc can reach 100% velocity for the game and i have the last version of citra canary with hle audio(fast). Here there is a video of another person that have the same problem.

https://www.youtube.com/watch?v=K4HZTz1pttA

**Comment by legoj15** [comment] 2019-01-05 09:33
Duplicate of #2552
For now, to fix that issue, go to the settings of Citra and change the audio mode from HLE to a LLE mode

**Comment by Subv** [comment] 2020-04-12 00:43
Closing as duplicate of #2552

**Closed by Subv** 2020-04-12 00:43 UTC
