### ISSUE TITLE
Citra window becomes unresponsive on Apple silicon M1

### ISSUE THREAD

**Issue by erikmartinessanches** [citra-emu/citra#6633] opened 2023-06-21 15:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2519

### Description of Issue

After a few seconds into starting a geme, the Citra window becomes unresponsive  
 with a spinner showing when the cursor is over the menu and window, preventing menu access and resizing of Citra window.

The game continues to run normally, receive input and render.

I'm not sure I have the right settings, as there's not way to restore default settings in the Settings window.

### Expected Behavior

The Citra window should continue to work. The window should stay responsive.

### Reproduction Steps

See description.

### Log File

```
[   0.000028] Config <Info> common/settings.cpp:LogSettings:141: Citra Configuration:
[   0.000030] Config <Info> common/settings.cpp:operator():138: Core_UseCpuJit: true
[   0.000031] Config <Info> common/settings.cpp:operator():138: Core_CPUClockPercentage: 100
[   0.000031] Config <Info> common/settings.cpp:operator():138: Renderer_UseGLES: false
[   0.000032] Config <Info> common/settings.cpp:operator():138: Renderer_GraphicsAPI: Invalid
[   0.000032] Config <Info> common/settings.cpp:operator():138: Renderer_AsyncShaders: false
[   0.000032] Config <Info> common/settings.cpp:operator():138: Renderer_AsyncPresentation: true
[   0.000033] Config <Info> common/settings.cpp:operator():138: Renderer_SpirvShaderGen: true
[   0.000033] Config <Info> common/settings.cpp:operator():138: Renderer_Debug: false
[   0.000033] Config <Info> common/settings.cpp:operator():138: Renderer_UseHwShader: false
[   0.000033] Config <Info> common/settings.cpp:operator():138: Renderer_ShadersAccurateMul: true
[   0.000034] Config <Info> common/settings.cpp:operator():138: Renderer_UseShaderJit: true
[   0.000034] Config <Info> common/settings.cpp:operator():138: Renderer_UseResolutionFactor: 4
[   0.000034] Config <Info> common/settings.cpp:operator():138: Renderer_FrameLimit: 105
[   0.000035] Config <Info> common/settings.cpp:operator():138: Renderer_VSyncNew: false
[   0.000035] Config <Info> common/settings.cpp:operator():138: Renderer_PostProcessingShader: none (builtin)
[   0.000035] Config <Info> common/settings.cpp:operator():138: Renderer_FilterMode: true
[   0.000036] Config <Info> common/settings.cpp:operator():138: Renderer_TextureFilter: None
[   0.000038] Config <Info> common/settings.cpp:operator():138: Stereoscopy_Render3d: 0
[   0.000038] Config <Info> common/settings.cpp:operator():138: Stereoscopy_Factor3d: 0
[   0.000038] Config <Info> common/settings.cpp:operator():138: Stereoscopy_MonoRenderOption: 0
[   0.000039] Config <Info> common/settings.cpp:operator():138: Layout_LayoutOption: 2
[   0.000039] Config <Info> common/settings.cpp:operator():138: Layout_SwapScreen: false
[   0.000039] Config <Info> common/settings.cpp:operator():138: Layout_UprightScreen: false
[   0.000040] Config <Info> common/settings.cpp:operator():138: Layout_LargeScreenProportion: 4
[   0.000041] Config <Info> common/settings.cpp:operator():138: Utility_DumpTextures: false
[   0.000041] Config <Info> common/settings.cpp:operator():138: Utility_CustomTextures: false
[   0.000041] Config <Info> common/settings.cpp:operator():138: Utility_PreloadTextures: false
[   0.000041] Config <Info> common/settings.cpp:operator():138: Utility_AsyncCustomLoading: true
[   0.000042] Config <Info> common/settings.cpp:operator():138: Utility_UseDiskShaderCache: false
[   0.000042] Config <Info> common/settings.cpp:operator():138: Audio_Emulation: HLE
[   0.000042] Config <Info> common/settings.cpp:operator():138: Audio_OutputType: 0
[   0.000043] Config <Info> common/settings.cpp:operator():138: Audio_OutputDevice: auto
[   0.000043] Config <Info> common/settings.cpp:operator():138: Audio_InputType: 0
[   0.000043] Config <Info> common/settings.cpp:operator():138: Audio_InputDevice: auto
[   0.000044] Config <Info> common/settings.cpp:operator():138: Audio_EnableAudioStretching: true
[   0.000044] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightName: blank
[   0.000044] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightConfig: 
[   0.000045] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightFlip: 0
[   0.000045] Config <Info> common/settings.cpp:operator():138: Camera_InnerName: blank
[   0.000045] Config <Info> common/settings.cpp:operator():138: Camera_InnerConfig: 
[   0.000045] Config <Info> common/settings.cpp:operator():138: Camera_InnerFlip: 0
[   0.000046] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftName: blank
[   0.000046] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftConfig: 
[   0.000046] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftFlip: 0
[   0.000047] Config <Info> common/settings.cpp:operator():138: DataStorage_UseVirtualSd: true
[   0.000047] Config <Info> common/settings.cpp:operator():138: DataStorage_UseCustomStorage: false
[   0.000047] Config <Info> common/settings.cpp:operator():138: System_IsNew3ds: true
[   0.000048] Config <Info> common/settings.cpp:operator():138: System_RegionValue: -1
[   0.000048] Config <Info> common/settings.cpp:operator():138: System_PluginLoader: false
[   0.000048] Config <Info> common/settings.cpp:operator():138: System_PluginLoaderAllowed: true
[   0.000048] Config <Info> common/settings.cpp:operator():138: Debugging_UseGdbstub: false
[   0.000049] Config <Info> common/settings.cpp:operator():138: Debugging_GdbstubPort: 24689
[   0.122487] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.153521] Frontend <Info> citra_qt/main.cpp:GMainWindow:237: Citra Version: Canary 2519  | HEAD-fa011fc-dirty
[   0.153530] Frontend <Info> citra_qt/main.cpp:GMainWindow:254: Host OS: macOS Ventura (13.4)
[   0.153547] Frontend <Info> citra_qt/main.cpp:GMainWindow:257: Host RAM: 16.00 GiB
[   0.153548] Frontend <Info> citra_qt/main.cpp:GMainWindow:258: Host Swap: 8.00 GiB
[   0.182249] Frontend <Info> citra_qt/main.cpp:CheckForUpdates:948: Update check started
[   1.541915] Frontend <Info> citra_qt/main.cpp:OnUpdateFound:961: No updates found
[  72.434494] Config <Info> common/settings.cpp:LogSettings:141: Citra Configuration:
[  72.434499] Config <Info> common/settings.cpp:operator():138: Core_UseCpuJit: true
[  72.434500] Config <Info> common/settings.cpp:operator():138: Core_CPUClockPercentage: 100
[  72.434500] Config <Info> common/settings.cpp:operator():138: Renderer_UseGLES: false
[  72.434500] Config <Info> common/settings.cpp:operator():138: Renderer_GraphicsAPI: Invalid
[  72.434501] Config <Info> common/settings.cpp:operator():138: Renderer_AsyncShaders: false
[  72.434501] Config <Info> common/settings.cpp:operator():138: Renderer_AsyncPresentation: true
[  72.434501] Config <Info> common/settings.cpp:operator():138: Renderer_SpirvShaderGen: true
[  72.434502] Config <Info> common/settings.cpp:operator():138: Renderer_Debug: false
[  72.434502] Config <Info> common/settings.cpp:operator():138: Renderer_UseHwShader: false
[  72.434502] Config <Info> common/settings.cpp:operator():138: Renderer_ShadersAccurateMul: true
[  72.434503] Config <Info> common/settings.cpp:operator():138: Renderer_UseShaderJit: true
[  72.434503] Config <Info> common/settings.cpp:operator():138: Renderer_UseResolutionFactor: 4
[  72.434504] Config <Info> common/settings.cpp:operator():138: Renderer_FrameLimit: 105
[  72.434504] Config <Info> common/settings.cpp:operator():138: Renderer_VSyncNew: false
[  72.434504] Config <Info> common/settings.cpp:operator():138: Renderer_PostProcessingShader: none (builtin)
[  72.434505] Config <Info> common/settings.cpp:operator():138: Renderer_FilterMode: true
[  72.434505] Config <Info> common/settings.cpp:operator():138: Renderer_TextureFilter: None
[  72.434507] Config <Info> common/settings.cpp:operator():138: Stereoscopy_Render3d: 0
[  72.434507] Config <Info> common/settings.cpp:operator():138: Stereoscopy_Factor3d: 0
[  72.434507] Config <Info> common/settings.cpp:operator():138: Stereoscopy_MonoRenderOption: 0
[  72.434507] Config <Info> common/settings.cpp:operator():138: Layout_LayoutOption: 2
[  72.434508] Config <Info> common/settings.cpp:operator():138: Layout_SwapScreen: false
[  72.434508] Config <Info> common/settings.cpp:operator():138: Layout_UprightScreen: false
[  72.434509] Config <Info> common/settings.cpp:operator():138: Layout_LargeScreenProportion: 4
[  72.434510] Config <Info> common/settings.cpp:operator():138: Utility_DumpTextures: false
[  72.434510] Config <Info> common/settings.cpp:operator():138: Utility_CustomTextures: false
[  72.434510] Config <Info> common/settings.cpp:operator():138: Utility_PreloadTextures: false
[  72.434510] Config <Info> common/settings.cpp:operator():138: Utility_AsyncCustomLoading: true
[  72.434511] Config <Info> common/settings.cpp:operator():138: Utility_UseDiskShaderCache: false
[  72.434511] Config <Info> common/settings.cpp:operator():138: Audio_Emulation: HLE
[  72.434511] Config <Info> common/settings.cpp:operator():138: Audio_OutputType: 0
[  72.434511] Config <Info> common/settings.cpp:operator():138: Audio_OutputDevice: auto
[  72.434512] Config <Info> common/settings.cpp:operator():138: Audio_InputType: 0
[  72.434512] Config <Info> common/settings.cpp:operator():138: Audio_InputDevice: auto
[  72.434512] Config <Info> common/settings.cpp:operator():138: Audio_EnableAudioStretching: true
[  72.434512] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightName: blank
[  72.434513] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightConfig: 
[  72.434513] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightFlip: 0
[  72.434513] Config <Info> common/settings.cpp:operator():138: Camera_InnerName: blank
[  72.434513] Config <Info> common/settings.cpp:operator():138: Camera_InnerConfig: 
[  72.434514] Config <Info> common/settings.cpp:operator():138: Camera_InnerFlip: 0
[  72.434514] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftName: blank
[  72.434514] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftConfig: 
[  72.434514] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftFlip: 0
[  72.434514] Config <Info> common/settings.cpp:operator():138: DataStorage_UseVirtualSd: true
[  72.434515] Config <Info> common/settings.cpp:operator():138: DataStorage_UseCustomStorage: false
[  72.434515] Config <Info> common/settings.cpp:operator():138: System_IsNew3ds: true
[  72.434515] Config <Info> common/settings.cpp:operator():138: System_RegionValue: -1
[  72.434515] Config <Info> common/settings.cpp:operator():138: System_PluginLoader: false
[  72.434516] Config <Info> common/settings.cpp:operator():138: System_PluginLoaderAllowed: true
[  72.434516] Config <Info> common/settings.cpp:operator():138: Debugging_UseGdbstub: false
[  72.434516] Config <Info> common/settings.cpp:operator():138: Debugging_GdbstubPort: 24689
[  72.434872] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:797: Change detected in the games directory. Reloading game list.
[  73.399178] Frontend <Info> citra_qt/main.cpp:BootGame:1179: Citra starting...
[  73.399563] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:160: 16384
[  73.403761] Frontend <Info> citra_qt/main.cpp:BootGame:1201: Using per game config file for title id 0004000000125600
[  73.403769] Config <Info> common/settings.cpp:LogSettings:141: Citra Configuration:
[  73.403773] Config <Info> common/settings.cpp:operator():138: Core_UseCpuJit: true
[  73.403774] Config <Info> common/settings.cpp:operator():138: Core_CPUClockPercentage: 100
[  73.403775] Config <Info> common/settings.cpp:operator():138: Renderer_UseGLES: false
[  73.403776] Config <Info> common/settings.cpp:operator():138: Renderer_GraphicsAPI: Invalid
[  73.403776] Config <Info> common/settings.cpp:operator():138: Renderer_AsyncShaders: false
[  73.403777] Config <Info> common/settings.cpp:operator():138: Renderer_AsyncPresentation: true
[  73.403777] Config <Info> common/settings.cpp:operator():138: Renderer_SpirvShaderGen: true
[  73.403778] Config <Info> common/settings.cpp:operator():138: Renderer_Debug: false
[  73.403779] Config <Info> common/settings.cpp:operator():138: Renderer_UseHwShader: false
[  73.403779] Config <Info> common/settings.cpp:operator():138: Renderer_ShadersAccurateMul: true
[  73.403780] Config <Info> common/settings.cpp:operator():138: Renderer_UseShaderJit: true
[  73.403781] Config <Info> common/settings.cpp:operator():138: Renderer_UseResolutionFactor: 4
[  73.403782] Config <Info> common/settings.cpp:operator():138: Renderer_FrameLimit: 105
[  73.403783] Config <Info> common/settings.cpp:operator():138: Renderer_VSyncNew: false
[  73.403784] Config <Info> common/settings.cpp:operator():138: Renderer_PostProcessingShader: none (builtin)
[  73.403785] Config <Info> common/settings.cpp:operator():138: Renderer_FilterMode: true
[  73.403786] Config <Info> common/settings.cpp:operator():138: Renderer_TextureFilter: None
[  73.403789] Config <Info> common/settings.cpp:operator():138: Stereoscopy_Render3d: 0
[  73.403790] Config <Info> common/settings.cpp:operator():138: Stereoscopy_Factor3d: 0
[  73.403790] Config <Info> common/settings.cpp:operator():138: Stereoscopy_MonoRenderOption: 0
[  73.403791] Config <Info> common/settings.cpp:operator():138: Layout_LayoutOption: 2
[  73.403791] Config <Info> common/settings.cpp:operator():138: Layout_SwapScreen: false
[  73.403792] Config <Info> common/settings.cpp:operator():138: Layout_UprightScreen: false
[  73.403796] Config <Info> common/settings.cpp:operator():138: Layout_LargeScreenProportion: 4
[  73.403797] Config <Info> common/settings.cpp:operator():138: Utility_DumpTextures: false
[  73.403797] Config <Info> common/settings.cpp:operator():138: Utility_CustomTextures: false
[  73.403798] Config <Info> common/settings.cpp:operator():138: Utility_PreloadTextures: false
[  73.403799] Config <Info> common/settings.cpp:operator():138: Utility_AsyncCustomLoading: true
[  73.403800] Config <Info> common/settings.cpp:operator():138: Utility_UseDiskShaderCache: false
[  73.403800] Config <Info> common/settings.cpp:operator():138: Audio_Emulation: HLE
[  73.403801] Config <Info> common/settings.cpp:operator():138: Audio_OutputType: 0
[  73.403802] Config <Info> common/settings.cpp:operator():138: Audio_OutputDevice: auto
[  73.403802] Config <Info> common/settings.cpp:operator():138: Audio_InputType: 0
[  73.403803] Config <Info> common/settings.cpp:operator():138: Audio_InputDevice: auto
[  73.403804] Config <Info> common/settings.cpp:operator():138: Audio_EnableAudioStretching: true
[  73.403804] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightName: blank
[  73.403805] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightConfig: 
[  73.403805] Config <Info> common/settings.cpp:operator():138: Camera_OuterRightFlip: 0
[  73.403806] Config <Info> common/settings.cpp:operator():138: Camera_InnerName: blank
[  73.403807] Config <Info> common/settings.cpp:operator():138: Camera_InnerConfig: 
[  73.403807] Config <Info> common/settings.cpp:operator():138: Camera_InnerFlip: 0
[  73.403808] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftName: blank
[  73.403808] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftConfig: 
[  73.403809] Config <Info> common/settings.cpp:operator():138: Camera_OuterLeftFlip: 0
[  73.403810] Config <Info> common/settings.cpp:operator():138: DataStorage_UseVirtualSd: true
[  73.403811] Config <Info> common/settings.cpp:operator():138: DataStorage_UseCustomStorage: false
[  73.403812] Config <Info> common/settings.cpp:operator():138: System_IsNew3ds: true
[  73.403812] Config <Info> common/settings.cpp:operator():138: System_RegionValue: -1
[  73.403813] Config <Info> common/settings.cpp:operator():138: System_PluginLoader: false
[  73.403814] Config <Info> common/settings.cpp:operator():138: System_PluginLoaderAllowed: true
[  73.403814] Config <Info> common/settings.cpp:operator():138: Debugging_UseGdbstub: false
[  73.403815] Config <Info> common/settings.cpp:operator():138: Debugging_GdbstubPort: 24689
[  73.849702] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:137: Cubeb Audio Stream Started
[  73.849714] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:12: Starting RPC server ...
[  73.849744] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:113: Request handler started.
[  73.849806] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:16: RPC started.
[  73.850944] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:807: ClCertA file missing
[  73.855096] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:CreateDevice:608: Geometry shaders not availabe! Accelerated rendering not possible!
[  73.855229] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_swapchain
[  73.855232] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_image_format_list
[  73.855233] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:operator():633: Extension VK_EXT_pipeline_creation_feedback unavailable.
[  73.855233] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_EXT_shader_stencil_export
[  73.855234] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_timeline_semaphore
[  73.855234] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_portability_subset
[  73.855235] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_dynamic_rendering
[  73.855235] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:operator():633: Extension VK_EXT_extended_dynamic_state unavailable.
[  73.855236] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:operator():633: Extension VK_EXT_custom_border_color unavailable.
[  73.855237] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:operator():633: Extension VK_EXT_index_type_uint8 unavailable.
[  73.855237] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_EXT_pipeline_creation_cache_control
[  73.859277] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:496: Format B8G8R8Unorm unsupported, falling back unconditionally to R8G8B8A8Unorm
[  73.859281] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:496: Format X8D24UnormPack32 unsupported, falling back unconditionally to D32Sfloat
[  73.859282] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:496: Format D24UnormS8Uint unsupported, falling back unconditionally to D32SfloatS8Uint
[  73.866336] Render.Vulkan <Info> video_core/renderer_vulkan/vk_resource_pool.cpp:Allocate:128: Allocating new descriptor pool
[  73.879329] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Upload buffer with size 131072 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached }
[  73.879478] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Download buffer with size 16384 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached }
[  73.879593] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 128 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached }
[  73.924733] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 65536 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached }
[  73.924878] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 4096 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached }
[  73.924929] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 2048 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached }
[  73.924989] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 2048 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached }
[  73.925622] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:ReportDriver:1117: VK_DRIVER: MoltenVK 0.2.2012
[  73.925627] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:ReportDriver:1118: VK_DEVICE: Apple M1 Pro
[  73.925628] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:ReportDriver:1119: VK_VERSION: 1.2.250
[  73.927254] Loader <Info> core/loader/ncch.cpp:Load:215: Program ID: 0004000000125600
[  73.927268] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:129: Failed to open /Users/erik/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/00125600/content/00000000.app
[  73.955551] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:151: ExHeader kernel version: 2.39
[  73.959580] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCodes:761: Preferred region code set to 2
[  74.029928] Service.CAM <Info> citra_qt/camera/qt_multimedia_camera.cpp:ResumeCameras:50: Resuming all cameras
[  74.030522] Core <Warning> core/savestate.cpp:ValidateSaveState:62: Save state file /Users/erik/.local/share/citra-emu/states/0004000000125600.01.cst created from a different revision 673e0df1ad580eafb6c448e1c2ba3f3cf32b6758
[  74.031344] Core <Warning> core/savestate.cpp:ValidateSaveState:62: Save state file /Users/erik/.local/share/citra-emu/states/0004000000125600.03.cst created from a different revision 673e0df1ad580eafb6c448e1c2ba3f3cf32b6758
[  74.031759] Core <Warning> core/savestate.cpp:ValidateSaveState:62: Save state file /Users/erik/.local/share/citra-emu/states/0004000000125600.04.cst created from a different revision 673e0df1ad580eafb6c448e1c2ba3f3cf32b6758
[  74.032091] Core <Warning> core/savestate.cpp:ValidateSaveState:62: Save state file /Users/erik/.local/share/citra-emu/states/0004000000125600.05.cst created from a different revision 673e0df1ad580eafb6c448e1c2ba3f3cf32b6758
[  74.032406] Core <Warning> core/savestate.cpp:ValidateSaveState:62: Save state file /Users/erik/.local/share/citra-emu/states/0004000000125600.06.cst created from a different revision 673e0df1ad580eafb6c448e1c2ba3f3cf32b6758
[  74.032622] Core <Warning> core/savestate.cpp:ValidateSaveState:62: Save state file /Users/erik/.local/share/citra-emu/states/0004000000125600.07.cst created from a different revision 673e0df1ad580eafb6c448e1c2ba3f3cf32b6758
[  74.033002] Core <Warning> core/savestate.cpp:ValidateSaveState:62: Save state file /Users/erik/.local/share/citra-emu/states/0004000000125600.08.cst created from a different revision 673e0df1ad580eafb6c448e1c2ba3f3cf32b6758
[  74.033340] Core <Warning> core/savestate.cpp:ValidateSaveState:62: Save state file /Users/erik/.local/share/citra-emu/states/0004000000125600.09.cst created from a different revision 673e0df1ad580eafb6c448e1c2ba3f3cf32b6758
[  74.289316] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
[  74.381098] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
[  74.384730] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F
[  74.384785] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
[  74.385214] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:599: (STUBBED) called, version: 0x070101C8
[  74.385573] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[  74.388049] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[  74.392058] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:338: (STUBBED) app_id=768
[  74.393319] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:637: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[  74.393479] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:637: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  74.400068] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:748: called flag=00000000 process=11 thread_id=0
[  74.435612] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:165: unknown / unimplemented function 'SetInternalPriorities': port='gsp::Gpu' cmd_buf={[0]=0x1e0080 (0x001E, 2, 0), [1]=0x10, [2]=0x11}
[  74.437893] Service.HID <Warning> core/hle/service/hid/hid.cpp:GetGyroscopeLowCalibrateParam:404: (STUBBED) called
[  74.438293] Service.HID <Warning> core/hle/service/hid/hid.cpp:GetGyroscopeLowCalibrateParam:404: (STUBBED) called
[  74.540431] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:512: Firmware hash: 0xe00a211577bc944e
[  74.540437] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:516: Structures hash: 0x228655de1258d999
[  74.540439] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:192: called size=0xC288, prog_mask=0x000000FF, data_mask=0x000E00FF
[  74.540748] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:258: Registered interrupt=2, channel=2, event=event-00163098
[  74.540860] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:274: (STUBBED) called
[  74.540985] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:284: (STUBBED) called mask=0x2000
[  74.541140] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:271: Application has requested initialization of DSP hardware
[  74.541211] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[  74.541901] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[  75.002967] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:637: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  75.078650] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:165: unknown / unimplemented function 'ControlArchive': port='fs:USER' cmd_buf={[0]=0x80d0144 (0x080D, 5, 4), [1]=0x3, [2]=0x0, [3]=0x0, [4]=0x1, [5]=0x1, [6]=0x1a, [7]=0x0, [8]=0x1c, [9]=0x1}
[  78.303730] Render.Vulkan <Info> video_core/renderer_vulkan/vk_resource_pool.cpp:Allocate:128: Allocating new descriptor pool
[ 100.336890] Service.FS <Warning> core/hle/service/fs/file.cpp:OpenLinkFile:214: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]
[ 142.733048] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[ 142.762947] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[ 142.762963] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:78: Non-existing file /Users/erik/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00125600/data/00000001/save1.bin can't be open without mode create.
[ 142.765000] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[ 142.765010] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:78: Non-existing file /Users/erik/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00125600/data/00000001/save2.bin can't be open without mode create.
```

### System Configuration

CPU: M1 10 core CPU
GPU/Driver: 16 core GPU, selected Vulkan driver in Citra prefs.
RAM: 16GB
OS: MacOS 13.4

**Comment by kevincrans** [comment] 2023-06-22 18:44
I confirm re-producing this on M2 13" 2022.

**Comment by kevincrans** [comment] 2023-06-23 14:39
It's also present when enabling Rosetta in the app info

**Comment by themacintoshnerd** [comment] 2023-06-28 04:06
Can also confirm this is happening on my machine as well. I'll attach some logs aswell. 
[citra_log.txt](https://github.com/citra-emu/citra/files/11889648/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/11889649/citra_log.txt.old.txt)

**Comment by kevincrans** [comment] 2023-06-28 07:19
I want to add that I'm running macos 13.4, in case it didn't happen earlier.

**Comment by TheGag96** [comment] 2023-07-05 04:13
I'm actually having this happen to me on Linux x64, commit 4c8a98a32, only when having launched the game through `citra` and not `citra-qt`. Is this perhaps the same issue?

**Comment by WojciechJamroz** [comment] 2023-07-08 00:14
For me this was caused by audio Output Type setting being set to Auto. Changing it to SDL2 helped with this issue.

Not sure what was the root cause, but I suspect that it may be something with the PS4 controller and it being recognized as audio output device (it has buitlin speaker)

**Comment by kevincrans** [comment] 2023-07-08 08:46
> For me this was caused by audio Output Type setting being set to Auto. Changing it to SDL2 helped with this issue.
> 
> Not sure what was the root cause, but I suspect that it may be something with the PS4 controller and it being recognized as audio output device (it has buitlin speaker)

Thanks for sharing, unfortunately it didn't work for me.
Here's a shot of the status bar:
![image](https://github.com/citra-emu/citra/assets/22748357/465df5db-88eb-44fb-895b-812da44d82a9)

**Comment by WojciechJamroz** [comment] 2023-07-08 20:56
Weird, i'm pretty sure that was the only setting i changed during the troubleshooting process, but when i reverted it back to Auto, it didn't reproduce the issue.

I know I experienced this issue, but can't reproduce it right now. I wonder if there is a way to trace back settings change history.

**Comment by JazzyStrat** [comment] 2023-07-31 00:18
I'm experiencing this same issue on build 2530.

**Comment by Steveice10** [comment] 2023-08-08 02:27
Have been told that the latest canary improved stability, can someone retest to verify if this is resolved?

**Comment by themacintoshnerd** [comment] 2023-08-08 04:31
> Have been told that the latest canary improved stability, can someone retest to verify if this is resolved?

It has been on my machine! (M2 Mac mini)

**Comment by parthmishra** [comment] 2023-08-08 18:57
> Have been told that the latest canary improved stability, can someone retest to verify if this is resolved?

Looks good for me so far, can't duplicate this issue anymore.

**Comment by Steveice10** [comment] 2023-08-08 19:48
Going to close this as resolved then, thanks.

**Closed** 2023-08-08 19:48 UTC
