### ISSUE TITLE
Love plus real time mode save issue

### ISSUE THREAD

**Issue by climbx56854** [citra-emu/citra#5475] opened 2020-07-28 16:28 UTC
Issue:
The issue happened in real time mode to do save and go to skip mode ( it will do save before go to skip mode) and stuck in saving status.
But it not happen in first 100 days.
The saving circle is running.
And audio is still playing.
Just like no response.
By the way,the data is successful be saved.
But the issue cause that I can’t do anything in game.
When it do saving ,it will write one log.
unknown / unimplemented function 'ControlArchive'
Maybe it has some relationship.
Hope it useful to debug.

System Information

Operating System: Windows 10 ver.1904
CPU: AMD Ryzen 3700X
GPU: NVIDIA GeForce RTX2070S
Citra Version (found in title bar): Citra Nightly 1598
Game: New Love Plus +
Screenshot of Issue (include the full Citra window including titlebar):
![image](https://user-images.githubusercontent.com/66115142/88693525-f8715100-d131-11ea-8ec2-915a94a33a85.png)

Attached please find the Citra log for your reference
[citra_log.txt](https://github.com/citra-emu/citra/files/4989709/citra_log.txt)

**Comment by zhaowenlan1779** [comment] 2020-07-30 00:38
Duplicate of #3822

**Closed by zhaowenlan1779** 2020-07-30 00:38 UTC
