### ISSUE TITLE
Pokemon Alpha Sapphire - Black Screen 

### ISSUE THREAD

**Issue by Ztaravion** [citra-emu/citra#2085] opened 2016-09-17 13:51 UTC
I am Petalburg Woods and heading out of there, and after I see the Aqua member checking in for the Team Aqua, my screen just turns black and I can't do much..

**Comment by JayFoxRox** [comment] 2016-09-17 13:52
Duplicate of #2026 ?

**Comment by Ztaravion** [comment] 2016-09-17 13:55
This may sound dumb, but what am I suppose to do exactly?

**Comment by MerryMage** [comment] 2016-09-17 13:58
Please read the [FAQ](https://citra-emu.org/wiki/FAQ). Do note this issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.

Note that Citra in hardly feature-complete. Not all 3DS software will be able to run on Citra.

**Comment by MerryMage** [comment] 2016-09-17 13:59
Marked as duplicate of #2026 as per IRC comment.

**Closed by MerryMage** 2016-09-17 13:59 UTC
