### ISSUE TITLE
Assign additional keys as option to a certain button (with image)

### ISSUE THREAD

**Issue by KingLeonidas2020** [citra-emu/citra#5485] opened 2020-08-02 01:40 UTC
Good Morning! I only want to suggest in your great CITRA program about additional keys to be assigned in a certain button. As shown, only a single key can be assigned in a certain button like Num5 only for B Button. Assigning multiple keys is a solution to activate 3 button key combination that wont work in keyboard. Thank you very much!

![Untitled](https://user-images.githubusercontent.com/69095582/89113447-d5350180-d4a3-11ea-8527-7841dd62763c.jpg)

**Comment by FearlessTobi** [comment] 2020-08-06 14:50
Duplicate of https://github.com/citra-emu/citra/issues/4795.

**Closed by FearlessTobi** 2020-08-06 14:50 UTC
