### ISSUE TITLE
Jake Hunter Detective Story: Ghost of the Dusk japanese version unable to save

### ISSUE THREAD

**Issue by ct5743** [citra-emu/citra#3736] opened 2018-05-12 10:55 UTC
![1](https://user-images.githubusercontent.com/39215157/39956568-e6e87060-5615-11e8-8b18-a8f121c25d16.png)
When pressing Yes in saving screen, it freezes.
[citra_log.txt](https://github.com/citra-emu/citra/files/1997524/citra_log.txt)

**Comment by Hexagon12** [comment] 2018-05-12 11:04
> [  12.021714] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:163: unknown / unimplemented function '0x87600c0': port='fs:USER' cmd_buf={[0]=0x87600c0, [1]=0x6, [2]=0x0, [3]=0x1000}

Possible candidate?

**Comment by Drflash55** [comment] 2018-05-26 15:04
Ah, so JHD has the same issue as PRW.

**Comment by Drflash55** [comment] 2018-11-29 03:48
Has there been any progress on trying to figure out the "unimplemented FS function"?

Or is the game itself the reason as to why Citra can't save properly?

**Comment by Dragios** [comment] 2020-03-18 02:53
Please try testing again with the latest nightly. If it does not fix you can try Canary that has PR #5120 and see if this fixes the issue.

**Comment by benderscruffy** [comment] 2023-08-29 12:14
Has this been fixed ??
Please update

**Comment by GPUCode** [comment] 2023-09-12 07:54
Cannot reproduce issue, closing

**Closed by GPUCode** 2023-09-12 07:54 UTC
