### ISSUE TITLE
Unable to open in MacOSX El Capitan Version 10.11.6 Beta (15G19a)

### ISSUE THREAD

**Issue by msbukkuri** [citra-emu/citra#1932] opened 2016-06-26 18:39 UTC
No further details to provide. The app simply does not open or throw an error.

**Comment by kgdiem** [comment] 2016-07-14 18:29
I'm also unable to open the latest nightly on OS X El Capitan 10.11.4 (15E65) but I get "citra-qt cannot be opened because of a problem" 
<img width="427" alt="citra screenshot" src="https://cloud.githubusercontent.com/assets/13109365/16850963/69546f22-49cf-11e6-827c-a31c86a33629.png">

**Comment by DaneErickson** [comment] 2016-07-14 21:08
Same- I delved into the app a little.
Running citra-qt.app/Contents/MacOS/citra-qt yields an error:

QWidget: Cannot create a QWidget without QApplication
Abort trap: 6

**Comment by JayFoxRox** [comment] 2016-07-14 21:24
[We are aware of this issue](https://discuss.citra-emu.org/d/340-error-message-when-trying-to-run-citra-for-os-x) but we have problems finding a *developer* who can reproduce it.
All reports so far were from users who were not able to look into the issue, and no developer has been able to reproduce.

So if you are a developer and could look into it, that'd be great.

**Comment by yuriks** [comment] 2016-09-14 04:29
Fix (#1962) has been merged already. Please re-open if this is still a problem.

**Closed by yuriks** 2016-09-14 04:29 UTC
