### ISSUE TITLE
Fix linux shader (compilation?)

### ISSUE THREAD

**Issue by Cpasjuste** [citra-emu/citra#1183] opened 2015-10-02 11:17 UTC
Hi,

Citra does hang for a few seconds/minutes on linux at start. This render the whole thing unusable for developing. I think it's related to the shader compilation code. Unfortunately i don't think i have the knowledge to resolve this bug ... 

Would be much, much appreciated if someone would take a look :)

Edit: the problem is located in OGLShader.Create, disabling the "ShaderUtil::LoadShaders" function does get homebrew to work normaly (i guess homebrews who doesnt request gpu access).

Edit2: Ubuntu 15.04 - x64

**Comment by lybxlpsv** [comment] 2015-10-10 18:27
you should tell which mesa driver version and graphics card you are using, might also want to upload glxinfo output somewhere.

**Comment by yuriks** [comment] 2015-10-10 22:50
Dupe of #819

**Closed by yuriks** 2015-10-10 22:50 UTC
