### ISSUE TITLE
Animal Crossing: A New Leaf - Buildings Invisible/Unable to Interact With

### ISSUE THREAD

**Issue by Saphiresurf** [citra-emu/citra#2647] opened 2017-03-31 07:20 UTC
The initial issue for this was getting a bit off of the trail and the beginning post didn't quite have a very good gathering of what the issue was to keep things simple, so I'm recreating this here to put in what I've solidly tested out... and hopefully in a format easy for a dev to go through.

Original Issue: https://github.com/citra-emu/citra/issues/1105

Environment
-------------------
Nightly: eb8a7a9
Bleeding Edge: https://github.com/citra-emu/citra-bleeding-edge/commit/82d4930

Shader JIT? Recreatable With and Without

Existing Save? No
QT or SDL? QT (not tested with SDL)

Log From Beginning Until Running Into an Invisible Villager Building (Nightly):
[log.txt](https://github.com/citra-emu/citra/files/886241/log.txt)

Issue
-----------------------
In Animal Crossing: A New Leaf buildings, bridges, shops, town hall, and the town centers tree are invisible and don't allow interaction (such as going inside of a building, sitting on the tree planter, etc.). Collisions do work correctly though as you seem to walk into an invisible wall where these 3D models are supposed to be located. This happens IN-GAME though, the buildings are visible on the title screen, just not once you enter the game.

In the previous issue some people were reporting that buildings _will_ show up sometimes, but the conditions of which they do are unknown. The train station, which is the building you come out of at the very start of the game, will usually appear if you _don't_ have the "00086400" save folder for ACNL, but if you do the train station will disappear and cause a soft-lock at the beginning of the game (no further events happen, but animations (idle in this case) continue). This isn't consistent though as other users have reported this not working. I'm able to recreate this on my hardware consistently, though.

Steps to Recreate 
------------------------
3-4 Minutes From Beginning to Finding a House
3 Touch Screen Prompts (Jam the A Button Otherwise)

1. Remove the "00086300" save folder from Citra
2. Launch Animal Crossing: A New Leaf
2. Start a new save file
3. Go through all of the intro parts until you walk out of the train station
4. Walk around town with Isabelle to find town hall or any villagers houses (you'll usually run into them, there's patches in the dirt that indicate whether a house is there or not as indicated in the screenshots below).

Actual Results:
All villager building, shops, bridges, and the town center tree aren't visible, but you can run into them. You are not able to go inside or interact with any of them either.

Expected Results:
To be able to see the buildings/enter them, for the bridges to be visible, and for the town center tree to be visible/also be able to sit on it's planter.

Screenshots
---------------

**Citra**
Bridge
![bridge](https://cloud.githubusercontent.com/assets/272940/24393115/b2674b62-134b-11e7-898e-d5ef86e65b41.PNG)

Town Hall
![townhall](https://cloud.githubusercontent.com/assets/272940/24393114/b26511da-134b-11e7-833c-46e3959e7384.PNG)

Villager's House
![villager](https://cloud.githubusercontent.com/assets/272940/24393113/b262e2c0-134b-11e7-8d24-3c7a2da52123.PNG)

**Hardware**
Bridge
![top_0004](https://cloud.githubusercontent.com/assets/272940/24538919/daad6a1e-15a0-11e7-8afd-f91b19377673.png)

Town Hall
![hni_0056](https://cloud.githubusercontent.com/assets/272940/24538966/0fc74c1a-15a1-11e7-91b9-f04b2042c7ac.JPG)

Villager's House

![top_0001](https://cloud.githubusercontent.com/assets/272940/24539000/3a77b382-15a1-11e7-82fa-3610ca558ea6.png)

Specs
-----------------------------

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Xeon X3360 @ 2.83GHz
	Yorkfield 45nm Technology
RAM
	5.00GB Dual-Channel DDR2 @ 399MHz (6-6-6-18)
Motherboard
	Dell Inc. 0M017G (CPU 1)	
Graphics
	2047MB NVIDIA GeForce GT 630 (ASUStek Computer Inc)

**Comment by wwylele** [comment] 2017-03-31 10:52
Could you provide an updated log? A log from the original issue ise like a year ago...

**Comment by KillzXGaming** [comment] 2017-03-31 13:53
[log.txt](https://github.com/citra-emu/citra/files/885846/log.txt)

Here is one on the very latest nighty build. From creating a save up to the bus station where it ended up stuck.

**Comment by RavenHome1** [comment] 2017-03-31 15:49
unrelated to issue but doesn't this error mean you are missing the home folder dump?

[  16.635940] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Init:627: Unable to load shared font

**Comment by KillzXGaming** [comment] 2017-03-31 15:58
Oh whoops forgot to add that in since i made a new Citra directory for the nighty. Here is a log with that added in.
[log.txt](https://github.com/citra-emu/citra/files/886240/log.txt)

**Comment by Saphiresurf** [comment] 2017-03-31 16:00
@wwylele Op sorry about that! Just included the log.txt underneath the "Environment" section.

**Comment by Cuyler36** [comment] 2017-04-02 03:10
Here's a debug level log taken on the the latest nightly build. I condensed the log for readability, but there were no other errors or warnings.
[log.txt](https://github.com/citra-emu/citra/files/888158/log.txt)

**Comment by pablothegreat** [comment] 2017-06-02 10:27
Could somebody send me the file, I would like to see how it performs.

**Comment by Zangetsu38** [comment] 2017-06-15 16:51
no works for me :/ last master and last edge build same think, and remove folder save change nothing
![image](https://user-images.githubusercontent.com/5261759/27192409-8656f268-51fb-11e7-8a5c-81a783723d4f.png)

**Comment by Abdulmalik123** [comment] 2017-08-10 01:34
This is the only game I want to play on 3DS :(

**Comment by MelonSpeedruns** [comment] 2017-11-08 18:36
I think the issue was fixed in the latest canary build! Can anyone confirm?

**Comment by TeaCharmer** [comment] 2017-11-08 23:24
Game works, however i have problems with saving. I can interact with everything, i can "save and quit" and then continue without stopping emulation, but when i stop emulation or quit Citra save file is corrupted or "it was not the last data saved"
![citerr](https://user-images.githubusercontent.com/33501297/32580181-59da54bc-c4e4-11e7-88fc-83e5179757a0.png)
![acerr](https://user-images.githubusercontent.com/33501297/32580183-5a111416-c4e4-11e7-8654-fedcd173076b.png)

**Comment by tootyta** [comment] 2017-11-09 00:50
How do I run Animal Crossing on the latest canary build? Whenever I use my 3ds file or cci file it always crashes.

**Comment by OscarOG** [comment] 2017-11-09 00:51
**Save and Continue** seems to work but **Save and Exit** may be not working all the times.
Temporary solution: First _save and continue_ then _save and exit_...

**Comment by tootyta** [comment] 2017-11-09 13:49
Yeah, I get the same saving issue as well @TeaCharmer , whenever the game saves and I close Citra and re-open it up, the save data will be corrupted.

**Comment by TeaCharmer** [comment] 2017-11-09 15:01
Okay, this works: https://www.reddit.com/r/AnimalCrossing/comments/3j8tbw/fixed_cannot_use_save_data_because_it_was_not_the/
But you have to do it every time you open Citra so it's only temporary solution and it's quite tiresome.

**Comment by tootyta** [comment] 2017-11-09 22:21
Woah, that is tiresome. I really hope the issue is fixed soon.

**Comment by Jamdoge** [comment] 2017-11-16 09:32
Yep, as of the latest Canary build, you still have to manually mess with the hexes. Is it possible to generate the hexes for the 'latest update' manually, without having to create a new save file everytime? I imagine that'd be the most efficient way. Right now, it's more efficient to just pause the emulator and leave it running.

**Comment by plfxplfx** [comment] 2017-11-16 17:37
The welcome amiibo version of new leaf does not have any save problems and works nicely for me.

**Comment by TeaCharmer** [comment] 2017-11-16 19:28
Is Welcome Aiimbo save compatible with earlier versions?

**Comment by TeaCharmer** [comment] 2017-11-16 20:40
Yes it is and indeed does not have any save problems, thanks @plfxplfx c:

**Comment by Jamdoge** [comment] 2017-11-19 10:25
Ah godamnit. Thought I finally got it working, and now I can't load the game - same thing as the 'invisible train station' bug, my player appears blacked out inside where his tent should be, unable to move. Trying to start another save on the same town just leads to the train station bug. Has the same 'memory' loop error. Will update if I find a fix/it magically starts working. Tried both Canary and Nightly so far.

**Comment by wwylele** [comment] 2017-11-19 10:44
@Jamdoge We temporarily pull the fix from canary build for scheduling tests for other fix first. We will add it back when everything settles down.

**Comment by Jamdoge** [comment] 2017-11-19 10:56
@wwylele Ah, cheers.

**Comment by elenuccia12** [comment] 2017-11-23 12:04
how do I continue?
![animal](https://user-images.githubusercontent.com/32220511/33172017-c4c67f60-d04e-11e7-873c-50323c5fa337.png)

**Comment by NukeyDuke** [comment] 2017-11-23 17:04
@wwylele Do we have an idea of when the fix might be making it back into Canary Build? I'm quiet curious.

**Comment by wwylele** [comment] 2017-11-23 17:05
@NukeyDuke When we get #3119 into master first. I think it will be soon

**Comment by NukeyDuke** [comment] 2017-11-23 17:07
@wwylele Ah, sweet. Thanks for letting me know!

**Comment by elenuccia12** [comment] 2017-11-23 17:22
please help me ... how do I play?

**Comment by BreadFish64** [comment] 2017-11-23 19:15
@elenuccia12 this is an issue tracker for developers, for support please pray on the [community forums](https://community.citra-emu.org)

**Comment by B3n30** [comment] 2017-12-10 19:00
Closed by #3091

**Closed by B3n30** 2017-12-10 19:00 UTC
