### ISSUE TITLE
Enhancement: Split lower/upper screen into separate windows

### ISSUE THREAD

**Issue by Icekhaos** [citra-emu/citra#2270] opened 2016-12-05 23:48 UTC
Would make some games a ton more bearable on both single and multimonitor configurations, for example, a HD upper screen on the main display, then the touchscreen off to the side.

**Comment by linkmauve** [comment] 2016-12-06 00:28
Duplicate of #204.

**Closed by linkmauve** 2016-12-06 00:28 UTC
Labels: A-frontend, enhancement

**Comment by Icekhaos** [comment] 2016-12-06 02:13
Whoops.
