### ISSUE TITLE
Broken screen scretching on macOS

### ISSUE THREAD

**Issue by roberthharvey** [citra-emu/citra#2415] opened 2017-01-08 06:46 UTC
issue 2 https://github.com/citra-emu/citra/issues/2416

so as it says, the screen stretching is wonky and the VRAM kills the app (crashes or asks me to close it). 

I have included dumps and screen captures. 

if you need any more info just let me know and I will provide specifics :)

game: PKM Moon, build (tried last 4, same issue)

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,4
  Processor Name:	Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP114.0172.B10
  SMC Version (system):	2.29f24

<img width="1011" alt="screen shot 2017-01-08 at 2 21 00 pm" src="https://cloud.githubusercontent.com/assets/12015507/21747890/cb5f3f0e-d5b0-11e6-8178-707e82badb8e.png">

<img width="1034" alt="screen shot 2017-01-08 at 2 20 53 pm" src="https://cloud.githubusercontent.com/assets/12015507/21747897/f64d9d46-d5b0-11e6-9f10-58434ea586e0.png">

[Terminal Dump.TXT](https://github.com/citra-emu/citra/files/691914/Terminal.Dump.TXT)
[Dump after program quit.TXT](https://github.com/citra-emu/citra/files/691915/Dump.after.program.quit.TXT)

[Screen Recording 2017-01-08 at 2.16.49 PM.mp4.zip](https://github.com/citra-emu/citra/files/691916/Screen.Recording.2017-01-08.at.2.16.49.PM.mp4.zip)

**Comment by roberthharvey** [comment] 2017-01-08 06:47
oh also: 

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,4
  Processor Name:	Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP114.0172.B10
  SMC Version (system):	2.29f24
  Serial Number (system):	C02R515WG8WN
  Hardware UUID:	D47C5CFF-61C8-58EB-99FE-F69190B7195C

**Comment by wwylele** [comment] 2017-01-08 07:05
Please Separate the two bugs into two issues

**Comment by archshift** [comment] 2017-01-08 09:39
This is a dupe of #2092

**Closed by archshift** 2017-01-08 09:39 UTC
