### ISSUE TITLE
Build failure - (nightly) source release doesn't contain submodules and isn't a git repository

### ISSUE THREAD

**Issue by Deuxis** [citra-emu/citra#4352] opened 2018-10-20 15:29 UTC
Like in the title, the .tar.gz release doesn't contain the submodules like the bundled boost, leading to "Git submodule externals/boost not found.Please run: git submodule update --init --recursive" errors, but because it also isn't a git repo (no .git directory), the suggested command fails, rendering the source release unbuildable. Unless I'm really not understanding something.

I need that because I'm creating a Portage ebuild for Citra, which is best based on downloading a release source from github archives and building it.

PS: the tar.gz also contains a "citra-nightly-nightly-version" directory, forcing me to additionally rename it on unpacking or tweak other parts of the build process.

**Comment by wwylele** [comment] 2018-10-20 15:31
Where did you get the .tar.gz package?

**Comment by Deuxis** [comment] 2018-10-20 15:39
https://github.com/citra-emu/citra-nightly/releases
the precise address for the latest (as of the time of writing this) release:
https://github.com/citra-emu/citra-nightly/archive/nightly-1063.tar.gz

**Comment by wwylele** [comment] 2018-10-20 15:39
If you are using the github release page to grab the source code package, it won't include the submodule. That package is generated by github automatically and the issue is also theirs. Every projects hosted on github share the same issue. We can't resolve it.

**Comment by Deuxis** [comment] 2018-10-20 15:41
That doesn't seem right, half of Gentoo's ebuilds are based on exactly those packages. There must be a way to either include the original repo data or the content of submodules in them. Will check how the others are done.

**Comment by wwylele** [comment] 2018-10-20 16:53
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-emulation/qemu/qemu-2.12.0-r3.ebuild#n17

Maybe you can directly fetch git repo like this. We are the other half haha

**Comment by Deuxis** [comment] 2018-10-20 17:05
Yeah, it seems there is no easy solution, automatic github releases just don't play well with submodules. The example you linked directly pulls the whole repo with git, which is possible but discouraged, or downloads a complete source package, which includes the subs.

You could build such a package along with the binaries, though. If there are no licensing problems with redistributing submodule contents, of course. As far as I understand all it takes is modifying the build process to copy the building directory after pulling the subs and before creating "build" and running cmake. (and then compress it)

**Comment by wwylele** [comment] 2018-10-21 15:07
I don't know how Gentoo community view this, but as far as I can tell I don't see how pulling a git repo is discouraged, as it is an integrated tool into the Portage thing.

Releasing source package is possible for sure and there is no licensing problem. IMO it is a matter of wasting resource, as our nightly builds can by updated even faster than, well, "nightly", and the git repo itself already serves the purpose of providing the source code of such frequent update. Duplicating the source code in another channel seems unnecessary. This problem can also attribute to that we currently don't have stable/versioned/milestone/long-term releases that deserve source code archiving in a separate channel.

This is just my thought. Other devs might have different opinion. If most of people agree on this, we can setup CI for packaging source code with submodules.

**Comment by vitor-k** [comment] 2022-10-24 01:04
@Deuxis is this fixed now, with the unified source from #6146?

**Comment by SleepingSnakezzz** [comment] 2023-04-27 22:55
This should be fixed by the above mentioned PR. Since the OP doesn't appear to be active on Github anymore to confirm, I'll be closing the issue for now.

**Closed by SleepingSnakezzz** 2023-04-27 22:55 UTC
