### ISSUE TITLE
The emulator simply restarts my phone.

### ISSUE THREAD

**Issue by Cybergbx** [citra-emu/citra#7357] opened 2024-01-15 08:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2748

### Description of Issue

The emulator is making my phone restart, especially in Monsters Hunter and Smash Bros games, in Smash Bros it was worse because the screen changed color slightly and restarted 

### Expected Behavior

...

### Reproduction Steps

...

### Log File

...

### System Configuration

CPU: snapdragon 680
GPU/Driver: 610
RAM: 4 gb ram
OS: android 13

**Comment by FearlessTobi** [comment] 2024-01-15 14:26
The issue template has not been filled out correctly.
I also can't reproduce this on my device.

Closing because of insufficient information.

**Closed by FearlessTobi** 2024-01-15 14:26 UTC
