### ISSUE TITLE
Luigi's Mansion Dark Moon Suction effect problem

### ISSUE THREAD

**Issue by OzzieTheCat** [citra-emu/citra#5096] opened 2020-02-19 02:43 UTC
This is not a good thing to be a glitch seeing as its a thing your ment to see every time you suck up a ghost

Citra:
![Citra lmdm suction eff](https://user-images.githubusercontent.com/61217162/74796699-5ce0d800-5297-11ea-9b34-174bae3ce121.gif)

3ds:
![lmdm 3ds suction eff](https://user-images.githubusercontent.com/61217162/74796717-679b6d00-5297-11ea-866a-db16f000c56e.gif)

this is a graphical error that really needs to be fixed
i have tried enabling Accurate multiplication and nothing changed i hope this can be fixed

[citra_log.txt](https://github.com/citra-emu/citra/files/4222862/citra_log.txt)

**Comment by BreadFish64** [comment] 2020-02-19 02:47
duplicate of #5058

**Closed** 2020-02-19 02:58 UTC
