### ISSUE TITLE
River City Tokyo Rumble Graphical Issues

### ISSUE THREAD

**Issue by blackman91** [citra-emu/citra#4626] opened 2019-02-05 05:02 UTC
The character sprites are cut in half, using latest nightly f620c86 on windows 10. No graphic setting fixes it.
![riverbug](https://user-images.githubusercontent.com/6578180/52254066-24ab6900-28d1-11e9-9877-0acf258593fc.png)

**Comment by FearlessTobi** [comment] 2019-02-05 20:39
This issue is missing a log file + your system information.

**Comment by blackman91** [comment] 2019-02-05 21:46
System info:
cpu: Intel core i7-87S0H 
Gpu: Nvidia gtx 1050

Log:
[citra_log.txt](https://github.com/citra-emu/citra/files/2834015/citra_log.txt)

**Comment by benderscruffy** [comment] 2019-02-06 12:48
duplicate 0f #3400 and #3801

**Comment by zhaowenlan1779** [comment] 2019-02-07 03:50
Are these issues about the same game? If not, I don't think we can call them duplicates, before the causes of these issues are identified.

**Comment by benderscruffy** [comment] 2019-02-07 13:00
yes of course they are the same game

**Comment by benderscruffy** [comment] 2019-02-12 09:55
@zhaowenlan1779  same game just american and japanese names
google is your friend

**Comment by Draic0** [comment] 2019-02-15 15:26
Nekketsu Kouha Kunio-Kun SP: Rantou Kyousoukyoku and Riki Densetsu are actually different games. They are actually not the only ones plagued by this bug. 2 more games: Nekketsu Kouha Kunio-Kun Special (without Rantou Kyousoukyoku) and River City: Rival Showdown.

**Comment by benderscruffy** [comment] 2019-02-16 00:55
yes but River City - Tokyo Rumble and Nekketsu Kouha Kunio-Kun SP - Rantou Kyousoukyoku are the same game so this is a duplicate of #3400

**Comment by Draic0** [comment] 2019-02-16 06:21
Nekketsu Kouha Kunio-Kun SP - Rantou Kyousoukyoku AND Nekketsu Kouha Kunio-Kun SP are different games. The first was released in 2013 (Japan) and the second - in 2011 (Japan as well). I mean, they are entirely different. Check it yourself. Or google. Or whatever. :)

**Comment by benderscruffy** [comment] 2019-02-16 09:52
i know the first 2 jap games are different 
http://www.advanscene.com/html/Releases/db3dsrel.php?id=0756
geez look what its region is called 
http://www.advanscene.com/html/Releases/db3dsrel.php?id=2186
so i did check i

**Comment by Draic0** [comment] 2019-02-16 11:12
Did you check this one?
[](http://www.advanscene.com/html/Releases/db3dsrel.php?id=745)
It is different from the game you posted:
[](http://www.advanscene.com/html/Releases/db3dsrel.php?id=0756)
So, basically, if we compare the issues, they concern 3 different games:
1. [#3801](https://github.com/citra-emu/citra/issues/3801#issue-328362315) - Riki Densetsu (z017 or z116 eShop)
2. [#3400](https://github.com/citra-emu/citra/issues/3400#issue-289903828) - Nekketsu Kouha Kunio-Kun Special (3DS0720)
3. [#4626](https://github.com/citra-emu/citra/issues/4626#issue-406631258) - Nekketsu Kouha Kunio-Kun SP - Rantou Kyousoukyoku (River City: Tokyo Rumble) (3DS0731)

**Comment by FearlessTobi** [comment] 2019-02-17 11:49
This issue is actually a regression. The bug doesn't appear on Nightly-2. Investigating...

**Comment by LOuroboros** [comment] 2019-12-06 19:10
This is still happening in the latest Canary build _(c4cb8b2)_.
![citra-qt-2019-12-06_16-07-34](https://user-images.githubusercontent.com/4485172/70349104-dc3b3f80-1842-11ea-9679-05fa82fc85d5.png)
_Don't mind the framerate. I usually play games at 105% speed._

**Comment by KoolAidtheRED** [comment] 2020-06-19 01:27
Is there still no fix or workaround for this?  I have tried everything I can find that is suggested with no success.

**Comment by wwylele** [comment] 2020-06-19 03:17
It seems that some old discussion on Discord didn't get logged here. So to summarize the current situation: I have two theories of how this happens:
 - these broken sprites are rendered right on the clipping plane z = 0 (unconfirmed), which results in non-deterministic result of whether the object passes the clipping. 
 - There is some unknown PICA register that can change the clipping plane / clipping behavior.

**Comment by LOuroboros** [comment] 2021-04-09 00:25
This is still happening in Canary 1956.
![Untitled4464](https://user-images.githubusercontent.com/4485172/114111633-e5ae3f00-98b0-11eb-94e8-d63e237ce474.png)

**Comment by fakk3** [comment] 2021-07-18 12:47
Unfortunately, the problem still exists in the latest version of the emulator.

**Comment by LOuroboros** [comment] 2022-01-06 06:48
Still happening in Canary 2013.

![citra-qt_3200](https://user-images.githubusercontent.com/4485172/148340954-e9899b94-06ed-42a9-8c2f-cd6b320c40e7.png)

**Comment by fakk3** [comment] 2022-01-06 15:17
Still wait for fix xD We have 2022!

**Comment by LOuroboros** [comment] 2022-05-05 08:12
Still happening in Canary 2132.

![citra-qt_20220505_0507986](https://user-images.githubusercontent.com/4485172/166884956-6f50b3b6-e238-4b9f-9c96-95334c41a691.png)

I figured it wouldn't make a difference but I also tested the latest Nightly. The issue is also happening there alright.

![citra-qt_20220505_0509728](https://user-images.githubusercontent.com/4485172/166885150-65e46238-bc33-45d7-98a4-93edde2219ef.png)

**Comment by masktao** [comment] 2022-08-24 06:55
yes,same problem for me
![image](https://user-images.githubusercontent.com/13614353/186350738-f360009a-0cc2-41a9-a9ee-292938004745.png)

my citra version night 1781 2022.8.24
river city:rival showdown japan&usa both bad
but
![image](https://user-images.githubusercontent.com/13614353/186351085-517a98b8-6265-419a-8c85-639877d03d9a.png)

nekketsu monogatari special work fine

**Comment by Anths2016** [comment] 2023-05-18 19:01
Any news?

**Comment by LOuroboros** [comment] 2023-05-18 19:51
> Any news?

Still happening on Canary 2491, both with OGL and Vulkan.

![citra-qt_20230518_165058184](https://github.com/citra-emu/citra/assets/4485172/1297c558-025e-41fe-90c9-2d4f6565cc3b)

![citra-qt_20230518_165133629](https://github.com/citra-emu/citra/assets/4485172/0bcce946-26cb-4992-bcda-eb272254e470)

**Comment by rmcin329** [comment] 2023-07-07 15:34
Is this still an issue?

**Comment by LOuroboros** [comment] 2023-07-07 18:47
> Is this still an issue?

Yup.

![citra-qt_20230707_154632890](https://github.com/citra-emu/citra/assets/4485172/5330632f-20bb-4cd8-ba46-9da7ff8741cd)

**Closed** 2023-09-10 21:29 UTC
Labels: A-graphics

**Comment by LOuroboros** [comment] 2023-09-11 03:17
Post closure confirmation that the issue was effectively solved 🥳 !

It's so freaking awesome to see long standing issues like this one or SMT IV's getting fixed 🥳 !

![citra-qt_20230911_001602930](https://github.com/citra-emu/citra/assets/4485172/5ce580f4-e94d-418d-b9f8-55621edb8874)
