### ISSUE TITLE
unmapped Read32

### ISSUE THREAD

**Issue by lefta** [citra-emu/citra#1895] opened 2016-06-10 14:36 UTC
I just updated Citra and was surprised to see no game working.

### Symptoms

The game view widget seems to be not repainted and closing Citra freezes the whole application.

### The log : 

    $ src/citra_qt/citra-qt
    using qt5ct plugin
    [   0.000000] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:207: path exists /home/cedric/.config/citra-emu/qt-config.ini
    [   0.000405] Audio <Error> audio_core/audio_core.cpp:SelectSink:66: AudioCore::SelectSink given invalid sink_id
    QWidget::paintEngine: Should no longer be called
    QPainter::begin: Paint device returned engine == 0, type: 1
    [   4.589359] Frontend <Info> citra_qt/main.cpp:BootGame:317: Citra starting...
    [   4.606761] Service.FS <Info> core/file_sys/archive_sdmc.cpp:ArchiveFactory_SDMC:21:  Directory /home/cedric/.local/share/citra-emu/sdmc/ set as SDMC.
    [   4.606799] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:207: path exists /home/cedric/.local/share/citra-emu/sdmc/
    [   4.606817] Service.FS <Info> core/file_sys/archive_savedata.cpp:ArchiveFactory_SaveData:42: Directory /home/cedric/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
    [   4.606838] Service.FS <Info> core/file_sys/archive_extsavedata.cpp:ArchiveFactory_ExtSaveData:62: Directory /home/cedric/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
    [   4.606851] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:207: path exists /home/cedric/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
    [   4.606863] Service.FS <Info> core/file_sys/archive_extsavedata.cpp:ArchiveFactory_ExtSaveData:62: Directory /home/cedric/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
    [   4.606875] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:207: path exists /home/cedric/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/
    [   4.607061] Service.APT <Warning> core/hle/service/apt/apt.cpp:Init:488: Unable to load shared font: /home/cedric/.local/share/citra-emu/sysdata/shared_font.bin
    [   4.607581] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:481: GL_VERSION: 3.3 (Core Profile) Mesa 11.2.2
    [   4.607594] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:482: GL_VENDOR: Intel Open Source Technology Center
    [   4.607602] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:483: GL_RENDERER: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
    [   4.615083] Loader <Info> core/loader/loader.cpp:GetLoader:143: Loading file /home/cedric/Téléchargements/Collection of 250 decrypted 3DS ROMs for Citra Emulator/0004 - Legend of Zelda, The - Ocarina of Time 3D (Europe) (En,Fr,De,Es,It) Decrypted.3ds as NCSD...
    [   4.615105] Loader <Warning> core/loader/ncch.cpp:LoadExeFS:242: Only loading the first (bootable) NCCH within the NCSD file!
    [   4.615114] Loader <Info> core/loader/ncch.cpp:LoadExeFS:266: Name:                        CtrApp
    [   4.615120] Loader <Info> core/loader/ncch.cpp:LoadExeFS:267: Program ID:                  0004000000033600
    [   4.744811] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x10000000
    [   4.744841] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x10000004
    [   4.744853] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x10000008
    [   4.744866] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x1000000C
    [   4.744878] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x00000000

The last message keeps repeating with the adress increasing before wrapping at 0xFFC, beggining 4 units further everytime (0xFFC => 0x140 ... 0xFFC => 0x144 ... etc)

### Investigation

A bisect turns out that the cuprit is c7ffd8a920cb2504c7cb9ec7f06e1a95cba73953

### Platform & build

Linux x86_64, configured with `cmake -GNinja -DENABLE_SDL2=no ../citra`

**Comment by legoj15** [comment] 2016-06-10 16:45
I can confirm that this happens with every game (that I own) on Windows, too. Started right after #1893 was merged. Built mine with VS2015.

**Comment by jroweboy** [comment] 2016-06-10 22:25
Oh! I was having the same issue, but I thought it was because I was compiling with Mingw64 on windows. I didn't realize that it was related to that PR though. When I was investigating it last night, I noticed that https://github.com/citra-emu/citra/blob/master/src/core/memory.cpp#L170 was returning NULL from the page table, but I didn't have time to look much more into it. If no one else picks this up, I can work on it tonight.

**Closed** 2016-06-11 00:45 UTC

**Comment by popa13** [comment] 2022-11-27 07:12
Hi, I still get the same issue.
My log is copied below:
[   0.000059] Config <Info> core/settings.cpp:LogSettings:80: Citra Configuration:
[   0.000088] Config <Info> core/settings.cpp:operator():77: Core_UseCpuJit: true
[   0.000091] Config <Info> core/settings.cpp:operator():77: Core_CPUClockPercentage: 100
[   0.000091] Config <Info> core/settings.cpp:operator():77: Renderer_UseGLES: false
[   0.000092] Config <Info> core/settings.cpp:operator():77: Renderer_UseHwRenderer: true
[   0.000092] Config <Info> core/settings.cpp:operator():77: Renderer_UseHwShader: true
[   0.000093] Config <Info> core/settings.cpp:operator():77: Renderer_SeparableShader: false
[   0.000093] Config <Info> core/settings.cpp:operator():77: Renderer_ShadersAccurateMul: true
[   0.000094] Config <Info> core/settings.cpp:operator():77: Renderer_UseShaderJit: true
[   0.000095] Config <Info> core/settings.cpp:operator():77: Renderer_UseResolutionFactor: 1
[   0.000096] Config <Info> core/settings.cpp:operator():77: Renderer_FrameLimit: 100
[   0.000096] Config <Info> core/settings.cpp:operator():77: Renderer_UseFrameLimitAlternate: false
[   0.000097] Config <Info> core/settings.cpp:operator():77: Renderer_FrameLimitAlternate: 180
[   0.000097] Config <Info> core/settings.cpp:operator():77: Renderer_VSyncNew: true
[   0.000098] Config <Info> core/settings.cpp:operator():77: Renderer_PostProcessingShader: none (builtin)
[   0.000099] Config <Info> core/settings.cpp:operator():77: Renderer_FilterMode: true
[   0.000099] Config <Info> core/settings.cpp:operator():77: Renderer_TextureFilterName: Anime4K Ultrafast
[   0.000105] Config <Info> core/settings.cpp:operator():77: Stereoscopy_Render3d: 0
[   0.000106] Config <Info> core/settings.cpp:operator():77: Stereoscopy_Factor3d: 0
[   0.000106] Config <Info> core/settings.cpp:operator():77: Stereoscopy_MonoRenderLeftEye: false
[   0.000107] Config <Info> core/settings.cpp:operator():77: Layout_LayoutOption: 0
[   0.000108] Config <Info> core/settings.cpp:operator():77: Layout_SwapScreen: false
[   0.000109] Config <Info> core/settings.cpp:operator():77: Layout_UprightScreen: false
[   0.000110] Config <Info> core/settings.cpp:operator():77: Utility_DumpTextures: false
[   0.000110] Config <Info> core/settings.cpp:operator():77: Utility_CustomTextures: false
[   0.000111] Config <Info> core/settings.cpp:operator():77: Utility_UseDiskShaderCache: true
[   0.000111] Config <Info> core/settings.cpp:operator():77: Audio_EnableDspLle: false
[   0.000112] Config <Info> core/settings.cpp:operator():77: Audio_EnableDspLleMultithread: false
[   0.000113] Config <Info> core/settings.cpp:operator():77: Audio_OutputEngine: auto
[   0.000113] Config <Info> core/settings.cpp:operator():77: Audio_EnableAudioStretching: false
[   0.000114] Config <Info> core/settings.cpp:operator():77: Audio_OutputDevice: auto
[   0.000115] Config <Info> core/settings.cpp:operator():77: Audio_InputDeviceType: 0
[   0.000115] Config <Info> core/settings.cpp:operator():77: Audio_InputDevice: Default
[   0.000116] Config <Info> core/settings.cpp:operator():77: Camera_OuterRightName: blank
[   0.000117] Config <Info> core/settings.cpp:operator():77: Camera_OuterRightConfig: 
[   0.000117] Config <Info> core/settings.cpp:operator():77: Camera_OuterRightFlip: 0
[   0.000118] Config <Info> core/settings.cpp:operator():77: Camera_InnerName: blank
[   0.000119] Config <Info> core/settings.cpp:operator():77: Camera_InnerConfig: 
[   0.000120] Config <Info> core/settings.cpp:operator():77: Camera_InnerFlip: 0
[   0.000120] Config <Info> core/settings.cpp:operator():77: Camera_OuterLeftName: blank
[   0.000121] Config <Info> core/settings.cpp:operator():77: Camera_OuterLeftConfig: 
[   0.000122] Config <Info> core/settings.cpp:operator():77: Camera_OuterLeftFlip: 0
[   0.000123] Config <Info> core/settings.cpp:operator():77: DataStorage_UseVirtualSd: true
[   0.000123] Config <Info> core/settings.cpp:operator():77: DataStorage_UseCustomStorage: false
[   0.000124] Config <Info> core/settings.cpp:operator():77: System_IsNew3ds: true
[   0.000125] Config <Info> core/settings.cpp:operator():77: System_RegionValue: -1
[   0.000126] Config <Info> core/settings.cpp:operator():77: Debugging_UseGdbstub: false
[   0.000127] Config <Info> core/settings.cpp:operator():77: Debugging_GdbstubPort: 24689
[   0.030477] Input <Error> input_common/gcadapter/gc_adapter.cpp:Adapter:31: libusb could not be initialized. failed with error = -1
[   0.109539] Input <Info> input_common/sdl/sdl_impl.cpp:InitGameController:508: opened joystick 0 as controller
[   0.109588] Input <Info> input_common/udp/client.cpp:StartCommunication:207: Starting communication with UDP input server on 127.0.0.1:26760
[   0.278685] Frontend <Info> citra_qt/main.cpp:GMainWindow:197: Citra Version: Canary 2306  | -128-NOTFOUND--128-NOTFOUND
[   0.278696] Frontend <Info> citra_qt/main.cpp:GMainWindow:213: Host CPU: Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz | AVX2 | FMA
[   0.278723] Frontend <Info> citra_qt/main.cpp:GMainWindow:215: Host OS: Ubuntu Core 20
[   0.328631] Frontend <Warning> citra_qt/main.cpp:CheckForUpdates:841: Unable to start check for updates
[   0.368357] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[   0.368365] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:261: Secure2 KeyX missing
[   0.368369] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   0.371657] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[   0.371666] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:261: Secure2 KeyX missing
[   0.371670] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   0.377154] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[   0.377160] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:252: Secure1 KeyX missing
[   0.377162] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   0.377566] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[   0.377569] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:252: Secure1 KeyX missing
[   0.377570] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   0.378743] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[   0.378746] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:252: Secure1 KeyX missing
[   0.378747] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[  49.477461] Config <Info> core/settings.cpp:LogSettings:80: Citra Configuration:
[  49.477477] Config <Info> core/settings.cpp:operator():77: Core_UseCpuJit: true
[  49.477481] Config <Info> core/settings.cpp:operator():77: Core_CPUClockPercentage: 100
[  49.477484] Config <Info> core/settings.cpp:operator():77: Renderer_UseGLES: false
[  49.477486] Config <Info> core/settings.cpp:operator():77: Renderer_UseHwRenderer: true
[  49.477489] Config <Info> core/settings.cpp:operator():77: Renderer_UseHwShader: true
[  49.477492] Config <Info> core/settings.cpp:operator():77: Renderer_SeparableShader: false
[  49.477495] Config <Info> core/settings.cpp:operator():77: Renderer_ShadersAccurateMul: true
[  49.477498] Config <Info> core/settings.cpp:operator():77: Renderer_UseShaderJit: true
[  49.477501] Config <Info> core/settings.cpp:operator():77: Renderer_UseResolutionFactor: 1
[  49.477505] Config <Info> core/settings.cpp:operator():77: Renderer_FrameLimit: 100
[  49.477507] Config <Info> core/settings.cpp:operator():77: Renderer_UseFrameLimitAlternate: false
[  49.477511] Config <Info> core/settings.cpp:operator():77: Renderer_FrameLimitAlternate: 180
[  49.477514] Config <Info> core/settings.cpp:operator():77: Renderer_VSyncNew: true
[  49.477517] Config <Info> core/settings.cpp:operator():77: Renderer_PostProcessingShader: none (builtin)
[  49.477520] Config <Info> core/settings.cpp:operator():77: Renderer_FilterMode: true
[  49.477523] Config <Info> core/settings.cpp:operator():77: Renderer_TextureFilterName: Anime4K Ultrafast
[  49.477544] Config <Info> core/settings.cpp:operator():77: Stereoscopy_Render3d: 0
[  49.477547] Config <Info> core/settings.cpp:operator():77: Stereoscopy_Factor3d: 0
[  49.477549] Config <Info> core/settings.cpp:operator():77: Stereoscopy_MonoRenderLeftEye: false
[  49.477553] Config <Info> core/settings.cpp:operator():77: Layout_LayoutOption: 0
[  49.477555] Config <Info> core/settings.cpp:operator():77: Layout_SwapScreen: false
[  49.477557] Config <Info> core/settings.cpp:operator():77: Layout_UprightScreen: false
[  49.477559] Config <Info> core/settings.cpp:operator():77: Utility_DumpTextures: false
[  49.477561] Config <Info> core/settings.cpp:operator():77: Utility_CustomTextures: false
[  49.477563] Config <Info> core/settings.cpp:operator():77: Utility_UseDiskShaderCache: true
[  49.477564] Config <Info> core/settings.cpp:operator():77: Audio_EnableDspLle: false
[  49.477566] Config <Info> core/settings.cpp:operator():77: Audio_EnableDspLleMultithread: false
[  49.477568] Config <Info> core/settings.cpp:operator():77: Audio_OutputEngine: auto
[  49.477570] Config <Info> core/settings.cpp:operator():77: Audio_EnableAudioStretching: false
[  49.477573] Config <Info> core/settings.cpp:operator():77: Audio_OutputDevice: auto
[  49.477576] Config <Info> core/settings.cpp:operator():77: Audio_InputDeviceType: 0
[  49.477578] Config <Info> core/settings.cpp:operator():77: Audio_InputDevice: Default
[  49.477581] Config <Info> core/settings.cpp:operator():77: Camera_OuterRightName: blank
[  49.477583] Config <Info> core/settings.cpp:operator():77: Camera_OuterRightConfig: 
[  49.477586] Config <Info> core/settings.cpp:operator():77: Camera_OuterRightFlip: 0
[  49.477589] Config <Info> core/settings.cpp:operator():77: Camera_InnerName: blank
[  49.477592] Config <Info> core/settings.cpp:operator():77: Camera_InnerConfig: 
[  49.477595] Config <Info> core/settings.cpp:operator():77: Camera_InnerFlip: 0
[  49.477596] Config <Info> core/settings.cpp:operator():77: Camera_OuterLeftName: blank
[  49.477598] Config <Info> core/settings.cpp:operator():77: Camera_OuterLeftConfig: 
[  49.477599] Config <Info> core/settings.cpp:operator():77: Camera_OuterLeftFlip: 0
[  49.477602] Config <Info> core/settings.cpp:operator():77: DataStorage_UseVirtualSd: true
[  49.477603] Config <Info> core/settings.cpp:operator():77: DataStorage_UseCustomStorage: false
[  49.477605] Config <Info> core/settings.cpp:operator():77: System_IsNew3ds: true
[  49.477606] Config <Info> core/settings.cpp:operator():77: System_RegionValue: 1
[  49.477608] Config <Info> core/settings.cpp:operator():77: Debugging_UseGdbstub: false
[  49.477610] Config <Info> core/settings.cpp:operator():77: Debugging_GdbstubPort: 24689
[  49.477885] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:744: Change detected in the games directory. Reloading game list.
[  49.479215] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[  49.479226] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:261: Secure2 KeyX missing
[  49.479231] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[  49.483577] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[  49.483587] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:261: Secure2 KeyX missing
[  49.483593] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[  49.490070] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[  49.490079] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:252: Secure1 KeyX missing
[  49.490084] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[  49.490875] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[  49.490889] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:252: Secure1 KeyX missing
[  49.490893] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[  49.493990] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[  49.494005] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:252: Secure1 KeyX missing
[  49.494010] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[  54.080572] Frontend <Info> citra_qt/main.cpp:BootGame:1031: Citra starting...
[  54.101240] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[  54.101249] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:252: Secure1 KeyX missing
[  54.101253] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[  54.510934] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:137: Cubeb Audio Stream Started
[  54.510971] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:12: Starting RPC server ...
[  54.511222] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:113: Request handler started.
[  54.511273] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:16: RPC started.
[  54.512435] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:806: ClCertA file missing
[  54.519451] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1254: GL_VERSION: 4.6 (Core Profile) Mesa 21.0.3
[  54.519462] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1255: GL_VENDOR: Intel
[  54.519465] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1256: GL_RENDERER: Mesa Intel(R) UHD Graphics (CML GT2)
[  54.529005] Render.OpenGL <Info> video_core/renderer_opengl/gl_format_reinterpreter.cpp:ShaderD24S8toRGBA8:167: Texture views are unsupported, reinterpretation will do intermediate copy
[  54.529017] Render.OpenGL <Info> video_core/renderer_opengl/gl_format_reinterpreter.cpp:FormatReinterpreterOpenGL:255: Using shader for D24S8 to RGBA8 reinterpretation
[  54.532940] Render.OpenGL <Critical> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:1231: API ERROR 1: GL_INVALID_VALUE in glGetUniformLocation
[  54.532951] Render.OpenGL <Critical> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:1231: API ERROR 1: GL_INVALID_OPERATION in glUniform(program not linked)
[  54.548370] Loader <Info> core/loader/ncch.cpp:Load:192: Program ID: 00040000000EC300
[  54.548396] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:130: Failed to open /home/pierre/snap/citra-emu/common/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/000ec300/content/00000000.app
[  54.588411] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:141: ExHeader kernel version: 2.35
[  54.589829] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCodes:656: Preferred region code set to 1
[  54.605438] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadTransferable:171: Found a transferable disk cache with 256 entries
[  54.619055] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadPrecompiledFile:274: Found a precompiled disk cache with 238 decompiled entries and 238 binary entries
[  55.041110] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
[  55.055734] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
[  55.058186] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetLockHandle:317: (STUBBED) called applet_attributes=0X00000000
[  55.062040] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F
[  55.062803] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
[  55.063445] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:600: (STUBBED) called, version: 0x050201C8
[  55.065032] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:607: (STUBBED) called, cpu_percent=20, value=1
[  55.065860] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:296: (STUBBED) app_id=768
[  55.069386] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[  55.069692] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  55.070152] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ReplySleepQuery': port='APT:U' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}
[  55.085848] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[  55.088513] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[  55.116485] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:706: called flag=00000000 process=11 thread_id=0
[  55.183148] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:496: Firmware hash: 0xe00a211577bc944e
[  55.183151] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:500: Structures hash: 0x228655de1258d999
[  55.183153] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:188: called size=0xC288, prog_mask=0x000000FF, data_mask=0x000E00FF
[  55.183934] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:254: Registered interrupt=2, channel=2, event=event-003de598
[  55.184250] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:271: (STUBBED) called
[  55.184504] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:281: (STUBBED) called mask=0x2000
[  55.184993] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:257: Application has requested initialization of DSP hardware
[  55.185212] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[  55.186819] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[  55.591381] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[  55.592429] Service.FS <Error> ./core/file_sys/file_backend.h:GetReadDelayNs:54: Delay generator was not initalized. Using default
[  55.620462] Service.FS <Error> core/file_sys/savedata_archive.cpp:CreateFile:233: /home/pierre/snap/citra-emu/common/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/00048000/F000000B/user/gamecoin.dat already exists
[  55.627283] Service.PTM <Warning> core/hle/service/ptm/ptm.cpp:GetTotalStepCount:107: (STUBBED) called
[  56.605718] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  56.610682] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[  56.629394] Service.FS <Error> core/hle/service/fs/file.cpp:Read:74: Reading from out of bounds offset=0x0 length=0x00001604 file_size=0x200
[  56.629502] Service.FS <Error> core/hle/service/fs/file.cpp:Read:74: Reading from out of bounds offset=0x200 length=0x00001404 file_size=0x200
[  64.091304] Service.FS <Warning> core/hle/service/fs/file.cpp:OpenLinkFile:214: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]
[  70.591847] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000001
[  70.601457] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:58: Create flag set but write flag not set
[  70.608862] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:ResumeDaemons:89: (STUBBED) bit_mask=0x00000001
[  70.609749] HW.Memory <Error> core/memory.cpp:Read:322: unmapped Read32 @ 0x00000018 at PC 0x002979E4
[  70.609752] HW.Memory <Error> core/memory.cpp:Read:322: unmapped Read32 @ 0x00000000 at PC 0x00000000
[  70.609754] HW.Memory <Error> core/memory.cpp:Read:322: unmapped Read32 @ 0x00000004 at PC 0x00000000
[  70.609755] HW.Memory <Error> core/memory.cpp:Read:322: unmapped Read32 @ 0x00000008 at PC 0x00000000
[  70.609756] HW.Memory <Error> core/memory.cpp:Read:322: unmapped Read32 @ 0x0000000C at PC 0x00000000
[  70.609757] HW.Memory <Error> core/memory.cpp:Read:322: unmapped Read32 @ 0x00000010 at PC 0x00000000
