### ISSUE TITLE
rhythm games suggestions

### ISSUE THREAD

**Issue by tommyTsaiTou** [citra-emu/citra#5259] opened 2020-04-20 23:32 UTC
_n rhythm games such as Taiko Tatsujin and rhythm tengoku/megamix/paradise there are four different frames when loading a song or level.
song, rhythm, thought, and the graphic frame
for now the problem seems these four frames are not together
the problem shows at this two kind of game.
can you guys fix it as soon as posible? thanks

**Comment by FearlessTobi** [comment] 2020-04-20 23:52
Duplicate of https://github.com/citra-emu/citra/issues/4649.

**Closed by FearlessTobi** 2020-04-20 23:52 UTC
