### ISSUE TITLE
Odd texture corruption (load failure?) in homebrew

### ISSUE THREAD

**Issue by zetaPRIME** [citra-emu/citra#2354] opened 2016-12-19 10:07 UTC
I'm working on a UI framework for 3DS, and in the course of my testing I found that after adding my bitmap font renderer my buttons' pressed state image didn't load properly on Citra (it appears to be rendering part of one of the font sheets instead? I know the font isn't overwriting the pressed image since the latter is loaded after the font) No such issue observed testing on hardware.

Commit of my UI framework where this was discovered:
https://github.com/zetaPRIME/starlauncher/commit/7e08868a2fdb529f9ee5f4d4604003e69b189fe6
(you need to uncomment something to compile using devkitARM r45; I'm using a test version of r46 at the moment)
Tested in Citra Edge HEAD-42dc6c4

How it renders in Citra:
![image](https://cloud.githubusercontent.com/assets/6675194/21308348/8d5e0ec4-c5a7-11e6-9dfe-3f78c06a1b9d.png)

How it's supposed to look:
![image](https://cloud.githubusercontent.com/assets/6675194/21308440/0221cf48-c5a8-11e6-8f9c-b647d3252485.png)

**Comment by j-selby** [comment] 2016-12-19 11:22
For reference, the code you need to enable is https://github.com/zetaPRIME/starlauncher/blob/master/source/starlight/_incLib/_stringfix.h (uncomment the obvious)

**Comment by j-selby** [comment] 2016-12-19 11:28
It seems this code doesn't compile at all with r45 - I'm not familiar with the homebrew toolchains to go further.

```
arm-none-eabi-g++ -MMD -MP -MF /home/James/starlauncher/build/RenderCore.d -g -Wall -O2 -mword-relocations -fomit-frame-pointer -ffunction-sections -fdata-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -I/home/James/starlauncher/source -I/home/James/starlauncher/include -I/c/devkitPro/libctru/include -I/c/devkitPro/portlibs/armv6k/include -I/c/devkitPro/portlibs/3ds/include -I/home/James/starlauncher/build -DARM11 -D_3DS -fno-rtti -std=gnu++14 -c /home/James/starlauncher/source/starlight/gfx/RenderCore.cpp -o RenderCore.o
C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp: In static member function 'static void starlight::gfx::RenderCore::Open()':
C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp:108:85: error: too many arguments to function 'void Mtx_OrthoTilt(C3D_Mtx*, float, float, float, float, float, float)'
     Mtx_OrthoTilt(&targetTopLeft->projection, 0.0f, 400, 240, 0.0f, 0.0f, 1.0f, true);
                                                                                     ^
In file included from c:/devkitPro/libctru/include/citro3d.h:12:0,
                 from C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp:5:
c:/devkitPro/libctru/include/c3d/maths.h:72:6: note: declared here
 void Mtx_OrthoTilt(C3D_Mtx* mtx, float left, float right, float bottom, float top, float near, float far);
      ^
C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp:109:86: error: too many arguments to function 'void Mtx_OrthoTilt(C3D_Mtx*, float, float, float, float, float, float)'
     Mtx_OrthoTilt(&targetTopRight->projection, 0.0f, 400, 240, 0.0f, 0.0f, 1.0f, true);
                                                                                      ^
In file included from c:/devkitPro/libctru/include/citro3d.h:12:0,
                 from C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp:5:
c:/devkitPro/libctru/include/c3d/maths.h:72:6: note: declared here
 void Mtx_OrthoTilt(C3D_Mtx* mtx, float left, float right, float bottom, float top, float near, float far);
      ^
C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp:110:84: error: too many arguments to function 'void Mtx_OrthoTilt(C3D_Mtx*, float, float, float, float, float, float)'
     Mtx_OrthoTilt(&targetBottom->projection, 0.0f, 320, 240, 0.0f, 0.0f, 1.0f, true);
                                                                                    ^
In file included from c:/devkitPro/libctru/include/citro3d.h:12:0,
                 from C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp:5:
c:/devkitPro/libctru/include/c3d/maths.h:72:6: note: declared here
 void Mtx_OrthoTilt(C3D_Mtx* mtx, float left, float right, float bottom, float top, float near, float far);
      ^
C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp: In static member function 'static starlight::gfx::CTexture* starlight::gfx::RenderCore::LoadTexture(void*, int, int)':
C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp:221:159: error: 'C3D_SafeDisplayTransfer' was not declared in this scope
     C3D_SafeDisplayTransfer(static_cast<u32*>(src), GX_BUFFER_DIM(width, height), static_cast<u32*>(tex->texture->data), GX_BUFFER_DIM(owidth, oheight), flags);
                                                                                                                                                               ^
C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp: In constructor 'starlight::gfx::CRenderTarget::CRenderTarget(int, int, bool)':
C:/devkitPro/msys/home/James/starlauncher/source/starlight/gfx/RenderCore.cpp:244:62: error: 'Mtx_Ortho' was not declared in this scope
     Mtx_Ortho(&projection, 0.0f, w, 0.0f, h, 0.0f, 1.0f, true);
```

**Comment by sykhro** [comment] 2016-12-19 13:26
It compiles just fine without modifications here. Be sure to have latest Citro3D

**Comment by JayFoxRox** [comment] 2016-12-19 14:56
What config does / doesn't this happen with?

* CPU JIT / Interpreter
* Shader JIT / Interpreter
* HW / SW rendering

Also test using nightly builds please.

**Comment by yuriks** [comment] 2016-12-19 16:35
And if none of that works, can you attach a compiled 3dsx please?

**Comment by zetaPRIME** [comment] 2016-12-19 20:57
Huh. It happens only when HW rendering is enabled at the point it loads the pressed texture.
Can't test on nightly, build server is still down?

[starlauncher.zip](https://github.com/citra-emu/citra/files/662120/starlauncher.zip)

**Comment by lefta** [comment] 2016-12-20 13:27
Could not reproduce the texture problem with the provided compiled 3dsx

* Citra commit: 20b832cf & 3a1eaf2e
* Tested HW/SW rendering, with and without shader/CPU JIT
* OS: Linux
* Graphics: Nvidia (proprietary driver) & intel

I think devs will need also want the log output if latest master is affected.

**Comment by mrRosset** [comment] 2016-12-20 13:46
Can reproduce the problem with the provided 3dsx
- master branch commit 3a1eaf2efc4e5cb3358ab7451182711dfbaa061b  
- OS: Windows 10 64bits (fully updated)
- Graphic card: Intel hd 4000 (last driver according to intel's driver utility)
- Compiled with Visual studio 2015
The problem appears only in HW rendering, doesn't happens in SW rendring.
Shader Jit doesn't affect the problem.

**Comment by lefta** [comment] 2016-12-20 14:27
I forgot, my graphics card are an Intel HD Graphics 530 and a NVidia GTX 960M.

Let's see If someone have the problem with other hardware to see if it is a problem specific to some graphics device/driver or to Windows. I bet on the second ;)

**Comment by zetaPRIME** [comment] 2016-12-20 21:37
my system:
Windows 8 x64
GeForce GTX 660 (driver version 368.22)

**Comment by lefta** [comment] 2016-12-22 07:40
It seems like it is specific to Windows in this case. Now that specific graphics cards / drivers have been excluded, let's let the developpers debug it. Good luck guys ;)

**Comment by JayFoxRox** [comment] 2016-12-22 15:05
Can someone apitrace it or debug the issue with our Citra Pica breakpoints / Shader debugger / Surface Viewer?

**Comment by FearlessTobi** [comment] 2017-11-19 01:53
The issue seems to be resolved in the latest Nightly.

![unbenannt](https://user-images.githubusercontent.com/20753089/32986546-bf231af0-ccd4-11e7-8c2c-d207f8dd4ef8.PNG)

**Comment by Dragios** [comment] 2017-11-19 01:59
But it's not centered?

**Comment by FearlessTobi** [comment] 2017-11-19 02:01
Actually the button with the text is moving, so it seems to be intended to me.

**Comment by Dragios** [comment] 2017-11-19 02:06
Oh, it's moving. I thought it was a static image. False alarm then.

**Closed** 2017-11-20 16:29 UTC
