### ISSUE TITLE
[Feature Request] Hold for Fast Forward

### ISSUE THREAD

**Issue by Shiriow** [citra-emu/citra#6447] opened 2023-04-18 16:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Would it be possible to add a hold for fast forward hotkey? Currently it only exists as a toggle.

### Why would this feature be useful?

Not having to press the same button twice for a one second fast forward.

**Comment by FearlessTobi** [comment] 2023-04-18 18:51
Duplicate of https://github.com/citra-emu/citra/issues/4932.

**Closed by FearlessTobi** 2023-04-18 18:51 UTC
