### ISSUE TITLE
Allow controller hotkeys. (e.g. Swap screens)

### ISSUE THREAD

**Issue by twoco** [citra-emu/citra#5197] opened 2020-04-12 14:47 UTC
Currently it's not possible to map a controller (e.g. XBOX One Controller) to the Citra hotkeys to e.g. swap screens. 

The "Enter a hotkey" ("Press shortcut") should "simply" accept controller inputs like the other input tab. 
This will allow to map the "Swap Screens" hotkey to e.g. the thumb key (R3) or any other key of the controller. No need for the keyboard anymore. 

Canary 1640 HEAD-4f8f8e8 (2020-04-07)

**Comment by FearlessTobi** [comment] 2020-04-12 21:36
Duplicate of https://github.com/citra-emu/citra/issues/4932.

**Closed by FearlessTobi** 2020-04-12 21:36 UTC
