### ISSUE TITLE
Beyond the Labyrinth - crashes after loading savegame 

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1457] opened 2016-03-05 18:12 UTC
I noticed that new revisions of Citra crashes after loading savegame. This happens with all locations, except the first dangeon, which does not use 3D graphics.

I uploaded saves, so you can check it for yourself
[00065c00.zip](https://github.com/citra-emu/citra/files/159974/00065c00.zip)

![01](https://cloud.githubusercontent.com/assets/13983158/13549517/a2da1a72-e317-11e5-9c44-68cc9e60ab8c.jpg)

**Comment by Romsstar** [comment] 2016-03-05 21:34
According to this https://www.3dbrew.org/wiki/DSP:InvalidateDCache is unimplemented,
Part of the Audiocore (DSP) But this shouldn't cause crashing after Savegame Loading...
If anything it should cause either all the time, or not at all, but not during Savegame Loading.
At least not in my opinion. I might be wrong but I think something else is going on.
Did this also happen on earlier builds? Because well doesn't look like a regression case to me.
If this used to work before than it might be, but you didn't specify...

What might be on the other hand: Lately some config block data was added. If you had dumped config data before this MIGHT cause issues... (Again just guessing here) 

1) Try an earlier build and see if that works for you, than it might be a case of regression
2) I'd try and delete config block data and see what happens. 

Just my ideas.

**Comment by Punk34** [comment] 2016-03-05 21:53
This game worked fine before, about 4-5 months ago. It will be difficult to find a regression build for now.

**Comment by Romsstar** [comment] 2016-03-05 23:58
https://builds.citra-emu.org/citra/nightly/windows-amd64/ This has builds archived from 19.03.2015.
Try to find the most recent one that still works with the game and you can pinpoint what broke the game.

**Comment by mailwl** [comment] 2016-03-06 04:33
Citra crashes only if HW Renderer enabled.
the same crash in game Adventure Time: Explore the Dungeon Because I DONT KNOW! (USA), but at start, when first screen will be shown
https://github.com/citra-emu/citra/blob/master/src/common/hash.cpp#L21

**Comment by Punk34** [comment] 2016-03-06 11:02
@Romsstar thanks.

Found it! Regression build - **citra-20150827-2978b5f**

**Comment by mailwl** [comment] 2016-03-06 12:34
it this commit added line 
`new_texture->hash = Common::ComputeHash64(texture_src_data, new_texture->size);`
which leads to illegal memory access

**Comment by Punk34** [comment] 2016-03-06 12:38
so it can be fixed, or this line is important?

**Comment by mailwl** [comment] 2016-03-06 12:40
i dont know, ask @yuriks

**Comment by JayFoxRox** [comment] 2016-04-02 23:40
Probably dupe of #1229

**Comment by exhalatio** [comment] 2016-04-26 12:16
@Punk34 It seems okay loading savegame with 4c9ed98.
![labyrinth](https://cloud.githubusercontent.com/assets/7089513/14817477/871f145a-0bf2-11e6-8cff-2d4633c51eb4.jpg)

**Comment by wwylele** [comment] 2016-08-03 19:29
Is this fixed on current master?

**Comment by Subv** [comment] 2016-11-27 05:46
Does this still happen?

**Comment by Subv** [comment] 2017-01-11 03:58
I'm closing this one due to lack of feedback. If the bug still happens please open a new issue

**Closed by Subv** 2017-01-11 03:58 UTC
Labels: T-bug, T-regression
