### ISSUE TITLE
Macbook cant run Citra

### ISSUE THREAD

**Issue by LimitedDani** [citra-emu/citra#4679] opened 2019-03-09 14:39 UTC
Citra says that my GPU does not support OpenGL 3.3 but the specs says something else, help?

![Screen Shot 2019-03-09 at 15 32 28](https://user-images.githubusercontent.com/11191383/54072924-6ee18a80-4281-11e9-939f-f51e7792ce72.png)
![Screen Shot 2019-03-09 at 15 33 26](https://user-images.githubusercontent.com/11191383/54072925-6f7a2100-4281-11e9-854c-d155a2223771.png)
![Screen Shot 2019-03-09 at 15 37 13](https://user-images.githubusercontent.com/11191383/54072926-6f7a2100-4281-11e9-9923-035572ad9198.png)
![Screen Shot 2019-03-09 at 15 37 23](https://user-images.githubusercontent.com/11191383/54072927-6f7a2100-4281-11e9-916e-dfc4cf06ef85.png)
![Screen Shot 2019-03-09 at 15 37 31](https://user-images.githubusercontent.com/11191383/54072928-6f7a2100-4281-11e9-89c6-6182434ffe69.png)

**Comment by wwylele** [comment] 2019-03-09 14:40
Duplicate of #4515

**Comment by FearlessTobi** [comment] 2019-03-09 14:41
Duplicate of https://github.com/citra-emu/citra/issues/4515.

**Closed by wwylele** 2019-03-09 14:40 UTC
