### ISSUE TITLE
Digimon World Re:Digitize Decode - Moflex Video Loading Black screen 

### ISSUE THREAD

**Issue by Romsstar** [citra-emu/citra#2119] opened 2016-10-09 20:40 UTC
This bug seems to be rather a regression but I was unable to pinpoint it exactly since I can't seem to find the build where it used to work:

With the current build of Citra, no additional merges, the game will freeze to a black screen when trying to play the intro of the game or when starting a new game. 

This happens in both cases because a .moflex video is about to be loaded. 

In past builds (I really can't tell which one, it's been months)) it was at least possible to skip the intros by pressing start, in spite of the black screen. But now, pressing start would do nothing and the game would simply freeze on starting a new game or starting the game without having a savegame present (Since having a savegame present will skip the first moflex video).

Now I'm not sure what caused that, or whether that is relevant at all, but I wanted to report it.

Unfortunately the log contains no useful information at all, literally nothing, so there's hardly any point pasting it or the black screen. 

Perhaps someone with a deeper understanding of the root of this problem might look into this.
I guess simplied the problem could be summarized to: Moflex Video Loading is freezing the game/emulator to a black screen.

**Comment by JayFoxRox** [comment] 2016-10-09 21:44
Does this only happen with JIT or also with interpreter? Did you keep your home folder dump?
Can you try to bisect it to find the version it first broke at?

**Comment by mailwl** [comment] 2016-10-12 11:29
problem the same, as FIFA games, which i tryed to fix in #2124 - no delay for signaling completion event in async functions (Y2R::StartConversion in this case)

**Comment by Romsstar** [comment] 2016-10-13 15:06
merged #2124 , didn't fix it. 
This also happens with and without JIT.
Unfortunately I didn't but I will try and find the version where it regressed.

**Comment by Romsstar** [comment] 2016-10-13 15:54
UPDATE: 

Found at least one version where it still worked.

Still worked in citra-20160501-17ecf0d-windows-amd64

I'm trying to pinpoint now, when exactly it regressed.

**Comment by Romsstar** [comment] 2016-10-13 16:05
Okay got it.

The regression occured between

Worked in 51ee2d2
citra-20160521-51ee2d2-windows-amd64.7z	12M	21-May-2016 15:20

Broken in e054e55:
citra-20160522-e054e55-windows-amd64.7z	12M	23-May-2016 00:16

**Comment by wwylele** [comment] 2016-10-14 01:58
Although I labelled this as a regression with respect to the observation, I think it is more like revealing a bug that we already had before, since it was already broken before #1837, and #1837 was just changing (improving?) the scheduler behaviour a bit and advanced the freeze.

**Comment by MerryMage** [comment] 2016-12-08 11:37
#2260 has not been merged.

**Closed** 2016-12-16 05:41 UTC
Labels: T-bug, T-regression
