### ISSUE TITLE
Pokemon MD:GtI Magnagate crash / hardlock

### ISSUE THREAD

**Issue by Hexagon12** [citra-emu/citra#2608] opened 2017-03-02 19:38 UTC
Using Bleeding Edge f239770.
I was going to test the Magnagate function, because CAM service was implemented, but something is still broken.

Reproducing the issue: 
Boot up the game, go to Discover A Magnagate, Search out a new Magnagate. Then the game will freeze up and is stuck.
![no fps](https://cloud.githubusercontent.com/assets/25362478/23523621/5839c4c2-ff90-11e6-800d-bcd49aac7350.PNG)

Log here: http://pastebin.com/xLLevx6C

**Comment by RavenHome1** [comment] 2017-03-02 20:21
duplicate of https://github.com/citra-emu/citra/issues/2110 or a completely unrelated?

**Comment by wwylele** [comment] 2017-03-02 23:20
@RavenHome1 Unrelated, I think

**Comment by wwylele** [comment] 2017-03-02 23:23
@Hexagon12 Could you take a screen shot of the Wait Tree when it freezes? (Do like the one in #2554)

**Comment by Hexagon12** [comment] 2017-03-03 12:06
@wwylele Here you go. The wait tree is kinda big, so I spilt it up to 2 parts.

![1st part](https://cloud.githubusercontent.com/assets/25362478/23550606/944bba8a-001a-11e7-83f7-4b5a85539b39.PNG)
![2nd part](https://cloud.githubusercontent.com/assets/25362478/23550612/96d37b4e-001a-11e7-9afd-4c83351aa789.PNG)

**Comment by Hexagon12** [comment] 2017-03-06 17:58
Is somebody looking into this issue? @wwylele are you alive? :)

**Comment by FernandoS27** [comment] 2017-03-06 18:07
Don't expect a fix anytime soon. Kernel stalls are among the hardest issues to resolve.

**Comment by Hexagon12** [comment] 2017-03-06 18:40
@FernandoS27 Ahhhh, OK, I understand. I am just looking, if a fix is available, because the Magnagate dungeons are really interesting to explore and the CAM service has been implemented, so I could theoretically pull up a image and it would scan it.

**Comment by Hexagon12** [comment] 2017-03-25 19:01
Just checked with Bleeding Edge 86 and it crashes? I mean it crashes the whole Citra program, not the game...

**Comment by B3n30** [comment] 2017-12-10 19:01
Closed by #3091

**Closed by B3n30** 2017-12-10 19:01 UTC
Labels: T-bug, T-game-hang
