### ISSUE TITLE
problem to mount the rank s support level in fire emblem fate

### ISSUE THREAD

**Issue by Vanphysla** [citra-emu/citra#4008] opened 2018-07-26 20:28 UTC
hello i currently encounter a problem when i want to pass the support of a rank s perso (me these hinako) solution to me give?
I use citra canary # 673 (from what I see with my window)
my configuration:
CPU: Intel Core I5-2400 has 3.10GHz / 3.40GHz in turbo
Ram: 4GB DDR3 1333
GPU: NVIDIA Quadro 2000

To put it simple when I speak a hinako everything goes well but at the time of the change of frame it remains white, I do not know where the trouble comes from but if you help me that I would be grateful

**Comment by Hexagon12** [comment] 2018-07-27 08:04
Duplicate of #3443.

Requesting to close.

**Closed** 2018-07-27 09:12 UTC

**Comment by Vanphysla** [comment] 2018-07-28 12:59
good morning / good evening sorry for having done that but being new on this platform I do not know how to use the tools and other in question

**Comment by zhaowenlan1779** [comment] 2018-07-28 14:11
@Vanphysla 
This is an issue tracker for developers. The issue is a duplicate, that is to say someone already know this and an issue is open for it.
If you need support, please visit our community forum at https://community.citra-emu.org , or you may also ask the question in #citra-support channel in our [Discord](https://citra-emu.org/discord/).
