### ISSUE TITLE
Zelda Triforce Heros Crash

### ISSUE THREAD

**Issue by brimaster2000** [citra-emu/citra#1443] opened 2016-03-02 22:59 UTC
Citra seems to lock up and freeze after a spin attack is charged.

**Comment by KillzXGaming** [comment] 2016-03-03 21:10
Issue occurs in Tri-Force Heroes and Kirby Triple deluxe too (and possibly Yoshi New Island). Happens when a particle effect occurs. Disabling shader effect results in no crash however shows buggy particles.

**Comment by ds84182** [comment] 2016-03-04 02:31
Possibly unimplemented Geometry Shaders. Can you both post logs?

**Comment by bunnei** [comment] 2016-03-04 04:32
@KillzXGaming what do you mean by "Disabling shader effect results"... Do you mean disabling the shader JIT?

**Comment by KillzXGaming** [comment] 2016-03-04 20:49
Yes. by disabling Shader JIT.

**Comment by JohnGodgames** [comment] 2016-03-05 06:03
Yeah there is more games that do the same thing and propably more:

Exstetra
Final Fantasy Explorers
Kirby Fighters Deluxe
Kirby Triple Deluxe
Sayonara Umihara Kawase

dupe of https://github.com/citra-emu/citra/issues/1081

**Closed** 2016-03-16 17:18 UTC
Labels: bug
