### ISSUE TITLE
Missing folder icons on non-existent directories 

### ISSUE THREAD

**Issue by lasers** [citra-emu/citra#6611] opened 2023-06-14 05:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1907

### Description of Issue

I added:
* `~/Games/Nintendo 3DS` (home storage)
* `/run/media/lasers/Example_Name/Games/Nintendo 3DS` (external storage)

If external storage is not mounted, you get an entry without folder icon.
The size of that entry is different too (much smaller) and looks out of place.

### Expected Behavior

Always display folder icons.

### Reproduction Steps

Test game directories with 1) games, 2) empty directory, and 3) non-existent directory

Close Citra.
Rename the directory.
Open Citra.
Directory without icon appears.

### Log File

N/A

### System Configuration

N/A

**Comment by FearlessTobi** [comment] 2023-06-14 13:12
I am unable to reproduce this.
For me, an error icon is shown correctly in this case: 
![grafik](https://github.com/citra-emu/citra/assets/20753089/9241db52-a962-4a62-b511-6ba44c4ca75e)

Closing since you did not fill out the issue template correctly and we therefore cannot investigate this further.

**Closed by FearlessTobi** 2023-06-14 13:12 UTC

**Comment by lasers** [comment] 2023-06-14 19:22
>For me, an error icon is shown correctly in this case

I didn't get that. Maybe it's a distro-related packaging. Thank you.
