### ISSUE TITLE
Citra Nightly 1255 

### ISSUE THREAD

**Issue by hpatto13** [citra-emu/citra#4788] opened 2019-06-03 04:14 UTC
Directory links appear to be broken when using Pop!_OS 19.04 and Citra Nightly 1255 on XPS 13 9370 with i7 8550u and UHD 620

(flatpak install)
"open log location" does not open anything

**Comment by wwylele** [comment] 2019-06-03 10:34
Duplicate of #4471

**Closed by wwylele** 2019-06-03 10:35 UTC
