### ISSUE TITLE
[Riki Densetsu] Characters disappear partially when facing left

### ISSUE THREAD

**Issue by aGrover12** [citra-emu/citra#3801] opened 2018-06-01 02:51 UTC
Nightly Build 72f9142

Whenever a character is turned towards the left, half of their person is not visible. I've tried disabling Enable Hardware Shader and disabling/enabling Accurate Multiplication. This did not solve the problem. I even tried disabling Enable Hardware Renderer, but it just made the game crash. Bellow is an image of the glitch.

![image](https://user-images.githubusercontent.com/39816744/40818418-94158bbe-651c-11e8-8cbd-4c857b338d78.png)

**Comment by Leo626** [comment] 2018-06-01 03:45
[Log](https://community.citra-emu.org/uploads/default/original/2X/9/971f900f79078e319cd1cb3b62a3c14b892251f1.txt) from OP's [forum thread](https://community.citra-emu.org/t/graphic-issues-characters-disappear-partially-when-facing-left/23593).

Real hardware comparison.
![screenshot](https://user-images.githubusercontent.com/17358613/40820100-eddb01ca-6534-11e8-8840-d1a2866b31cc.png)

**Comment by benderscruffy** [comment] 2018-06-01 09:27
duplicate of #3400

**Comment by benderscruffy** [comment] 2020-02-29 07:57
it is still an issue

**Comment by OdinNoah** [comment] 2022-01-31 07:10
Of the 4 Kunio games on the 3ds, this is plagueing 3 of them.
River City: Tokyo Rumble has the same problem.
River City: Rival Showdown has the same problem but when you pick up an object and face left.
Riki Densetsu: Has this problem.
River City: Knights of Justice does NOT have this problem.

**Closed** 2023-09-10 21:29 UTC
Labels: A-graphics
