### ISSUE TITLE
Crash by clicking on F6 then F5 in game

### ISSUE THREAD

**Issue by Fewnity** [citra-emu/citra#6214] opened 2022-12-10 16:05 UTC
Hello, I'm using the latest version of Citra Windows (Canary and nightly) and I found a way to cause a crash on the emulator.
You just need to launch a game, press F6 to reboot the game and then quickly press F5 to quit the game. And the emulator crash.

**Comment by RokkumanX** [comment] 2022-12-11 06:59
While I can't replicate your specific issue pressing F6 and then quickly press F5 to make the emulator crash I have something similar that makes the emulator crash 100% of the times.

1. Start a game
2-A. Close the emulator while the game is running and the emulator will crash
2-B. Pause emulation or stop emulation and when you close the emulator it will crash

If you just open the emulator and close it, it will not crash. And if you are indeed playing a game and stop the emulation, then go into configuration and thereafter close the emulator it will not crash.

According to to Windows Reliability Monitor the faulting module is citra-qt.exe with the exception code 0xc000005 and the fault offset being 0x00000000002e8ee5

This is my first time in a long while I decided to test a new version of Citra out, my last working version is Canary 2174 from this summer and I'm making a half-good attempt finding a version that does not crash closing the emulator after stopping, pausing.

**Comment by Fewnity** [comment] 2022-12-23 21:10
Update : the crash can be caused just by pressing twice F6 quickly too. On Citra Nightly 1822 and Citra Canary 2344. (I can reproduce the bug on my second pc).
I need to download a game to test on a different game, because I'm playing an homebrew.

**Comment by RokkumanX** [comment] 2022-12-31 06:50
@Fewnity 

Does Canary 2310 work for you? I want to know if it's related with the crashes I mentioned above and if it started after 2310

**Comment by GPUCode** [comment] 2023-09-15 15:03
Cannot reproduce this anymore on recent builds. Feel free to reopen if this still an issue

**Closed by GPUCode** 2023-09-15 15:03 UTC

**Comment by Fewnity** [comment] 2023-09-15 15:13
@GPUCode Oh I had forgotten this issue, I just downloaded the latest version of Citra (Nightly 1990 and Canary 2620) I can still produce the crash on both version.
I can't reopen the issue but I can create a new one if you can't reopen the issue too

**Comment by GPUCode** [comment] 2023-09-15 15:15
Yes would be good so it can get more attention. Also add more details like a log file and testing platform.
This is strange though can't get it to crash

**Comment by Fewnity** [comment] 2023-09-15 15:16
@RokkumanX Sorry for the late reply, I can reproduce the crash on Canary 2310 too
