### ISSUE TITLE
Pokemon Omega Ruby Crashes at first Tabitha fight in Meteor Falls

### ISSUE THREAD

**Issue by PublicNeusance** [citra-emu/citra#6871] opened 2023-08-07 03:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1962

### Description of Issue

Fighting Tabitha in Omega Ruby for the first time in Meteor Falls causes Citra to close (crash?). Not sure what to make of the error log, but any help would be appreciated. Running on the most updated software for the Steam Deck (Proton 8.0).

### Expected Behavior

The fight with Tabitha should begin without issue, and load into him and his grunt using their first set of Pokemon.

### Reproduction Steps

Engaging in dialogue with May and leading into the fight will cause it to crash. Even if you decide you "need time to prepare," so long as the fight begins, it crashes.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12271815/citra_log.txt)

### System Configuration

CPU: AMD Custom APU 0405
GPU/Driver: N/A
RAM: 14.47GiB
OS: Proton 8.0

**Comment by gidoly** [comment] 2023-08-07 03:41
Can you post save

**Comment by PublicNeusance** [comment] 2023-08-07 03:55
one moment, a pinch difficult to get the folder to paste

**Comment by PublicNeusance** [comment] 2023-08-07 04:02
> Can you post save

Hope this helps some: [00000000000000000000000000000000.zip](https://github.com/citra-emu/citra/files/12271927/00000000000000000000000000000000.zip)

**Comment by ianhealy91** [comment] 2023-08-23 17:29
Suspect it's the same issue as here https://github.com/citra-emu/citra/issues/6696 Pokemon with smoke effects seem to instantly crash Citra (Koffing, Torkoal etc.)

**Comment by benderscruffy** [comment] 2023-09-12 09:18
@PublicNeusance 
using Canary 2617
doesn't crash out now
does it crash out for you

**Comment by benderscruffy** [comment] 2023-09-14 08:34
using Canary 2618
doesn't crash out now
Can be closed

**Comment by ianhealy91** [comment] 2023-09-14 09:39
Still crashes on Flatpak nightly

**Comment by benderscruffy** [comment] 2023-09-14 10:35
ok im on windows that's why it didn't crash

**Comment by Steveice10** [comment] 2023-10-12 04:31
Can you check on the latest Flatpak as we've made some fixes recently

**Comment by SamsonHua** [comment] 2023-10-27 03:44
> Can you check on the latest Flatpak as we've made some fixes recently

Tried on flatpak nightly 2020, still crashing unfortunately. :(

If I run the app version on SD on 2020 it works but not on flatpak run

**Comment by DrZoidburger** [comment] 2023-11-02 06:37
Having same issue on flatpak nightly 2020 on SteamOS

**Comment by Wunkolo** [comment] 2023-11-03 02:04
> Suspect it's the same issue as here #6696 Pokemon with smoke effects seem to instantly crash Citra (Koffing, Torkoal etc.)

Looks to be the same issue. I put some notes in https://github.com/citra-emu/citra/issues/6696. Seems to depend on if the build has asserts enabled or not. When asserts are off, it just quietly corrupts memory. Flatpack probably has asserts enabled.

**Comment by Steveice10** [comment] 2023-11-03 03:36
> > Suspect it's the same issue as here #6696 Pokemon with smoke effects seem to instantly crash Citra (Koffing, Torkoal etc.)
> 
> Looks to be the same issue. I put some notes in #6696. Seems to depend on if the build has asserts enabled or not. When asserts are off, it just quietly corrupts memory. Flatpack probably has asserts enabled.

It’s possible that this is because Flatpak adds some additional hardening compile options by default which are catching something we don’t elsewhere.

**Comment by Steveice10** [comment] 2023-11-03 10:36
Crash should be fixed by https://github.com/citra-emu/citra/pull/7111

We are tracking the underlying issue in https://github.com/citra-emu/citra/issues/7112

Please let us know if the issue is not fixed when the above PR is available in releases.

**Closed by Steveice10** 2023-11-03 10:36 UTC

**Comment by DrZoidburger** [comment] 2023-11-05 01:32
Any timeline on when the fix will be availiable in the emudeck flatpak release?

**Comment by Steveice10** [comment] 2023-11-05 01:46
> Any timeline on when the fix will be availiable in the emudeck flatpak release?

It's in Nightly 2024. We don't have any control over Emudeck but it is in our latest flatpak release.

**Comment by SamsonHua** [comment] 2023-11-05 01:48
Just updated to nightly 2024 using flatpak update in desktop mode on Steam Deck! Works like a charm now and no longer crashes on Koffing. Thanks Citra Dev team! :)

**Comment by DrZoidburger** [comment] 2023-11-05 04:08
Im a little new to this stuff, but when I tried through emudeck it stayed at nightly 2020, how did you do it?

**Comment by SamsonHua** [comment] 2023-11-05 05:16
> Im a little new to this stuff, but when I tried through emudeck it stayed at nightly 2020, how did you do it?

Emudeck just works off the flatpak launcher so if you update it through flatpak it should work on emudeck.

Enter into desktop mode on your Steam Deck, then open up Konsole application (terminal).

In Konsole, type `flatpak update`, it should tell you all the packages that have new updates, once it asks for the citra one, you can enter in Y (It'll prompt you Y/N) to update. Wait for the update to finish (It'll say in the terminal)

From there, go back into Steam Deck mode and Emudeck should launch into the new nightly.

**Comment by DrZoidburger** [comment] 2023-11-05 19:34
Thanks Citra Dev Team:), proper legends.
