### ISSUE TITLE
Feature Request: Add AA or filtering Options

### ISSUE THREAD

**Issue by wingedonezero** [citra-emu/citra#3623] opened 2018-04-03 03:31 UTC
Requesting either or both to clean up jaggys on increased internal resolution. Since we now have a great gpu renderer can now do higher internal resolutions. Included a pic below im sure everyone already knows why im requesting this. I didn't see any other request for aa by searching.

![untitled - copy](https://user-images.githubusercontent.com/15163316/38227803-005c1022-36ce-11e8-865d-0251459cc0d5.png)

**Comment by adityaruplaha** [comment] 2018-04-03 04:51
Hardware Accurate mipmapping isn't implemented yet, so this isn't a high priority right now as it'll be useless. I had PRed Anisotropic Filtering, but had closed it due to the same reasons.

**Comment by LogPod** [comment] 2018-04-03 05:28
@wingedonezero the jagged outlines are fixed in the latest builds

**Comment by Hexagon12** [comment] 2018-04-03 07:44
Requesting to close, because the issue is caused by an outdated build.

**Comment by Hexagon12** [comment] 2018-04-03 08:24
That's strange. This should have been fixed by #3281?

**Comment by Hexagon12** [comment] 2018-04-03 08:29
OS: Windows 10 Pro 64-bit 16299
CPU: Intel Core i3-6100 3.7 GHz
GPU: Nvidia GeForce GTX 750 Ti
Issue: Failed to reproduce. (?)
Citra build: 7d71017 - Nightly
![fixed](https://user-images.githubusercontent.com/25362478/38238370-4574668c-3732-11e8-8f81-fc73fc562fb6.PNG)

**Comment by Dragios** [comment] 2018-04-03 10:07
@Hexagon12 It sometimes happen when the outline texture did not get updated initially for some reason. It only occurs first time and will not happen again (until the emulator restarted? Have not been test this theory yet) As a workaround, change to native and increase to any internal resolution will fix the problem.

**Comment by wingedonezero** [comment] 2018-04-03 22:16
Using build c084c97 this time and at first it was like before but when i did as @Dragios suggested that made it a lot better than it was still some jaggys but i dont think itll get any better than that without filtering or aa. But its more playable with that workaround and visually appeasing. So this ended up being two issues in one i guess. But i did test if it keeps after restart and it seems so tryed 4 times and looks the same after workaround. Pic of after below.


![](https://user-images.githubusercontent.com/15163316/38227803-005c1022-36ce-11e8-865d-0251459cc0d5.png)

**Comment by MelonSpeedruns** [comment] 2018-04-06 21:53
AA can be added through your Graphic Card's control panel.

**Comment by natuschaos** [comment] 2018-04-07 22:49
I think this could help people who play at low resolutions like 1x on outaded hardware or implement 1.5x resolutions for weak hardware.

**Comment by SonofUgly** [comment] 2018-04-08 17:57
>Requesting either or both to clean up jaggys on increased internal resolution. Since we now have a great gpu renderer can now do higher internal resolutions.

Something that would be nice is to switch to bicubic or lanczos when downscaling. Pic is 4x downscaled, top is how Citra is now (bilinear I'm guessing), middle is bicubic, bottom is lanczos:
<details><summary>Image</summary>
Make sure to open in new tab and view at full resolution.

![](https://i.imgur.com/IfxpuUs.png)

</details>

**Comment by wwylele** [comment] 2018-09-15 01:18
Closing as the issue description and following discussions isn't really on topic on the pixelated outline bug (if exist). Please open a new one specifically for that bug if it is confirmed.

**Closed by wwylele** 2018-09-15 01:18 UTC
Labels: A-graphics, enhancement, proposal
