### ISSUE TITLE
Bravely Default/Second stuck

### ISSUE THREAD

**Issue by pippo2931** [citra-emu/citra#1822] opened 2016-05-19 23:01 UTC
Got 3 similar crashes in the Bravely games:
Default:
1) Chapter 1 when saving the merchant introduces the friend bot
   Stuck when pressing X to exit the window
2) When closing the special move menu
Second:
Black screen when closing the characters menu

<img width="1193" alt="screen shot 2016-05-19 at 3 38 11 pm" src="https://cloud.githubusercontent.com/assets/17737754/15412189/7e46ff6a-1dda-11e6-869d-c40027461cc6.png">
[err_log_default_friend _bot.txt](https://github.com/citra-emu/citra/files/273614/err_log_default_friend._bot.txt)

<img width="1193" alt="screen shot 2016-05-19 at 3 51 59 pm" src="https://cloud.githubusercontent.com/assets/17737754/15412205/99e9e16a-1dda-11e6-8343-148e4f6c725f.png">
[err_log_special.txt](https://github.com/citra-emu/citra/files/273615/err_log_special.txt)

![screen shot 2016-05-19 at 3 53 00 pm](https://cloud.githubusercontent.com/assets/17737754/15412214/aa58b472-1dda-11e6-8ce3-381b9b0242e7.png)
[err_log_second.txt](https://github.com/citra-emu/citra/files/273617/err_log_second.txt)

**Comment by lenoso1992** [comment] 2016-07-24 10:50
The error seems is in CancelLibraryApplet.

**Comment by pippo2931** [comment] 2016-07-24 18:37
I tried to stub it, but no improvements.

**Comment by lenoso1992** [comment] 2016-07-25 09:30
I tried many things to resolve the error that occurs when saving the merchant introduces the friend bot.

**Comment by Marborao** [comment] 2016-09-07 14:00
sup, anyway to solve this problem?

**Comment by vsub** [comment] 2016-09-25 09:08
I'm also experiencing the same problems(on any rev I tried,including the latest one).
You can still play the game but from that point on,you will not be able to save the game by using the merchant(enabling auto-saving is another way to save)

Now more and more things appear which are accessed from the merchant but because of that freeze,you can't use them too.

Other than those freezes,the game works fine 99% of the time at full speed(almost 10 hours of gameplay and I'm almost at the end of chapter 1)

**Comment by Kpskills** [comment] 2016-10-08 12:31
I'm also experiencing the friendbot issue but other than that the game runs fairly well but the problem is you can't save before the boss battle or buy one of the strongest sword [Night Emperor] or the best armors or accesory etcetera

**Comment by wakka1** [comment] 2016-10-08 18:50
I didn't even reach the friendbot thing and i got a freeze. It happens whenever i select "update data" and go back. Since it's an online thing,  is it because of lack of wifi in  citra maybe? Also, is it possible to acquire nemesis without connection??

**Comment by Kpskills** [comment] 2016-10-09 02:55
nope you cant actually acquire nemesis or fight them for that matter because they will not appear in norende without the net connection or streetpass

**Comment by wakka1** [comment] 2016-10-09 10:51
so is the game fully playable minus that merchant freeze? asking if anyone finished the game already

**Comment by JayFoxRox** [comment] 2016-10-09 11:05
Reminder that this is a bug tracker for developers of Citra.
Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
I'll clean up the discussion because this is not a chat or forum.

**Comment by JayFoxRox** [comment] 2016-11-18 01:05
A stub / hack -solution for this was proposed on the forums: https://discuss.citra-emu.org/d/907-bravely-default-second-stuck-1822-unofficial-workaround-fix

As some OP on forums did not react yet, I'll do their job of posting it in the proper channels.

I do not intend to implement or PR this change. OP or someone who knows that part of the codebase better should do it.
- If nobody does it, it probably won't be fixed.

gist:

> apparently the issue's been open since may and there hasn't been any progress. a lot of people probably moved on to a different game now but i managed to make the CancelLibraryApplet error disappear by modifying the source code from their git and building my own. since i'm not allowed to post my build here, and i don't have a github account, i'd like to share my changes here :)
>
>1) core/hle/service/apt/apt_u.cpp (replace nullptr with function CancelLibraryApplet):
```c++
	{0x003B0040, CancelLibraryApplet, "CancelLibraryApplet"},
```
>
>2) core/hle/service/apt/apt.h (add function CancelLibraryApplet):
```c++
	/**
	 * APT::CancelLibraryApplet service function
	 *  Inputs:
	 *      0 : Command header [0x003B0040]
	 *      1 : u8, Exists (0 = does not exist, 1 = exists)
	 *  Outputs:
	 *      0 : Return header
	 *      1 : Result of function, 0 on success, otherwise error code
	 */
	void CancelLibraryApplet(Service::Interface* self);
```
>
>3) core/hle/service/apt/apt.cpp (implement function CancelLibraryApplet with default response code):
```c++
	void CancelLibraryApplet(Service::Interface* self) {
		u32* cmd_buff = Kernel::GetCommandBuffer();
		LOG_DEBUG(Service_APT, "called %s", "CancelLibraryApplet");
		cmd_buff[1] = 1;
	}
```

(I think it's pretty sad that a solution is proposed on the forums and before anybody cares to work on an actual patch or at least a proper stub-PR for master, (some) people just leave with their hacked versions, not bothering about the future of the project)

**Closed** 2016-11-24 03:57 UTC
