### ISSUE TITLE
Bravely Default/Second recently stop working 

### ISSUE THREAD

**Issue by vsub** [citra-emu/citra#2128] opened 2016-10-15 12:01 UTC
I just get black screen when I try to run those games

Since I can't compile citra,the only option I have is to try the bleeding edge builds.
I tried all of the available releases 35-40 but the games don't work at all
And I also tried the latest nighty release too(Citra | HEAD-cc7f115) but it was the same thing.

This is the log I get when I try to run the game
```
[   0.000000] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:194: path exists X:\Citra/user/config/qt-config.ini
[   0.048136] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file ./console.chm as unknown...
[   0.048472] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file ./Console.exe as unknown...
[   0.048815] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file ./ConsoleHook.dll as unknown...
[   0.049128] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file ./ConsoleHook32.dll as unknown...
[   0.049371] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file ./ConsoleWow.exe as unknown...
[   0.049532] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file ./FreeImagePlus.dll as unknown...
[   5.493375] Frontend <Info> citra_qt\main.cpp:GMainWindow::BootGame:331: Citra starting...
[   5.620315] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:20: Directory X:\Citra/user/sdmc/ set as SDMC.
[   5.620786] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:194: path exists X:\Citra/user/sdmc/
[   5.620979] Service.FS <Info> core\file_sys\archive_savedata.cpp:FileSys::ArchiveFactory_SaveData::ArchiveFactory_SaveData:42: Directory X:\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[   5.621215] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory X:\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[   5.621596] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:194: path exists X:\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[   5.621682] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory X:\Citra/user/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[   5.621861] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:194: path exists X:\Citra/user/nand/data/00000000000000000000000000000000/extdata/
[   5.622170] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Init:511: Unable to load shared font: X:\Citra/user/sysdata/shared_font.bin
[   5.622723] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:490: GL_VERSION: 3.3.0 NVIDIA 364.51
[   5.622795] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:491: GL_VENDOR: NVIDIA Corporation
[   5.622859] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:492: GL_RENDERER: GeForce GTX 750 Ti/PCIe/SSE2
[   5.626818] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file D:/Games/Nintendo/3DS/Games/Bravely Default.3ds as NCSD...
[   5.627185] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:246: Only loading the first (bootable) NCCH within the NCSD file!
[   5.627464] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:270: Name:                        HikariTr
[   5.627552] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:271: Program ID:                  00040000000FC600
[   5.649675] Loader <Info> core\hle\kernel\process.cpp:Kernel::Process::ParseKernelCaps:99: ExHeader kernel version: 2.32
[   5.844532] Service.SRV <Warning> core\hle\service\srv.cpp:SRV::RegisterClient:38: (STUBBED) called
[   5.845073] Service.SRV <Warning> core\hle\service\srv.cpp:SRV::EnableNotification:62: (STUBBED) called
[   5.846739] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:120: (STUBBED) called handle=0x00030008 applet_attributes=0x00000000
[   5.849064] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::OverrideDefaultDaemons:201: (STUBBED) default_daemon_bit_mask=0x0000000F
[   5.849466] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::SuspendDaemons:87: (STUBBED) daemon_bit_mask=0x00000009
[   5.851383] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:74: unknown / unimplemented function 'SetClientSdkVersion': port=frd:u, cmd_buff[1]=0x40205C8, cmd_buff[2]=0x20, cmd_buff[3]=0x58011
[   5.851906] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::GetMyPresence:29: (STUBBED) called
[   5.852499] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Enable:128: (STUBBED) called attributes=0x00000000
[   5.853513] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:247: called app_id=0x00000300, buffer_size=0x00001000
[   5.854290] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:102: (STUBBED) app_id=768
[   5.855214] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:224: called app_id=0x00000300, buffer_size=0x00001000
[   5.856292] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF00, buffer2_addr=0x0FFFFECC
[   5.856618] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFEC8, buffer2_addr=0x0FFFFECC
[   5.857190] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetAppCpuTimeLimit:332: (STUBBED) called cpu_percent=20, value=1
[   5.857573] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:782: (STUBBED) called unk1=0x040205C8, unk2=0x00000020, unk3=0x00060019
[   5.879503] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::AcquireRight:690: called
[   5.880098] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::RegisterInterruptRelayQueue:386: called, flags=0x00000001
[   5.882528] HW.GPU <Critical> core\hw\gpu.cpp:GPU::MemoryFill:89: invalid start address 0x00000000
[   5.882736] HW.GPU <Critical> core\hw\gpu.cpp:GPU::MemoryFill:89: invalid start address 0x00000000
[   5.915053] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF68, buffer2_addr=0x0FFFFF6C
[   5.983704] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:DSP_DSP::LoadComponent:144: Firmware hash: 0xc4673b93fcea5419
[   5.984455] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:DSP_DSP::LoadComponent:148: Structures hash: 0x93e48663943cad39
[   5.984777] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::LoadComponent:152: (STUBBED) called size=0xC234, prog_mask=0x505300FF, data_mask=0x000F00FF, buffer=0x00664E14
[   5.985429] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:DSP_DSP::RegisterInterruptEvents:243: Registered type=2, pipe=2, event_handle=0x000F802E
[   5.985757] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::GetSemaphoreEventHandle:169: (STUBBED) called
[   5.986047] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphoreMask:448: (STUBBED) called mask=0x00002000
[   5.986419] Audio.DSP <Info> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:134: Application has requested initialization of DSP hardware
[   5.986673] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphore:266: (STUBBED) called
[   5.987732] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphore:266: (STUBBED) called
[   5.995446] Kernel.SVC <Warning> core\hle\svc.cpp:SVC::CreateThread:529: Newly created thread is allowed to be run in the SysCore, unimplemented.
[   6.019387] Service.CECD <Warning> core\hle\service\cecd\cecd.cpp:Service::CECD::GetCecInfoEventHandle:33: (STUBBED) called
[   6.044810] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::IsDirectory:116: stat failed on X:\Citra/user/nand/data/00000000000000000000000000000000/extdata/00000000/F000000B/user//ubll.lst: The system cannot find the file specified.

[   6.045617] Service.FS <Error> core\file_sys\disk_archive.cpp:FileSys::DiskFile::Open:129: Non-existing file X:\Citra/user/nand/data/00000000000000000000000000000000/extdata/00000000/F000000B/user//ubll.lst can't be open without mode create.
[   6.045984] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFile:76: failed to get a handle for file [Wchar: /ubll.lst]
[   6.047769] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:123: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 020201009b00040000ffffff02000000]
[   6.048679] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:107: Fatal error!
[   6.048787] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:114: PID: 0x00000000_0x00000000
[   6.048988] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:115: REV: 50249
[   6.049165] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:116: AID: 0x00000000_0x00000000
[   6.049358] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:117: ADR: 0x0013CA04
[   6.049551] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:119: RSL: 0xFFFFFFFF
[   6.049734] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:120:   Level: 31
[   6.049907] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:121:   Summary: 63
[   6.050080] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:122:   Module: 255
[   6.050263] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:123:   Desc: 1023
```

I remember trying recently(this month)the nightly and bleading engle and those games were working so it must be some recent change

**Comment by wwylele** [comment] 2016-10-15 12:41
> [   6.047769] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:123: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 020201009b00040000ffffff02000000]

dump your home folder.

**Comment by JayFoxRox** [comment] 2016-10-15 12:41
There is no support for bleeding edge - Only report issues on nightly builds.

Please bisect the issue and figure out which nightly build was the first broken one.
If you know why / where it stopped working open a new issue. This one is tainted with all the bleeding-edge info.

However, to me, it looks like you are simply missing the home folder dump.
Also check if this issue has been reported before.

---

Closed as invalid.

**Closed** 2016-10-15 12:41 UTC

**Comment by vsub** [comment] 2016-10-15 13:24
I mention bleeding edge because that's the only thing I can use to try older versions because I can't compile citra.

And as I said,both games were working before while using the nightly builds downloaded from the official page.

The games worked before but I didn't use the nightly/bleeding edge just because the Large Screen feature was not added till now(at least on the bleeding edge)

And just as info,I already cleared the whole game(Bravely Default...81 hours)and I'm 2 hours playtime already on Bravely Second while using some gcc mingw version from 8 September.

If there is some kind of archive that keeps old nightly builds,I can find the problematic rev.

**Comment by wwylele** [comment] 2016-10-15 13:31
@vsub The problem is that you didn't put the system archives from 3DS to citra's home folder. As you said old nightly builds work, I assume that you dumped those files before, and forgot to move them to the new build. I admit that bleeding edge installer hides that perfectly, but you still need to do it.

Anyway, this is not a support forum.

**Comment by JayFoxRox** [comment] 2016-10-15 15:34
FTR: [Archived builds](https://builds.citra-emu.org/citra/nightly/)
