### ISSUE TITLE
Tomodachi Life - Freeze after resetting save data

### ISSUE THREAD

**Issue by Fredabill** [citra-emu/citra#1148] opened 2015-09-11 19:30 UTC
Says SD Card Save is corrupted, after resetting, the message box disappears and it freezes...

Last important part of log before freezing:
```
SCROLL DOWN TWO COMMENTS FOR CORRECT LOG
```

**Comment by Subv** [comment] 2015-09-12 16:38
Huh, archive id 0x567890B4, 3dbrew says "SaveData from Demo Version of Retail Game " that's interesting.

**Comment by Fredabill** [comment] 2015-09-13 00:13
Darn, just realized I uploaded the wrong output log...
That must be the log for a different game.
Gonna have to fix that in a minute...

**Comment by Fredabill** [comment] 2015-09-13 00:17
Correct Log:
[  76.515206] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A24E0
[  76.518206] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A3108
[  76.521229] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A3D30
[  76.525207] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A4958
[  76.529285] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A5580
[  76.532387] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A61A8
[  76.536312] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A6DD0
[  76.540309] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A79F8
[  76.544312] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A8620
[  76.547310] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A9248
[  76.550310] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88A9E70
[  76.554309] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88AAA98
[  76.557312] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88AB6C0
[  76.560310] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88AC2E8
[  76.564313] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88ACF10
[  76.567314] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88ADB38
[  76.571314] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88AE760
[  76.575310] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88AF388
[  76.578311] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88AFFB0
[  76.581311] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88B0BD8
[  76.584311] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88B1800
[  76.588312] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88B2428
[  76.593315] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88B3050
[  76.596385] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x88B3C78
[  76.632313] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89ECD80
[  76.635318] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89ED980
[  76.639178] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89EE580
[  76.643178] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89EF180
[  76.646256] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89EFD80
[  76.649257] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F0980
[  76.652256] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F1580
[  76.656180] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F2180
[  76.659183] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F2D80
[  76.663180] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F3980
[  76.665179] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F4580
[  76.668180] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F5180
[  76.672183] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F5D80
[  76.678212] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F6980
[  76.681180] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F7580
[  76.684181] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F8180
[  76.686183] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F8D80
[  76.690182] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89F9980
[  76.693181] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89FA580
[  76.695181] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89FB180
[  76.698181] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89FBD80
[  76.701001] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89FC980
[  76.704999] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89FD580
[  76.709001] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89FE180
[  76.712000] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89FED80
[  76.714028] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x89FF980
[  76.717071] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A00580
[  76.721998] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A01180
[  76.726088] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A01D80
[  76.729998] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A02980
[  76.732998] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A03580
[  76.734998] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A04180
[  76.738002] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A04D80
[  76.741003] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A05980
[  76.745002] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A06580
[  76.748078] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A07180
[  76.751022] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A07D80
[  76.754004] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A08980
[  76.757003] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A09580
[  76.760004] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A0A180
[  76.763003] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A0AD80
[  76.765000] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A0B980
[  76.768000] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A0C580
[  76.771005] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A0D180
[  76.775001] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A0DD80
[  76.778001] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A0E980
[  76.781004] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A0F580
[  76.783001] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A10180
[  76.787031] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A10D80
[  76.791007] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:68: unknown / unimplemented function '0x00460104': port=APT:A, cmd_bu
ff[1]=0x70, cmd_buff[2]=0x60, cmd_buff[3]=0xC, cmd_buff[4]=0xA, cmd_buff[5]=0x60
A, cmd_buff[6]=0xFFFF998, cmd_buff[7]=0x70C, cmd_buff[8]=0x8A11980
[  77.136886] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::Op
enArchive:389: failed to get a handle for archive archive_id=0x00000006 archive_
path=[Binary: 01000000c308000000000000]

**Comment by InusualZ** [comment] 2015-09-13 23:05
Please paste the log on pastebin or similar site

**Comment by oblivss** [comment] 2015-10-31 19:22
Wait -- Tomodachi Life works on Citra? All the ROMs I've tried don't work. Where did you get yours?

**Comment by Subv** [comment] 2015-12-28 15:22
This seems to be a duplicate of #1278

**Closed by Subv** 2015-12-28 15:22 UTC
