### ISSUE TITLE
Pokemon Ruby can't run on OSX system

### ISSUE THREAD

**Issue by JWDei** [citra-emu/citra#4592] opened 2019-01-22 06:15 UTC
I tried to run Pokemon Ruby, but I always prompt "Shared fonts is missing. Please dump your system archives. Continuing emulation may result in crashes and bugs.", I don't know how to fix it.

**Comment by JWDei** [comment] 2019-01-22 06:44
> 你根本没有提供太多信息。
> 
> 尝试在我们的网站上升级到最新版本的Citra。如果问题仍然存在，
> 请向我们展示问题的完整截图，以及OSX的哪个版本等
My Citra is the latest version, and here are the screenshots

![image](https://user-images.githubusercontent.com/45089101/51516888-dff4ec00-1e53-11e9-99b9-7b1c2dcafe77.png)

![image](https://user-images.githubusercontent.com/45089101/51516900-eaaf8100-1e53-11e9-9d19-ce1b7b1b36f3.png)

![image](https://user-images.githubusercontent.com/45089101/51516974-33ffd080-1e54-11e9-8556-d0fa7e95cd23.png)

![image](https://user-images.githubusercontent.com/45089101/51516916-fb5ff700-1e53-11e9-97c8-3ed8aedcd361.png)

**Comment by FearlessTobi** [comment] 2019-01-22 22:07
Well, did you try to actually dump your shared fonts from the 3ds?

**Comment by zhaowenlan1779** [comment] 2019-01-23 14:38
Closing this as (a) this seems to be caused by not dumping the fonts and (b) the issue tracker is not a support forum, use our [forums](https://community.citra-emu.org) or [discord](https://citra-emu.org/discord) instead.

**Closed by zhaowenlan1779** 2019-01-23 14:38 UTC
