### ISSUE TITLE
Pokemon Mystery Dungeon Gates to Infinity - soft lock in the first cutscene

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#1713] opened 2016-04-24 15:33 UTC
Separated from #1472 as suggest.
The game is soft locked at this point  (after choosing pokemon)
![pokemon](https://cloud.githubusercontent.com/assets/4592895/13608215/6e8b48f8-e55c-11e5-8ab5-63fd24512c14.PNG)
objects are still moving. no new logs shows up.
On real console there should be a flash effect and the cutscene goes on itself.

[Full log](http://pastebin.com/2xxZh9Ps) <- this log is an old one. On current master the game shows more "GetPointer"-like error early in the cutscene, but still no more log near the lock

**Comment by RavenHome1** [comment] 2016-04-24 18:46
pretty sure it's a duplicate of an issue buried down deep with the other hundreds of issues open, i can't get to it at the moment but i am pretty sure someone reported this before

**Comment by MerryMage** [comment] 2016-04-24 18:51
@RavenHome1 You were probably thinking about when it was a comment on #1472

**Comment by RavenHome1** [comment] 2016-04-24 19:17
@MerryMage yes that is the one

**Comment by JohnGodgames** [comment] 2016-04-25 11:52
I think that it also related to https://github.com/citra-emu/citra/issues/1484

**Comment by emmauss** [comment] 2016-04-29 07:03
can you test this and all other similar freezes with #1730 .it may have fixed them

**Comment by wwylele** [comment] 2016-04-29 07:18
@emmauss #1730 doesn't help Pokemon

**Comment by hrydgard** [comment] 2016-04-29 09:05
@wwylele  it's not expected to help, that's just a minor cleanup and performance improvement

**Comment by wwylele** [comment] 2016-04-29 09:54
@MerryMage's audio branch + pipe3 branch fixes this! :smile: Now just wait for their PR

**Closed** 2016-05-04 14:22 UTC
Labels: audio, unimplemented
