### ISSUE TITLE
[Feature Request] Search memory and replace values

### ISSUE THREAD

**Issue by jknut** [citra-emu/citra#5370] opened 2020-05-27 14:00 UTC
Request option to search Citra memory for value then write over it.  Similar to a built-in Cheat Engine.

This unofficial Android fork had a working built-in memory search/write:
https://github.com/weihuoya/citra

**Comment by BreadFish64** [comment] 2020-05-27 14:44
Duplicate of #504

**Closed by BreadFish64** 2020-05-27 14:44 UTC
