### ISSUE TITLE
(Feature Request) play with 2 monitors at a time

### ISSUE THREAD

**Issue by JuanchoES** [citra-emu/citra#5803] opened 2021-06-21 21:25 UTC
There are guides to how to do this like this one https://community.citra-emu.org/t/multi-monitor-full-screen-tutorial-citra/358898

But i want an option like "2 monitor mode" on citra, it would be awesome!

**Comment by JohelEGP** [comment] 2021-06-21 21:28
This is #204.

**Comment by zhaowenlan1779** [comment] 2021-06-22 00:04
Duplicate of #204.

**Closed by zhaowenlan1779** 2021-06-22 00:04 UTC
