### ISSUE TITLE
[Android] Launching a game causes Citra to crash

### ISSUE THREAD

**Issue by Someguy1519** [citra-emu/citra#7279] opened 2023-12-22 22:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2724

### Description of Issue

Launching a game on Citra causes Citra to crash on the aforementioned build on Android

### Expected Behavior

Citra doesn't crash when launching a game

### Reproduction Steps

Be on Canary 2724 on Android.

Try to launch a game (doesn't matter if it's on OpenGL or Vulkan)

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13757039/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/13757041/citra_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 8 Gen 1
GPU/Driver: Adreno 730 (both stock and Turnip drivers)
RAM: 8GB
OS: Android 14
Device: Galaxy S22+

**Comment by Looped312** [comment] 2023-12-23 02:49
This is also a problem for me in citra 2725

**Comment by Siber009** [comment] 2023-12-23 04:04
I have this problem on canary 2724/2725 
Andriod 14 
SD 8 gen 2

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/13757933/citra_log.txt.old.txt)
[citra_log.txt](https://github.com/citra-emu/citra/files/13757934/citra_log.txt)

**Comment by Angstdiscord** [comment] 2023-12-23 06:57
This is also broken for me as well.

**Comment by FearlessTobi** [comment] 2023-12-23 07:42
Does it work on Nightly?
Can you find out the last Canary where it was working?

**Comment by Angstdiscord** [comment] 2023-12-23 07:50
> Does it work on Nightly? Can you find out the last Canary where it was working?

https://github.com/citra-emu/citra/pull/7272

Pretty sure it's this.

Nightly works, just canary isn't working.

**Comment by GPUCode** [comment] 2023-12-23 10:20
Found the cause and this will be fixed in next canary

**Closed by GPUCode** 2023-12-23 10:20 UTC
