### ISSUE TITLE
Qt errors on startup

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#449] opened 2015-01-08 23:15 UTC
```
QObject::connect: Cannot connect (null)::screenChanged(QScreen*) to GRenderWindow::OnFramebufferSizeChanged()
QObject::connect: No such slot GraphicsFramebufferWidget::OnFramebufferWidthChanged(int) in ..\..\..\src\citra_qt\debugger\graphics_framebuffer.cpp:87
QObject::connect:  (receiver name: 'PicaFramebuffer')
QObject::connect: No such slot GraphicsFramebufferWidget::OnFramebufferHeightChanged(int) in ..\..\..\src\citra_qt\debugger\graphics_framebuffer.cpp:88 
QObject::connect:  (receiver name: 'PicaFramebuffer')
```
They've been happening for a while, I'm not sure when it started

**Comment by Subv** [comment] 2015-01-08 23:35
@neobrain

**Comment by purpasmart96** [comment] 2015-01-09 02:41
Same here.

**Comment by tgharib** [comment] 2015-02-11 02:23
Someone fixed the other Qt errors except this one:

`QObject::connect: Cannot connect (null)::screenChanged(QScreen*) to GRenderWindow::OnFramebufferSizeChanged()`

It is caused by commit 40acd63631eeaca248b2393cde399714a730214f on Nov 18. It is caused by this line: `connect(this->windowHandle(), SIGNAL(screenChanged(QScreen*)), this, SLOT(OnFramebufferSizeChanged()));` in src/citra_qt/bootmanager.cpp. It seems that the issue is that this->windowHandle() is equal to 0.

**Comment by neobrain** [comment] 2015-06-21 21:18
This was fixed in PR #671, but that branch was never finished.

**Comment by TheOddler** [comment] 2015-09-01 18:20
I get this bug too. Seems like an old problem, was it never fixed?

**Closed** 2015-09-22 01:16 UTC
Labels: bug, frontend
