### ISSUE TITLE
Pokemon Mystery Dungeon hangs in citra 6436d10 and latest citra which requires msvp120 is not working

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#1489] opened 2016-03-10 10:10 UTC
I found that Pokemon Mystery Dungeon has started working in citra 6436d10  but when i tried i found the game failed to execute after this point. I have tried 3-4 times.
![capture](https://cloud.githubusercontent.com/assets/14974622/13666074/a93c3f46-e6d5-11e5-829d-cbd4678023d3.PNG)

It should look like this - https://www.youtube.com/watch?v=nE0rSb_WRMk

and secondly the latest citra shows error
![capture](https://cloud.githubusercontent.com/assets/14974622/13666161/1d145430-e6d6-11e5-8618-558fb6efd20c.PNG)

**Comment by wwylele** [comment] 2016-03-10 10:17
duplicate of #1472

**Closed** 2016-03-10 15:47 UTC
