### ISSUE TITLE
Nightly #977 | HEAD-687e3e7 (2018-09-20): Pokemon X/Y/Omega Ruby problems

### ISSUE THREAD

**Issue by WellBeSerious** [citra-emu/citra#4236] opened 2018-09-20 08:24 UTC
- **Problem**:
I just updated on 2018-09-20 to **Nightly #977 | HEAD-687e3e7**, and now certain Pokemon games won't go past the menu. The problem games currently tested are X, Y, and Omega Ruby. Yes, **X/Y** couldn't enter the game after entering your name, but at least it got that far and now only shows Asian text and buttons don't work. Updating to **1.5** didn't do anything. Now with **Omega Ruby**, it's the same (although its counterpart Alpha Sapphire WORKS PERFECTLY, BUT maybe already having a game save SKIPPED that problem?). Updating this one to **1.4** didn't help.

- **Screenshots**:
X: https://drive.google.com/open?id=1H0niVYhCR5ro2eAx9TtiWHijmJ31E-CD
Y (looks the same as X): https://drive.google.com/open?id=1Z_JYWm7nfU29ZRbsmMn785ATXZYwweBH
Omega Ruby: https://drive.google.com/open?id=1RwnXJc0BFde_WUfBO3OopT80-WFQqqVo
Omega Ruby 1.4: https://drive.google.com/open?id=1vMQJI78iCui3EW0WPEoqEmlvXXhB-eTt
Alpha Sapphire 1.4 (without save): https://drive.google.com/open?id=1DyErAxuWXxu0MB2U6aMDmTknpBDBmcWL
Alpha Sapphire 1.4 (with save): https://drive.google.com/open?id=1YnSK4KP8Bai3yuQv_cs3Z_BhvtKXpqxt

- **Hardware**: GIGABYTE GA-AB350M-Gaming 3 (Rev. 1.0), AMD Ryzen 7 1700X @3.89GHz, 16GB (2 x 8GB) DDR4 3200MHz, HIS/AMD Radeon R9 290 4GB GDDR5, Samsung SM953 Series MZ-1WV4800 480GB M.2 SSD (OS/apps), 4TB HDD (roms/installed on), 2TB HDD (PC games).

- **Logs**:
Roms closed: https://drive.google.com/open?id=1dEVt-9iJTuXI5PuaCLX8742C50ozVBAs
X: https://drive.google.com/open?id=1geIQr_CF0xL-WmMGgEHotvOLIbuIFAFx
Y: https://drive.google.com/open?id=18jbN-zdQl-bfBERqisxPNbTYeTNP0tin
Omega Ruby: https://drive.google.com/open?id=1lwT9jS2D-krhrNWKalJWy47-1pu5fetP

- **Game Save**:
Alpha Sapphire (X/Y/Omega Ruby have no saves): https://drive.google.com/open?id=10p_8kIxqdCGlRvJQag8W9XGgFqpu46DW

**Comment by wwylele** [comment] 2018-09-20 15:18
I can't really reproduce this on a clean citra without game save. Did you copy-pasted user folder from somewhere?

**Comment by WellBeSerious** [comment] 2018-09-20 20:44
https://drive.google.com/open?id=1dEVt-9iJTuXI5PuaCLX8742C50ozVBAs

**Comment by WellBeSerious** [comment] 2018-09-20 21:10
The problem has something to do with not having save games. I added screenshots from Alpha Sapphire with and without a game save. It exhibits the same issue without a save, and no issue with the save.

**Comment by wwylele** [comment] 2018-09-20 21:43
Does it help if you remove the entire sdmc folder? (Back it up if you have important game save)

**Comment by WellBeSerious** [comment] 2018-09-21 02:39
That solved the problem! But Pokemon X/Y still have no music in the intro, only the 'chirp/beep' sounds, and doesn't start after entering your name (yes I know, separate posted issue). All 8 main 3DS Pokemon games were tested and work how they used to.

**Comment by wwylele** [comment] 2018-09-21 03:38
I am closing this issue as this is likely caused by some unusual operation (for example iirc deleting the `main` file without deleting the folder would cause this)

**Closed by wwylele** 2018-09-21 03:38 UTC
