### ISSUE TITLE
Devil Survivor Overclocked fails to load on latest versions

### ISSUE THREAD

**Issue by viocar** [citra-emu/citra#3330] opened 2017-12-28 01:37 UTC
Devil Survivor Overclocked (US version - other versions untested) currently hangs during the intro cutscene on Canary 291/Nightly 510. The music plays and loops, but the video never begins and the game does not accept controller input until the video loads. I don't know of any workarounds. However, as late as Canary 156/Nightly 427, this issue could be worked around by letting the intro music loop roughly twice. The video would eventually load around that time, and you can skip to the title screen. The current issue began in the versions following Canary 157/Nightly 428 and has not been resolved as of Nightly 510.

**Comment by wwylele** [comment] 2017-12-28 09:20
For whoever is wondering, the new commit in Nightly 428 is e9a95b2 (#3119, CoreTiming: Reworked CoreTiming). However, I think this is more like revealing a hidden bug by the core timing revision instead of a regression.

**Comment by viocar** [comment] 2017-12-28 20:42
Yes, that is most likely. It never really "worked" before 428 either - here's a video of its behaviour pre-428:

https://www.youtube.com/watch?v=uondua33BsY

The intro video comes up shortly after the third loop of the intro music plays (though I think this is just coincidence - the video is supposed to start playing in sync with the music, but it's a little late here). I then skip the video by pressing a key and go to the title screen, allowing me to play the game. After 428, the video never loads no matter how long I wait (I waited like 40 loops with frame limiting off - it never showed up), and since the video doesn't show up, I can't skip the intro, rendering the game unplayable.

**Comment by ahmedulkavi** [comment] 2018-10-27 05:02
I really want to play this game. Can somebody please give me the link to download nightly 427/canary 156?
I can't find the link anywhere. Your help is appreciated... thank you.

**Comment by benderscruffy** [comment] 2019-01-03 04:16
this is a duplicate of #2436 
this can be closed

**Comment by viocar** [comment] 2019-01-03 04:18
It's mostly the same - you could get past the title screen back when that was posted, but you can no longer do so as per the version in my OP.

**Comment by YuutaDFM** [comment] 2019-04-22 02:11
The game works correctly in HEAD-f4884d6

**Comment by HintonR** [comment] 2019-04-22 14:49
> The game works correctly in HEAD-f4884d6

Can you state which nightly or canary? As far as Nightly 1252 HEAD-2706a4d - It is still not running properly. As stated above, the last known working build was 427. Also does the game run straight after the first intro, or does it still have to loop twice before loading the video?

**Comment by YuutaDFM** [comment] 2019-04-23 21:21
1.- I think my version is not completely official, because it does not show me if it's Nighltly or Canary, when I see the version in "About Citra" it only shows me what I said before (If there is another way to know it, and they tell me, I'll be happy to be specific in which version I use), anyway, I attach a screenshot of the test.

2.- The game starts without any problem, I do not completely understand what you mean when you talk about "Loop"

![Sin título](https://user-images.githubusercontent.com/49850178/56616293-08bf8580-65eb-11e9-8073-c35b671fe6e2.png)

**Comment by viocar** [comment] 2019-04-23 22:35
Did you get your copy from either https://citra-emu.org/, https://github.com/citra-emu/citra-canary/releases, or https://github.com/citra-emu/citra-nightly/releases?

**Comment by YuutaDFM** [comment] 2019-04-24 02:14
I would say none of the above, it will sound simple, but frankly I took it from a YouTube video xD

**Comment by flyyngkds** [comment] 2019-12-25 21:16
The intro video plays if my "CPU Clock Speed" is at 55% or below as a workaround.

**Comment by viocar** [comment] 2019-12-25 21:23
> 
> 
> The intro video plays if my "CPU Clock Speed" is at 55% or below as a workaround.

Can confirm that this works. Even if you start the intro with clock speed over 55%, as soon as you lower it to that level or lower, the video will start playing.

**Comment by vitor-k** [comment] 2020-05-12 21:55
Can you test this on latest Nightly now that #5257 is merged?
A user on discord reported that it might have been fixed by it, without having to change the CPU slider or letting it loop. (Could still be some other change on Canary, but this one is the more likely one)

**Comment by benderscruffy** [comment] 2020-05-13 00:41
yep goes ingame now in the nightly
can be closed

**Closed** 2020-05-13 02:06 UTC
