### ISSUE TITLE
Problem with Colours in Some games (Actually Fantasy Life)

### ISSUE THREAD

**Issue by XiNaru** [citra-emu/citra#6365] opened 2023-03-22 12:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1860 AND Canary 2426

### Description of Issue

https://i.imgur.com/wIm3AZb.png

Same with Hair and Eye Color
So i cant see what color is in the game
And: Hair and Taint color was changed and i see on the CHARAKTER
but eye color i dont see completly. Not in the color change section and not on the charakter too.

And: Sry i dont find the Console from Citra for a log.

### Expected Behavior

is expected that I:
1. directly see which color I would choose when choosing a color.
2. at the character the eye color is also adapted accordingly.

### Reproduction Steps

Simple start new game...

### Log File

sry i dont find the log

### System Configuration

CPU: AMD Ryzen 7 5800X
GPU/Driver: Raedon RX 580 with newest Graphics Driver
RAM: 64GB DDR4 Ram
OS: Windows 10

**Comment by sakuramipha** [comment] 2023-03-22 13:04
Duplicate of #3654

**Closed** 2023-03-22 14:24 UTC
