### ISSUE TITLE
Donkey Kong Country Returns 3D

### ISSUE THREAD

**Issue by NekokoTime** [citra-emu/citra#3815] opened 2018-06-05 20:38 UTC
Citra Canary 
Donkey Kong Country Returns 3D
[  17.164953] Kernel.SVC <Error> core/hle/kernel/svc.cpp:CreateThread:752: Newly created thread must run in the SysCore (Core1), unimplemented.
![anotacao 13](https://user-images.githubusercontent.com/38867013/41001424-39317e3c-68e7-11e8-84d0-d0415a20b49e.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/2073904/citra_log.txt)

**Comment by FearlessTobi** [comment] 2018-06-05 20:39
Duplicate of https://github.com/citra-emu/citra/issues/2599. 

Requesting to close.

**Closed** 2018-06-05 20:40 UTC
