### ISSUE TITLE
Mystery Dungeon Super Blackscreen

### ISSUE THREAD

**Issue by Kokujou** [citra-emu/citra#2107] opened 2016-10-02 15:50 UTC
Version: 16.09.2016
The game goes to blackscreen right after starting a new game and after you "loaded your power" with touching the screen. Switching to Software Renderer, VSync and all other options didn't help.
i guess you all know how a blackscreen looks.
In the command line no bigger errors just lots of warnings (usual)

**Comment by JayFoxRox** [comment] 2016-10-02 21:10
That's not how a version number should look like. The log probably contains some valuable information still, we don't know how the menu looks by heart, so a video or screenshots just before it crashes would be helpful.

---

Closed as invalid.

**Closed by JayFoxRox** 2016-10-02 21:10 UTC

**Comment by Kokujou** [comment] 2016-10-02 21:58
of course i just don't know where to find the version number. i looked up other issues and they didn't provide anything. so i guessed i should at least name the date ^_^
![unbenannt](https://cloud.githubusercontent.com/assets/13001250/19024034/f46efb5c-88fb-11e6-88f3-814263e3c015.png)
as i said just start the game there is no way you can miss it. no choices. there's just a part where you have to press at the bottom screen and right after this is done it freezes.

**Comment by wwylele** [comment] 2016-10-02 23:49
dupe of #1832

**Comment by Kokujou** [comment] 2016-10-03 08:12
oh, sorry! didn't know it was already posted.
