### ISSUE TITLE
Pokemon X - Buttons on touch screen not appearing

### ISSUE THREAD

**Issue by Mayoniez** [citra-emu/citra#2084] opened 2016-09-16 10:33 UTC
When i opened Pokemon X's clothing customization session the buttons to go back and confirm the changes are not apparent. This problem is not only experienced by me alone but has been reproduced by other users.

![issue](https://cloud.githubusercontent.com/assets/22235580/18583234/e62984c6-7c3b-11e6-85fc-d0622c8481cc.png)

The area inside the red circle is where those buttons supposed to be, as you can see they are not there.

Please help!

**Comment by JayFoxRox** [comment] 2016-12-03 03:11
Does this work without hw-rendering or without the CPU or Shader jit?

**Comment by Dragios** [comment] 2016-12-04 09:54
Tested again on the latest commit 4f0f88b but shows no improvement.
Toggled all settings, *Hardware renderer*, *Shader JIT* & *CPU JIT* does not make any difference.

**Comment by JayFoxRox** [comment] 2016-12-10 17:16
This is not related to geometry shaders by any chance? What's does the full log say with a master build?

**Comment by Dragios** [comment] 2016-12-11 04:31
Nope, not related at all.
Full log based on commit 42edd7911e4924560b44001acca7ac4442f254e9
http://pastebin.com/z1YeiKTS

**Comment by JayFoxRox** [comment] 2016-12-11 05:21
yes it probably is.

```
[  34.387085] HW.GPU <Critical> video_core\shader\shader_jit_x64.cpp:Pica::Shader::JitShader::Compile_NextInstr:799: Unhandled instruction: 0x2b (0xacc00000)
[  34.387675] HW.GPU <Critical> video_core\shader\shader_jit_x64.cpp:Pica::Shader::JitShader::Compile_NextInstr:799: Unhandled instruction: 0x2a (0xa8000000)
```

0x2A and 0x2B are the 2 geometry shader instructions

**Comment by Dragios** [comment] 2016-12-11 05:29
I have tested it with your geometry shader branch and the issue is still there and does not show the above log. Unless something else is still not implemented in your GS branch.

`Render.OpenGL <Error> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:482: API ERROR 1282: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.`

**Comment by JayFoxRox** [comment] 2016-12-11 05:31
Note that my GS branch is still not fully functional. Someone should verify what the shaders / states are during the rendering of these sprites. It's also usually a good idea to manually disable depth testing / alpha testing / alpha blending etc to see if the vertex data is correct.

**Comment by ShinobiAtlas** [comment] 2017-11-03 07:43
It does not let you also enter into the pokemon world

**Comment by Subv** [comment] 2017-11-04 14:48
Does this still happen?

**Comment by Dragios** [comment] 2017-11-04 15:37
Unfortunately, it still happens.

**Comment by Dragios** [comment] 2017-11-04 15:37
Unfortunately, it still happens.

**Comment by YOUDONTSAYMEMEWILLBEMINE** [comment] 2017-11-22 16:23
I'm willing to bet this is the issue with battles.

**Comment by Dragios** [comment] 2018-12-13 13:50
This is fix with DSP LLE. #4490

**Comment by wwylele** [comment] 2019-01-11 15:47
DSP LLE is merged. Please continue to track this issue on while we fix DSP HLE.

**Comment by takeshineale128** [comment] 2019-01-11 18:55
This has been fixed works on the latest canary build 1156 with the HLE ACC decoder installed

**Closed** 2020-03-18 05:06 UTC
Labels: A-graphics, has-games-wiki-entry
