### ISSUE TITLE
citra-qt : widgets glitch

### ISSUE THREAD

**Issue by Lectem** [citra-emu/citra#925] opened 2015-07-13 20:11 UTC
If no game is loading and you resize the window, you will get the following glitch : 
![citra-qt-glitch](https://cloud.githubusercontent.com/assets/6024225/8659544/f322f8f8-29ab-11e5-80e6-4013750dbd81.png)
Probably has something to do with the repaint/resize events handling.

**Comment by neobrain** [comment] 2015-07-13 20:16
Probably a duplicate of #174 .

**Comment by Lectem** [comment] 2015-07-13 20:28
Confirmed duplicate of #174 and fixed by https://github.com/citra-emu/citra/pull/827

**Closed** 2015-07-13 20:42 UTC
