### ISSUE TITLE
Mario & Luigi Paper Jam Opening event Game crash

### ISSUE THREAD

**Issue by zaranrapu** [citra-emu/citra#2598] opened 2017-02-25 23:14 UTC
Used nightly-81 Citra.
Error log
`[  25.123782] Render.OpenGL <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::AppendSource:86: Unknown source op 6
[  25.164501] Debug <Critical> video_core\renderer_opengl\gl_shader_util.cpp:GLShader::LoadProgram::<lambda_266eea3411ef3ed2b6bce9f64306f4d5>::operator ():91: Assertion Failed!
Shader not linked`
![snapcrab_noname_2017-2-26_8-6-59_no-00](https://cloud.githubusercontent.com/assets/11900318/23335539/ae6f33fc-fbfa-11e6-9590-284a570019c5.png)

win10 x64
 i7 6700
 GTX 1080

**Comment by wwylele** [comment] 2017-02-27 14:38
Please provide a full log. Also probably a duplicate of #2213

**Comment by zaranrapu** [comment] 2017-02-28 10:43
bleeding edge 234 log.
http://pastebin.com/uDCTMYSy

**Comment by mailwl** [comment] 2017-02-28 11:19
```
uniform sampler2D tex[3];
...
void main() {
...
    vec3 surface_normal = 2.0 * texture(tex[3], texcoord[3]).rgb - 1.0;
```

out of bound

**Comment by wwylele** [comment] 2017-02-28 11:22
dupe of #2213

**Closed by wwylele** 2017-02-28 11:22 UTC
