### ISSUE TITLE
it is not possible to install citra via flatpak

### ISSUE THREAD

**Issue by isaacx01** [citra-emu/citra#5591] opened 2020-10-30 14:34 UTC
erro: Não foi possível carregar resumo do remoto citra-nightly-origin: Signature made ter 20 out 2020 19:41:50 using RSA key ID F8B088B90782CA9B
BAD signature from " <citra@citra-emu.org>"
Key expired dom 25 out 2020 22:12:42

**Comment by FearlessTobi** [comment] 2020-10-31 03:17
Duplicate of https://github.com/citra-emu/citra/issues/5588.
We are looking into solving the issue.

**Closed by FearlessTobi** 2020-10-31 03:17 UTC
