### ISSUE TITLE
Custom Textures: Missing Features

### ISSUE THREAD

**Issue by khang06** [citra-emu/citra#4997] opened 2019-11-10 16:38 UTC
now that #4868 has been merged, i think it would be helpful to have a list of features that didn't make it into the initial pr

- [ ] proper mipmap support
the original pr just takes the highest lod texture and generates mipmaps based on that. this definitely has a lot of flaws.
something that could be done is having a separate mipmaps file that details the corresponding mipmaps for each texture to avoid breaking current texture packs, but i'm not sure how the format should look like

- [ ] better texture pack verification
it would be nice to have a gui option to verify a texture pack beforehand instead of having to go in-game to see if the textures actually applied

- [ ] dds support
better compression, what more can i say?

- [ ] custom texture cache limits
the current cache implementation just has each texture stay in memory indefinitely after being loaded once, even if preload is disabled. implementing a proper configurable lfu cache would probably help out people with low memory/phones

- [ ] opengl es support
custom textures were never actually tested on opengl es, so there's no handling for any byteswapping that might need to happen

- [ ] texture preload progress on gui
definitely not high priority, but might be nice to have for eventual large texture packs

**Comment by RocketRobz** [comment] 2019-11-10 20:51
What about fixing the "normal small texture over custom larger texture" bug?
Maybe that didn't work correctly for some games, but if you plan to use the same code, could that be an option?

**Comment by khang06** [comment] 2019-11-11 17:43
maybe. the last time i tried fixing that broke layton, but i think i have an idea on how to fix it once and for all

**Comment by kianoosh34** [comment] 2019-12-18 13:09
Still dealing with issues involving garbage textures being dumped every frame (during gameplay). The game is Paper Mario: Sticker Star, and the problem is consistently active while the game is running

**Comment by khang06** [comment] 2019-12-18 18:39
@kianoosh34 hmmm, i can probably just have it check if it's dumping a texture that's a power of 2. i actually did find a few other games that dumped out 3ds screen res textures, but i didn't think it was much of a problem until now

**Comment by kianoosh34** [comment] 2020-01-27 23:44
@khang06 I actually neglected to mention that while the garbage textures are being dumped the game runs very slowly. What I would like to additionally know is if a custom filter list could be possible and also if, once a specific type of texture is filtered, the lag it causes eliminated as well.

**Comment by v1993** [comment] 2020-04-05 12:35
@kianoosh34 Lags arise mostly from encoding textures to png and writing them onto disk, so as long as hashing/filtering algorithms are fast and operates on uncompressed image data (as they should), filters should improve performance during dumping a lot.

**Comment by GPUCode** [comment] 2023-07-29 12:03
Addressed in https://github.com/citra-emu/citra/pull/6452

**Closed by GPUCode** 2023-07-29 12:03 UTC
