### ISSUE TITLE
Touch screen doesn't work on touch screen devices.

### ISSUE THREAD

**Issue by MerryMage** [citra-emu/citra#1437] opened 2016-03-02 09:19 UTC
This issue arises in Qt and GLFW (and the new SDL2 frontend).

On my Windows 10 tablet, a tap is registered as a click and release of the mouse that happens so quickly `EmuWindow::TouchPressed` then `EmuWindow::TouchReleased` are called in quick succession by `EmuWindow::PollEvents` before `Service::HID::Update` runs.

A suggested fix is for `EmuWindow::GetTouchState` to return a vector of changes since last being called. `Service::HID::Update` can then add multiple `TouchDataEntry`s to the ring buffer.

**Comment by Subv** [comment] 2016-03-02 15:49
I agree with the proposed solution

**Comment by JamePeng** [comment] 2016-03-02 18:24
yeah！the game “Taiko no Tatsujin” can't touch on touch screen devices

**Comment by JamePeng** [comment] 2016-03-02 18:24
yeah！the game “Taiko no Tatsujin” can't touch on touch screen devices

**Comment by JamePeng** [comment] 2016-03-02 18:24
yeah！the game “Taiko no Tatsujin” can't touch on touch screen devices

**Comment by JamePeng** [comment] 2016-03-02 18:24
yeah！the game “Taiko no Tatsujin” can't touch on touch screen devices

**Comment by JamePeng** [comment] 2016-03-02 18:24
yeah！the game “Taiko no Tatsujin” can't touch on touch screen devices

**Comment by JamePeng** [comment] 2016-03-02 18:24
yeah！the game “Taiko no Tatsujin” can't touch on touch screen devices

**Comment by JamePeng** [comment] 2016-03-02 18:24
yeah！the game “Taiko no Tatsujin” can't touch on touch screen devices

**Comment by JamePeng** [comment] 2016-03-02 18:24
yeah！the game “Taiko no Tatsujin” can't touch on touch screen devices

**Comment by phly95** [comment] 2017-01-06 15:54
yeah, i tried playing parascientific cruise and it did not work well with my stylus

**Comment by mailwl** [comment] 2017-01-06 16:18
Subv, want support controller, when you merge it? sorry for offtop

**Comment by phly95** [comment] 2017-01-06 18:19
I found a solution to the issue! Go to the start menu and type "Pen and Touch". Then go under the pen options tab and click the option that says "Press and Hold". Once clicked then click the settings button below the selection box. At the top of the window, there is a checkbox that says "Enable press and hold for right-clicking". Uncheck that box, hit OK, and then hit apply on the pen and touch window. You may now close the pen and touch window. Open citra, and experience the magic of a working stylus :D

**Comment by NeatNit** [comment] 2018-05-08 11:51
I would also like this feature. Some games that rely on taps, such as Picross e and SmileBASIC, are unusable with touch because of this tiny thing. The workaround @phly95 suggested did not work for me - I did not find all of the relevant settings, maybe they've been removed or changed in the most recent Windows 10 update.

**Comment by MerryMage** [comment] 2018-05-11 15:53
Slight complexity increase due to the new input core & `InputDevice`.

**Comment by Valkirie** [comment] 2018-05-15 14:14
Also interested in getting this issue fixed. Right now touchscreen users have to double/triple tap the touchscreen and/or tap and drag a bit to get the input registered.

**Comment by NeatNit** [comment] 2018-05-15 15:52
I am not familiar with the APIs at play, but I *would think* that you can just say "I want to handle touch on my own, I don't want Windows to make it abstract for me". The issue is that Windows is hiding the actual taps from the software, and just showing a fake instantaneous tap instead. If you get the "touch start" and "touch end" events *as they're actually happening*, nearly all occurrences of this issue will be fixed, except for those where the user really tapped the screen so fast it was in-between frames.

Unless I have a huge misunderstanding on the issue...

**Comment by NeatNit** [comment] 2018-09-22 12:13
This seems to have been forgotten, which is understandable (especially if the devs don't have a device to test it on - do they?), but I think it's a bit of a shame and ironic that a touchscreen can't be properly emulated on a touchscreen.

One thing I want to clarify is that this isn't just about **tapping**, but more about **holding** a button. This video demonstrates how Citra fails to emulate a touchscreen tap-and-hold compared to a real 3DS:

https://youtu.be/96Mlk4enCkA

The times where it "works" later in the video, it's because I intentionally drag my finger a bit immediately after touching.

**Comment by NeatNit** [comment] 2018-09-29 23:55
Did some more digging into this. Somewhat unsurprisingly, it turns out that physical touchscreens aren't implemented in Citra at all. The only places that activate `EmuWindow::TouchPressed`, `EmuWindow::TouchMoved` and `EmuWindow::TouchReleased` are *mouse events*, and the conversion from touch to mouse events is left for the framework/OS to do. Those in turn use logic that fits general GUI, not games, which is what's causing all of the problems.

### Solution: implement touch events
Implement http://wiki.libsdl.org/SDL_TouchFingerEvent or http://doc.qt.io/qt-5/qtouchevent.html or whatever (I got lost). They should, hopefully, get *proper* touch input as it is happening and fix all of the issues here.

**Comment by NeatNit** [comment] 2018-10-01 23:38
Trying to do this in https://github.com/NeatNit/citra, it already works in Qt pretty much perfectly, but I couldn't get rid of Windows's touch contact visualization (e.g. the square that pops up when you touch for too long), and I've yet to implement it on SDL.

**Comment by MerryMage** [comment] 2018-10-04 16:14
> couldn't get rid of Windows's touch contact visualization

You can probably use `SetWindowFeedbackSetting`; you'll have to get the hwnd with `QWidget::winId()`

**Closed** 2018-10-09 15:02 UTC
Labels: A-frontend, E-intermediate, T-bug
