### ISSUE TITLE
nothing in graphics settings

### ISSUE THREAD

**Issue by Sagametroid** [citra-emu/citra#4487] opened 2018-12-06 02:36 UTC
setting spanish language and choosing "graphics" nothing appears. but choosing english works without problems

Using Latest canary (1108)

![graphics](https://user-images.githubusercontent.com/38576597/49557384-6f126880-f8d5-11e8-980c-1eea9e86de72.PNG)

**Comment by zhaowenlan1779** [comment] 2018-12-12 13:03
This was caused by #4437, should be fixed now.
If not please leave a comment and I'll reopen

**Closed by zhaowenlan1779** 2018-12-12 13:03 UTC
