### ISSUE TITLE
Swap screens with a Controller

### ISSUE THREAD

**Issue by rrrcabral** [citra-emu/citra#6309] opened 2023-02-17 16:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

 I see in Citra there is only an option to enter a keyboard key but nothing for the controller.
Preferably I'd like to play with one large screen and toggle between them on the fly.

### Why would this feature be useful?

You can do it on emulators like MelonDs no problem at all.

too many people want this: https://www.reddit.com/r/Citra/comments/p9d4hb/swap_screens_with_a_controller/

**Comment by FearlessTobi** [comment] 2023-02-17 17:30
Duplicate of https://github.com/citra-emu/citra/issues/5885.

**Closed by FearlessTobi** 2023-02-17 17:30 UTC
