### ISSUE TITLE
Fire Emblem Echoes: Shadows of Valentia - Freeze after the opening cutscenes

### ISSUE THREAD

**Issue by GDhex12** [citra-emu/citra#3134] opened 2017-11-19 11:40 UTC
Tested on Nightly c810a3f, though this issue persists even on the second Nightly 4650486.

The game becomes frozen after the third dialogue that happens after all of the cutscenes.
Log file: 
[log.txt](https://github.com/citra-emu/citra/files/1485503/log.txt)

**Comment by acnleditor2** [comment] 2017-11-19 14:24
`[  58.084174] Audio.DSP <Critical> audio_core/hle/pipe.cpp:PipeWrite:166: pipe_number = 3 unimplemented`

**Comment by Awesalot** [comment] 2017-11-29 14:58
Having the same issue and the top screen in bars issue.
Hoping someone fixes it!
Is there any guide for these things so I can learn how to fix it myself?

**Comment by chris062689** [comment] 2017-11-29 15:14
@Awesalot Unless you have additional information to provide please just add a thumbs-up. 
You can follow our Discord's development channel and follow the Github's pulse for more information on how these types of bugs are fixed.

**Comment by Awesalot** [comment] 2017-11-30 19:16
https://www.youtube.com/watch?v=hV6PcbLZIsE

Try this, it's pretty good

**Comment by Dragios** [comment] 2020-04-24 01:52
@Hexagon12 Is this still an issue now?

**Comment by gapg64** [comment] 2020-08-05 05:22
I've been experimenting with this problem looking for it since version stopped working,  it found the canary version that breaks, it is from the canary version # 1444 that the game stops working. I'm still looking for the nightly version where the problem starts

**Comment by gapg64** [comment] 2020-08-19 08:33
I know it takes me a while but I found that the problem is fixed in canary # 1206 I have searched the versions of nightly from February 17 to April 15 and I have not seen any version of nightly that has applied the patch which sent me to the conclusion that this correction never reached nightly

**Comment by gapg64** [comment] 2020-09-09 06:29
I just realized that I am an idiot and did not upload the logs;
Citra Nightly 1619 log: https://drive.google.com/file/d/1ollFKO7P4ZcJH6ogIF-XKY0J2u02l-FN/view?usp=sharing
Citra Canary 1443 log (in this version the game works): https://drive.google.com/file/d/1UIhQ-zc8EaCEhHCQnukC6I8VtwG9Wy6A/view?usp=sharing

**Comment by gapg64** [comment] 2020-09-23 11:28
I have corrected the problem using this https://github.com/citra-emu/citra/issues/5556

**Comment by FearlessTobi** [comment] 2020-09-23 21:29
So apparently this is fixed with HLE AAC anyway.
Closing.

**Closed by FearlessTobi** 2020-09-23 21:29 UTC
