### ISSUE TITLE
Large CIA files fail to install

### ISSUE THREAD

**Issue by TheMCNerd2017** [citra-emu/citra#3704] opened 2018-05-01 01:42 UTC
I can no longer install CIA files that are very large(like Pokemon Ultra Sun). A message comes up claiming that the installation failed. The console window shows that the installation was aborted with error code "c86044d2". I have attached screenshots below of the issue. The CIA file I was attempting to install installed correctly in older versions of Citra.

![selectinggame](https://user-images.githubusercontent.com/25375242/39457746-f47c2be2-4cbd-11e8-9470-905d83145138.PNG)
![installaborted](https://user-images.githubusercontent.com/25375242/39457751-fa5e6c28-4cbd-11e8-80a2-13f6754b6e9b.PNG)

I am using the latest version of Citra Nightly(HEAD-9c65a45).

**Comment by jroweboy** [comment] 2018-05-01 01:45
Closing as a duplicate of https://github.com/citra-emu/citra/issues/3644

**Closed by jroweboy** 2018-05-01 01:45 UTC
