### ISSUE TITLE
Crashes on OS X nightly builds

### ISSUE THREAD

**Issue by tylerhou** [citra-emu/citra#1929] opened 2016-06-23 23:08 UTC
Hello,

It seems that later nightly builds crash on OS X.

citra-20160622-4d31874-osx-amd64.tar.xz:

OS X error log: https://gist.github.com/tylerhou/b82d32114d66d8140cd15cd51ee00458
Console output: https://gist.github.com/tylerhou/b64892e6b756a55548d1cf9e7c6a34bf

This issue seems to have first appeared in the 0c56c9f build. It does not show up in the previous build (7139e63).

**Comment by JayFoxRox** [comment] 2016-06-23 23:14
Duplicate of https://github.com/citra-emu/citra/issues/1902

**Comment by tylerhou** [comment] 2016-06-23 23:15
This isn't a duplicate. It's because of a completely different issue. The other issue is because their Qt5 dependency is out of date; this is a bug in the code.

**Comment by JayFoxRox** [comment] 2016-06-23 23:57
So I'll reopen this. However, note that 0c56c9f should only affect the SDL frontend which you are not even running. However 7139e6353f9d0af4dfa2a9a0947fef13cf16dd86  was broken so we reverted it.
So really it looks like a change in Travis OR it must have happened earlier.

Also note that the code seems to work fine on Linux and Windows.

**Comment by tylerhou** [comment] 2016-06-24 03:10
I'll look at earlier builds and try find a source of the issue but it could be caused by any commit between 0c56c9f and 7139e63 (or earlier). I didn't go commit-by-commit, just through each nightly build.

**Comment by JayFoxRox** [comment] 2016-12-05 02:57
This should be fixed already according to #1962

**Closed by JayFoxRox** 2016-12-05 02:57 UTC
