### ISSUE TITLE
Regression since commit 7ea3ce1

### ISSUE THREAD

**Issue by andreieichler** [citra-emu/citra#2937] opened 2017-09-19 13:50 UTC
Got the error message "./citra-qt: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./citra-qt)" after this commit.

OS: Linux 4.13, Manjaro KDE 17.0.5

**Comment by B3n30** [comment] 2017-09-19 13:53
That's expected, your system needs libcurl. If it isn't installed you need to install it with either `apt-get install libcurl4-openssl-dev` or `pacman -S libcurl-compat`, depending on your distribution

**Comment by andreieichler** [comment] 2017-09-19 14:05
I already have libcurl-compat installed:

`pacman -Qs libcurl-compat
local/libcurl-compat 7.54.1-1
    An URL retrieval library (without versioned symbols)
`
And that's how my /usr/lib looks like

`ls -1 /usr/lib/libcurl*
/usr/lib/libcurl-compat.so.4.4.0
/usr/lib/libcurl.so
/usr/lib/libcurl.so.3
/usr/lib/libcurl.so.4
/usr/lib/libcurl.so.4.0.0
/usr/lib/libcurl.so.4.1.0
/usr/lib/libcurl.so.4.2.0
/usr/lib/libcurl.so.4.3.0
/usr/lib/libcurl.so.4.4.0
`

**Comment by j-selby** [comment] 2017-09-22 01:16
`pacman -S libcurl-openssl-1.0`?

**Comment by andreieichler** [comment] 2017-09-22 01:26
This package doesn't exists on Manjaro:

```
pacman -Ss libcurl*
core/curl 7.55.1-2 [installed]
    An URL retrieval utility and library
extra/python-pycurl 7.43.0-3 [installed]
    A Python 3.x interface to libcurl
extra/python2-pycurl 7.43.0-3
    A Python 2.x interface to libcurl
extra/ruby-ethon 0.9.0-1
    Libcurl wrapper.
community/curlftpfs 0.9.2-6
    A filesystem for acessing FTP hosts based on FUSE and libcurl.
community/gnurl 7.54.0-1
    fork of libcurl, which is mostly for GNUnet
community/libcurl-compat 7.54.1-1 [installed]
    An URL retrieval library (without versioned symbols)
community/libcurl-gnutls 7.54.1-1
    An URL retrieval library
multilib/lib32-libcurl-compat 7.54.1-1
    An URL retrieval library (without versioned symbols)
multilib/lib32-libcurl-gnutls 7.54.1-1
    An URL retrieval library
```

**Comment by andreieichler** [comment] 2017-09-22 01:27
If I build locally it works, only the one from download page triggers this error

**Comment by j-selby** [comment] 2017-09-22 01:28
Yeah, sorry, built that from the AUR. Carry on.

**Comment by MerryMage** [comment] 2017-10-10 22:04
Duplicate of #2976.

**Closed by MerryMage** 2017-10-10 22:04 UTC
