### ISSUE TITLE
Pokemon Y screen freezes in pokemon-amie

### ISSUE THREAD

**Issue by keanufg** [citra-emu/citra#5084] opened 2020-02-02 12:25 UTC
I’m using Citra Nightly 1415 
It’s not constant but often when feeding my pokemon in Pokemon-amie a pokepuff the screen freezes and the framerate drops. But after a few seconds the framerate goes back to normal but the screen stays frozen.

The game actually still works, i can save, go to options etc by clicking where the icons are and you can hear it responding through the sound.
I can save the game this way but I need to restart the game everytime.

I am playing on a Lenovo Yoga 370
Intel Core i5-7200U @ 2.50GHz
64 bit

**Comment by BreadFish64** [comment] 2020-02-19 03:00
duplicate of #4670

**Closed by BreadFish64** 2020-02-19 03:00 UTC
