### ISSUE TITLE
Issues with citra ubuntu 18.04

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [citra-emu/citra#4180] opened 2018-09-04 14:19 UTC
So ive been getting people messaging me on discord and YT asking why Citra isnt working 
Seems 18.04 doesnt have sndio installed by default and the version it does give you is out of date and when you compile and install it's in a weird place so the fix for other distro's wont work 

so here is a fix and a package you guys need to add to reduce confusion 
 
https://launchpad.net/ubuntu/cosmic/+package/libsndio-dev < once its install the user needs to link the library with this cmd in terminal sudo ln -T /usr/lib/x86_64-linux-gnu/libsndio.so.7.0 /usr/lib/libsndio.so.6.1 which the location of the install isnt normal and is debian Based only 

and for other distro's that follow proper install locations of usr/lib the cmd would be 

sudo pacman -S sndio 
sudo dnf install sndio 

And the terminal cmd would be sudo ln -T /usr/lib/libsndio.so.7.0 /usr/lib/libsndio.so.6.1 

that is the fix for Yuzu as well if you added this somewhere it would help many people avoid issues

**Comment by Hexagon12** [comment] 2018-09-04 14:35
Duplicate of #3862.

Requesting to close.

**Closed** 2018-09-04 14:46 UTC
