### ISSUE TITLE
DualSense input

### ISSUE THREAD

**Issue by SoloBackup** [citra-emu/citra#6057] opened 2022-06-16 21:23 UTC
citra has support for SDL, but unlike pcsx2 and yuzu, when citra is opened, the emulator does not recognize that the controller is specifically DualSense and does not change the controller's led indicating that the input was successful, something that occurs on pcsx2 and yuzu. So I need to get into one of these two emulators that change the control system and turn on the control's led indicating that it worked, and only then go to citra, to be able to use the motion sensor, if I don't, the sensor of motion does not work. I hope they fix this

**Comment by SachinVin** [comment] 2022-06-17 14:49
duplicate of #6027, you can use ds4windows in the mean time.

**Closed by SachinVin** 2022-06-17 14:49 UTC
