### ISSUE TITLE
Super Mario 3D Land DEMO - Graphics glitches / missing textures

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1039] opened 2015-08-16 17:35 UTC
Spamming error:
HW.GPU <Error> video_core\debug_utils\debug_utils.cpp:Pica::DebugUtils::LookupTexture:592: Unknown texture format: 6

![sm3dl 1](https://cloud.githubusercontent.com/assets/11453507/9294434/a1cee5b8-444d-11e5-8117-dbcba046a1fc.PNG)

![sm3dl 2](https://cloud.githubusercontent.com/assets/11453507/9294436/a95c3d12-444d-11e5-945a-2c8f9daeb531.PNG)

CITRACE LOG: https://goo.gl/5auSyA

**Comment by OatmealDome** [comment] 2015-08-16 20:13
I think #1034 should fix this. You should give it a try.

**Comment by Subv** [comment] 2015-08-17 15:46
This issue doesn't happen in the software renderer. Some testing i did suggests that this is not related to texture caching, nor stencil.
The game is using DestColor as alpha blend factor and the sw renderer doesn't currently implement this (it spams a critical log), however this is not the cause for the gray screen (Implementing  DestColor = DestSource as per the OpenGL documentation doesn't replicate the hw renderer's behavior).

My guess is that this is related to some copy (GPU->CPU) we're not performing.

**Comment by JohnGodgames** [comment] 2015-08-27 17:17
Fixed by #1049

**Comment by neobrain** [comment] 2015-08-27 17:19
#1049 is not merged yet...

**Comment by JohnGodgames** [comment] 2015-08-27 17:20
sorry...closed by a mistake

**Closed** 2015-08-30 00:06 UTC
Labels: bug, graphics
