### ISSUE TITLE
Add a visual reference to the Controls configuration screen

### ISSUE THREAD

**Issue by x3ro** [citra-emu/citra#5694] opened 2021-01-17 17:03 UTC
Hey folks,

I used Citra for the first time today, and I'm really impressed by the quality of this project 🙂 One thing I had a bit of trouble with setting up was that I wasn't very clear on what the different pads and sticks referred to in the controls configuration screen. That made me wonder whether it'd make sense to add a simple visual reference telling the user e.g. what the "C-Stick" is. I imagine it to look something like this:

![citra-3ds](https://user-images.githubusercontent.com/243719/104850194-f1134f00-58ed-11eb-8340-048db1076fe7.JPG)

(coincidentally that is currently lacking the C-stick, but please don't let that distract you 😄 )

In any case, I'd be happy to submit a PR for such a change, but wanted to check in with the maintainers whether or not this'd be a good idea and could be accepted.

**Comment by vitor-k** [comment] 2021-01-21 16:55
Similar to #3673
I don't think a real photo is suitable for the UI, something like what jroweboy linked in that issue would be better.
There was a user who did a few mockups on discord, you could ask there as well.
Adding even more vertical height to the controls tab is also inadvisable, as it would cause or worsen issues like #5212

Also, porting the relevant parts from yuzu-emu/yuzu#4530 is probably easier than doing it from scratch.

**Comment by FearlessTobi** [comment] 2021-01-31 02:27
I'll close this as a duplicate of https://github.com/citra-emu/citra/issues/3673.
I've also started porting the mentioned PR from yuzu, but I haven't found the time to finish it yet.

**Closed by FearlessTobi** 2021-01-31 02:27 UTC
