### ISSUE TITLE
Harvest Moon a New Beginning Freezing

### ISSUE THREAD

**Issue by DamiloW** [citra-emu/citra#3573] opened 2018-03-25 02:09 UTC
Hello everyone, everything good? I need your help, the Harvest Moon 3DS New Beginning Game is freezing on the create name screen, please help me out, I'm new here. There is an error in the images.

![hm](https://user-images.githubusercontent.com/37759672/37870917-54b9f890-2fb8-11e8-8847-70a7930d7476.jpg)
![hm erro](https://user-images.githubusercontent.com/37759672/37870918-54db1322-2fb8-11e8-8b01-9f3d7ec66b22.jpg)

**Comment by valentinvanelslande** [comment] 2018-03-25 02:15
duplicate of #1583

**Comment by Hexagon12** [comment] 2018-03-25 06:45
Requesting to close.

**Closed** 2018-03-25 10:05 UTC
