### ISSUE TITLE
OSX memory leak issues causes freeze up every 20 minutes.

### ISSUE THREAD

**Issue by NiklasKunkel** [citra-emu/citra#2813] opened 2017-06-29 10:40 UTC
citra-osx-20170625-d1e414d

OSX 10.12.5
2.2 GHz Intel Core i7
16 GB RAM
Intel Iris Pro 1536 MB
OWC Mercury Aura Pro SSD

The memory leak issue on OSX makes this emulator almost unplayable. Even without any other applications open within 15-20 minutes all of the memory gets eaten up and the whole system will just freeze.

Here is a top I ran during my last run. You'll notice the actual Mem usage is low but the CMPRS is huge. As soon as the CMPRS reaches 32G citra will crash like clockwork every time. 

http://imgur.com/U28sSDS

I've piped the terminal output from Citra here:

https://paste.ee/p/wAWrj

I've heard none of the devs have OSX and so cannot seem to reproduce this bug. I'm fairly technical and willing to produce whatever data or stack trace is necessary for the developers to pinpoint this problem. This is a huge issue for the OSX userbase and I really hope it gets the necessary attention.

**Comment by legoj15** [comment] 2017-06-29 11:45
Possibly related to #1701 & #2416 (?)

**Comment by j-selby** [comment] 2017-06-30 10:07
Duplicate of #2416

**Comment by wwylele** [comment] 2017-06-30 10:35
Close as duplicated

**Closed by wwylele** 2017-06-30 10:35 UTC
