### ISSUE TITLE
[Fix Request - Patch for you] Hyrule Warriors 3DS now loads after the loading screen but low FPS ingame

### ISSUE THREAD

**Issue by JackoboLeChocobo** [citra-emu/citra#4100] opened 2018-08-15 00:48 UTC
Here is a patch that corrects the crash of the game (and so add some features of New 3DS) according to valentinvanelslande fork ( https://github.com/valentinvanelslande/ : but his fork uses a old version of citra apparently (?) ).

However I get on my setup low FPS ingame after the loading of the chapter 1 and during cutscenes movies (60%-75% speed). I updated the code with your datas and variables. Do you have an idea of low FPS with official citra code ? valentinvanelslande fork has normal FPS speed during the gameplay of chapter 1.

Note : How to configure qt-config.ini ?
```
[System]
is_new_3ds=true
is_new_3ds\default=false
```
Link of the patch : https://gitlab.com/JackoboLeChocobo/citra-patches/blob/master/01-hyrule-warriors-fix.patch

In a friendly manner,
Jackobo

Tested on Lubuntu 18.04 - 64 bits
Video card : NVIDIA GeForce GTX680 with 4096 MB as Total Memory
Processor : Intel(R) Core(TM) i5 CPU 760  @ 2.80GHz ( fixed at 2.40 GHz in the BIOS )
RAM : 16 Go

**Comment by FearlessTobi** [comment] 2018-11-01 21:03
This is just a hack and a duplicate of https://github.com/citra-emu/citra/issues/2198.

**Closed by FearlessTobi** 2018-11-01 21:03 UTC
