### ISSUE TITLE
Kirby Planet Robobot First BOSS Battle Glitch

### ISSUE THREAD

**Issue by zaranrapu** [citra-emu/citra#1970] opened 2016-07-23 10:59 UTC
Video of the bug: https://github.com/citra-emu/citra/files/379506/Citra.zip

(Post restored by JayFoxRox after vandalism)

**Comment by wwylele** [comment] 2016-07-23 11:10
This looks like a regression. I used to successfully beat that boss on citra, but can confirm this happens today.

**Comment by neobrain** [comment] 2016-12-05 21:07
This bug report is useless.

**Comment by JayFoxRox** [comment] 2016-12-05 21:36
@wwylele commented on Jul 23:
This looks like a regression. I used to successfully beat that boss on citra, but can confirm this happens today. Regression caused by edf30d8 (PR #1810) (issue #1919)

**Comment by Subv** [comment] 2017-05-22 19:26
Closed by #2696

**Closed by Subv** 2017-05-22 19:26 UTC
Labels: F-cpu:interpreter, T-regression
