### ISSUE TITLE
Performance regression in Super Mario 3D Land

### ISSUE THREAD

**Issue by LOuroboros** [citra-emu/citra#5209] opened 2020-04-14 00:41 UTC
As the title says, I found a performance regression in Super Mario 3D Land and I came here to report it.
This all started when I decided to test out the game on Citra Canary. I noticed that the game didn't go beyond ~45 FPS in the first stage of the game with the latest version of Citra Canary _(1640 at the time)_, where as the version that I use normally _(Citra Canary 1560)_ was working pretty much at 60 FPS throughout all the first stage.
My hunch was that the cause of this was the Core Timing 2.0 PR, seeing how [it already caused issues in various games](https://github.com/citra-emu/citra/pull/4913#ref-issue-199092812).

When I brought up the possibility in the Discord server for Citra, I was suggested by Discord user Aura Of The Dawn to compare the performance between Citra Nightly 1422 and Citra Nightly 1423, being the latter the version in which the Core Timing 2.0 PR was merged.

Effectively, just like in my test with Citra Canary, I can notice a performance regression. Two, in fact.
There's a difference between 1422 and 1423, and then there's another difference between 1423 and 1469, which I tested in order to check if maybe the regression was fixed.

I recorded some videos showing off my results:
Citra Nightly 1422: https://streamable.com/ikizpe
Citra Nightly 1423: https://streamable.com/y2vcy5
Citra Nightly 1469: https://streamable.com/4c6a1k

As it can be seen, there's minimal framerate drops in the first stage of the game on Citra Nightly 1422, where as on Citra Nightly 1423 and Citra Nightly 1469 there's many, many framerate drops.

Here's the 3 citra_log.txt files I got from the tests:
Citra Nightly 1422: https://pastebin.com/kG949HQk
Citra Nightly 1423: https://pastebin.com/QkdHDC5T
Citra Nightly 1469: https://pastebin.com/7i5eEe45

PC Specs:
**CPU**: i3 2120
**RAM**: 4 GB (Running in single channel because reasons)
**GPU**: Gigabyte NVIDIA GeForce GT 1030 _(Driver Version 441.66)_
**OS**: Windows 8.1 x64

If there's any bit of information I forgot to add, please let me know.

**Comment by BreadFish64** [comment] 2020-04-14 02:38
I have profiled SM3DL and it's doing something that cause threads to reschedule often, which take up about 20% of CPU time.

**Comment by Subv** [comment] 2020-04-14 03:06
Some AppCore thread might be stuck fighting for an userspace mutex (essentially a memory address managed with atomic instructions and svcArbitrateAddress) with another thread on the SysCore, this would usually cause them to call svcSleepThread a lot. Our svcSleepThread implementation enqueues a CoreTiming event, which may be shortening the available timeslices each core gets on Dynarmic.

This is all just conjecture though, I haven't actually checked the game

**Comment by LOuroboros** [comment] 2020-04-17 02:49
> please retest with latest canary

I just woke up and decided to give it a shot, @B3n30. The results weren't favorable.

Video: https://streamable.com/w4zptz
citra_log: https://pastebin.com/8p2y3pCS

**Comment by CaelTheColher** [comment] 2020-04-17 18:41
Not sure if related, but I'm seeing some performance regression in pokemon X too. It was fine on Canary until a few days ago after an update (not sure which one exactly) it started running slow until I switched to Nightly and it started running fine again. Now Nightly updated (1480) and its running slower again. I also tried the latest Canary (1654) and it seems to still be running slower.
In both cases I was seeing full speed at 720p internal resolution and mostly full speed at 960p but after the updates it dropped to 25-22 fps at the same places I was getting 30-28.
My specs are:
CPU: Ryzen 3 2200g
GPU: Integrated Vega 8
RAM: 2x8GB @ 2666Mhz Dual Channel
OS: Windows 10 x64
Driver Version: 20.4.1

**Comment by B3n30** [comment] 2020-04-17 18:43
@CaelTheColher Can you please try different nightly versions and figure out from which version to which version the regression happened?

**Comment by CaelTheColher** [comment] 2020-04-17 18:48
> 
> 
> @CaelTheColher Can you please try different nightly versions and figure out from which version to which version the regression happened?

I will try

**Comment by CaelTheColher** [comment] 2020-04-17 19:04
@B3n30 
1479: 29-30 fps with occasional dips to 26-28 and also some small stutter I assume is related to shaders(?)
1480: 26-27 fps with occasional dips to 24-25 and once it dipped all the way to 20 for a few seconds, in some places it ran full speed but I noticed it was not as smooth (microstutter?)

All tests were done in Lumiose City

**Comment by B3n30** [comment] 2020-04-17 19:08
Hmm. Are you sure about this? that would mean #5133 cause the regression which doesn't make sense, since it didn't touch any performance relevant parts in Citra

**Comment by CaelTheColher** [comment] 2020-04-17 19:09
> 
> 
> Hmm. Are you sure about this? that would mean #5133 cause the regression which doesn't make sense, since it didn't touch any performance relevant parts in Citra

I will try some older versions and see if anything changes, but those are the versions I tested

**Comment by CaelTheColher** [comment] 2020-04-17 19:11
Maybe something is causing random variances in performance between launches? Or I'm dumb and this could be entirely my fault? (not an impossibility)

**Comment by CaelTheColher** [comment] 2020-04-17 19:54
So.. When I went to test the version I had before (1472), it run fine as I expected, but then I tried 1480 again and its running mostly fine again(!) with the exception that its slowing down a bit more in some places. I have no idea what I did different, I went to the same places in the same city with everything being the same as the other tests. I don't know if I'm being dumb or pokémon x is being dumb or anything really

**Comment by Acid-Crash** [comment] 2020-04-17 22:11
Hi here,
Wanted to share my feedback on the same issue.
Super Mario 3D Land:
On Nightly 1480 it runs fine (54-60fps) but on 1481 the performance drops (40-45 fps).

**Comment by B3n30** [comment] 2020-04-18 07:19
this issue should probably get fixed by #5223. Please retest as soon as the latest canary is available

**Comment by Acid-Crash** [comment] 2020-04-18 10:02
Hi,
Sadly I'm not sure whether the mentioned patch was pushed live.
Here are current results:
Canary 1657 - Works fine (Speed at 100% FPS: 60)
Nightly 1484 - Laggy (Speed 80-82%, FPS: 49-52)

Nightly 1480 - Works fine (Speed at 100% FPS: 60)

All in all it looks good on Latest Canary, but not on Nightly

Hope this helps

**Comment by B3n30** [comment] 2020-04-18 10:04
yes this helps.  The fix is currently only in canary and not in nightly yet

**Comment by LOuroboros** [comment] 2020-04-18 14:03
I just woke up and tested the latest Canary a minute ago. It looks to me like the problem was solved, @B3n30!
https://streamable.com/p6ba93

I suppose it's no longer necessary, but I'll still drop the citra_log because why not.
https://pastebin.com/kXAXwyMa

**Comment by CaelTheColher** [comment] 2020-04-18 15:18
Latest Canary is running fine for too now

**Comment by B3n30** [comment] 2020-04-18 18:54
fixed by #5223

**Closed by B3n30** 2020-04-18 18:54 UTC
