### ISSUE TITLE
Controller profiles do no name duplication checking

### ISSUE THREAD

**Issue by FearlessTobi** [citra-emu/citra#4611] opened 2019-01-30 22:34 UTC
It is possible to create several named profiles with the same name. This obviously isn't intended here and will confuse users. Fixing this should be easy by just checking if a profile with the same name already exists.

Screenshot:
![unbenannt](https://user-images.githubusercontent.com/20753089/52017351-69a55900-24e7-11e9-8bca-f8c9263f345d.png)

cc @valentinvanelslande

**Comment by valentinvanelslande** [comment] 2019-01-30 22:34
i can't fix it because my laptop that i use for citra coding is broken (it's true)

**Comment by valentinvanelslande** [comment] 2019-01-30 22:53
This should also be fixed in cheats. Includes the Gateway cheat file parser.
If you want to fix this, don't forget to add the check in the INI loading.

**Comment by Amnesia1000** [comment] 2019-01-30 22:57
In addition, profile names are reset when the emulator is closed and reopened. All are renamed default. It would be great to fix the two issues in one

**Comment by Mates1500** [comment] 2019-05-22 18:20
> In addition, profile names are reset when the emulator is closed and reopened. All are renamed default. It would be great to fix the two issues in one

Can you elaborate, describe the steps to reproduce? On my windows build I can't seem to be able to reproduce the issue profile names persist just fine between sessions.

**Comment by FearlessTobi** [comment] 2019-05-22 19:41
I fixed this already @Mates1500.

**Closed** 2019-05-24 21:28 UTC
Labels: A-frontend, E-easy, T-bug
