### ISSUE TITLE
[Feature request] Add Xbrz Filter

### ISSUE THREAD

**Issue by LuismaSP89** [citra-emu/citra#4217] opened 2018-09-15 00:40 UTC
Xbrz filter is a great improvement in all games. I think it must be added like Desmume does, you can see some comparisons of the great improvements of this filter here:

https://a.fsdn.com/con/app/proj/xbrz/screenshots/xBRZ%20-%20SOTN2.png/max/max/1
https://a.fsdn.com/con/app/proj/xbrz/screenshots/xBRZ%2022.png/max/max/1
https://a.fsdn.com/con/app/proj/xbrz/screenshots/xBRZ_Doom.png/max/max/1

**Comment by BreadFish64** [comment] 2018-09-15 00:48
Duplicate of #3623

**Comment by Jules-A** [comment] 2018-09-15 08:49
Can't you use xBrz with Retroarch Citra? Why not post comparisons of that?

**Comment by LuismaSP89** [comment] 2018-09-15 12:16
@Jules-A I don't use retroarch, and I don't know if the included citra build uses xbrz or not. But that's not the point. The point is to include native support in citra of shaders and filters such this one in order to improve the graphics, specially the 2D ones. You can see that a lot of emulators like snes-9x, punes, vba-m, ppsspp, gliden64 plugin for project64 and mupen, scvmm, epsxe/pcsx, MAME, dosbox, desmume, etc have it's own implementation of this plugin.

**Closed** 2020-03-16 14:42 UTC
