### ISSUE TITLE
The Sim 3 : graphics error！

### ISSUE THREAD

**Issue by JamePeng** [citra-emu/citra#1440] opened 2016-03-02 20:06 UTC
look like a alien
![qq 20160303035956](https://cloud.githubusercontent.com/assets/17095606/13473575/e5bfda7c-e0f4-11e5-85b4-df52d48663f6.png)
![qq 20160303040108](https://cloud.githubusercontent.com/assets/17095606/13473577/e5c55b3c-e0f4-11e5-8565-27d28ad9299d.png)
![qq 20160303040208](https://cloud.githubusercontent.com/assets/17095606/13473576/e5c473fc-e0f4-11e5-8c68-6c3f48cc7595.png)

the log:
[The sim3 log.txt](https://github.com/citra-emu/citra/files/155542/The.sim3.log.txt)

**Comment by MerryMage** [comment] 2016-03-02 20:08
Possible duplicate of #974.

**Comment by JayFoxRox** [comment] 2016-03-09 16:05
Fixed by #1479

**Comment by JamePeng** [comment] 2016-03-09 17:08
@JayFoxRox I‘m agree!

**Comment by Subv** [comment] 2016-03-16 17:28
fixed by #1479

**Closed by Subv** 2016-03-16 17:28 UTC
Labels: bug, graphics
