### ISSUE TITLE
Pokemon alpha sapphire crashes when trainers send out specific pokemon

### ISSUE THREAD

**Issue by techno-arch** [citra-emu/citra#6696] opened 2023-07-14 17:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

240bb19 | master-240bb19-dirty (2023-06-20)

### Description of Issue

when a opposing trainer sends out koffing or torkoal the game freezes on during pokeball opening animation and then closes citra

### Expected Behavior

the game lets me continue with the battle without freezing 

### Reproduction Steps

play untill you reach flannery's gym and get in a battle with Ninja Boy Hiromichi, Ninja Boy hoji or flannery

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12052625/citra_log.txt)

### System Configuration

CPU: Intel i7-5600U
GPU/Driver: Mesa Intel(R) HD Graphics 5500
RAM: 16gb ddr3
OS: Arch Linux x86_64

**Comment by techno-arch** [comment] 2023-07-15 13:36
https://github.com/citra-emu/citra-canary/releases/tag/canary-2550 issue seems to be fixed when running the app image on the newest canary version with no no noticeable drop in the frame rate I was even able to set the internal resolution to 2x 
![20230715_16h33m21s_grim](https://github.com/citra-emu/citra/assets/52927301/e9606f05-cb18-4ed7-9557-d4840311ad47)

**Comment by ianhealy91** [comment] 2023-08-07 19:40
Hey @GPUCode @FearlessTobi this bug is still present in current nightlies - started a conversation here https://discord.com/channels/220740965957107713/220742362740162560/1137789509610766358 I uploaded a log here https://discord.com/channels/220740965957107713/220742362740162560/1137781153307299932

**Comment by Cesura** [comment] 2023-08-18 09:59
In my case, this was consistently reproducible with the Flatpak version of nightly-1970, but I haven't encountered it since switching to the AppImage.

**Comment by spacedghost-1** [comment] 2023-10-23 05:53
I am having this exact issue on Steam Deck with Citra and Pokemon Alpha Sapphire with the gym fight involving Torkal crashing my program every time. is it possible to fix this on steam deck?

**Comment by CalebWhiting** [comment] 2023-10-25 20:53
Also happening on Pokemon X, whenever one of the elite four sends out Torkal the game crashes.

ArchLinux, Ryxen 7 7700X, Radeon RX 6650 XT
Installed via Flatpak (nightly-1994/stable)

**Comment by Wunkolo** [comment] 2023-11-03 00:02
> I'm encountering the same issue. I'm seeing a failed assertion from libstdc++ in the terminal:
> 
> ```
> /usr/include/c++/12.2.0/array:208: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = Common::Vec4<Pica::Float<16, 7> >; long unsigned int _Nm = 96; reference = Common::Vec4<Pica::Float<16, 7> >&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
> ```
> 
> Wondering if it's related to Pokemon with texture effects for smoke?
> 
> I have a EUR save just before Flannery if that helps:
> 
> [save.tar.gz](https://github.com/citra-emu/citra/files/12053916/save.tar.gz)
> 
> I am able to repro this issue on two pretty different machines:
> 
> * Alpine Linux (edge) - Intel(R) Core(TM) i7-8550U integrated graphics
> * SteamOS - Steam Deck 512 GB
> 
> I've also tried nearly all combinations of graphics settings with no success. Judging from the assertion msg the error is coming from accessing the float uniforms array (declared at):
> 
> https://github.com/citra-emu/citra/blob/0bedb28bdc5084a504aeb5a95da3221f8170c6ec/src/video_core/shader/shader.h#L219

Might be this:
https://github.com/citra-emu/citra/blob/79ea06b226b98916ea98d04e77d341c2078b671a/src/video_core/command_processor.cpp#L81-L87

Looks like `auto& uniform = setup.uniforms.f[uniform_setup.index];` should be _inside_ of the `else` here.

**Comment by Wunkolo** [comment] 2023-11-03 00:31
![image](https://github.com/citra-emu/citra/assets/644247/1256ea8e-d803-4ccf-bfc2-f9d470e75c23)

Ah that seems to be the issue. Happening on latest(b231a22ea52abf0109055aa63454337c5cd53e08).
Seems to depend on having asserts/debugging info enabled.

**Comment by Steveice10** [comment] 2023-11-03 03:38
Nice find! Would you mind opening a PR to fix the placement of that array access? Of course we’ll need to root-cause why the indexes are bad as well.

**Comment by Wunkolo** [comment] 2023-11-03 03:42
Sure, getting one setup now, though it may turn it into log-spam. We can discuss in the PR.

**Comment by Steveice10** [comment] 2023-11-03 10:36
Crash should be fixed by https://github.com/citra-emu/citra/pull/7111

We are tracking the underlying issue in https://github.com/citra-emu/citra/issues/7112

Please let us know if the issue is not fixed when the above PR is available in releases.

**Closed by Steveice10** 2023-11-03 10:36 UTC
