### ISSUE TITLE
Slowdowns in SMT IV Apocalypse. (Android)

### ISSUE THREAD

**Issue by stepsy** [citra-emu/citra#6642] opened 2023-06-25 20:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2530

### Description of Issue

Some Slowdowns seems to happen in SMT IV Apocalypse. However, as I'm using canary with Vulkan. The slowdowns seems to happen different for both renderers.

For OpenGL
The seems to happen in the beginning of the game. As soon you're able to roam the map looking for relics.

For Vulkan
As soon I entered a bar and exit during my second time to free roam. The game slows to 40% speed.

### Expected Behavior

The slowdowns should not happen.

### Reproduction Steps

For OpenGL
The seems to happen in the beginning of the game. As soon you're able to roam the map looking for relics.

For Vulkan
As soon I entered a bar and exit during my second time to free roam. The game slows to 40% speed.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11860719/citra_log.txt)

### System Configuration

Android 13
Snapdragon 680
Adreno 610

**Comment by stepsy** [comment] 2023-06-25 20:18
I think I seen a one year old video of the same problem on YouTube but that was on pc. Don't really know long this has been an issue.

**Comment by FearlessTobi** [comment] 2023-06-26 01:57
Duplicate of https://github.com/citra-emu/citra/issues/5051.

**Closed by FearlessTobi** 2023-06-26 01:57 UTC
