### ISSUE TITLE
Colors are missing in Fantasy Life

### ISSUE THREAD

**Issue by WiseFiend** [citra-emu/citra#7265] opened 2023-12-20 20:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2056

### Description of Issue

The player character's eyes and the characters creator's color palette selection display as white with no other colors appearing.

In the image below, the character's eyes are supposed to be green but appear as white. None of the different texture filters or using Vulkan fixes this issue. 
![image](https://github.com/citra-emu/citra/assets/154467586/cb933196-a0be-45ec-9ce5-d183a1d0af2c)

### Expected Behavior

For the colors to appear instead of being just pure white. 

### Reproduction Steps

By going to character creator and selecting hair color, skin color, or eye color. The color selections appear as pure white and so do the eyes of the player.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13731709/citra_log.txt)

### System Configuration

CPU: Intel i5-9600K 3.60GHz 6 Cores
GPU/Driver: Nvidia GeForceX 1070
RAM: 16GB
OS: Windows 10

**Comment by WiseFiend** [comment] 2023-12-20 20:04
I am posting this issue as it seems to be completely ignored, I understand there may be issues already opened here.

**Comment by GPUCode** [comment] 2023-12-20 20:06
This seems to be a duplicate of https://github.com/citra-emu/citra/issues/3654
I have investigated this in the past, the game appears to be relying on an unknown GPU edge case to render correctly

**Comment by WiseFiend** [comment] 2023-12-20 20:19
Correct, but the colors are different this time. I wonder if it could have to do with Nvidia cards? I've never seen anyone test with AMD before.

**Comment by WiseFiend** [comment] 2023-12-20 20:22
Forget my previous statement about Nvidia, finally found a post from someone claiming it with AMD.

**Comment by FearlessTobi** [comment] 2023-12-21 05:14
Closing as duplicaze of https://github.com/citra-emu/citra/issues/3654.

**Closed by FearlessTobi** 2023-12-21 05:14 UTC
