### ISSUE TITLE
Changing audio device makes Citra crash (Logitech G430 Headset bug)

### ISSUE THREAD

**Issue by Navimus** [citra-emu/citra#3960] opened 2018-07-19 10:34 UTC
Issue:

Citra really doesn’t like the audio device of my Logitech G430 Gaming Headset… Every other Audio device works fine except the “Speaker (Logitech G430 Gaming Headset)”. When the Citra audio device is set to auto it will output it through my Logitech G430 if I also set that in Windows, but if I manually set the Citra audio device to the G430 headset it crashes, irrespective of what audio device is set on windows!

System Information:

Operating System: Windows 10
CPU: Ryzen 5 1600x Overclocked to 4 GHz (100% Stable)
GPU: Asus Strix GTX 960 Overclocked to 1441 MHz (100% Stable)
Citra Version (found in title bar): 802
Game: Pokemon Ultra Moon
Screenshot of Issue (include the full Citra window including titlebar): I can't really show a screenshot because it literally crashes… Nothing in task manager either.

Diagnostic Log:

Log for some reason, and yes also the windows console, doesnt even show any error. It also doesn't show when I switch between the audio devices in Citra…

**Comment by Navimus** [comment] 2018-07-19 10:35
If needed I can provide Video evidence!

**Comment by zhaowenlan1779** [comment] 2018-07-19 10:58
Did you try previous builds? Specially, I recommend you to try out Nightly 798.

Thanks!

**Comment by FearlessTobi** [comment] 2018-07-19 11:05
cc @MerryMage

**Comment by Navimus** [comment] 2018-07-19 12:41
Ill try nightly 798 a bit later, will give feedback in like 2 hours

**Comment by NeatNit** [comment] 2018-09-27 23:47
FWIW, I can't replicate this with my G930 headset.

**Comment by FearlessTobi** [comment] 2018-09-28 13:38
I'm unable to reproduce this, even though I'm using a G430 headset myself.

**Comment by MerryMage** [comment] 2018-09-28 16:48
We've had major changes to audio backend code since the original report. Closing. Please reopen if this is still an issue.

**Closed by MerryMage** 2018-09-28 16:48 UTC
Labels: T-crash, more-info-required
