### ISSUE TITLE
Problem with fishing on Animal Crossing New Leaf

### ISSUE THREAD

**Issue by Kirit0x** [citra-emu/citra#5142] opened 2020-03-24 19:32 UTC
When attrempting to catch a big fish or some rare fishes, I press the key for A but the fish act like I pressed the key too late or too early. It happened a lot of time and I tried a few things like pressing right after the fishing cap goes under water or pressing the key longer but it's inefficient.

I play with Citra Nightly 1444 | Head-25ebf03

It's happening on the normal edtion of the game not the Welcome Amiibo version

**Comment by FearlessTobi** [comment] 2020-03-24 20:58
I was told by a user on Discord that you need to upgrade your fishing rod.
Closing as this is intended behavior and not an emulator bug.

**Closed by FearlessTobi** 2020-03-24 20:58 UTC

**Comment by Kirit0x** [comment] 2020-03-25 17:09
Okay but I think that's not true, first of all nothing in the game wiki mention that having the silver fishing rod increase the laps of time when you need to press a button and second of all even if you have it when you go to the island the gyroide only gives you the basic fishing rod. I went to the island on the emulator to check if there is a difference, and no it's still the same I try to catch 3 sharks but didn't work. I'm maybe wrong but for me it's a bug
