### ISSUE TITLE
Shared Memory PR Caused Black Screens

### ISSUE THREAD

**Issue by KillzXGaming** [citra-emu/citra#1790] opened 2016-05-13 20:09 UTC
May be an issue with compatibility to recent merges as this PR once worked before when i merged it myself. Using latest master and games pop up with memory errors in the log and a black screen. Some games show fatal error. I would like to point out I have my shared font and config and every necessary file dumped and in the proper location. 

[LOG](http://pastebin.com/n4nn8Yuh)

Citra Version: 18b517e
Specs:
GTX 970
I5 4670K
8GB RAM

**Comment by wwylele** [comment] 2016-05-13 20:14
It works fine here, the same version 18b517e
Specs:
Intel Graphics
I7 4500U
8GB RAM
Ubuntu
haven't test on windows.

**Comment by KillzXGaming** [comment] 2016-05-13 20:22
This happens regardless of the game for me. 
OOT3D
Majoras Mask 3D
Pokemon Rumble World
Triforce Heroes
Kirby Triple Deluxe
And more.

**Comment by SonofUgly** [comment] 2016-05-13 20:55
Getting the same issue as well in all games (that worked before). [Games tested](http://i.imgur.com/AgsK9pi.png).

Specs:
6600k
750ti
Win8.1

**Comment by Mrcl1450** [comment] 2016-05-13 20:56
I had the same problem with Rune Factory 4 but it's working again after revert #1695

**Comment by JohnGodgames** [comment] 2016-05-13 21:29
Hmm I'm pretty sure that https://github.com/citra-emu/citra/pull/1695 is causing these problems, because I have shmem merged and testem many games without any problems, but I've remember that merging #1695 from Subv/tls_alloc has bad results.

**Comment by wwylele** [comment] 2016-05-14 10:51
Problem found: the bug is caused by both #1689 (Shared Memory) and #1695 (TLS) .
The problem is that both shared memory and TLS are allocated from linear heap memory ([Shared memory](https://github.com/citra-emu/citra/blob/18b517e236b7f6710567e57dab6a7c5329db948f/src/core/hle/kernel/shared_memory.cpp#L39); [TLS](https://github.com/citra-emu/citra/blob/18b517e236b7f6710567e57dab6a7c5329db948f/src/core/hle/kernel/thread.cpp#L456) ) 
Take [this service function](https://github.com/citra-emu/citra/blob/18b517e236b7f6710567e57dab6a7c5329db948f/src/core/hle/service/gsp_gpu.cpp#L328) for example, it first gets the command buffer pointer (which is a part of TLS), then creates a shared memory, which causes the `linheap_memory` vector get reallocated. Now TLS is in the new address in the computer memory, but the command buffer pointer is still pointing to the old address (say hello to the wild pointer). Then the service function writes response to the deleted old TLS memory. Boom.

**Closed** 2016-05-14 21:02 UTC
