### ISSUE TITLE
Replacing Citra Python scripting with gRPC

### ISSUE THREAD

**Issue by dylmeadows** [citra-emu/citra#5041] opened 2019-12-28 15:38 UTC
I recently stumbled upon the fact that Citra supports scripting with Python, which is internally sending UDP packets. I was curious if the RPC support could be swapped out for an implementation in [gRPC](https://grpc.io/) that would allow scripting support in multiple languages. If backwards compatibility is an issue, then the gRPC server could start on a different port and the existing RPC implementation could continue to work as expected.

If this is something the Citra team is interested in, I don't mind working on the implementation - I have experience working with gRPC.

Would love to hear some feedback on this.

**Comment by jroweboy** [comment] 2019-12-28 15:42
Hello! Its already independent of language as its just a bare bones UDP protocol, and python is just a reference implementation. Theres nothing preventing you from sending packets to the listening port from any language of your choice, the python library is just an example of how to use it. We originally used zeroMQ as the protocol implementation, but that proved to be too much of a pain to build, so we dropped it. I'm not sure what the benefits of adding gRPC would be since multiple language support isn't an issue as it stands.

**Comment by wwylele** [comment] 2019-12-29 07:08
I am going to close this because the issue is basically invalidated by the misunderstanding on the language-independent protocol.

**Closed by wwylele** 2019-12-29 07:08 UTC
