### ISSUE TITLE
Touchscreen Hotkeys/Macros/Scripts/Custom inputs

### ISSUE THREAD

**Issue by phly95** [citra-emu/citra#3545] opened 2018-03-17 19:02 UTC
It would be quite useful if tapping areas of the touchscreen could be mapped to inputs. For example, selecting a weapon in Metroid Samus Returns involves tapping specific areas of the touchscreen, and it would be much easier if these could be mapped to a keyboard.

**Comment by MelonSpeedruns** [comment] 2018-03-17 19:57
This was already requested in #3494 .

**Comment by MerryMage** [comment] 2018-03-18 18:09
Duplicate of #3494.

**Closed by MerryMage** 2018-03-18 18:09 UTC
