### ISSUE TITLE
[Feature request] 7zip and/or zip support

### ISSUE THREAD

**Issue by enderandrew** [citra-emu/citra#2808] opened 2017-06-27 19:24 UTC
I would like to request support for opening roms within 7zip and/or zip files. It can greatly reduce the size of roms on disk.

Thanks!

**Comment by jroweboy** [comment] 2017-06-27 20:58
This has been brought up previously https://github.com/citra-emu/citra/issues/2157 If you would like to add it, we can discuss it in further details. If I recall, anything related to rom loading is due for a rewrite, so this feature won't be happening until after that is complete.

**Comment by yuriks** [comment] 2017-06-29 03:41
I don't think this is practical to implement, unfortunately. Zip and 7-zip (afaik, though correct me if I'm wrong) don't allow random access inside a compressed file, and 3DS ROMs tend to be quite big, so it's not practical to just load the entire thing to memory. Furthermore, once we start supporting (and encouraging) encrypted ROMs, they will be essentially uncompressable. Support for compressed ROMs would have to be done through a specialized format.

**Comment by wwylele** [comment] 2017-06-29 08:56
> ... don't allow random access inside a compressed file, and 3DS ROMs tend to be quite big, so it's not practical to just load the entire thing to memory

A less related topic, but this reminds me that the same issue also applies to encrypted CIA files, which uses CBC mode that doesn't allow random access either. Loading encrypted CIA files would require decrypting the whole ROM in the memory.

**Comment by RavenHome1** [comment] 2017-06-29 10:05
imo we should not bother with this, citra's job is to load a rom in a known format why should anyone go through the trouble of supporting compressed archives and possibly start having regression and more bugs to to fix.

even standard prebuilt pcs and laptops these days come with a nice hdd space from 200+ GB and if it comes to it a 1TB drive is not that horribly expensive either and a rom file would most likely go 2 or 3GB maximum.

**Comment by nicholatian** [comment] 2017-06-29 10:08
Agreed with @RavenHome1 and @yuriks… dog days are over when it comes to ROM formats like that. It’s not the same as a GBA binary or whatever where things are stored simply, so it doesn’t make sense like it used to.

**Comment by mailwl** [comment] 2017-06-30 09:58
1) roms can be trimmed. often up to ~2.3 gb for 4gb rom.
2) yes, zip/7z don't have random access. But, i remember on hacked PSP was format CISO (compressed ISO), where every 4kb (or something like it) was compressed separately. So, to access to some offset need to decompress only 4kb block. Not sure if is possible on Citra

**Comment by MerryMage** [comment] 2017-07-02 09:42
> So, to access to some offset need to decompress only 4kb block. Not sure if is possible on Citra

There are some existing compression formats that do that, like bgzf which is used in bioinformatics for compressing genomes.

Though, as stated before, encrypted files cannot be compressed; too much entropy.

**Comment by i30817** [comment] 2017-07-27 13:47
The thing i most disagree with compressing rom formats, especially some of the modern ones is that as a matter of course, some of them are already performing 'big archive' compression inside the rom as part of the game, so you're paying latency twice for fewer gains.

I'd expect that to be true on the 3ds because i'd expect cartriges manufacturing to be expensive and squeezed as much as possible in a few standard sizes (not sure). 

There are other reasons to compress, ofc (such as projects like retroarch wanting checksums and taking them direct from precalculated size headers).

**Comment by Sanaki** [comment] 2020-07-21 19:53
I had a moment and decided to test. I picked a large game, specifically the encrypted No-Intro verified `Bravely Second - End Layer (USA) (En,Fr,Es)`.

4.0GiB (4294967296 bytes) - Uncompressed
2.6GiB (2708261293 bytes) - Max compression 7z
2.6GiB (2709183215 bytes) - HDD format chd

Checking the chd breakdown, I got this:
```
     Hunks  Percent  Name
----------  -------  ------------------------------------
   661,095    63.0%  Uncompressed
   387,471    37.0%  Copy from self
         8     0.0%  LZMA
         1     0.0%  Deflate
         1     0.0%  FLAC
```
The large uncompressed chunk may be a result of being encrypted, I'm not sure. I'll have to check into that. I'm not too intimately familiar with the 3ds format structure myself. Regardless, the result here is that 7z and chd produce nearly an identical filesize (1MiB difference), both save 1.4GiB over uncompressed, but 7z requires full extraction to be used, while chd can be read directly in that format at near-uncompressed speed. Given the advantages, you might be surprised how many people get on board with the format. After adding support to various libretro cores, chd has become extremely popular (for CD/GD-ROM games).

In case it hasn't already been made clear, chd support can be added through the libchdr library:
https://github.com/rtissera/libchdr

**Comment by wwylele** [comment] 2020-07-21 20:31
@Sanaki A freshly dumped game file from cartridge usually contains massive amount of zero/padding bytes at the end. This is because game cartridge only have a few capacity types that are usually powers of 2, and most game dumpers, for the sake of keeping data original, will dump all the padding bytes even though they do nothing.

I would bet that Bravely Second has ~1.4GiB zero bytes. If you simply remove these 1.4GiB bytes from the end, the game can still run perfectly, and now you get a nice *uncompressed* 2.6GiB game file. All compression algorithm will give you this the same result due to the rest of data being encrypted and incompressible, so comparing compression algorithm here is meaningless.

**Comment by enderandrew** [comment] 2020-07-21 20:56
If you run Bravely Second through a decryptor, you end up with a 2.6 GB
file so I suspect you are correct. 7zip with ultra LZMA2 compression can
get that down to 2.2 GB. So maybe the savings aren't as drastic as I would
have hoped. I believe CHD and 7zip have libraries you can bring for support.

This would benefit people who have padded/unencrypted roms more and less
for people with decrypted roms.

**Comment by Sanaki** [comment] 2020-07-21 22:07
You generally get nearly identical sizes between 7z and chd (with chd slightly larger on average), since it compresses each hunk individually based on which compression method is the most efficient for it. I'm aware of the zero padding, though I wasn't aware 3ds can potentially function with it trimmed. Decompressed being 2.2GiB does confirm that it's the encryption resulting in the large uncompressed block. I'll decrypt mine later to provide an updated comparison, since that'd be far more useful.

**Comment by i30817** [comment] 2020-07-21 23:10
Creating sparse files that get filled with the real part of the roms might be possible in some (linux) filesystems.

**Comment by Sanaki** [comment] 2020-07-22 00:38
Right, got it decompressed. New stats for that (decrypted No-Intro verified `Bravely Second - End Layer (USA) (En,Fr,Es)`):
```
4.0GiB (4294967296 bytes) - Uncompressed
2.2GiB (2302623720 bytes) - Max compression 7z
2.3GiB (2440564011 bytes) - HDD format chd
```
Definitely not a game that compresses well in general, regardless of method (other than the padding of course, which as pointed out previously is only relevant to people who meticulously keep perfect No-Intro sets).

Compression breakdown:
```
     Hunks  Percent  Name
----------  -------  ------------------------------------
   143,945    13.7%  Uncompressed
   389,619    37.2%  Copy from self
   147,356    14.1%  LZMA
    33,878     3.2%  Deflate
   333,146    31.8%  Huffman
       632     0.1%  FLAC
```

**Comment by extherian** [comment] 2021-01-22 15:22
Is there any reason why gzip wouldn't work? PCSX2 uses gzip with a separate index to minimise random access times, which bypasses the issue with 7zip not being seekable. 

Also, I see no value in keeping ROMs encrypted once they've been dumped, so it doesn't matter how poorly encrypted files compress. Surely the point of compression over trimming is to eliminate padding in a reversible manner?

**Comment by i30817** [comment] 2021-01-23 00:15
Encryption is only part of the story. The game companies themselves that make the games use compressed filesystems in the game engine, and compressing already compressed data is 'almost' as bad as compressing encrypted data.

**Comment by extherian** [comment] 2021-01-23 16:54
Yeah, compressing the 0-padding is the real benefit here. Dolphin does something like this with its RVZ file format, which is basically just Deflate compression applied to the garbage data, while the game files that are already compressed are left alone. 

Also, there's no need for the archive to even be seekable if Citra just unzips them before running them and then deletes the file again afterwards. This is how Project64 handles zip files. I just think this topic has been dismissed prematurely.

**Comment by Sanaki** [comment] 2021-01-23 20:01
> Also, there's no need for the archive to even be seekable if Citra just unzips them before running them and then deletes the file again afterwards.

I disagree on this point. Extraction is a functional solution, but distinctly worse than being directly seekable. It comes with a moderate to severe slowdown on -every- launch (especially for games that approach 4GiB), contributes to HDD or especially SSD wear for anyone not using a ramdisk as a cache location, and can be entirely unworkable on limited memory systems. By no means am I saying it shouldn't be an option, but there are distinct advantages to directly seekable compressed formats for a large number of users.

**Comment by extherian** [comment] 2021-01-26 00:27
If extraction isn't considered acceptable, then wouldn't something like nicoboss's [NSZ format](https://github.com/nicoboss/nsz) do the job? It uses Zstandard to compress 256 KB chunks while uncompressible chunks are stored without compression, making fast random reads possible. This is very much along the same lines as Dolphin's RVZ format and seems to have been designed with emulator support in mind.

**Comment by bebess** [comment] 2021-02-18 16:32
any updates of this feature ?

**Comment by i30817** [comment] 2022-09-30 16:30
rvz is a optical disc compression format. It's not suitable.

**Comment by TomTurbine** [comment] 2022-10-07 01:28
Honestly, I would like for Citra to implement it's own version of Cemu's WUA format where it is both compressed and allows you to combine any DLC and Updates into a single file with it that can be later extracted if you wanted.

**Comment by TomTurbine** [comment] 2022-10-10 04:29
Actually was just thinking about this.

Compressing these game does logically make sense nowadays. I mean a few years ago, yeah, the games were too big to really fit in memory and the computers just really didn't have the power to run it well enough and the emulator wasn't as optimized as it is now.

By comparison, the biggest game for the 3DS is something like 4GB while even a subpar computer now has at least 8GB, the one I am typing this on has 32GB for instance and that's pretty standard and likely to be on the low end when DDR5 becomes more mainstream. You can even get a Rasberry Pie with 8GB RAM.

So the full emulator on full tilt running the biggest 3DS game there is loaded entirely into memory would still be no bigger than most common PC games running now. Running a game currently uses around 660MB on a quick test, so even doubling that to run the game along with storing the biggest game they make in memory would still use less than 6GB.

So yeah, I would gladly sign up for a CHD format for streaming and if they couldn't do that allow support for 7zip and the option to load the game into RAM for players who wanted to enable those options.

**Comment by Quest79** [comment] 2022-10-10 06:39
How is this still not a thing? Every other emulator has this now. This is a basic feature for the last several years.  This is 100GB lost, and my collection isnt even half complete.

**Comment by TomTurbine** [comment] 2022-10-12 04:11
Just checked out of curiosity, can actually load 7-zip files on the Retroarch core if Citra, it loaded and played just fine BUT, it took about 10 seconds to load it.

So can definitely see putting this as an optional feature for those that want it but off by default.

But do definitely agree with supporting CHD which is actually streamed and compresses pretty well on these I have heard.

Off-topic, really hope they start including support for loading the updates and dlc with the games directly from the CIA instead of requiring it to be installed into the system itself similar to how Ryujinx allows you to with Switch games or how Cemu allows you to by having them in the game folder itself or even adding them into a single WUA file which allows them to be compressed, merged, and streamed as needed as well as being able to decompress it back if needed.

**Comment by d0k3** [comment] 2023-02-07 18:00
I think @Exzap's [ZArchive](https://github.com/Exzap/ZArchive) could help a lot here. It's the compression component in a WUA file (as seen in Cemu) and it is actually designed for random access reads. Writes need to be sequential (= only appending, no editing), but that shouldn't be a problem here. I had a quick look over the interface of the library and it pretty much looks like a drop in replacement for standard file i/o.

I'd estimate that, with ZArchiver, an additional 20% of savings compared to a trimmed, decrypted NCSD would be possible (as the padding areas would melt to basically nothing with compression) on average. For encrypted NCSD, additional compression wouldn'd do any good, of course.

Instead of just putting a ZArchive layer over the NCSD, you could also decrypt original (= encrypted) dumps when compressing and restore the encryption when decompressing. That would mean you'd have a playable, effective, archive quality compressed file format for 3DS cart dumps. I've done something similar in GodMode9 with the on-the-fly decryption when mounting NCCH/NCSD/CDN dumps.

And, you could of course go overboard and add (playable, without installation) compatibility with CDN dumps and CIAs. ZArchiver actually has a filesystem inside of the compressed archives, meaning adding multiple contents (/updates/DLCs) inside one compressed file is possible. If you also add a titlekey file to the archive, you could also achive archive-quality, playable compression of CDN contents.

Anyways, just wanted to add my 5 cents. I know that stuff still means a lot of work, probably even better than most others.

**Comment by d0k3** [comment] 2023-02-10 15:24
Following up on my last post, I hope the devs are reading. I did a small compression test with a testset of 50 decrypted, untrimmed .3ds cart dumps of various kinds.

All percent numbers are relative to original size.

Original size: 53.2GB
Trimmed size: 37.1GB (~30% less)
7-zip (normal): 25.9GB (~50% less)
**ExZaps ZArchive (standard): 29.8GB (~44% less)**

In other words, that's worth it. Compression will be a lot worse with encrypted game data, of course. But the good thing here is: _You guys don't have to worry about it._ You could add reading from ZArchive files via @ExZap's [libraries](https://github.com/Exzap/ZArchive) and call it a day.

And, as long as ZArchive files would be supported by Citra, you could leave the job of optimizing compression (via decryption) to others. I already got some ideas how to achieve archive-quality (that means, altering dumps in a way that the original file can still be restored).

**Comment by Phantop** [comment] 2023-02-10 16:23
I'll personally argue in favor of [SquashFS](https://github.com/plougher/squashfs-tools), mainly because it's a much more mature and widely supported format and if a filesystem-based format is being considered, it may be the better option. It also has much more flexible (and better!) compression than ZArchive.

There's honestly no shortage of rather straightforward filesystem-based ways of dealing with this problem, especially on Linux where SquashFS and [DwarFS](https://github.com/mhx/dwarfs) are easily usable. I personally just have all my games decrypted in a file of the latter, which definitely beats out both SquashFS and ZArchive by a fair share.

**Comment by d0k3** [comment] 2023-02-11 11:38
@Phantop - can you provide compression test results on a large enough set for the alternatives you suggested?

ZArchive does handle filesystems (that's important, think of the CDN format, or even combining title, update, DLC into one file). I had a look over the source code, and the library really provides drop in replacements for standard file i/o. Easy (or as easy as possible) implementation is one of the important factors here, too. Citra now has well over 600 issues open, and the devs most likely don't have much time on their hands for side-issues such like this one.

I haven't checked for available libraries on the alternatives you named, to be honest, so I just don't know. Maybe one other remark: Citra does need something that has good support on all platforms, so a solution that works well on Linux and not so well elsewhere won't cut it.

**Comment by Phantop** [comment] 2023-02-12 05:54
> @Phantop - can you provide compression test results on a large enough set for the alternatives you suggested?

I only keep a few games on hand but on a set made of three games (Animal Crossing: New Leaf Welcome Amiibo and Happy Home Designer, and Zelda: A Link Between Worlds) which I keep on hand and is 2.2GB trimmed but uncompressed, I get 1.5GB with Zarchive, 1.4GB with SquashFS, and 1.3GB with DwarFS. Seeing as your example with 7-Zip vs ZArchive only saved about 4GB with an 53.2GB source, I do wonder how much differences here could scale so perhaps Zarchive *is* the best option here.

> I haven't checked for available libraries on the alternatives you named, to be honest, so I just don't know. Maybe one other remark: Citra does need something that has good support on all platforms, so a solution that works well on Linux and not so well elsewhere won't cut it.

I actually do suspect SquashFS may be better on this front, as 7-Zip has been able to extract (and maybe make? I dunno, I don't use it much anymore) SquashFS images for ages. ZArchive is a very new format, but if it's easier to integrate it's ultimately up to whoever wants to actually implement this.

**Comment by Quest79** [comment] 2023-02-12 19:54
Why are we fixiated on 7z and zip when CHD is quickly becoming the open standard for emulation compression?

**Comment by Phantop** [comment] 2023-02-12 21:23
> Why are we fixiated on 7z and zip when CHD is quickly becoming the open standard for emulation compression?

CHD seems to mainly be targeted at disc based formats and the type of content common to them. It also currently doesn't support Zstandard which I argue has a notable enough performance advantage alone to be worthwhile, and in fact compresses far worse than the other listed options in this thread, at least from my testing. Unless I'm using MAME's `chdman` wrong, it doesn't seem to be a good pick, at least to me.

**Comment by monyarm** [comment] 2023-07-10 13:33
> > Why are we fixiated on 7z and zip when CHD is quickly becoming the open standard for emulation compression?
> 
> CHD seems to mainly be targeted at disc based formats and the type of content common to them. It also currently doesn't support Zstandard which I argue has a notable enough performance advantage alone to be worthwhile, and in fact compresses far worse than the other listed options in this thread, at least from my testing. Unless I'm using MAME's `chdman` wrong, it doesn't seem to be a good pick, at least to me.

Not necessarily. chdman supports making chd's of disk images. Or in other words filesystems. For mame this is mostly used for arcade games that use a HDD. It should be possible to use for decrypted 3ds roms.

Though personally, I think the best choice would be a custom format. Basically, a format with support for multiple types of compression, which compresses the game chunk by chunk or file by file, choosing the best compression.  And custom handling could be added for common 3ds file formats. Maybe even a possibility for handling nested archives? (NCCH files within the NCHD, instead of compressing the whole file, compressing the files within it, individually.)

I'm currently experimenting with something similar for nds files, though at the moment I'm still working on reading and rebuilding all the header information.

**Closed** 2023-09-13 12:25 UTC
Labels: enhancement, E-easy
