### ISSUE TITLE
Pokemon X/Y - Black Rectangles on Character Face

### ISSUE THREAD

**Issue by between1and1** [citra-emu/citra#4539] opened 2018-12-29 04:39 UTC
Citra Version Info & Commit Hash: citra-windows-mingw-20181227-68f2d6e

In Pokemon X/Y, there are black rectangles on the character's face (male) as shown below: 

![Black Spot Face](https://cloud.githubusercontent.com/assets/18496868/19618958/d7db784a-988b-11e6-8fae-c78f8e93f1cc.png)

This is how it's supposed to look when playing the game in a physical 3DS:

![3DS reference](https://cloud.githubusercontent.com/assets/18496868/19619023/5ec6be08-988e-11e6-8877-e51377223154.png)

**Comment by tgsm** [comment] 2018-12-29 04:41
duplicate of #2133, please close.

**Closed** 2018-12-29 04:41 UTC
