### ISSUE TITLE
Inazuma Eleven 3 Audio Issue

### ISSUE THREAD

**Issue by MFlynny86** [citra-emu/citra#5440] opened 2020-07-01 11:51 UTC
I've tried at least 30 different citra versions, some from canary and some from nightly and for all 3 Inazuma 3 games and it has bad audio and it's running at around 80% speed.
I'm sure it's not a speed issue as I've not had this audio issue with any other Inazuma games.
The audio is very grainy and hard to listen to which makes playing annoying and not suitable to record gameplay.

https://drive.google.com/file/d/1zhJ7bRyju4KqdQjS9MNl19ljN1sPQx1x/view?usp=sharing

**Comment by FearlessTobi** [comment] 2020-07-01 12:31
Duplicate of https://github.com/citra-emu/citra/issues/4721.

**Closed by FearlessTobi** 2020-07-01 12:31 UTC
