### ISSUE TITLE
[Feature Request] Run title from extracted files

### ISSUE THREAD

**Issue by mariomadproductions** [citra-emu/citra#2748] opened 2017-06-04 13:41 UTC
Like cemu and dolphin can.

**Comment by RavenHome1** [comment] 2017-06-04 13:48
what benefit would that have?

**Comment by mariomadproductions** [comment] 2017-06-04 13:50
Test mods (and homebrew?) without building it into a ROM

**Comment by wwylele** [comment] 2017-06-04 14:27
I see this as a duplicate of #2735, so closed for now

**Closed by wwylele** 2017-06-04 14:27 UTC
