### ISSUE TITLE
Paper Jam can't run

### ISSUE THREAD

**Issue by bryancyriel** [citra-emu/citra#1298] opened 2015-12-26 13:57 UTC
Issues about Paper Jam can't run with Citra. Please look.

![1](https://cloud.githubusercontent.com/assets/2939045/12006670/3e603b5e-ac1b-11e5-8602-a48149c6bb72.PNG)
![2](https://cloud.githubusercontent.com/assets/2939045/12006671/3e99e0e8-ac1b-11e5-94ff-17856debeb88.PNG)
![3](https://cloud.githubusercontent.com/assets/2939045/12006672/3ec57ed8-ac1b-11e5-93b1-d46bb6bac46c.PNG)
![4](https://cloud.githubusercontent.com/assets/2939045/12006673/3ef30218-ac1b-11e5-9d27-cb7de76990d3.PNG)

**Comment by mailwl** [comment] 2015-12-26 14:07
read https://github.com/citra-emu/citra/issues/1292 - the same issue

**Comment by Subv** [comment] 2015-12-26 14:11
Duplicate of #1292

**Closed by Subv** 2015-12-26 14:11 UTC
