### ISSUE TITLE
add internet

### ISSUE THREAD

**Issue by soupnuts6061** [citra-emu/citra#6708] opened 2023-07-19 13:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

add internet compatibility, maybe also pretendo compatibilty too?

### Why would this feature be useful?

you can play online in mk7 per say

**Comment by FearlessTobi** [comment] 2023-07-19 23:48
Duplicate of https://github.com/citra-emu/citra/issues/6679.

**Closed by FearlessTobi** 2023-07-19 23:48 UTC
