### ISSUE TITLE
Pac-Man Party 3D - Graphic not in line

### ISSUE THREAD

**Issue by Reegea85** [citra-emu/citra#1767] opened 2016-05-07 20:55 UTC
This is how it look like

![pac-manparty3d](https://cloud.githubusercontent.com/assets/19243224/15094457/03b8a610-14a5-11e6-90e1-020f1c6563b3.png)

[Log](https://github.com/citra-emu/citra/files/253604/pac-manparty3d.txt)

**Comment by JayFoxRox** [comment] 2016-05-07 21:01
Duplicate of #1542

**Closed by JayFoxRox** 2016-05-07 21:01 UTC
