### ISSUE TITLE
Shin Megami Tensei 4: Apocalypse combat texture bug

### ISSUE THREAD

**Issue by Salijour** [citra-emu/citra#2272] opened 2016-12-06 04:20 UTC
Tested on 12/5 master build 9a439b9.  

Enemy death animations doesn't display properly. Even with everything off.

When the animation happens the console pops up with this:
```
[ 100.082544] HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::AppendSource:58: Unhandled texture type 2
```

**Citra:**
![Citra](https://i.gyazo.com/998d43c6d3923bf87e8c966028bc3126.png)

**Real:**
![Real](http://i.imgur.com/8NW9XZI.png)

---

Easier to see example:
![Example](https://i.gyazo.com/ee65b08d7051e2d54c6180625171559a.png)

To reproduce error. Go into combat and kill an enemy with an ability other than basic attack or shoot. It will then do a special death animation.
**Save:** 
[0019a200.zip](https://github.com/citra-emu/citra/files/635067/0019a200.zip)
For testing this bug use the save in slot 2 and run into blue creature to start combat.

**Comment by JayFoxRox** [comment] 2016-12-06 04:47
I've fixed some markup for you, please provide a savegame to reach that spot in the game, describe how to reproduce the issue (what to do after loading the savegame?), which version of citra is affected? does it work with / without cpu jit, shader jit or without hw-rendering?

**Comment by NaaleinGrohiik** [comment] 2018-03-10 11:55
The same thing happens in SMT 4 too, there seems to be a black texture square around the textures themselves, I think that part was meant to be transparent. The bug is preduced just like in smt 4 apocalypse by using a spell or gun/melee skill to finish off a low health enemy. Here is a screenshot :
![untitled](https://user-images.githubusercontent.com/32201158/37241953-91258932-2461-11e8-8d5f-49b428bbc32c.jpg)

![untitled1](https://user-images.githubusercontent.com/32201158/37242002-4f69bfb2-2462-11e8-9339-910f04cb1f09.jpg)

**Comment by NaaleinGrohiik** [comment] 2018-03-13 16:24
I just tested it on the latest Canary Build (not sure if it's the one you are talking about) and I got this:

![untitled](https://user-images.githubusercontent.com/32201158/37354986-2ad07fe6-26e3-11e8-99b7-d3979d6682fc.jpg)

Let me know if you want me to test it again on another version, it's the least I could do.

**Comment by wwylele** [comment] 2018-03-13 17:04
Looks like unrelated to shadow map. I am unlabeling then...

**Comment by Dragios** [comment] 2018-03-14 01:57
@NaaleinGrohiik You tested on the wrong version. Latest canary build does not have shadow map PR included. Try this [build](https://ci.appveyor.com/api/buildjobs/d5btsuflp1i2xavf/artifacts/citra-windows-mingw-20180313-a5dc40b.7z) instead and let us know the result. To me it seems to be unrelated but test it just to be sure.

**Comment by jroweboy** [comment] 2018-03-14 02:09
Also isn't shadow map in the software renderer only? make sure you turn off the hardware renderer when you get to the spot that you need to test.

**Comment by NaaleinGrohiik** [comment] 2018-03-14 07:54
I just test it with the build @Dragios provided and made sure to disable hardware renderer and still got the weird black square. 
Maybe citra is not rendering the transparency part of the texture and instead showing the black part?


![untitled](https://user-images.githubusercontent.com/32201158/37389526-fba795d8-2764-11e8-8b3b-2d347af051de.jpg)

**Comment by LOuroboros** [comment] 2020-01-07 05:03
This issue seems to still be happening, even around a year and 10 months later.

This is how the effect that appears when you kill a demon with Bufu should look like: https://www.youtube.com/watch?v=CRTi08NHZWE&t=244

And here's how it currently looks on Citra Canary 1529: https://streamable.com/e9yju

**Comment by Demaar** [comment] 2020-04-26 16:13
Has this gotten a workaround in the years since it was reported?

**Comment by ofsaleem** [comment] 2020-08-05 02:16
im on nightly 1599 and i still experience this bug, along with various other annoying-but-not-game-breaking stutters

**Comment by KrisanThyme** [comment] 2020-12-30 19:39
Been about four years since this was originally reported, but yeah sadly I can confirm it is still an issue as of Nightly 1659 and Canary 1903. Both SMTIV and SMTIV Apocalypse suffer from this issue. It's a relatively minor issue I know, but it would be nice if after all this time it could be looked into.

**Comment by Jorge9811** [comment] 2021-07-02 09:29
It's a bit saddening, but this is still happening in Canary 1977.

https://user-images.githubusercontent.com/4485172/124253791-c5cc9700-dafe-11eb-9e6e-427e8acb3809.mp4

**Comment by megaboyx90** [comment] 2022-07-02 04:18
It's still a thing as of me writing this message

**Comment by Bensouda98** [comment] 2022-11-21 14:30
I tried the new Vulkan implementation, and the issue is still not fixed as of me writing this message.

**Comment by JeremiahPeters311** [comment] 2023-02-03 05:21
seven years and counting still no fix (I'm playing on nightly 1833 as of this writing)

**Comment by Meridiann** [comment] 2023-03-18 19:29
Sad to see this hasn't been resolved after all this time. Is there anything that can be done to get any effort put into a resolution for this issue?

**Comment by OpenSauce04** [comment] 2023-05-09 12:29
I would also pitch into a bug bounty for this issue to be fixed on both 4 and 4A

**Comment by Bensouda98** [comment] 2023-07-09 11:37
Would be willing to pitch in too for a bug bounty.

**Comment by Mortise976** [comment] 2023-07-17 15:27
Today is the 10th anniversary of SMT IV and with no sign of a remaster in sight this bug is the only remaining issue. I really hope you guys fix it at some point.

**Comment by GPUCode** [comment] 2023-08-26 10:50
Can someone post a new save file for this alonside reproduction steps, intereted to take a look into this

**Comment by Meridiann** [comment] 2023-08-26 11:19
> Can someone post a new save file for this alonside reproduction steps, intereted to take a look into this

I can post a save later tonight. It's extremely easy to reproduce as pretty much anything you land a killing blow on with physical/gun/magic of any element will produce this effect.

Get into a fight and land the killing blow with any of your skills, you'll see it.

It's the reason there's interest in this being fixed, it's something that you'll have to deal with your entire playthrough! It also ruins some of the fun effects that come alongside certain types of damage.

**Comment by LOuroboros** [comment] 2023-08-26 12:12
As Meridiann said, reproducing this error is rather easy as it happens with a majority of "killing/finishing blow animations".

You can see it happen in action in the first hour of gameplay in fact, which becomes a much smaller amount of time if you just Fast Forward your way through the conversations.

Regardless, here's a fresh save as requested. I'm glad to see this will finally be looked into!

[sdds4game1.zip](https://github.com/citra-emu/citra/files/12445310/sdds4game1.zip)

https://github.com/citra-emu/citra/assets/4485172/0af4ed84-d3f3-48fc-b623-71d0a4d8c75b

**Comment by GPUCode** [comment] 2023-08-26 20:53
Thanks so much for the save. I believe the linked PR fixes the issue, can you confirm?

**Comment by Bensouda98** [comment] 2023-08-26 22:47
I just tested it with the linked PR and as far as I can tell for my testing it is fixed! I tried all sorts of spells with different effects and that black square bug no longer appears.

**Comment by Meridiann** [comment] 2023-08-26 23:00
No way, did you fix it GPUCode? Does this fix apply to SMT IV and SMT I A?

**Comment by sukerokushin** [comment] 2023-08-27 07:15
With the SMTIV Apocalypse save file linked by LOuroboros recently, Citra crashes upon entering a battle on my 10th gen Intel i5 iGPU. [Log here](https://github.com/citra-emu/citra/files/12447429/citra_log.txt).

My laptop's Nvidia dGPU showed zero issues.
![image](https://github.com/citra-emu/citra/assets/55974345/d9b243d1-f88e-4f89-b274-a7e8c2633c15)

**Comment by GPUCode** [comment] 2023-08-27 07:21
Just pushed a fix commit yeah. Feel free to test the PR artifact when it finishes building in about 30 minutes

**Comment by GPUCode** [comment] 2023-08-27 07:21
> No way, did you fix it GPUCode? Does this fix apply to SMT IV and SMT IV:A?

From the testing so far, it appears to be the case

**Comment by Meridiann** [comment] 2023-08-27 09:12
> > No way, did you fix it GPUCode? Does this fix apply to SMT IV and SMT IV:A?
> 
> From the testing so far, it appears to be the case

Amazing, thank you so much. It was a huge visual bug in what a lot of people might consider one of the best games out there. Thank you again!

**Comment by inaxy** [comment] 2023-08-27 12:32
Hi, I see that I'm solved, but how is the solution implemented in citra for android?

**Comment by JocarLixo** [comment] 2023-08-28 20:02
This may be an issue on my end, but it's still happening for me. I tested on a Arch Linux system and a Windows 10 system with the PR builds, and the issue still happened on Arch with the native Linux build, and running the Windows build via Wine. It also happens on both the Software Renderer, and OpenGL. On the Windows machine the effects were normally rendered though.

https://github.com/citra-emu/citra/assets/89185603/dd033276-5742-48c3-8a3f-f2001574fceb

**Comment by GPUCode** [comment] 2023-08-28 20:05
> This may be an issue on my end, but it's still happening for me. I tested on a Arch Linux system and a Windows 10 system with the PR builds, and the issue still happened on Arch with the native Linux build, and running the Windows build via Wine. It also happens on both the Software Renderer, and OpenGL. On the Windows machine the effects were normally rendered though.
> smtiv.issue.mp4

Can you upload your opengl extension list with [this](https://opengl.gpuinfo.org/download.php) app and send link to the report here? It's likely that your linux system is missing the required extensions

**Comment by JocarLixo** [comment] 2023-08-28 21:16
https://opengl.gpuinfo.org/displayreport.php?id=10200
Here's the report, some of the extensions you mentioned on the PR (like GL_AMD_blend_minmax_factor) are in fact missing. I got a glewinfo log aswell, both with Mesa and with the AMDGPU-PRO drivers, and they are only present on the latter. I'll be linking them here too, could be of some help.
[glewinfomesa.txt](https://github.com/citra-emu/citra/files/12458283/glewinfomesa.txt)
[glewinfoamdgpupro.txt](https://github.com/citra-emu/citra/files/12458284/glewinfoamdgpupro.txt)

**Comment by GPUCode** [comment] 2023-08-28 21:21
I see. All extensions required by the PR are missing, so this will need a fallback path for Mesa. Does the PR work with AMDGPU-PRO drivers btw?

**Comment by JocarLixo** [comment] 2023-08-28 21:25
Using progl, Citra opens but can't open anything using OpenGL rendering, with a warning saying "OpenGL shared context are not supported", and the terminal throws "Unrecognized OpenGL version".

**Comment by GPUCode** [comment] 2023-08-28 21:52
@JocarLixo I have pushed a Mesa fallback commit to the PR, can you test if it works for you?

**Comment by JocarLixo** [comment] 2023-08-28 22:41
Yes, it works perfectly! Thank you for the attention, and the amazing work you're doing!

![image](https://github.com/citra-emu/citra/assets/89185603/285bcee2-0c6d-4cf4-b108-3013307fd711)

**Closed** 2023-08-30 18:26 UTC
Labels: A-graphics
