### ISSUE TITLE
"My Mom Hid My Game!" has major graphical issues making it unplayable + save data is always corrupted

### ISSUE THREAD

**Issue by BowzasaurusRex** [citra-emu/citra#4558] opened 2019-01-08 20:25 UTC
The game "My Mom Hid My Game!" from the eShop doesn't work in Citra. Specifically, the game doesn't save correctly causing Citra to drop to 0 FPS and get stuck on a black screen before the title screen loads (but after the developer's logo is shown). Attempting to exit the game or close Citra when this happens causes Citra to stop responding.

The game boots if you delete games.bin before running it, but major graphical issues make it unplayable.

I asked about this on the Citra forums, and after troubleshooting for awhile I was told I should post an issue here.

>Citra version: Nightly 1169 | HEAD-941d241 (2019-01-07)
>OS: Windows 10 Home (x64)
>CPU: Intel Core i7-6700K
>GPU: NVIDIA GeForce GTX 970

I've attached two log files, save_create.txt when the game is run after deleting saves.bin and save_load.txt when the game is run without deleting saves.bin

I've also attached two screenshots, one is of the game running on CItra with major graphical issues (with saves.bin having been deleted before running) and the other of the game running on a real 3DS at the same point

[save_create.txt](https://github.com/citra-emu/citra/files/2738322/save_create.txt)
[save_load.txt](https://github.com/citra-emu/citra/files/2738323/save_load.txt)
![citra](https://user-images.githubusercontent.com/13355923/50856711-693af780-1359-11e9-8a00-c222e6cde450.png)
![3ds](https://user-images.githubusercontent.com/13355923/50856761-8c65a700-1359-11e9-87ea-f8b514708aca.png)

**Comment by FearlessTobi** [comment] 2019-01-08 20:31
This game is New3ds exclusive, so that's very likely the cause of the issues. 
You need to wait until Citra adds support for it.

**Comment by BowzasaurusRex** [comment] 2019-01-08 22:07
Ah, my mistake. I didn't realize it was a New 3DS exclusive

**Comment by Peduls** [comment] 2020-04-19 02:00
Game looks mostly fine now but has serious sound issues. Tested in Citra Nightly 1488

**Comment by FearlessTobi** [comment] 2020-04-19 02:16
@Peduls Please test if they persist when enabling LLE Audio in the settings.

**Comment by Peduls** [comment] 2020-04-19 03:08
LLE Audio is far better but still not perfect. Audio occasionally sounds slow and choppy despite game running at 100%/100% 30FPS

**Comment by vitor-k** [comment] 2023-04-28 00:49
Closing as the original issue has been fixed and the audio problem now has its own issue.

**Closed by vitor-k** 2023-04-28 00:49 UTC
