### ISSUE TITLE
Emulator crash in Ocarina of Time 3D

### ISSUE THREAD

**Issue by marouf33** [citra-emu/citra#2740] opened 2017-05-31 15:18 UTC
Hi, I have encountered a crash in the emulator . It is reproduced consistently in 	"Nightly Build - 54ea95c".
The crash happens after Sheik is revealed as Zelda in the temple of time. 
I'm sorry I can't provide a backtrace, but I will attach the save file to right before the scene of the crash happens.

[00000001.zip](https://github.com/citra-emu/citra/files/1042014/00000001.zip)

**Comment by jroweboy** [comment] 2017-05-31 15:55
Here's a summary of the issue:

There's an assert here https://github.com/citra-emu/citra/blob/54ea95cca74f76777aa156f6d750c9d1ba5b6f11/src/video_core/renderer_opengl/pica_to_gl.h#L32 which prevents any texture modes from getting used that aren't in the enum. The problem is there's a messed up config being passed in http://i.imgur.com/bayduef.png with some clearly bogus values in it.

**Comment by wwylele** [comment] 2017-05-31 17:18
Ref #2703. This is a regression due to length expansion of the wrap mode fields, and the game seems using invalid wrap modes 6 and 7.

**Comment by Abyss2381** [comment] 2017-06-05 12:16
I was able to work around this by downloading bleeding-edge-300, v 0.1.300. I tried several between it and the current build, but they all failed at the same spot. If you download and run this one, continue your save, you should be able to get past the point and save again. I will test the rest of OoT 3D this afternoon to see if any more crashes occur with the newest build.

**Comment by Abyss2381** [comment] 2017-06-07 01:48
Okay, it will crash again in the final credits, when young Link is approaching Zelda at the window in Hyrule Castle. Same error, so only those two spots are affected.

**Comment by jroweboy** [comment] 2017-06-23 02:08
Fixed in https://github.com/citra-emu/citra/pull/2743 (Please retest on nightly if you wish)

**Closed by jroweboy** 2017-06-23 02:08 UTC
